ES_TEACHERS = {
    "cd_t_000": "El MOOC de ciencias del aprendizaje más popular del mundo (más de 4M de estudiantes) — chunking, memoria, pensamiento difuso. Gratis para auditar.",
    "cd_t_001": "Podcast y blog de Jennifer Gonzalez — cientos de análisis profundos gratuitos sobre estrategias instruccionales, engagement y técnica de aula.",
    "cd_t_002": "Seis estrategias de estudio basadas en evidencia (práctica espaciada, recuperación, elaboración, etc.) explicadas con claridad para docentes y alumnos.",
    "cd_t_003": "Guía gratuita definitiva de Vanderbilt sobre la taxonomía de Bloom revisada — listas de verbos, plantillas de preguntas y modelos de planificación.",
    "cd_t_004": "Pautas gratuitas del Diseño Universal para el Aprendizaje — planifica clases que funcionen para todos desde el inicio, no como añadido.",
    "cd_t_005": "Las 63 técnicas de aula de Doug Lemov — videoclips gratuitos, lecturas y guías de campo sobre cold calling, ritmo y más.",
    "cd_t_006": "Artículos de investigación a la práctica sobre diferenciación, aprendizaje basado en proyectos, integración socioemocional y diseño de evaluaciones.",
    "cd_t_007": "Artículos gratuitos sobre modelos pedagógicos modernos — taxonomías de aprendizaje, marcos innovadores y herramientas de pensamiento listas para el aula.",
    "cd_t_008": "Recursos gratuitos de Jim Knight sobre el ciclo de impacto — un marco práctico que cualquier docente puede usar para mejorar de forma autodirigida.",
    "cd_t_009": "Investigación y herramientas gratuitas del MIT sobre el aprendizaje docente — simulaciones, estudios de caso y cursos de diseño instruccional.",
    "cd_t_010": "Cientos de artículos revisados por pares gratuitos sobre currículo, instrucción y evaluación de la principal asociación docente del mundo.",
    "cd_t_011": "Informes gratuitos que traducen la ciencia cognitiva a principios de formación docente — La Ciencia del Aprendizaje hecha accesible.",
    "cd_t_012": "Artículos gratuitos de un científico cognitivo sobre memoria, atención y motivación — del laboratorio a la práctica de aula.",
    "cd_t_013": "Mindset Works de Carol Dweck — resúmenes de investigación gratuitos y estrategias listas para construir una cultura de mentalidad de crecimiento.",
    "cd_t_014": "La SDT de Deci y Ryan explicada — por qué autonomía, competencia y relación son las tres claves de la motivación del estudiante.",
    "cd_t_015": "Kit gratuito de rutinas de pensamiento de Project Zero — Ver-Pensar-Preguntar, Afirmar-Apoyar-Cuestionar y más de 20 protocolos listos para el aula.",
    "cd_t_016": "Manuales gratuitos de Angela Duckworth para docentes sobre grit, curiosidad, gratitud y autocontrol — basados en investigación, listos para usar.",
    "cd_t_017": "Prácticas SEL gratuitas del Berkeley Science Center basadas en psicología positiva — bondad, mindfulness y resiliencia.",
    "cd_t_018": "Podcast y artículos gratuitos sobre cómo funciona el aprendizaje — neurociencia, motivación, equidad y el futuro de la educación.",
    "cd_t_019": "Artículos de investigación gratuitos de la Harvard Graduate School of Education — equidad, ciencias del aprendizaje, liderazgo escolar y políticas.",
    "cd_t_020": "Resumen gratuito en lenguaje claro de la EEF sobre la teoría de la carga cognitiva — qué implica para el diseño de clases, ejemplos resueltos y práctica.",
    "cd_t_021": "Guía gratuita y clara sobre la Zona de Desarrollo Próximo de Vygotsky — cómo el andamiaje y el aprendizaje social moldean el aula.",
    "cd_t_022": "Síntesis basada en evidencia de Edutopia sobre lo que la investigación dice que hace efectiva la enseñanza — accesible y práctica.",
    "cd_t_023": "Proyecto gratuito Visible Thinking de Harvard PZ — rutinas que hacen visible, discutible y transferible el pensamiento del alumno.",
    "cd_t_024": "Videoteca de enseñanza real en aula — observa a docentes expertos en acción en distintas materias y edades, con guías de reflexión.",
    "cd_t_025": "El recurso de referencia para el Aprendizaje Basado en Proyectos — kits de inicio, rúbricas e ideas de proyectos basados en investigación.",
    "cd_t_026": "Kit gratuito de design thinking de IDEO para educadores — un proceso centrado en el ser humano para resolver retos de aula y escolares.",
    "cd_t_027": "Recursos gratuitos de Expeditionary Learning — carácter, crew y evaluación basada en maestría con décadas de evidencia escolar.",
    "cd_t_028": "Artículos gratuitos de investigación a la práctica con video de aula — cada estrategia explicada, fundamentada y mostrada en acción.",
    "cd_t_029": "Más de 250 effect sizes de Hattie con descargas gratuitas — entiende qué prácticas docentes tienen mayor impacto y por qué.",
    "cd_t_030": "Protocolos gratuitos de Harvard PZ para hacer visible la comprensión del alumno — rutinas de pensamiento con guías de aplicación.",
    "cd_t_031": "Marco gratuito para adaptar la instrucción en tiempo real — uniendo la teoría de la evaluación formativa con la práctica momento a momento.",
    "cd_t_032": "Cursos auditables sobre diseño para el aprendizaje — diseño del entorno, teoría del engagement y pensamiento sistémico instruccional.",
    "cd_t_033": "Planes de clase, estrategias y herramientas de gestión de aula basados en investigación — todos vinculados a estándares de aprendizaje.",
    "cd_t_034": "Artículos, webinars y guías docentes basados en investigación del principal medio de periodismo educativo de EE. UU.",
    "cd_t_035": "Recursos prácticos gratuitos de investigación en ciencias del aprendizaje financiada por la NSF — traduciendo la neurociencia a la acción de aula.",
    "cd_t_036": "Centro Docente gratuito con formación, rutas de certificación y guías de integración en el aula — la plataforma docente gratuita más usada.",
    "cd_t_037": "Rutas de aprendizaje gratuitas con insignias sobre Teams, OneNote, Minecraft Edu y herramientas de IA para el aula.",
    "cd_t_038": "Artículos, videos y guías de DPC gratuitos curados sobre todos los aspectos de la enseñanza — el mejor punto de partida único para docentes.",
    "cd_t_039": "Rutas gratuitas estructuradas hacia la pedagogía moderna — por dónde empezar, qué leer y cómo crecer en tu práctica docente.",
    "cd_t_040": "Guías gratuitas de The New Teacher Project — cómo se ve la gran enseñanza y cómo construirla de forma sistemática.",
    "cd_t_041": "Portal gratuito de DPC de la National Education Association — cursos, webinars y recursos para cada etapa profesional.",
    "cd_t_042": "Recursos gratuitos seleccionados de ASCD para docentes en sus primeros años — montaje del aula, mentalidad y supervivencia inicial.",
    "cd_t_043": "Recursos de clase, artículos de consejo y foros comunitarios gratuitos pensados para docentes en sus primeros años.",
    "cd_t_044": "Iniciadores prácticos gratuitos para docentes nóveles — gestión de carga de trabajo, estrategias de corrección y afrontar tu primera clase.",
    "cd_t_045": "Onboarding docente gratuito de Khan Academy — configura tu aula, asigna trabajo y sigue el progreso del alumnado desde el primer día.",
    "cd_t_046": "Programa gratuito y autoguiado de reconocimiento Apple Teacher — gana insignias en iPad, Mac y aprendizaje creativo.",
    "cd_t_047": "Una membresía asociada gratuita da acceso a la revista Impact, resúmenes de investigación y foro comunitario para docentes del Reino Unido.",
    "cd_t_048": "Lecciones de lectura gratuitas alineadas con estándares para grados 3-12 — textos, preguntas, evaluaciones y unidades completas de ELA.",
    "cd_t_049": "Currículo gratuito de ELA y matemáticas PK-12 del estado de Nueva York — módulos anuales completos, guías docentes y cuadernos de alumno.",
    "cd_t_050": "Currículos abiertos top de matemáticas y ELA gratuitos (Illustrative Math, EL Education ELA) — cursos anuales completos creados por equipos líderes.",
    "cd_t_051": "Más de 420.000 planes de clase, actividades y unidades gratuitos compartidos por docentes de la AFT — buscables por materia, grado y estándar.",
    "cd_t_052": "La sección gratuita de Teachers Pay Teachers — millones de fichas, unidades y materiales imprimibles filtrados a la opción sin coste.",
    "cd_t_053": "Recursos gratuitos alineados al currículo del Reino Unido de la mayor comunidad docente del mundo — programaciones completas y packs de clase.",
    "cd_t_054": "Clips de video y lecciones listas alineadas al currículo y gratuitas de la BBC — sólidos en historia, ciencia y literatura inglesa.",
    "cd_t_055": "Planificador digital gratuito con vista semanal, alineación a estándares y vista de unidades — buen plan gratuito para docentes individuales.",
    "cd_t_056": "Planificador digital ligero — prueba gratuita de 30 días, luego un plan de bajo coste; vista semanal apreciada por docentes de aula.",
    "cd_t_057": "Biblioteca gratuita de planes de clase de docentes expertos en K-12 — revisados, probados en aula y alineados a Common Core.",
    "cd_t_058": "Biblioteca digital gratuita PBS K-12 — más de 100.000 videos, lecciones e interactivos alineados a estándares en todas las materias.",
    "cd_t_059": "Libros de texto digitales personalizables gratis (FlexBooks) para cada materia K-12 — adapta contenidos, añade notas y compártelos.",
    "cd_t_060": "Lecciones de pizarra interactiva y actividades listas para docentes de primaria — gran biblioteca gratuita de herramientas drag-and-drop.",
    "cd_t_061": "Crea clases interactivas combinando diapositivas, cuestionarios, video y encuestas — plan gratuito con miles de lecciones compartidas.",
    "cd_t_062": "Canva Pro gratis para docentes K-12 verificados — fichas, pósters, videos, diapositivas, animaciones e infografías en un solo estudio.",
    "cd_t_063": "Adobe Express gratis para docentes y alumnos K-12 — folletos, posts, videos y generación de imágenes con IA para cualquier clase.",
    "cd_t_064": "Millones de iconos gratuitos para fichas y diapositivas — atribución obligatoria, pero excelente calidad y variedad.",
    "cd_t_065": "Fotos gratuitas de alta calidad para cualquier material de aula — sin atribución requerida, totalmente usables en recursos de clase.",
    "cd_t_066": "Fotos, videos, ilustraciones y música gratuitas — totalmente usables en materiales de aula sin necesidad de atribución.",
    "cd_t_067": "Fotos y videos de stock gratuitos curados por una comunidad de fotógrafos — alta calidad, totalmente libres para uso educativo.",
    "cd_t_068": "Generador gratuito de nubes de palabras — convierte listas de vocabulario en visuales atractivos para displays, starters y chequeos formativos.",
    "cd_t_069": "Fichas configurables gratis de matemáticas y lectura — generar, imprimir, regenerar. Sin login, un clásico docente desde hace décadas.",
    "cd_t_070": "Genera hasta 7 estilos de juego diferentes a partir de una sola lista — gratis para docentes, ideal para vocabulario y repaso.",
    "cd_t_071": "Creador de videos animados explicativos — plan gratuito que admite videos de 5 minutos con amplia biblioteca de personajes.",
    "cd_t_072": "Editor de audio gratuito y de código abierto — graba podcasts, edita audio para clases y trabaja con cualquier formato.",
    "cd_t_073": "Editor de video de escritorio gratuito y de código abierto — sencillo para proyectos de alumnos, potente para tutoriales docentes.",
    "cd_t_074": "Herramienta de autoría gratuita y de código abierto — más de 50 tipos de contenido interactivo (cuestionarios, escenarios ramificados, drag-the-words) embebibles.",
    "cd_t_075": "Adapta cualquier texto a cualquier nivel de lectura al instante — pasajes nivelados, vocabulario y preguntas; la IA de diferenciación de referencia.",
    "cd_t_076": "Artículos de noticias nivelados gratuitos — cada artículo disponible en 5 niveles de lectura para acceso diferenciado al contenido.",
    "cd_t_077": "Biblioteca de lectura K-12 completa y gratuita — miles de pasajes nivelados y textos pareados con preguntas de comprensión.",
    "cd_t_078": "Pega cualquier texto difícil — Rewordify reemplaza palabras complicadas por otras más simples en línea, con definiciones al pasar el cursor.",
    "cd_t_079": "Material imprimible alineado al currículo y gratis para distintas edades y habilidades — adapta cualquier ficha de nivel arriba o abajo en segundos.",
    "cd_t_080": "Herramienta gratuita de Microsoft — lee cualquier texto en voz alta con foco de línea, división silábica, diccionario visual y más de 60 idiomas.",
    "cd_t_081": "Texto a voz gratis con voces naturales — lee PDFs, páginas web y documentos Word en voz alta para apoyar el acceso a la lectura.",
    "cd_t_082": "Tipografía gratuita y de código abierto pensada para la dislexia — diseñada para reducir la rotación de letras, incluye extensiones de navegador.",
    "cd_t_083": "Prueba gratuita de 30 días de la principal herramienta de apoyo a la alfabetización — texto a voz, tipeo predictivo y diccionario visual.",
    "cd_t_084": "Gratis para alumnos estadounidenses con dificultades de lectura — más de 1,4M de audiolibros y ebooks accesibles con texto a voz.",
    "cd_t_085": "El marco de referencia del Diseño Universal para el Aprendizaje — pautas, ejemplos y herramientas de implementación gratis para cada aula.",
    "cd_t_086": "Recursos completos y gratuitos para docentes y familias sobre dislexia, TDAH y diferencias de aprendizaje — basados en investigación y prácticos.",
    "cd_t_087": "Tareas, lecciones y herramientas de planificación alineadas a Common Core gratis del equipo que escribió los estándares — ELA y matemáticas.",
    "cd_t_088": "Portal oficial de los Common Core State Standards — estándares completos de Lengua Inglesa y Matemáticas, gratis y buscables.",
    "cd_t_089": "Portal gratuito de los Next Generation Science Standards — expectativas de desempeño, evidencias y lecciones ejemplares.",
    "cd_t_090": "Portal gratuito de los estándares ISTE — marco para una enseñanza innovadora con tecnología, con descriptores y rúbricas.",
    "cd_t_091": "Estándares gratuitos WIDA de desarrollo del inglés — usados en más de 40 estados de EE. UU. para planificación y evaluación de ELL/EAL.",
    "cd_t_092": "Plantillas y artículos de Understanding by Design de Wiggins y McTighe — diseño inverso desde objetivos hasta evidencias e instrucción.",
    "cd_t_093": "Ruedas gratuitas de referencia y verbos de la taxonomía de Bloom revisada — escribe objetivos de orden superior en segundos con verbos de acción.",
    "cd_t_094": "Recursos gratuitos de Pam Hook sobre la Taxonomía SOLO — la Estructura de Resultados de Aprendizaje Observados para una progresión clara en objetivos.",
    "cd_t_095": "Marcos de clase reutilizables gratis ligados a objetivos de aprendizaje — Cyber Sandwich, Iron Chef, Worst Preso Ever y más.",
    "cd_t_096": "Biblioteca gratuita de recursos educativos abiertos — más de 50.000 lecciones, unidades y cursos completos etiquetados por estándar.",
    "cd_t_097": "Mayor repositorio gratuito de OER — más de 70.000 recursos etiquetados por Common Core, NGSS y estándares estatales, con reseñas de calidad.",
    "cd_t_098": "Base de datos gratuita de John Hattie con más de 320 influencias en el logro estudiantil, ordenadas por effect size — elige estrategias de alto impacto.",
    "cd_t_099": "Lecciones interactivas en diapositivas con encuestas, cuestionarios, dibujos y RV — el plan gratuito Silver cubre la mayoría de necesidades de aula.",
    "cd_t_100": "Inserta preguntas y notas directamente en cualquier video — gratis para docentes (hasta 20 videos guardados) con analíticas completas.",
    "cd_t_101": "Grabación de pantalla ilimitada y gratuita para docentes verificados — graba videos de aula invertida con engagement integrado.",
    "cd_t_102": "Herramienta de screencasting gratuita con subtítulos amigables para el aula y alojamiento sencillo — usada por millones de docentes.",
    "cd_t_103": "Pantalla de aula todo-en-uno gratis — cronómetro, selector aleatorio de nombres, semáforo, símbolos de trabajo y medidor de ruido en una pantalla.",
    "cd_t_104": "Herramienta de curación gratuita — organiza videos, artículos, tweets y trabajos en colecciones compartibles para cualquier clase.",
    "cd_t_105": "Crea presentaciones interactivas, escape rooms e infografías — plan gratuito con cientos de plantillas para docentes.",
    "cd_t_106": "Añade hotspots a imágenes y videos con texto, audio y enlaces — el plan Basic gratuito cubre el uso en clases pequeñas.",
    "cd_t_107": "Videolecciones K-12 gratis con práctica de maestría — cálculo, biología, historia, finanzas y preparación SAT, todo gratis para siempre.",
    "cd_t_108": "Videos educativos animados gratuitos con herramientas didácticas integradas — prompts Pensar, Profundizar y Discutir junto a cada clip.",
    "cd_t_109": "Series de conferencias gratuitas en YouTube sobre historia, ciencia, literatura y economía — producción excepcional, presentada por expertos.",
    "cd_t_110": "Videos animados alineados al currículo con cuestionarios y mapas conceptuales en cada materia K-12 — prueba gratuita y temas gratis.",
    "cd_t_111": "Software de clase interactivo gratuito para cualquier pantalla táctil — diapositivas, herramientas y plantillas para enseñanza en gran grupo, interfaz en inglés.",
    "cd_t_112": "Más de 160 simulaciones interactivas gratuitas de física, química, biología y matemáticas de la Universidad de Colorado — traducidas a más de 90 idiomas.",
    "cd_t_113": "Matemáticas dinámicas gratis — geometría, álgebra, cálculo, 3D y estadística en una herramienta. Usada por más de 100M de estudiantes.",
    "cd_t_114": "Plataforma gratuita de Autodesk con diseño 3D, simulación electrónica y bloques de código — creada específicamente para el aula.",
    "cd_t_115": "Plataforma gratuita de programación por bloques del MIT — más de 100M de proyectos, la puerta de entrada a la programación para niños desde 8 años.",
    "cd_t_116": "Experimentos musicales lúdicos gratis de Google — Song Maker, Rhythm, Spectrogram, Kandinsky. Sin login, funcionan en cualquier navegador.",
    "cd_t_117": "Software gratuito y de código abierto de notación musical — escribe, reproduce e imprime partituras para cualquier instrumento o conjunto.",
    "cd_t_118": "DAW colaborativo en navegador — graba podcasts y música con alumnos en tiempo real. Plan gratuito generoso.",
    "cd_t_119": "Software gratuito y de código abierto de pintura y animación digital profesional — motor de pinceles completo, usado en escuelas de arte.",
    "cd_t_120": "Planetario gratuito en tu navegador — muestra a los alumnos el cielo nocturno desde cualquier lugar y momento, ideal para clases de astronomía.",
    "cd_t_121": "Calculadora gráfica y actividades de aula gratis — el estándar de oro para visualizar funciones en clases de matemáticas.",
    "cd_t_122": "Currículo gratuito de informática K-12 — Hour of Code, cursos anuales, AI Lab y Dance Party. Usado por más de 60M de estudiantes.",
    "cd_t_123": "Globo terráqueo 3D gratis en el navegador — tours Voyager de cultura, historia y ciencia; crea marcadores propios para cualquier clase de geografía.",
    "cd_t_124": "Plan Education gratuito con tableros y plantillas ilimitadas para docentes verificados — la herramienta de colaboración visual más querida.",
    "cd_t_125": "FigJam gratis para educadores y alumnos — pizarra colaborativa con plantillas estupendas y funciones de engagement.",
    "cd_t_126": "Muro de notas adhesivas gratuito para publicar ideas, fotos, enlaces y audios — tres padlets gratis y muy querido por docentes.",
    "cd_t_127": "Pizarra virtual gratuita y de código abierto con estética dibujada a mano — colaboración instantánea, sin login y con cifrado de extremo a extremo.",
    "cd_t_128": "Panel docente instantáneo y gratis — cada alumno tiene su propia pizarra y el docente las ve todas en vivo.",
    "cd_t_129": "3 mapas mentales gratis con colaboración — ideal para mapeo de conceptos en clase y proyectos en grupo.",
    "cd_t_130": "Mapas mentales públicos ilimitados gratis — jerarquía visual limpia, colaboración en tiempo real e inserción de imágenes.",
    "cd_t_131": "Plan educativo gratuito de la pizarra de Lucid — notas adhesivas, votación y lienzo infinito para lluvia de ideas en clase.",
    "cd_t_132": "Gratis para estudiantes y docentes verificados de educación superior — espacio visual colaborativo para design thinking y trabajo en grupo.",
    "cd_t_133": "Diagramación gratuita y de código abierto — diagramas de flujo, ER, UML y mapas mentales. Guarda directo en Drive o OneDrive.",
    "cd_t_134": "Pizarra interactiva gratuita y de código abierto para escuelas — funciona con cualquier proyector o pantalla interactiva, sin suscripción.",
    "cd_t_135": "Pizarra colaborativa gratuita dentro de Teams y Office — notas adhesivas, tinta, imágenes y plantillas con autoguardado.",
    "cd_t_136": "Mapeo mental visual sencillo para el aula — los alumnos hacen lluvia de ideas, organizan conceptos y comparten tableros en tiempo real.",
    "cd_t_137": "El clásico formato de juego de preguntas — el plan Basic gratuito admite hasta 40 jugadores para evaluación formativa en vivo.",
    "cd_t_138": "Cuestionarios y lecciones autodirigidos con IA — gratis para docentes con amplios bancos de preguntas y modo en vivo.",
    "cd_t_139": "Encuestas en vivo, nubes de palabras y Q&A del público — el plan gratuito cubre perfectamente la evaluación formativa en clases pequeñas.",
    "cd_t_140": "Añade preguntas interactivas a Google Slides o PowerPoint — el plan gratuito admite los formatos de evaluación formativa más queridos.",
    "cd_t_141": "Encuestas, sondeos y Q&A en vivo superpuestos en cualquier reunión o clase — plan gratuito que admite hasta 100 participantes.",
    "cd_t_142": "Cuestionarios rápidos, exit tickets y juego Space Race — gratis para hasta 50 alumnos por sala.",
    "cd_t_143": "Tarjetas QR en papel y escaneo con teléfono — evaluación formativa sin dispositivos del alumno, gratis hasta 60 tarjetas.",
    "cd_t_144": "Juegos tipo cuestionario con plantillas — match-up, anagrama, gameshow — genera cualquier actividad desde una lista; gratis hasta 5 guardados.",
    "cd_t_145": "Mira las respuestas del alumnado en vivo mientras escriben — dibujos, ecuaciones, párrafos. El plan Bronze gratuito cubre el uso formativo central.",
    "cd_t_146": "Herramienta gratuita de feedback instantáneo con nube de palabras — formula una pregunta, los alumnos responden en 20 caracteres y observa cómo crecen.",
    "cd_t_147": "Encuestas en vivo embebidas en PowerPoint o Google Slides — el plan gratuito admite hasta 25 respuestas por encuesta.",
    "cd_t_148": "Plataforma de cuestionarios gamificados muy popular entre adolescentes — partidas en vivo o asignaciones autodirigidas. Plan gratuito de uso completo.",
    "cd_t_149": "Más de 40 plantillas listas de widgets interactivos — cuestionarios, crucigramas, exit tickets, ruletas — autocorregidos y embebibles.",
    "cd_t_150": "El LMS gratuito por defecto para millones de docentes — tareas, calificaciones, comunicación y compartir archivos en un solo lugar.",
    "cd_t_151": "Plan educativo gratuito con clases, tareas, cuadernos OneNote y 1TB de almacenamiento OneDrive por alumno.",
    "cd_t_152": "Versión gratuita del LMS líder en educación superior — tareas, calificaciones y rúbricas completas para docentes individuales.",
    "cd_t_153": "LMS gratuito y de código abierto usado en universidades de todo el mundo — autohospedado o el plan gratuito MoodleCloud para clases pequeñas.",
    "cd_t_154": "LMS gratis para docentes individuales — tareas, libreta de calificaciones, cuestionarios y comunicación con familias en una plataforma.",
    "cd_t_155": "Libreta de calificaciones por estándares con la confianza de más de 5M de alumnos — gratis para docentes individuales; planes pagos para escuelas.",
    "cd_t_156": "Libreta de calificaciones e informes en web — el plan gratuito cubre necesidades de aula; integra con los principales LMS.",
    "cd_t_157": "Cuestionarios autocorregidos gratis con feedback instantáneo y analíticas — la herramienta de cabecera para calificar en Google Classroom.",
    "cd_t_158": "Cuestionarios y encuestas gratis con autocorrección y lógica ramificada — incluido con cualquier cuenta de Microsoft.",
    "cd_t_159": "Generador de rúbricas gratuito — elige plantilla, personaliza criterios, imprime o guarda. Usado por docentes desde hace más de 20 años.",
    "cd_t_160": "Constructor y galería de rúbricas gratuita con miles de plantillas compartidas por docentes — adáptalas y reúsalas con atribución.",
    "cd_t_161": "SIS K-12 con libreta de calificaciones e informes basados en estándares — prueba gratuita; muchos distritos ofrecen acceso.",
    "cd_t_162": "Plan gratuito de Grammarly — sugerencias de gramática, claridad y tono para escritos del alumnado en navegador, Word y Docs.",
    "cd_t_163": "App web gratuita que resalta oraciones complejas, voz pasiva y adverbios — escritura del alumnado más clara en segundos.",
    "cd_t_164": "Anotación gratuita de PDFs y documentos — añade comentarios, notas de voz, dibujos y stickers directamente sobre el trabajo del alumno.",
    "cd_t_165": "Add-on gratuito de Google Sheets para autoevaluación, evaluación entre pares y por rúbrica docente — genera feedback personalizado por alumno.",
    "cd_t_166": "Extensión gratuita de Chrome que añade una barra lateral de IA a Google Docs y Slides — feedback instantáneo, nivelación y rúbricas.",
    "cd_t_167": "Extensión gratuita de comentarios por voz en Chrome para Google Docs, Slides y Classroom — deja audios de 30 segundos en segundos.",
    "cd_t_168": "Herramienta gratuita de feedback por voz para escritos — vincula etiquetas de rúbrica a comentarios y reúsa feedback común entre alumnos.",
    "cd_t_169": "Feedback ultrarrápido para matemáticas y ciencias — los alumnos suben su trabajo, los docentes comentan con un banco reusable.",
    "cd_t_170": "Add-on gratuito de Google Docs para feedback de escritura por lotes — inserta comentarios estándar desde una biblioteca docente.",
    "cd_t_171": "Práctica adaptativa de gramática y escritura — gratis para docentes con feedback autocorregido en cada respuesta.",
    "cd_t_172": "Herramientas interactivas gratuitas de escritura y gramática — práctica adaptativa a nivel de oración para grados 3-12 con feedback instantáneo.",
    "cd_t_173": "Editor de estilo gratuito con más de 25 informes — gramática, legibilidad, transiciones y palabras sobreusadas en escritos del alumnado.",
    "cd_t_174": "Plataforma gratuita de Microsoft de discusión por video — los alumnos publican breves reflexiones en video; los docentes crean temas seguros.",
    "cd_t_175": "Portafolios digitales creados por alumnos con visibilidad para familias — el plan gratuito Seesaw for Schools cubre aulas individuales.",
    "cd_t_176": "Los alumnos diseñan ebooks para reflexión o proyectos — gratis para una biblioteca de 40 libros por docente.",
    "cd_t_177": "Herramienta gratuita de Microsoft — cada alumno tiene un cuaderno privado para diarios y reflexiones, más una biblioteca compartida y espacio colaborativo.",
    "cd_t_178": "Herramienta gratuita de check-in emocional dentro de Teams for Education — los alumnos eligen emociones; los docentes ven tendencias de bienestar.",
    "cd_t_179": "Plataforma gratuita de creación para historias y reflexiones digitales del alumnado — combina texto, voz, video y animación en un lienzo.",
    "cd_t_180": "Plan Plus gratuito para educadores verificados — diarios de reflexión, registros de aprendizaje y portafolios de proyectos en un único espacio.",
    "cd_t_181": "Blogs de clase y de alumnos gratuitos con WordPress — ideales para diarios de reflexión, con moderación docente integrada.",
    "cd_t_182": "Líneas de tiempo e historias interactivas gratuitas para reflexiones y narrativas de proyectos — colaborativas e imprimibles.",
    "cd_t_183": "Backchannel anónimo gratuito para discusión en clase — recoge reflexiones rápidas en texto e imagen desde cualquier dispositivo.",
    "cd_t_184": "Historias en mapa gratuitas de ArcGIS — los alumnos reflexionan combinando texto, fotos, video y datos geográficos.",
    "cd_t_185": "Herramienta gratuita de reflexión Q&A en video — formula una pregunta, los alumnos graban respuestas breves y la clase las revisa juntas.",
    "cd_t_186": "Paneles gratuitos para familias en todas las materias K-12 — sigue el progreso, ve fortalezas y debilidades, comparte con docentes.",
    "cd_t_187": "Repaso gratuito alineado al currículo del Reino Unido por niveles — guías para familias sobre cómo apoyar tareas y exámenes.",
    "cd_t_188": "10 preguntas/día gratis en 8.500 destrezas — práctica K-12 completa con informes de progreso amigables para familias.",
    "cd_t_189": "Reseñas gratuitas de cada app, juego y película infantil — ayuda a las familias a tomar decisiones mediáticas inteligentes basadas en investigación.",
    "cd_t_190": "Prueba gratuita de 30 días del currículo integral de educación temprana — fonética, matemáticas, arte y música para edades 2-8.",
    "cd_t_191": "Prueba gratuita del programa líder de lectura temprana — fonética, palabras frecuentes y libros decodificables para edades 3-13.",
    "cd_t_192": "Práctica adaptativa de matemáticas K-12 con torneos mundiales — pruebas gratuitas en casa y seguimiento de progreso para familias.",
    "cd_t_193": "Matemáticas gamificadas gratis para grados 1-8 — los niños vencen monstruos respondiendo preguntas, las familias reciben informes semanales.",
    "cd_t_194": "Plataforma gratuita de repaso GCSE/A-level para familias del Reino Unido — cursos interactivos basados en ciencia cognitiva.",
    "cd_t_195": "Tarjetas y modos de estudio gratis — más de 500 millones de sets cubriendo cada materia y programa de examen.",
    "cd_t_196": "Imprimibles, fichas y packs de actividades alineados al currículo y gratuitos — con base en el Reino Unido pero usados en más de 200 países.",
    "cd_t_197": "Más de 40.000 ebooks, audiolibros y videos infantiles — gratis para educadores verificados, de bajo coste para familias.",
    "cd_t_198": "Construye una cultura de aula positiva — puntos, mensajes a familias y portafolios. Gratis para todos los docentes y familias.",
    "cd_t_199": "Plataforma gamificada de gestión de aula — los alumnos ganan XP y poderes por buena conducta. Plan gratuito generoso.",
    "cd_t_200": "Medidor visual de ruido en el aula que se anima con el sonido — la versión Lite gratuita es muy querida por docentes de primaria.",
    "cd_t_201": "Medidor de ruido visual divertido y gratis — pelotas que rebotan al volumen del aula. Perfecto como herramienta de fondo durante el trabajo en grupo.",
    "cd_t_202": "Selector aleatorio de nombres gratis — gira la ruleta para elegir alumnos con justicia. Listas guardadas, colores personalizados y sin anuncios.",
    "cd_t_203": "Cronómetros divertidos para el aula gratis — bombas, velas, autos de carrera — mantén las actividades a tiempo con visuales atractivos.",
    "cd_t_204": "Generador gratuito de planos de asientos con seguimiento de puntos de conducta — usado en miles de escuelas del Reino Unido, gratis para docentes individuales.",
    "cd_t_205": "Plataforma de refuerzo positivo de conducta para toda la escuela — prueba gratuita; muchos recursos PBIS gratuitos en el sitio.",
    "cd_t_206": "Videos gratuitos de movimiento y mindfulness — pausas activas breves probadas para reenfocar a alumnos K-5 a mitad de clase.",
    "cd_t_207": "Saludos, actividades e ideas de mensajes gratis para reuniones matinales — comunidad socioemocional de aula basada en investigación.",
    "cd_t_208": "Recursos SEL gratis y webinars semanales de la organización de referencia en investigación de aprendizaje socioemocional.",
    "cd_t_209": "El blog docente más seguido del Reino Unido — estrategias prácticas gratis sobre conducta, engagement y rutinas.",
    "cd_t_210": "Selector aleatorio de alumnos gratis — selección animada y justa que mantiene el cold-calling impredecible y atractivo para toda la clase.",
    "cd_t_211": "Envía mensajes seguros y unidireccionales a alumnos y familias — el plan gratuito cubre anuncios diarios con autotraducción.",
    "cd_t_212": "Mensajería gratuita de engagement familiar que autotraduce entre docentes y familias en más de 100 idiomas.",
    "cd_t_213": "Mensajería segura y gratis para familias con compartición de fotos y videos — traduce mensajes automáticamente a más de 35 idiomas.",
    "cd_t_214": "Comunicación con familias y agendador de reuniones gratuitos — favorito en infantil y primaria, con compartición de fotos.",
    "cd_t_215": "Hermosos boletines de aula con drag-and-drop — el plan gratuito admite 5 boletines con herramientas de diseño completas.",
    "cd_t_216": "Plataforma de comunicación para toda la escuela con autotraducción — muchos distritos ofrecen cuentas docentes gratis vía planes escolares.",
    "cd_t_217": "Traducción instantánea gratuita en más de 130 idiomas — texto, fotos, conversaciones y documentos para comunicación con familias.",
    "cd_t_218": "Traducciones de mayor calidad que Google para idiomas europeos — el plan gratuito cubre la mayoría de las necesidades docentes.",
    "cd_t_219": "Traducción gratuita de conversaciones en tiempo real para reuniones con familias — los teléfonos hablan cada idioma y la app subtitula en vivo.",
    "cd_t_220": "Agendado de reuniones, inscripciones a fiestas de clase y rosters de voluntariado gratuitos — la herramienta de coordinación familiar.",
    "cd_t_221": "Plan gratuito de email (hasta 500 contactos) — ideal para boletines de clase, actualizaciones a familias y comunicación de la PTA.",
    "cd_t_222": "Herramienta gratuita de Microsoft para boletines e informes interactivos — plantillas hermosas, autoflow, sin necesidad de formato.",
    "cd_t_223": "15GB gratis de almacenamiento en la nube con Docs, Sheets y Slides — comparte materiales y recoge tareas sin fricciones.",
    "cd_t_224": "5GB gratis de almacenamiento en la nube con Office Online — Word, Excel, PowerPoint con controles de compartición amigables para el aula.",
    "cd_t_225": "Plan gratuito de 2GB con compartición en aula y carpetas colaborativas — planes educativos con descuento disponibles.",
    "cd_t_226": "Plan gratuito de 10GB — sólido en permisos y trazabilidad, popular entre administradores de distrito y educación superior.",
    "cd_t_227": "Plan Plus gratuito para educadores verificados — wikis, notas de clase, seguimiento de alumnos y hubs colaborativos de aula.",
    "cd_t_228": "Base de datos flexible y gratis — ideal para seguimiento de datos del alumnado, objetivos IEP, portafolios de proyectos y mapas curriculares.",
    "cd_t_229": "Tableros kanban gratis — sigue planificación de clases, proyectos del alumnado, comités escolares y to-dos personales del docente.",
    "cd_t_230": "Gratis para equipos de hasta 15 personas — gestiona proyectos de mejora escolar, flujos de trabajo de departamento y tareas administrativas.",
    "cd_t_231": "Herramienta gratuita de reservas — comparte un enlace, las familias eligen horario para reuniones. Se acabaron los emails de ida y vuelta.",
    "cd_t_232": "Encuesta gratuita de horarios para reuniones de personal y familias — encuentra cuándo todos pueden reunirse sin hilos interminables.",
    "cd_t_233": "Espacio de trabajo gratuito para equipos de personal — canales por departamento, mensajes directos e integraciones con Drive, Calendar y más.",
    "cd_t_234": "5GB gratis de almacenamiento Apple en la nube con Pages, Numbers y Keynote en navegador — ideal para aulas con Apple.",
    "cd_t_235": "Iniciativa gratuita de Calm para docentes K-12 — acceso completo a la app incluyendo sleep stories, meditaciones y música.",
    "cd_t_236": "Headspace Plus gratis para docentes K-12 verificados en EE. UU., Reino Unido, Canadá y Australia — mindfulness y meditación.",
    "cd_t_237": "App de meditación gratuita con la mayor biblioteca gratis — más de 200.000 meditaciones guiadas y pistas específicas para docentes.",
    "cd_t_238": "Artículos, prácticas guiadas e investigación sobre mindfulness gratis — introducción accesible para docentes con estrés.",
    "cd_t_239": "Recursos SEL basados en ciencia y gratis de Berkeley para docentes — prácticas de gratitud, bondad y resiliencia en aula.",
    "cd_t_240": "Podcast y artículos gratuitos de Daniela Falecki — estrategias prácticas de bienestar y prevención del burnout para docentes.",
    "cd_t_241": "Organización benéfica del Reino Unido — línea de ayuda 24/7 gratis, terapia y recursos de salud mental para cualquier docente, sin importar el país.",
    "cd_t_242": "Movimiento global gratuito de reuniones de apoyo a la salud mental docente — más de 100 capítulos en todo el mundo, en línea y presenciales.",
    "cd_t_243": "Artículos y episodios de podcast gratuitos de Jennifer Gonzalez sobre autocuidado docente — práctico, honesto y sin positividad tóxica.",
    "cd_t_244": "Blog gratuito con estrategias realistas para gestionar el estrés, las familias y la administración — escrito por docentes de aula.",
    "cd_t_245": "Kits MHA gratuitos — autoevaluación de burnout, estrategias de afrontamiento basadas en evidencia y directorios de apoyo en crisis.",
    "cd_t_246": "Programa interactivo gratuito de terapia cognitivo-conductual — autoayuda probada para estrés y bajo ánimo, usado en todo el mundo.",
    "cd_t_247": "Más de 60 herramientas de IA creadas por docentes — planes de clase, objetivos IEP, rúbricas, diferenciación y feedback. Plan gratuito generoso.",
    "cd_t_248": "Lecciones interactivas generadas por IA en 30 segundos — diapositivas, encuestas, dibujos y exit tickets, con un plan gratuito sólido para docentes.",
    "cd_t_249": "Más de 100 generadores para planes de clase, evaluaciones y adaptaciones — el plan gratuito cubre la mayoría de las necesidades cotidianas.",
    "cd_t_250": "Espacios de chat con IA seguros y monitorizados para alumnos más un asistente IA para docentes — plan gratuito generoso para K-12.",
    "cd_t_251": "Asistente IA insignia de Anthropic — excepcional para planificar clases, redactar rúbricas, emails a familias y borradores de feedback.",
    "cd_t_252": "El plan gratuito de OpenAI cubre GPT-4o mini — fuerte para generación de preguntas, resúmenes y creación de fichas.",
    "cd_t_253": "IA de Google profundamente integrada en Docs, Slides y Drive — ideal para docentes que ya viven en Google Workspace.",
    "cd_t_254": "IA gratis dentro de Word, OneNote, PowerPoint — genera esquemas de clase, presentaciones y materiales para alumnos en sitio.",
    "cd_t_255": "Sube capítulos de tu libro y notas — la IA de Google responde estrictamente desde tus fuentes, con resúmenes en audio para repasar.",
    "cd_t_256": "Curso gratuito de Anthropic sobre las cuatro competencias centrales con IA — delegación, descripción, discernimiento, diligencia. Hecho para educadores.",
    "cd_t_257": "Tutor IA gratuito de Khan Academy para docentes — planificación, emails a familias y tutoría socrática del alumnado en materias K-12.",
    "cd_t_258": "Buscador con IA que cita cada afirmación — perfecto cuando los docentes necesitan fuentes verificables en lugar de respuestas alucinadas.",
    "cd_t_259": "Pega cualquier texto y obtén preguntas esenciales y objetivos alineados, además de cuestionarios autogenerados — plan gratuito ilimitado.",
    "cd_t_260": "Guía gratuita del Teacher Development Trust — investigación sobre qué desarrollo profesional realmente mejora la enseñanza y los resultados.",
    "cd_t_261": "Los estándares globales para un aprendizaje profesional efectivo — un marco claro para evaluar y planificar tu propio DPC.",
    "cd_t_262": "Artículos, videos y guías de DPC curados gratis sobre todos los aspectos de la enseñanza — el mejor punto de partida todo en uno.",
    "cd_t_263": "Rutas estructuradas gratuitas hacia la pedagogía moderna — qué leer, ver y probar mientras creces como docente.",
    "cd_t_264": "Toolkit gratuito de la Education Endowment Foundation — estrategias evaluadas con orientación clara sobre dónde enfocar.",
    "cd_t_265": "Guías gratuitas de The New Teacher Project sobre cómo se ve la enseñanza efectiva y cómo construirla paso a paso.",
    "cd_t_266": "Encuesta semanal de 3 preguntas + recursos de DPC — ve cómo piensan miles de colegas y compara tu propia práctica.",
    "cd_t_267": "Empieza por ti — el MOOC gratuito de Barbara Oakley sobre memoria, chunking y foco. Esencial antes de diseñar aprendizaje para otros.",
    "cd_t_268": "Introducción gratuita al Ciclo Reflexivo de Gibbs y otros modelos — convierte tus experiencias docentes en crecimiento estructurado.",
    "cd_t_269": "Portal gratuito de DPC de la National Education Association — cursos, webinars y recursos mapeados a cada etapa profesional.",
    "cd_t_270": "Membresía asociada gratuita — accede a la revista Impact, resúmenes de investigación y comunidad docente para enseñanza basada en evidencia.",
    "cd_t_271": "Cursos introductorios gratuitos de la Open University en educación — enseñanza inclusiva, mentoría y liderazgo escolar. Sin requisitos de acceso.",
    "cd_t_272": "Audita gratis cursos de Stanford, Penn y Johns Hopkins sobre enseñanza — certificados pagos disponibles, pero todo el contenido es gratis.",
    "cd_t_273": "Cursos de educación de Harvard, MIT y HarvardX — gratis para auditar, con MicroMasters opcionales para liderazgo escolar.",
    "cd_t_274": "Cursos cortos gratuitos de enseñanza de universidades del Reino Unido — pedagogía práctica, EdTech y DPC por materia.",
    "cd_t_275": "Formación gratuita que conduce a los exámenes Google Certified Educator nivel 1 y 2 — credencial tecnológica de aula reconocida globalmente.",
    "cd_t_276": "Insignias gratuitas Microsoft Innovative Educator — Teams, OneNote, Minecraft Edu, herramientas de IA y colaboración global.",
    "cd_t_277": "Programa gratuito y autoguiado de reconocimiento Apple Teacher — gana insignias Swift y credenciales de creatividad en aula.",
    "cd_t_278": "Certificados gratuitos acreditados de docencia y educación — gestión de aula, necesidades especiales, primera infancia y más.",
    "cd_t_279": "Cursos gratuitos de la OU con declaraciones de participación — enseñanza inclusiva, mentoría, liderazgo escolar y competencias digitales.",
    "cd_t_280": "Materiales completos de cursos del MIT disponibles gratis — videos, problem sets y notas docentes de clases reales del MIT.",
    "cd_t_281": "Cursos universitarios acreditados y gratuitos — completa cursos enteros y recibe expedientes sin coste.",
    "cd_t_282": "Certificación Common Sense Educator gratuita en ciudadanía digital — práctica y reconocida internacionalmente.",
    "cd_t_283": "Webinars, artículos y DPC gratuitos de ISTE, la principal organización mundial de EdTech — membresía comunitaria incluida.",
    "cd_t_284": "El recurso de referencia para el aprendizaje basado en proyectos — kits, rúbricas y bibliotecas de proyectos gratis de la autoridad global del PBL.",
    "cd_t_285": "Recursos gratuitos sobre diseño de aula invertida — cómo grabar, invertir y aprovechar el tiempo presencial para aprendizaje activo.",
    "cd_t_286": "Guía gratuita de la NSTA sobre ciencia basada en indagación — cómo pasar de la demostración a la investigación dirigida por el alumnado.",
    "cd_t_287": "Artículos introductorios gratis sobre las Estructuras Kagan — Think-Pair-Share, Jigsaw y más de 200 técnicas de aprendizaje cooperativo.",
    "cd_t_288": "Pautas gratuitas del Diseño Universal para el Aprendizaje — cómo diseñar cada clase para que funcione con todo el rango de aprendices.",
    "cd_t_289": "Toolkit gratuito de IDEO para educadores — aplica design thinking centrado en el ser humano a retos de aula y creación de clases.",
    "cd_t_290": "Más de 30 rutinas de pensamiento de Harvard PZ — protocolos estructurados que profundizan el pensamiento del alumnado en cualquier materia.",
    "cd_t_291": "Recursos gratuitos de ASCD sobre instrucción diferenciada — cómo escalonar tareas, flexibilizar agrupamientos y ajustar el ritmo.",
    "cd_t_292": "Recursos instruccionales gratuitos de Expeditionary Learning — carácter, hábitos de trabajo y evaluación basada en maestría en acción.",
    "cd_t_293": "Más de 250 effect sizes — descubre qué métodos de enseñanza tienen mayor impacto en el logro estudiantil y por qué.",
    "cd_t_294": "Videoteca gratuita de técnicas de aula — cold call, no opt out, comprobar comprensión y más de 60 estrategias.",
    "cd_t_295": "Artículos prácticos sobre cómo aplicar cada gran enfoque instruccional — con videos de aula y consejos de implementación.",
    "cd_t_296": "Tareas gratuitas de enriquecimiento matemático de Cambridge — problemas ricos que desarrollan razonamiento, no solo cálculo. Buscables por edad y tema.",
    "cd_t_297": "Recursos gratuitos de enseñanza de la alfabetización — estrategias de lectura, fonética, fluidez y participación familiar.",
    "cd_t_298": "Simulaciones interactivas gratis de ciencia y matemáticas de la Universidad de Colorado — guías docentes incluidas para cada simulación.",
    "cd_t_299": "Recursos gratuitos de implementación de los Next Generation Science Standards — unidades narrativas, fenómenos y guías tridimensionales.",
    "cd_t_300": "Lecciones gratuitas de geografía, ciencia e historia de National Geographic — mapas, videos, artículos y guías docentes.",
    "cd_t_301": "Plataforma gratuita de ELA para docentes — textos alineados a estándares, preguntas de discusión y evaluaciones para grados 3–12.",
    "cd_t_302": "Miles de recursos gratuitos para enseñar inglés — poesía, drama, escritura creativa y preparación de exámenes para docentes de secundaria.",
    "cd_t_303": "Recursos gratuitos de enseñanza de historia de la principal revista de historia del Reino Unido — artículos, fuentes y propuestas de clase.",
    "cd_t_304": "Recursos gratuitos de enseñanza de química de la Royal Society of Chemistry — planes de clase, DPC y guías prácticas.",
    "cd_t_305": "Acertijos matemáticos desafiantes gratuitos y problemas no resueltos para K-12 — diseñados para crear lucha hermosa y pensamiento profundo.",
    "cd_t_306": "Lecciones animadas TED-Ed curadas en cada materia — herramientas gratuitas de planificación, guías de discusión y cuestionarios.",
    "cd_t_307": "Fotos y estímulos gratuitos para inspirar la escritura — usa trabajos publicados de alumnos como modelo para elevar los estándares.",
    "cd_t_308": "Recursos gratuitos de Jim Knight sobre el ciclo de impacto — un marco basado en investigación para el coaching docente y la automejora.",
    "cd_t_309": "Recursos gratuitos de mentoría de NTC — cómo estructurar conversaciones de mentoría, observar de forma efectiva y dar feedback útil.",
    "cd_t_310": "Recursos gratuitos de ASCD sobre liderazgo docente — cómo liderar desde el aula sin un cargo formal.",
    "cd_t_311": "Artículos y videos gratuitos sobre coaching instruccional — observación entre pares, ciclos de feedback y construcción de cultura de coaching.",
    "cd_t_312": "Recursos gratuitos sobre cómo construir una comunidad profesional de aprendizaje — cómo los líderes docentes impulsan la mejora escolar.",
    "cd_t_313": "National Board for Professional Teaching Standards — recursos gratuitos de preparación para la credencial docente de referencia.",
    "cd_t_314": "Estándares gratuitos de aprendizaje profesional — cómo diseñar y liderar DPC que realmente mejore la enseñanza y los resultados.",
    "cd_t_315": "Recursos gratuitos de Teach Like a Champion para líderes instruccionales — marcos de observación, herramientas de feedback y videos de coaching.",
    "cd_t_316": "Recursos gratuitos para educadores que asumen liderazgo — mapeo curricular, planificación colaborativa y construcción de comunidad.",
    "cd_t_317": "Guías gratuitas de mando intermedio — gestionar hacia arriba, liderar un equipo, gestionar la carga y mantener conversaciones difíciles.",
    "cd_t_318": "Recursos gratuitos de liderazgo de Education Week — investigación, casos y análisis de políticas para líderes docentes y directores.",
    "cd_t_319": "Marco gratuito de estándares ISTE para líderes EdTech — un mapa para liderar el aprendizaje digital en cualquier escuela o distrito.",
    "cd_t_320": "El estándar de oro — evaluaciones gratuitas de evidencia para más de 50 estrategias docentes, con effect size, coste e implementación.",
    "cd_t_321": "Más de 250 effect sizes de Hattie sobre logro estudiantil — entiende qué estrategias funcionan y cuáles son mitos educativos.",
    "cd_t_322": "Charlas gratuitas, posts y una comunidad global dedicada a mejorar la alfabetización en investigación educativa.",
    "cd_t_323": "Reseñas gratuitas del Departamento de Educación de EE. UU. sobre intervenciones — evaluaciones rigurosas e imparciales de programas y prácticas.",
    "cd_t_324": "Resúmenes gratuitos de estrategias de estudio basadas en evidencia — práctica espaciada, recuperación, intercalado y más, explicados para docentes.",
    "cd_t_325": "Artículos gratuitos de un científico cognitivo sobre por qué los alumnos piensan y aprenden como lo hacen — directamente aplicable al diseño de clases.",
    "cd_t_326": "Informes y resúmenes de investigación gratuitos de NFER — investigación educativa independiente y rigurosa del Reino Unido.",
    "cd_t_327": "Investigación educativa gratuita de Brookings Institution — análisis de políticas basado en evidencia y resúmenes orientados al docente.",
    "cd_t_328": "Investigación gratuita de RAND sobre efectividad docente, currículo y sistemas educativos — rigurosa, revisada por pares y de acceso libre.",
    "cd_t_329": "Investigación traducida a la práctica de aula — cada artículo expone con claridad la base de evidencia y los pasos de implementación.",
    "cd_t_330": "Recursos gratuitos de Marzano sobre estrategias instruccionales — nueve estrategias de alto rendimiento basadas en 35 años de investigación.",
    "cd_t_331": "Hub gratuito de investigación educativa del gobierno de EE. UU. — base ERIC, guías prácticas y What Works Clearinghouse en un solo lugar.",
    "cd_t_332": "Encuesta diaria de 3 preguntas + contenido semanal de DPC — ve cómo responden más de 10.000 colegas y compara tus propias opiniones.",
    "cd_t_333": "Foros gratuitos por materia y nivel — compartir recursos, hilos de consejos y discusiones de carrera de una comunidad docente global.",
    "cd_t_334": "La mayor PLN docente informal del mundo — #EduTwitter, #EduChat y cientos de hashtags por materia conectan a educadores globalmente.",
    "cd_t_335": "Discusión docente anónima y honesta — conversación real sobre carga, conducta, administración y lo que realmente funciona en el aula.",
    "cd_t_336": "Comunidad global gratuita de docentes orientados a la evidencia — conferencias anuales, eventos regionales y debates en línea.",
    "cd_t_337": "Inconferencias docentes informales gratuitas — comparticiones de docente a docente de 7 y 2 minutos, locales y en línea en todo el mundo.",
    "cd_t_338": "Google Educator Groups locales y en línea en más de 100 países — aprendizaje profesional, eventos y apoyo entre pares para docentes Google.",
    "cd_t_339": "Comunidad gratuita de educadores Microsoft — comparte clases, gana insignias y conecta con innovadores que usan Microsoft en educación.",
    "cd_t_340": "Comunidad gratuita de blogueo y discusión de Edutopia — comparte tu historia docente y lee qué está funcionando en aulas de todo el mundo.",
    "cd_t_341": "Red gratuita de la National Education Association para miembros — conexiones profesionales, herramientas de incidencia y apoyo entre pares.",
    "cd_t_342": "Grupos gratuitos de educadores en LinkedIn — networking profesional, desarrollo de carrera y liderazgo de pensamiento en educación.",
    "cd_t_343": "Red de educadores de ISTE — espacios comunitarios gratuitos, grupos de interés especial y discusiones sobre EdTech y aprendizaje innovador.",
}
