ES_STUDENTS = {
    "cd_000": "App galardonada de alfabetización temprana — letras, fonética, cuentos y escritura, todo gratis y sin anuncios.",
    "cd_001": "Actores célebres leen libros infantiles en voz alta — bellos videos que cultivan la escucha y lectura tempranas.",
    "cd_002": "Más de 40.000 libros digitales, audiolibros y lecturas guiadas — gratis para docentes durante el horario escolar.",
    "cd_003": "Miles de pasajes de lectura de alta calidad con preguntas de comprensión, todos gratuitos para K-12.",
    "cd_004": "Biblioteca digital gratuita con más de 2.000 textos de ficción y no ficción, con lectura guiada, debate y evaluación.",
    "cd_005": "Práctica adaptativa de gramática y escritura basada en los intereses de cada estudiante — versión básica gratuita.",
    "cd_006": "Clases estructuradas de inglés, videos y cuestionarios para primaria y secundaria, gratis y sin anuncios.",
    "cd_007": "Vocabulario adaptativo — aprende lo que sabes y te examina sobre lo que falta; ideal para preparar el SAT.",
    "cd_008": "Los estudiantes se vuelven autores — escriben, ilustran y publican sus propios libros digitales en el navegador.",
    "cd_009": "Asistente de escritura con IA que detecta errores de gramática, ortografía y claridad — el plan gratuito basta para estudiantes.",
    "cd_010": "Más de 70.000 ebooks gratuitos de dominio público — literatura clásica, poesía y no ficción, totalmente gratis para descargar.",
    "cd_011": "Actividades interactivas gratuitas de escritura y gramática — retroalimentación inmediata sobre construcción de oraciones y revisión.",
    "cd_012": "Fonética, canciones y actividades de lectura temprana — un sitio gratuito muy querido para lectores principiantes.",
    "cd_013": "Biblioteca gratuita de e-books de Oxford — cientos de lecturas niveladas con narración en audio.",
    "cd_014": "Aventura fonética galardonada — gratis en la web, usada por escuelas en todo el mundo.",
    "cd_015": "La app de idiomas más popular del mundo — vocabulario, gramática y lectura gamificados, gratis con anuncios.",
    "cd_016": "Juegos gratuitos de lectura y alfabeto con personajes de PBS que los niños ya adoran.",
    "cd_017": "Una \"Maravilla del Día\" diaria — lecturas breves de no ficción que despiertan curiosidad y vocabulario.",
    "cd_018": "Coach de escritura en el navegador que resalta oraciones largas y voz pasiva — pule el estilo.",
    "cd_019": "Videos y juegos gratuitos del alfabeto — Big Bird y sus amigos enseñan letras a niños de 3 a 5 años.",
    "cd_020": "Recursos gratuitos de alfabetización de PBS — consejos de lectura, artículos y actividades imprimibles para K-3.",
    "cd_021": "Currículo K-12 completo con clases en video, práctica adaptativa y seguimiento por dominio — el estándar de oro en matemáticas gratis.",
    "cd_022": "Conteo, formas y aritmética temprana mediante actividades lúdicas — la primera app de matemáticas perfecta para los más pequeños.",
    "cd_023": "Hermosa calculadora gráfica, calculadora científica y actividades interactivas para el aula — un clásico moderno.",
    "cd_024": "Herramientas dinámicas para geometría, álgebra, estadística y graficación 3D — gratis en cualquier navegador.",
    "cd_025": "Libros de texto interactivos y un espacio de manipulables virtuales — lúdico, visual y alineado con estándares.",
    "cd_026": "Serie basada en juegos que enseña álgebra y números a escondidas — los niños resuelven ecuaciones sin darse cuenta.",
    "cd_027": "RPG de matemáticas gamificado que se adapta al nivel de cada estudiante y se alinea al currículo escolar.",
    "cd_028": "Cientos de juegos de matemáticas gratuitos, acertijos lógicos y actividades de resolución de problemas para primaria.",
    "cd_029": "Motor computacional que resuelve — y explica — cualquier problema de matemáticas, desde ecuaciones hasta cálculo.",
    "cd_030": "Libros de texto digitales adaptativos gratuitos con práctica, videos y rutas personalizadas \"FlexMath\".",
    "cd_031": "Cursos interactivos de resolución de problemas de matemáticas — acceso gratis al primer capítulo de docenas de temas.",
    "cd_032": "Videos animados impresionantes de matemáticas que hacen comprender visualmente cálculo, álgebra lineal y probabilidad.",
    "cd_033": "Juegos de conteo, formas y aritmética temprana con personajes favoritos de PBS — totalmente gratis.",
    "cd_034": "Clases en video animadas y gratuitas que cubren todo, desde aritmética hasta álgebra.",
    "cd_035": "Biblioteca gratuita de la Universidad de Cambridge con problemas matemáticos ricos para todas las edades.",
    "cd_036": "Cientos de juegos matemáticos gratis para preescolar a 6.º grado — versión web con publicidad.",
    "cd_037": "Programa interactivo de matemáticas alineado al currículo — gratis en casa con cuentas de docente.",
    "cd_038": "Apps web e iPad gratuitas — rekenrek, recta numérica, geoplano y herramientas de fracciones.",
    "cd_039": "Tareas matemáticas abiertas y gratuitas de Stanford — visuales, creativas y forjan mentalidad de crecimiento.",
    "cd_040": "Juegos gratuitos de resolución de problemas matemáticos con Peg + Cat — conteo, formas y patrones.",
    "cd_041": "Serie gratuita de la BBC sobre conteo con juegos — convierte los números en personajes para niños de 3 a 6 años.",
    "cd_042": "Cursos gratuitos de matemáticas de pregrado del MIT — cálculo, álgebra lineal y más, con clases completas.",
    "cd_043": "Acceso gratis para auditar cursos de matemáticas de las mejores universidades — demostraciones, estadística, cálculo.",
    "cd_044": "Manipulables matemáticos virtuales y juegos gratuitos sin anuncios para primaria — fichas, fracciones y más.",
    "cd_045": "Más de 150 simulaciones científicas interactivas de la Universidad de Colorado — el mejor laboratorio gratis del mundo en un navegador.",
    "cd_046": "Clases prácticas de \"misterio\" científico para primaria — video, actividad práctica y debate en cada unidad.",
    "cd_047": "Sitio gratuito de la NASA para los más pequeños — juegos, actividades y videos sobre clima, Tierra y espacio.",
    "cd_048": "Videos científicos cortos, divertidos y llenos de datos para niños — perfectos para responder a cada \"¿por qué?\".",
    "cd_049": "Libros de texto digitales gratuitos de física, química, biología, ciencias de la Tierra y más — práctica adaptativa incluida.",
    "cd_050": "Películas asombrosas de biología, actividades de análisis de datos y clases de aula del Howard Hughes Medical Institute.",
    "cd_051": "Videos cortos y enérgicos de ciencia para 5.º y 6.º grado — ciencias de la vida, la Tierra, físicas y del espacio.",
    "cd_052": "Clases estructuradas de ciencias para primaria y secundaria — videos, cuestionarios y guías de repaso.",
    "cd_053": "Actividades prácticas de ciencia y demostraciones en video del legendario museo de ciencias de San Francisco.",
    "cd_054": "Cursos de física, química, biología y alineados con NGSS con práctica, videos y artículos — todo gratis.",
    "cd_055": "Lecciones, actividades, datos y desafíos directamente de la NASA — desde cohetes hasta el clima y los exoplanetas.",
    "cd_056": "Recursos científicos de calidad museística — millones de especímenes, imágenes y colecciones de clases, todo gratis.",
    "cd_057": "Juegos de ciencias gratuitos con SciGirls, Wild Kratts y más — indagación divertida para edades de 4 a 8 años.",
    "cd_058": "Datos increíbles, experimentos y videos de animales — despierta curiosidad desde los más pequeños hasta los preadolescentes.",
    "cd_059": "Conceptos básicos del clima y el espacio explicados con juegos y videos — gratis de la NASA y la NOAA.",
    "cd_060": "Investigaciones tipo museo y ciencia creativa — gratis y sin anuncios para niños de 5 a 12 años.",
    "cd_061": "Enciclopedia infantil de cualquier tema científico — gratuita, segura y escrita con claridad.",
    "cd_062": "Laboratorios virtuales, videos y casos de estudio creados por científicos en activo — gratis.",
    "cd_063": "Acceso gratuito para auditar cursos de ciencias de nivel universitario del MIT, Harvard y más.",
    "cd_064": "Cursos gratuitos de ciencia de pregrado del MIT — biología, química, física con clases completas.",
    "cd_065": "Acceso gratuito para auditar física, química y ciencias de la Tierra de nivel universitario.",
    "cd_066": "Explora el planeta en impresionante 3D con tours guiados \"Voyager\" — historia, cultura y naturaleza al alcance de tu mano.",
    "cd_067": "Más de 300 cuestionarios gratuitos de geografía — países, capitales, banderas, ríos, montañas y más.",
    "cd_068": "Geografía, culturas, animales y aventuras adaptados para niños de National Geographic — gratis en línea.",
    "cd_069": "La serie de historia rápida, ingeniosa y rica en datos de John Green — mundial, europea, estadounidense y más.",
    "cd_070": "Clases de historia estructuradas para primaria y secundaria — romanos, Tudor, guerras mundiales e historia global.",
    "cd_071": "Juegos y clases de civismo gratuitos fundados por la jueza O'Connor — cómo funciona el gobierno, jugando.",
    "cd_072": "\"Reading Like a Historian\" — clases gratuitas de indagación que enseñan fuentes, corroboración y argumentación.",
    "cd_073": "Curso interdisciplinario de 13.800 millones de años desde el Big Bang hasta el futuro de la humanidad.",
    "cd_074": "Artículos gratuitos de historia revisados por pares, mapas, líneas de tiempo y videos que cubren todo continente y época.",
    "cd_075": "Fuentes primarias listas para el aula — fotos históricas, cartas, mapas y audios — todos de uso gratuito.",
    "cd_076": "Miles de actividades históricas y artefactos gratuitos de los museos del Smithsonian.",
    "cd_077": "Herramienta gratuita de los Archivos Nacionales de EE. UU. para enseñar con documentos y fotografías de fuentes primarias.",
    "cd_078": "Artículos adaptados a niños sobre cada civilización con líneas de tiempo, juegos y cuestionarios.",
    "cd_079": "Juegos gratuitos de mapas y comunidad — geografía y civismo iniciales para los más pequeños.",
    "cd_080": "Antiguo Egipto, vikingos, imperios — artículos ilustrados y videos para niños de 5 a 12 años.",
    "cd_081": "Atlas interactivo de historia mundial — observa cualquier región en cualquier momento desde el 3500 a. C. hasta hoy.",
    "cd_082": "Artículos de historia claros y precisos escritos para niños — cubren todas las épocas.",
    "cd_083": "Colecciones gratuitas de fuentes primarias con ideas de clases — manuscritos, mapas y más.",
    "cd_084": "Acceso gratuito para auditar cursos de historia de Harvard, Columbia y otras universidades de élite.",
    "cd_085": "Juegos gratuitos que introducen vecindarios, ayudantes y nociones básicas de civismo para preescolares.",
    "cd_086": "Kit gratuito que enseña comunidad, familia y cultura a niños de 3 a 5 años.",
    "cd_087": "Enciclopedia gratuita DK para niños — civilizaciones antiguas, exploradores y líneas de tiempo.",
    "cd_088": "Artículos históricos gratuitos tipo revista con vibrantes ilustraciones para los más pequeños.",
    "cd_089": "El lenguaje de programación por bloques gratuito del MIT — la forma más popular del mundo para que los niños creen juegos, arte y cuentos.",
    "cd_090": "Currículo completo K-12 de informática — Hour of Code, CS Fundamentals, cursos a nivel AP — todo gratis.",
    "cd_091": "Programación solo en tableta para niños de 5 a 7 años — arrastra imágenes para dar vida a personajes. No requiere lectura.",
    "cd_092": "Cursos de programación tipo aventura que pasan paso a paso de bloques a Python y JavaScript.",
    "cd_093": "JavaScript, HTML/CSS, SQL y teoría de informática — clases interactivas con retroalimentación inmediata.",
    "cd_094": "El legendario curso introductorio de informática de Harvard — completamente gratis en edX, con certificado real.",
    "cd_095": "Más de 3.000 horas gratuitas de formación práctica en desarrollo web, análisis de datos y ML — con certificaciones que conservas.",
    "cd_096": "Entorno de programación en el navegador para más de 50 lenguajes — sin instalación, colaboración como en Google Docs.",
    "cd_097": "Editor en línea gratuito (bloques + Python) para programar una pequeña computadora física — miles de proyectos gratis.",
    "cd_098": "Aprende Python y JavaScript jugando un RPG — resuelve niveles escribiendo código real.",
    "cd_099": "Referencia amigable de desarrollo web con miles de editores en vivo \"Try It Yourself\" — HTML, CSS, JS, Python, SQL.",
    "cd_100": "\"Katas\" de programación breves en más de 50 lenguajes — afila la resolución de problemas con desafíos reales de programación.",
    "cd_101": "Introduce conceptos de programación a K-2 con simpáticos personajes \"fuzz\" — versión lite gratuita.",
    "cd_102": "Acertijo gratuito en el navegador que enseña secuencias, bucles y condicionales — sirve para K-12.",
    "cd_103": "Serie gratuita de Google de acertijos de programación que avanzan desde arrastrar bloques hasta JavaScript.",
    "cd_104": "Juegos gratuitos de programación basados en queridos programas de PBS — la primera introducción a la lógica de programación.",
    "cd_105": "Tutoriales de programación de una hora para todas las edades — desde Minecraft hasta Python, todos gratis.",
    "cd_106": "Clases móviles breves en Python, JS, SQL — comunidad gratuita de programación social.",
    "cd_107": "Clases interactivas de programación en el navegador — el plan gratuito cubre lo básico de Python, HTML/CSS y JS.",
    "cd_108": "App gratuita de introducción a la programación — arrastra comandos para hacer bailar a Daisy. Apta para preescolar.",
    "cd_109": "Clases gratuitas para K-2 que desarrollan hábitos de mecanografía y pensamiento computacional.",
    "cd_110": "Bee-Bot gratuito en línea — una abeja programable que desarrolla la secuenciación para los programadores más pequeños.",
    "cd_111": "Currículo gratuito K-12 de ciudadanía digital — privacidad, seguridad, alfabetización informativa e IA, por grupo de edad.",
    "cd_112": "Enseña a una IA a clasificar vida marina — primera experiencia infantil con aprendizaje automático supervisado y sesgos.",
    "cd_113": "El juego gratuito \"Interland\" de Google y materiales para el aula que enseñan seguridad en internet, amabilidad y privacidad.",
    "cd_114": "Currículo gratuito \"Everyday Ethics\" y de alfabetización en IA del MIT para secundaria — sesgo, justicia, agencia.",
    "cd_115": "MOOC gratuito de la Universidad de Helsinki y Reaktor — qué es realmente la IA, en lenguaje sencillo.",
    "cd_116": "Entrena tu propio modelo de aprendizaje automático con imágenes, sonido o poses — directo en el navegador, sin programar.",
    "cd_117": "Cursos cortos gratuitos de Andrew Ng sobre LLMs, prompting e IA moderna — la forma más rápida de subir de nivel.",
    "cd_118": "Centro canadiense de alfabetización digital y mediática — juegos, clases y recursos contra la desinformación.",
    "cd_119": "El marco europeo de competencia digital — una lista de las habilidades digitales que todo adulto necesita.",
    "cd_120": "Actividades gratuitas K-12 de IA del MIT — experiencias de aula de un día sobre sesgo, IA generativa y más.",
    "cd_121": "El tutor de IA de Khan Academy que nunca da la respuesta — pídele que debata, te entrene o te interrogue.",
    "cd_122": "Clases gratuitas en video sobre tareas digitales cotidianas — documentos, hojas, presentaciones, investigación, presupuesto y más.",
    "cd_123": "Extensión gratuita de Scratch — entrena modelos con texto, imágenes o números, y úsalos en juegos.",
    "cd_124": "Clases y proyectos curados de IA para K-12 — el plan gratuito cubre los módulos introductorios.",
    "cd_125": "Clases gratuitas K-12 sobre cómo funciona la IA, el sesgo, los deepfakes y el uso responsable.",
    "cd_126": "Módulos gratuitos de IA con clases sin pantalla, videos y actividades de capacitación para grados 3-12.",
    "cd_127": "Juego divertido de 20 segundos de garabatear que muestra cómo una red neuronal reconoce tus dibujos.",
    "cd_128": "Experimentos lúdicos en el navegador que desmitifican el aprendizaje automático — todos gratis, sin registro.",
    "cd_129": "Guía gratuita para estudiantes sobre cómo usar la IA con ética en la escuela — disparadores de conversación y consejos.",
    "cd_130": "Clases introductorias gratuitas sobre qué es la IA para niños de 5 a 7 años — usa canciones e historias.",
    "cd_131": "App de creación gratuita donde los más pequeños construyen cuentos interactivos — primeros hábitos de pensamiento sobre IA.",
    "cd_132": "Juegos gratuitos que sientan las bases para IA y CS — patrones, predicción, decisiones para edades de 4 a 8.",
    "cd_133": "Cursos interactivos de resolución de problemas en lógica, probabilidad, CS y más — el mejor gimnasio mental.",
    "cd_134": "Clases animadas cortas con preguntas y debate — una biblioteca de momentos \"ajá\" que expanden la mente.",
    "cd_135": "Cursos en video inteligentes, divertidos y rápidos sobre filosofía, estadística, técnicas de estudio y cómo pensar.",
    "cd_136": "Videos científicos galardonados que modelan curiosidad, errores conceptuales y resolución de problemas reales.",
    "cd_137": "Libros, videos y el reconocido entrenador adaptativo Alcumus — resolución de problemas estilo olimpiadas matemáticas.",
    "cd_138": "Videos animados de conceptos en cada materia con cuestionarios que comprueban la comprensión real.",
    "cd_139": "Artículos reales de actualidad en 5 niveles de lectura — enseña a analizar noticias y formular argumentos.",
    "cd_140": "Noticias en paralelo de izquierda, centro y derecha — detecta sesgos y observa el panorama completo.",
    "cd_141": "Herramienta de debate estructurado para el aula — los estudiantes construyen árboles de argumentos y aprenden a razonar juntos.",
    "cd_142": "Desafíos matemáticos en familia diseñados para que la lógica y la resolución de problemas se sientan como un juego.",
    "cd_143": "Caja de herramientas de rutinas de pensamiento del Project Zero de Harvard (\"Veo-Pienso-Me Pregunto\", \"Afirma-Apoya-Cuestiona\"…).",
    "cd_144": "Plataforma gratuita de alfabetización mediática del News Literacy Project — combate la desinformación con habilidades reales del periodismo.",
    "cd_145": "Planes gratuitos de discusión basados en preguntas que desarrollan el razonamiento — funcionan desde kínder hacia arriba.",
    "cd_146": "Juego gratuito de ritmo rápido — ¿puedes detectar las noticias falsas? Construye reflejos de alfabetización mediática.",
    "cd_147": "Videos y clases gratuitos sobre cómo detectar sesgos y desinformación — un excelente disparador de discusión.",
    "cd_148": "Recursos gratuitos de Ellen Galinsky sobre las siete habilidades esenciales para la vida en niños que piensan.",
    "cd_149": "Videos gratuitos de rutinas de pensamiento desde aulas reales — muestra seminarios socráticos en acción.",
    "cd_150": "Problemas abiertos y sin resolver gratuitos para K-12 — pensamiento profundo, sin respuestas fáciles.",
    "cd_151": "Actividades gratuitas curadas de pensamiento crítico para cada grado, de Common Sense Education.",
    "cd_152": "Juegos gratuitos que desarrollan razonamiento y reconocimiento de patrones tempranos para edades de 3 a 5.",
    "cd_153": "Juegos gratuitos de razonamiento y resolución de problemas con personajes favoritos de PBS.",
    "cd_154": "Orientación gratuita para construir habilidades tempranas de pensamiento — para padres de niños de 0 a 5 años.",
    "cd_155": "Recurso gratuito de la BBC — videos cortos, ideas y juegos que desarrollan pensamiento y lenguaje en la primera infancia.",
    "cd_156": "Artículos gratuitos con actividades de pensamiento para la primera infancia — observación, predicción, clasificación.",
    "cd_157": "App de mindfulness totalmente gratuita de una organización sin fines de lucro australiana, con programas de los 3 años hasta adultos.",
    "cd_158": "Las queridas aventuras de yoga infantil de Jaime Amor — gratis en YouTube, usadas por millones de familias y escuelas.",
    "cd_159": "Videos cortos de movimiento y mindfulness que los docentes pueden poner en clase — desfoga energía y luego recentra.",
    "cd_160": "Meditaciones guiadas para niños del Committee for Children — \"sesiones\" cortas para calmarse y enfocarse.",
    "cd_161": "Más de 150.000 meditaciones guiadas, sonidos para dormir y charlas — la mayor biblioteca gratuita de mindfulness.",
    "cd_162": "Headspace Premium — gratis para docentes K-12 en todo el mundo, incluido contenido listo para el aula.",
    "cd_163": "Calm premium gratis para docentes K-12 — meditación, cuentos para dormir y contenido relajante para el aula.",
    "cd_164": "App gratuita basada en evidencia de Anxiety Canada — herramientas de TCC para que los adolescentes manejen ansiedad y preocupación.",
    "cd_165": "Videos cortos animados de \"vocabulario emocional\" SEL — chequea, expresa sentimientos y recentra.",
    "cd_166": "El marco líder en aprendizaje socioemocional — recursos gratuitos para docentes, escuelas y familias.",
    "cd_167": "Información gratuita basada en evidencia sobre salud mental juvenil — estrés, identidad, familia y más, desde Australia.",
    "cd_168": "Información confidencial gratuita, herramientas de afrontamiento y línea de ayuda para niños — un lugar seguro cuando todo se siente abrumador.",
    "cd_169": "Videos y materiales imprimibles gratuitos sobre sentimientos, rutinas y resiliencia para los más pequeños.",
    "cd_170": "Clases gratuitas de muestra sobre ansiedad y mindfulness para niños y preadolescentes — animadas y relajantes.",
    "cd_171": "Mindfulness gratuito amigable para niños — chequea cómo te sientes, luego elige una actividad calmante.",
    "cd_172": "Recursos gratuitos de salud mental para adolescentes — estrés, sueño, relaciones y cómo pedir ayuda.",
    "cd_173": "Currículo gratuito de resiliencia para escuelas primarias — basado en evidencia comprobada.",
    "cd_174": "Guías gratuitas basadas en evidencia para padres y niños sobre ansiedad, TOC y preocupación.",
    "cd_175": "Recurso gubernamental gratuito — cómo se ve el bullying y exactamente qué hacer.",
    "cd_176": "Kit gratuito de herramientas para la ansiedad y animaciones de respiración pensados para adolescentes de 13 a 18 años.",
    "cd_177": "Tamizaje gratuito de salud mental para adolescentes y recursos de autoayuda, sin juicios.",
    "cd_178": "El currículo gratuito de educación financiera personal de referencia — cursos completos, proyectos y unidades interactivas.",
    "cd_179": "Simulador realista de finanzas — los estudiantes practican ahorro, presupuesto y decisiones de crisis en un entorno seguro.",
    "cd_180": "Clases gratuitas K-12 de economía y finanzas personales del Council for Economic Education.",
    "cd_181": "Hitos del dinero por edades del CFPB de EE. UU. para familias — conversaciones simples que construyen hábitos para toda la vida.",
    "cd_182": "Juegos, calculadoras y planes de clase gratuitos de Visa — temas de dinero por etapa de vida para todas las edades.",
    "cd_183": "Curso gratuito de finanzas personales — impuestos, crédito, préstamos, vivienda, seguros y nociones básicas de jubilación.",
    "cd_184": "Programas globales K-12 de educación financiera, preparación laboral y emprendimiento — a menudo impartidos gratuitamente.",
    "cd_185": "Currículo gratuito federal de educación financiera de EE. UU. — fundamentos de banca, crédito, deuda y seguros.",
    "cd_186": "Temas de finanzas del currículo del Reino Unido — cómo funcionan los bancos, presupuesto, impuestos, seguros e intereses.",
    "cd_187": "Currículo de finanzas con espíritu crítico producido entre pares — enseña a los adolescentes cómo los mercados intentan venderles.",
    "cd_188": "Definiciones gratuitas y en lenguaje claro de cualquier término bancario, de seguros e inversión que vayas a encontrar.",
    "cd_189": "Programa de PBS y materiales de aula gratuitos que enseñan a los niños sobre dinero, negocios y emprendimiento.",
    "cd_190": "Compilación gratuita de los mejores juegos de dinero en línea, desde primaria hasta secundaria.",
    "cd_191": "Clases gratuitas de dinero por etapas — desde alcancías hasta tarjetas de crédito — del blog de Mint.",
    "cd_192": "Juegos gratuitos sobre dinero con queridos personajes de PBS — primera introducción a monedas e intercambio.",
    "cd_193": "Clases y cuestionarios gratuitos globales de educación financiera de la Universidad George Washington.",
    "cd_194": "Juego de cuestionario gratuito sobre dinero con temática de la NFL — múltiples niveles, ideal para adolescentes.",
    "cd_195": "Lecciones gratuitas de economía y dinero diseñadas para grados K-2 con libros de cuentos.",
    "cd_196": "Currículo gratuito de Wells Fargo para niños, adolescentes y adultos — sin necesidad de registro.",
    "cd_197": "Juegos gratuitos de conteo e intercambio — construye el primer sentido del dinero para preescolares.",
    "cd_198": "Kit gratuito de herramientas sobre ahorrar, gastar y compartir — diseñado para niños de 3 a 5 años.",
    "cd_199": "Actividades familiares gratuitas que introducen conceptos de dinero a los más pequeños.",
    "cd_200": "Orientación gratuita por edades sobre cómo enseñar el dinero a los niños — incluye edades de 3 a 5 años.",
    "cd_201": "Currículo gratuito del FDIC para preescolar a 2.º grado — nociones básicas de dinero con cuentos.",
    "cd_202": "Información de salud revisada por médicos en tres voces — para niños, adolescentes y padres. Cuerpo, mente, nutrición, seguridad.",
    "cd_203": "Recetas, habilidades culinarias y videos sobre la ciencia de cocinar de America's Test Kitchen, probadas con niños y gratuitas.",
    "cd_204": "Recetas seguras para niños por edad y nivel — desde caritas de pizza hasta cenas familiares completas, paso a paso.",
    "cd_205": "Sitio gratuito de nutrición del USDA — planifica comidas balanceadas y aprende los cinco grupos alimenticios con juegos y clases.",
    "cd_206": "Guía gratuita del NHS del Reino Unido sobre alimentación, ejercicio, sueño, salud sexual y bienestar mental — confiable y clara.",
    "cd_207": "Apps gratuitas de primeros auxilios y emergencias de la Cruz Roja — practica RCP, respuesta ante atragantamiento y preparación ante desastres.",
    "cd_208": "Juegos y planes familiares gratuitos de preparación ante desastres de FEMA — incendios, tormentas, terremotos, apagones.",
    "cd_209": "Entrenamientos gratuitos, rutinas de 7 minutos y Couch to 5K — movimiento basado en evidencia para todos.",
    "cd_210": "Más de 600 videos gratuitos de entrenamientos completos para todos los niveles — la mayoría sin equipamiento.",
    "cd_211": "Orientación gratuita basada en evidencia sobre el sueño dirigida a adolescentes — por qué importa y cómo dormir mejor.",
    "cd_212": "Sitio gratuito de crianza de la Academia Estadounidense de Pediatría — respuestas confiables sobre salud, seguridad y crecimiento.",
    "cd_213": "Clases gratuitas del Reino Unido sobre cocina, habilidades del hogar, bienestar y vida adulta esencial.",
    "cd_214": "Juegos y videos gratuitos sobre rutinas, sentimientos y autocuidado para preescolares.",
    "cd_215": "Proyectos prácticos gratuitos de habilidades del hogar — circuitos, costura, jardinería y más.",
    "cd_216": "Orientación oficial gratuita de nutrición con juegos, consejos de compra y menús de muestra.",
    "cd_217": "Páginas gratuitas dirigidas a niños sobre amistades, respeto y manejo de conflictos.",
    "cd_218": "Biblioteca gratuita de recetas pensadas para niños — simples, seguras y deliciosamente balanceadas.",
    "cd_219": "Artículos gratuitos basados en evidencia sobre desafíos cotidianos para niños y adolescentes.",
    "cd_220": "Blog gratuito de recetas económicas — enseña a cocinar y a presupuestar la comida con costos transparentes.",
    "cd_221": "\"Playbooks\" gratuitos basados en investigación del equipo de Angela Duckworth — grit, amabilidad, curiosidad, autocontrol.",
    "cd_222": "Clases gratuitas anti-sesgo y de justicia social y revistas estudiantiles del Southern Poverty Law Center.",
    "cd_223": "Recursos gratuitos sobre historia, ética y participación cívica — cómo las decisiones cotidianas moldean la sociedad.",
    "cd_224": "Clases gratuitas con respaldo de la ONU sobre los 17 Objetivos de Desarrollo Sostenible — para todas las edades y todos los idiomas.",
    "cd_225": "Currículo gratuito K-12 de amabilidad, planes de clase y materiales imprimibles — SEL basado en evidencia mediante la acción.",
    "cd_226": "Prácticas gratuitas basadas en investigación de UC Berkeley para fomentar empatía, gratitud y bienestar estudiantil.",
    "cd_227": "Marco gratuito \"Seis Pilares del Carácter\" — confiabilidad, respeto, responsabilidad, justicia, cuidado, ciudadanía.",
    "cd_228": "Juegos y planes de clase gratuitos de civismo — derecho, derechos, política pública. La ciudadanía activa hecha atractiva.",
    "cd_229": "Cortometrajes, ensayos fotográficos y clases de aula gratuitos sobre culturas, resiliencia y nuestro mundo compartido.",
    "cd_230": "Historias de personas reales que \"se la juegan\" por el bien común — más un programa de aprendizaje-servicio.",
    "cd_231": "Clases y actividades gratuitas de Amnistía Internacional — comprende y defiende los derechos humanos universales.",
    "cd_232": "Programa gratuito SEL y de ciudadanía global donde la actividad de los niños ayuda a entregar comida terapéutica a niños necesitados.",
    "cd_233": "Videos y juegos gratuitos de PBS que modelan amabilidad, respeto y amistad para los más pequeños.",
    "cd_234": "Clases gratuitas K-12 sobre derechos humanos, equidad y ciudadanía global de UNICEF.",
    "cd_235": "Clases gratuitas K-12 sobre identidad, diversidad, justicia y acción.",
    "cd_236": "Artículos y videos gratuitos sobre cómo enseñar empatía, integridad y responsabilidad.",
    "cd_237": "Actividades de amabilidad, materiales imprimibles e ideas de proyectos de servicio gratuitos para todas las edades.",
    "cd_238": "Recursos gratuitos sobre los Objetivos de Desarrollo Sostenible de la ONU — caricaturas, pósters y clases.",
    "cd_239": "Currículo gratuito que usa entrevistas reales para construir empatía y habilidades de escucha.",
    "cd_240": "Una docena de experimentos gratuitos en el navegador que enseñan ritmo, armonía y sonido — sin cuenta, sin instalar.",
    "cd_241": "Estudio musical completo en el navegador — grabación, mezcla y compartido ilimitados y gratis, usado en miles de escuelas.",
    "cd_242": "App profesional de pintura digital de código abierto — 100% gratis en cualquier plataforma, sin marcas de agua.",
    "cd_243": "Diseña pósters, presentaciones, videos y más — todo Canva Pro es gratis para estudiantes y docentes K-12.",
    "cd_244": "Herramienta gratuita en el navegador de Autodesk para diseño 3D, circuitos y bloques de código — la primera app CAD más fácil.",
    "cd_245": "Modelado, animación y renderizado 3D de nivel profesional — completamente gratis y de código abierto.",
    "cd_246": "Envía un emoji, ánimo o palabra al SFMOMA y recibe una pieza sorpresa de su colección de 45.000 obras.",
    "cd_247": "Recorre virtualmente más de 2.000 museos — acerca pinturas, explora exhibiciones, juega a juegos de arte.",
    "cd_248": "Actividades artísticas, audioguías y recursos para el aula gratuitos del Museo de Arte Moderno (MoMA).",
    "cd_249": "Proyectos gratuitos de invención — convierte plátanos en teclas de piano. Combina creatividad, fabricación y pensamiento computacional.",
    "cd_250": "Sitio interactivo gratuito que enseña fundamentos para hacer música — ritmo, acordes, melodía — en el navegador.",
    "cd_251": "Adobe Express Premium gratis para K-12 — crea videos, gráficos, folletos y páginas web como un diseñador.",
    "cd_252": "Tutoriales gratuitos paso a paso de dibujo en YouTube — desde formas hasta personajes detallados.",
    "cd_253": "Sitio gratuito del Met pensado primero para niños — explora arte, viaja en el tiempo y crea proyectos creativos.",
    "cd_254": "Exhibiciones en línea y guías de actividades creativas gratuitas para el mundo del juego.",
    "cd_255": "Actividades gratuitas de arte y fotografía de National Geographic — inspiran curiosidad.",
    "cd_256": "Programación visual gratuita para crear animaciones, arte e historias — enorme comunidad creativa.",
    "cd_257": "Clases gratuitas de dibujo — lápiz, perspectiva, retratos — organizadas desde principiante absoluto en adelante.",
    "cd_258": "Cursos gratuitos de historia del arte, teoría musical y diseño con videos y proyectos.",
    "cd_259": "Actividades artísticas gratuitas para edades de 4 a 8 — imprimibles, ideas, garabatos en línea.",
    "cd_260": "Materiales imprimibles y tutoriales paso a paso gratuitos de manualidades — ideal para la hora de arte en preescolar.",
    "cd_261": "El MOOC mundialmente famoso de Barbara Oakley sobre técnicas de estudio basadas en neurociencia — gratis para auditar, transformador para estudiantes mayores.",
    "cd_262": "La app de tarjetas de repetición espaciada de referencia — científicamente probada para fijar datos en la memoria a largo plazo.",
    "cd_263": "Crea sets de tarjetas, juega a juegos de aprendizaje y haz exámenes de práctica — usada por cientos de millones de estudiantes en el mundo.",
    "cd_264": "Temporizador Pomodoro limpio en el navegador — bloques de enfoque de 25 minutos con descansos cortos, probado para vencer la procrastinación.",
    "cd_265": "Agenda estudiantil gratuita — registra clases, exámenes, tareas y deberes en todos tus dispositivos en un calendario inteligente.",
    "cd_266": "Pósters, podcasts y guías de estrategia de estudio gratuitos basados en ciencia cognitiva — práctica de recuperación, elaboración y más.",
    "cd_267": "Clases y actividades de mentalidad de crecimiento de Carol Dweck, gratis para todas las edades — enseñan que la inteligencia puede crecer.",
    "cd_268": "Herramienta gratuita de mapas conceptuales del IHMC — construye mapas visuales del conocimiento que hacen que las ideas complejas se comprendan y se fijen.",
    "cd_269": "Toma de notas combinada con repetición espaciada — convierte cualquier párrafo en una tarjeta al instante mientras estudias.",
    "cd_270": "App gratuita de notas tipo \"segundo cerebro\" — enlaza ideas como en una Wikipedia personal para ver cómo se conecta el conocimiento.",
    "cd_271": "Mantente fuera del teléfono haciendo crecer un árbol virtual — si abandonas antes, el árbol muere. Gamifica las sesiones de estudio enfocado.",
    "cd_272": "Plataforma de estudio con IA — convierte PDFs y notas en tarjetas, mapas mentales y cuestionarios automáticamente.",
    "cd_273": "Estrategias de estudio gratuitas probadas por estudiantes — toma de notas, recuperación, práctica espaciada.",
    "cd_274": "Tarjetas, planes de estudio y notas gratuitos — funcionan para cualquier materia y edad.",
    "cd_275": "Canal gratuito de YouTube — productividad, estudio y estrategias de toma de notas que funcionan.",
    "cd_276": "Tarjetas y juegos de estudio gratuitos — más de 800 materias cubiertas por estudiantes reales.",
    "cd_277": "Tarjetas, mapas mentales y cuestionarios gratuitos — web y móvil, excelentes para repaso.",
    "cd_278": "Curso gratuito en video de 10 episodios sobre cómo aprender a aprender — hecho para adolescentes.",
    "cd_279": "Actividades gratuitas de aprendizaje temprano que abarcan ABCs, conteo, rutinas y hábitos de curiosidad.",
    "cd_280": "Orientación gratuita para padres sobre cómo apoyar los hábitos tempranos de aprendizaje en niños de 0 a 5 años.",
    "cd_281": "Artículos gratuitos sobre cómo el juego construye el aprendizaje temprano, el enfoque y la formación de hábitos.",
    "cd_282": "Rutinas y actividades de autorregulación gratuitas para construir hábitos tempranos de aprendizaje.",
    "cd_283": "Guías gratuitas para padres y docentes sobre rutinas de aprendizaje para K-2.",
    "cd_284": "Actividades gratuitas de aprendizaje temprano — enfoque, rutinas y curiosidad para edades de 3 a 7.",
    "cd_285": "Canciones y rutinas gratuitas que afianzan los hábitos tempranos de alfabetización y aprendizaje numérico.",
    "cd_286": "Prueba gratuita de un programa adaptativo de lectura temprana — desarrolla la fluidez de aprendizaje desde kínder.",
    "cd_287": "Gratis para educadores — un hábito diario de 20 minutos de lectura cultiva a los aprendices más pequeños.",
}
