FR_UNI = {
    "cd_uni_000": "L'assistant phare d'Anthropic — un niveau gratuit généreux couvre la rédaction, le code et la recherche avec un raisonnement avancé.",
    "cd_uni_001": "ChatGPT d'OpenAI — le niveau gratuit inclut GPT-4o mini, le mode vocal, la compréhension d'images et l'analyse de données de base.",
    "cd_uni_002": "L'assistant multimodal de Google avec une intégration poussée dans Docs, Drive et Gmail — niveau gratuit solide avec support image et code.",
    "cd_uni_003": "Copilot gratuit avec raisonnement de classe GPT-4, génération d'images et intégration Microsoft 365 — inclus gratuitement avec tout compte Microsoft.",
    "cd_uni_004": "Moteur de recherche IA qui cite chaque affirmation — idéal quand des sources vérifiables sont nécessaires plutôt que des réponses hallucées.",
    "cd_uni_005": "Permet de téléverser ses propres notes et PDF — l'IA de Google répond strictement à partir des sources fournies, avec citations et résumés audio.",
    "cd_uni_006": "Exécute des milliers de modèles IA open source dans le navigateur — texte, vision, parole, agents — et permet d'héberger ses propres Spaces gratuitement.",
    "cd_uni_007": "Cours gratuits d'une heure par Andrew Ng sur le prompting, le RAG, les agents et le fine-tuning — enseignés avec les principaux laboratoires d'IA.",
    "cd_uni_008": "Cours open source gratuit enseignant les quatre compétences fondamentales du travail avec l'IA — délégation, description, discernement, diligence.",
    "cd_uni_009": "MOOC gratuit de l'Université d'Helsinki — 30 heures couvrant les fondamentaux de l'IA, l'éthique et ses limites, suivi par un million d'apprenants.",
    "cd_uni_010": "Programme gratuit de Google sur les bases de l'IA générative, la conception de prompts et l'usage responsable — aucune expérience préalable requise.",
    "cd_uni_011": "Guide communautaire open source sur le prompting — techniques, exemples et articles de recherche, tout gratuit et régulièrement mis à jour.",
    "cd_uni_012": "Le légendaire cours d'introduction à l'informatique de Harvard — vidéos gratuites, séries d'exercices et certificat gratuit via audit edX. Toujours le meilleur premier cours d'informatique en ligne.",
    "cd_uni_013": "Des milliers d'heures de cours de codage pratiques et des certifications gratuites — développement web, analyse de données et apprentissage automatique.",
    "cd_uni_014": "Programme gratuit et complet de développement web utilisé par des développeurs autodidactes qui décrochent de vrais emplois — piloté par la communauté et éprouvé.",
    "cd_uni_015": "Cours de codage interactifs dans le navigateur — Python, JS, SQL, HTML/CSS — avec un niveau gratuit solide couvrant toutes les bases.",
    "cd_uni_016": "Micro-cours courts et pratiques en data science et ML — plus des milliers de jeux de données réels et des compétitions pour s'entraîner.",
    "cd_uni_017": "Notebooks Jupyter gratuits dans le navigateur avec GPU gratuit — idéal pour le ML, la data science et le prototypage de recherche sans configuration.",
    "cd_uni_018": "Practical Deep Learning for Coders — un cours gratuit ascendant qui transforme les développeurs en praticiens du deep learning en sept semaines.",
    "cd_uni_019": "Les premiers chapitres gratuits de chaque cours — bonne introduction à Python, R, SQL et la visualisation de données avec des exercices dans le navigateur.",
    "cd_uni_020": "Le tutoriel SQL gratuit le plus clair en ligne — orienté analytique, avec des jeux de données réels et un éditeur intégré dans le navigateur.",
    "cd_uni_021": "Permet de coder dans plus de 50 langages directement dans le navigateur — sans configuration, hébergement gratuit, collaboration instantanée et codage assisté par IA.",
    "cd_uni_022": "Exercices pratiques gratuits dans plus de 70 langages avec retours de mentors — permet d'affiner la syntaxe et les idiomes au-delà de ce que couvrent les tutoriels.",
    "cd_uni_023": "Introduction à l'informatique du MIT en Python — cours magistraux gratuits, séries d'exercices et examens issus du programme universitaire.",
    "cd_uni_024": "Gestionnaire de mots de passe open source avec un niveau gratuit généreux — appareils illimités, mots de passe illimités et chiffrement de bout en bout.",
    "cd_uni_025": "Vérification gratuite de l'exposition d'un e-mail ou d'un mot de passe dans une fuite de données — par le chercheur en sécurité Troy Hunt.",
    "cd_uni_026": "Messagerie gratuite chiffrée de bout en bout — référence en matière de chats privés, appels vocaux et vidéo. Utilisée par des journalistes du monde entier.",
    "cd_uni_027": "Application gratuite open source d'authentification à deux facteurs — bien plus sûre que les codes SMS et protège les comptes même en cas de fuite de mots de passe.",
    "cd_uni_028": "Navigateur d'anonymat gratuit qui achemine le trafic via des relais bénévoles — indispensable pour les journalistes, les militants et les utilisateurs à risque élevé.",
    "cd_uni_029": "Guide gratuit de Mozilla évaluant la confidentialité des technologies grand public — téléphones, enceintes connectées, applications de santé mentale. Facile à consulter avant tout achat.",
    "cd_uni_030": "Guide gratuit de l'Electronic Frontier Foundation sur la sécurité numérique — guides pratiques pour les étudiants, les militants et les utilisateurs du quotidien.",
    "cd_uni_031": "Formation en cybersécurité gamifiée — les salles gratuites couvrent les réseaux, Linux et la sécurité web ; la plateforme de hacking la plus accessible aux débutants.",
    "cd_uni_032": "Cours d'introduction gratuits aux fondamentaux de la cybersécurité, au hacking éthique et à la préparation à l'examen CompTIA Security+.",
    "cd_uni_033": "Conseils gratuits en cybersécurité de la CISA américaine — pratiques pour les particuliers et les petites organisations.",
    "cd_uni_034": "Open Worldwide Application Security Project — listes top-10 gratuites, aide-mémoires et référentiels que tout développeur web devrait connaître.",
    "cd_uni_035": "Cours de sécurité informatique et réseau de Stanford — diapositives de cours gratuites, notes et listes de lectures d'un programme phare.",
    "cd_uni_036": "Cours gratuit de l'Université de Washington pour repérer les erreurs dans les chiffres, les graphiques et les récits — toutes les vidéos et lectures disponibles en ligne.",
    "cd_uni_037": "Introduction gratuite et complète aux statistiques et aux probabilités — les bases pour remettre en question n'importe quel graphique vu dans l'actualité.",
    "cd_uni_038": "Affiche des titres de presse de gauche, du centre et de droite côte à côte — permet d'étalonner son régime médiatique et de repérer les biais au quotidien.",
    "cd_uni_039": "Compare la couverture d'un même sujet à travers le spectre politique — le niveau gratuit met en lumière les angles morts et les biais.",
    "cd_uni_040": "Le site de vérification des faits original — verdicts gratuits et transparents sur les affirmations virales, les légendes urbaines et les rumeurs politiques.",
    "cd_uni_041": "Podcast gratuit de Tim Harford sur BBC et articles décryptant les chiffres derrière les manchettes — la formation la plus accessible à la pensée statistique.",
    "cd_uni_042": "Audit gratuit de Richard Nisbett sur les concepts les plus utiles en psychologie et en statistiques pour le raisonnement quotidien.",
    "cd_uni_043": "Introduction gratuite de la longueur d'un livre à la rationalité — biais cognitifs, pensée probabiliste, raisonnement scientifique et prise de décision.",
    "cd_uni_044": "Guide interactif gratuit sur 24 sophismes logiques courants — à mettre en favori pour repérer les mauvais arguments en ligne et hors ligne.",
    "cd_uni_045": "Encyclopédie gratuite des biais cognitifs et des sciences comportementales — explications claires et bien illustrées sur nos erreurs de pensée.",
    "cd_uni_046": "Cours gratuits de littératie médiatique pour adolescents et adultes de l'Institut Poynter — vérification des faits pratique avec des exemples du monde réel.",
    "cd_uni_047": "Articles gratuits de Ben Goldacre démantelant les mauvaises statistiques en médecine et en journalisme — l'antidote canonique aux gros titres douteux.",
    "cd_uni_048": "Plus de 2 500 cours MIT gratuits — notes de cours, séries d'exercices, examens et souvent des cours vidéo complets de la meilleure école d'ingénieurs au monde.",
    "cd_uni_049": "Permet d'auditer la plupart des cours de Stanford, Yale, Michigan et d'autres gratuitement — vidéos et lectures incluses dans la formule sans frais.",
    "cd_uni_050": "Cours de Harvard, MIT et Berkeley — gratuits à l'audit, avec des certificats payants optionnels et des programmes MicroMasters éligibles aux crédits.",
    "cd_uni_051": "Cours gratuits sélectionnés par des membres du corps enseignant de Stanford — IA, ingénierie, médecine, éducation et entrepreneuriat.",
    "cd_uni_052": "Cours magistraux complets du premier cycle de Yale — philosophie, économie, astronomie, littérature — vidéos complètes et listes de lectures.",
    "cd_uni_053": "Cours gratuits de The Open University — plus de 1 000 sujets avec attestations de participation disponibles sans frais.",
    "cd_uni_054": "Cours universitaires en auto-apprentissage avec certificats gratuits — certains éligibles aux crédits via des partenariats ACE, sans frais de diplôme.",
    "cd_uni_055": "Cours adaptatifs fondés sur la recherche de Carnegie Mellon — statistiques, psychologie, biologie et logique.",
    "cd_uni_056": "Cours fondamentaux avec suivi de la maîtrise — calcul, algèbre linéaire, physique, économie et préparation aux examens, entièrement gratuits.",
    "cd_uni_057": "Cours courts gratuits d'universités européennes et du Commonwealth — apprentissage par discussion avec des pairs du monde entier.",
    "cd_uni_058": "Moteur de recherche gratuit pour plus de 200 000 MOOCs — le moyen le plus simple de trouver la meilleure version gratuite de n'importe quel cours en ligne.",
    "cd_uni_059": "Le MOOC le plus populaire jamais créé — cours gratuit et auditable sur le méta-apprentissage, la pratique ciblée et la lutte contre la procrastination.",
    "cd_uni_060": "Le plus grand moteur de recherche académique gratuit — articles, citations et souvent des liens directs vers des PDF gratuits dans toutes les disciplines.",
    "cd_uni_061": "Gestionnaire de références gratuit et open source — capture n'importe quelle source en un clic et formate automatiquement les bibliographies dans n'importe quel style.",
    "cd_uni_062": "Recherche académique propulsée par l'IA de l'Allen Institute — met en évidence les citations influentes et les travaux connexes pour n'importe quel article.",
    "cd_uni_063": "Graphe visuel des articles liés à un article clé — un outil révolutionnaire pour la revue de littérature dans le cadre de thèses et de synthèses.",
    "cd_uni_064": "Le plus grand agrégateur mondial de recherche en libre accès — 300 millions d'articles issus de 11 000 dépôts, entièrement consultable.",
    "cd_uni_065": "Base de données gratuite des NIH avec plus de 35 millions de citations biomédicales — indispensable pour les sciences de la vie, la médecine et la psychologie.",
    "cd_uni_066": "Répertoire des revues en libre accès — plus de 20 000 revues évaluées par les pairs avec texte intégral gratuit, sans abonnement.",
    "cd_uni_067": "Manuels gratuits évalués par les pairs de l'Université Rice — biologie, physique, économie, sociologie et calcul, entièrement téléchargeables.",
    "cd_uni_068": "La plus grande bibliothèque de manuels ouverts — chimie, ingénierie, sciences humaines et médecine, librement adaptables pour les enseignants.",
    "cd_uni_069": "Serveur gratuit de prépublications en physique, mathématiques, informatique et biologie quantitative — découvrez les nouvelles recherches des mois avant leur publication formelle.",
    "cd_uni_070": "Plus de 75 000 livres classiques gratuits dans le domaine public — idéal pour les cours de littérature, d'histoire et de philosophie.",
    "cd_uni_071": "Des millions de livres gratuits, d'articles académiques et de documents historiques — incluant le service de prêt Open Library.",
    "cd_uni_072": "Vérifications gratuites en temps réel de la grammaire, de l'orthographe et de la clarté dans le navigateur ou Word — le niveau gratuit couvre tous les usages quotidiens essentiels.",
    "cd_uni_073": "Met en évidence les phrases alambiquées, la voix passive et les adverbes — rend l'écriture académique et professionnelle nettement plus claire.",
    "cd_uni_074": "Correcteur grammatical open source supportant plus de 30 langues — niveau gratuit solide, idéal pour les essais en allemand, français et espagnol.",
    "cd_uni_075": "Éditeur LaTeX en ligne — rédaction collaborative de thèses et d'articles avec aperçu en direct et modèles de revues, le niveau gratuit convient à la plupart des étudiants.",
    "cd_uni_076": "Alternative moderne open source à LaTeX — compilation plus rapide, syntaxe plus propre, produit toujours de beaux PDF pour les travaux académiques.",
    "cd_uni_077": "La référence d'écriture gratuite la plus utilisée sur le web — guides de style APA/MLA/Chicago, conseils grammaticaux et guides d'écriture académique.",
    "cd_uni_078": "Leçons TED-Ed gratuites sur la prise de parole en public, la narration et la présentation — enseignées par des personnes qui donnent réellement des conférences TED.",
    "cd_uni_079": "La plus grande communauté mondiale de prise de parole en public — de nombreux clubs locaux permettent des visites gratuites, avec des parcours structurés de progression.",
    "cd_uni_080": "Spécialisation gratuite à l'audit de Patrick Barry sur l'écriture et la révision pour la persuasion — pratique pour les dissertations, les candidatures et les arguments.",
    "cd_uni_081": "Coach vocal IA gratuit — permet de s'entraîner sur des présentations vidéo et d'obtenir des retours sur les mots de remplissage, le rythme, la clarté et la confiance.",
    "cd_uni_082": "Traitement de texte collaboratif gratuit avec édition en temps réel, commentaires, historique des versions et saisie vocale — universel pour les travaux étudiants.",
    "cd_uni_083": "Assistant de rédaction IA gratuit de DeepL — reformule le ton et la clarté en anglais, en allemand et dans d'autres langues principales.",
    "cd_uni_084": "Plan Plus gratuit pour les étudiants avec une adresse e-mail .edu — notes, bases de données, listes de tâches et wikis réunis dans un seul espace de travail.",
    "cd_uni_085": "Prise de notes markdown locale avec rétroliens — le meilleur outil gratuit pour construire un graphe de connaissances académiques personnelles.",
    "cd_uni_086": "Flashcards gratuites open source à répétition espacée — utilisées par des étudiants en médecine et des apprenants en langues du monde entier ; l'outil de mémorisation éprouvé.",
    "cd_uni_087": "Gestionnaire de tâches simple qui gère les devoirs récurrents et les délais sur tous les appareils — le niveau gratuit convient à la plupart des flux de travail.",
    "cd_uni_088": "Minuteur de concentration gamifié — un arbre virtuel meurt si l'on quitte l'application. La version web gratuite bloque efficacement les distractions.",
    "cd_uni_089": "Minuteur Pomodoro simple et gratuit — permet de démarrer des sessions de 25 minutes concentrées dans le navigateur sans inscription ni configuration.",
    "cd_uni_090": "Bloqueur gratuit de sites et d'applications difficile à contourner — permet de planifier des plages de travail en profondeur que même l'utilisateur ne peut pas annuler.",
    "cd_uni_091": "Essais, podcasts et guides gratuits de l'auteur de Deep Work — guides pratiques pour une concentration soutenue et sans distraction.",
    "cd_uni_092": "Graphe de connaissances local open source — notes quotidiennes, plans et rétroliens ; une alternative gratuite et respectueuse de la vie privée à Roam.",
    "cd_uni_093": "Tableaux Kanban gratuits — gestion visuelle des tâches pour les projets de groupe, les thèses et les projets personnels.",
    "cd_uni_094": "Calendrier gratuit de planification temporelle avec événements partagés et saisie en langage naturel — la colonne vertébrale de toute pratique de travail en profondeur.",
    "cd_uni_095": "Application gratuite de suivi du temps avec minuteurs en un clic — permet de voir où vont réellement les heures d'étude et de concevoir de meilleures routines.",
    "cd_uni_096": "Le cours le plus populaire de l'histoire de Yale — gratuit à l'audit, enseigné par Laurie Santos, couvrant la psychologie du bonheur avec des pratiques quotidiennes.",
    "cd_uni_097": "Headspace Plus gratuit pour les étudiants dans plus de 1 000 universités — méditations guidées, histoires pour dormir et cours sur le stress.",
    "cd_uni_098": "Méditations guidées gratuites, exercices de respiration et histoires pour dormir — les bases de la pleine conscience sans abonnement payant.",
    "cd_uni_099": "Programme gratuit basé sur la TCC de l'Université nationale australienne — avéré pour réduire les symptômes de dépression et d'anxiété.",
    "cd_uni_100": "Soutien en santé mentale gratuit basé sur un chatbot — utilise des techniques de TCC pour aider avec l'humeur, l'anxiété et les pensées stressantes.",
    "cd_uni_101": "Portail gratuit de santé mentale du NHS britannique — conseils pratiques pour l'anxiété, le sommeil, la déprime et le stress.",
    "cd_uni_102": "Méditations et exercices gratuits de Kristin Neff — pratiques d'auto-compassion fondées sur la recherche, avérées pour renforcer la résilience.",
    "cd_uni_103": "La plus grande application de méditation gratuite — plus de 200 000 méditations guidées gratuites, conférences et musiques d'enseignants du monde entier.",
    "cd_uni_104": "Soutien émotionnel gratuit de la part d'auditeurs formés — chats anonymes disponibles 24h/24 et 7j/7, plus une thérapie en ligne à faible coût si nécessaire.",
    "cd_uni_105": "Soutien gratuit en cas de crise par SMS, disponible 24h/24 — conseillers formés et confidentiels aux États-Unis, au Royaume-Uni, en Irlande et au Canada.",
    "cd_uni_106": "Ressource éducative gratuite de la Harvard Medical School sur la biologie du sommeil, l'hygiène et les troubles — claire, fondée sur des preuves et accessible.",
    "cd_uni_107": "Calendriers mensuels gratuits d'actions quotidiennes fondées sur des preuves — petites habitudes durables avérées pour améliorer l'humeur et la résilience.",
    "cd_uni_108": "Cours complet gratuit sur les finances personnelles — impôts, crédit, investissement, retraite et immobilier, enseigné avec la clarté d'un cours secondaire.",
    "cd_uni_109": "Encyclopédie gratuite de la finance et de l'investissement — plus de 30 000 articles et un simulateur gratuit pour le paper trading d'actions sans risque.",
    "cd_uni_110": "Guides gratuits comparant les cartes de crédit, les prêts étudiants, les comptes d'épargne et les plateformes d'investissement — conseils indépendants des fournisseurs.",
    "cd_uni_111": "Wiki communautaire gratuit sur l'investissement indiciel à faible coût — basé sur les principes de John Bogle, la référence pour les investisseurs passifs.",
    "cd_uni_112": "Outils et guides gratuits du Bureau américain de protection financière des consommateurs — prêts étudiants, crédit, arnaques et bases financières.",
    "cd_uni_113": "Portail gouvernemental australien gratuit sur les finances — calculatrices, guides et outils budgétaires utilisables à l'international.",
    "cd_uni_114": "Cours gratuit du lauréat du prix Nobel Robert Shiller — auditable sur Coursera, couvre le risque, la finance comportementale et les marchés modernes.",
    "cd_uni_115": "Introduction à la théorie financière du MIT Sloan — cours magistraux gratuits et séries d'exercices couvrant la valorisation, les portefeuilles et les marchés de capitaux.",
    "cd_uni_116": "Vidéos financières pratiques gratuites pour jeunes adultes — budget, investissement, négociation salariale et inflation du style de vie, sans jargon.",
    "cd_uni_117": "Plus de 15 ans d'écriture accessible et gratuite sur les finances personnelles par JD Roth — remboursement de dettes, épargne, investissement et dépenses conscientes.",
    "cd_uni_118": "Essais gratuits sur l'indépendance financière et la frugalité — le texte fondateur du mouvement FIRE, opinionné mais pratique.",
    "cd_uni_119": "Abonnement gratuit de 12 mois à YNAB pour les étudiants universitaires — la méthode de budgétisation la plus appréciée, avec des cours inclus.",
    "cd_uni_120": "Cours gratuit de 10 semaines du meilleur accélérateur mondial — plus d'un million de fondateurs formés, avec une bibliothèque d'essais et de conférences YC.",
    "cd_uni_121": "De nombreuses bibliothèques publiques offrent un accès gratuit à LinkedIn Learning — des milliers de cours sur les carrières, les outils et les compétences comportementales.",
    "cd_uni_122": "Retours gratuits par IA sur les CV et les profils LinkedIn — développé par d'anciens recruteurs, évalue le CV selon de véritables critères de recrutement.",
    "cd_uni_123": "Modèles de CV téléchargeables gratuits et guides de rédaction — pratiques pour les premiers emplois, les stages et les reconversions professionnelles.",
    "cd_uni_124": "Archive gratuite d'articles sur la carrière — préparation aux entretiens, négociation salariale, navigation dans la politique d'entreprise et changements de carrière.",
    "cd_uni_125": "Données salariales gratuites issues de vraies offres — permet de voir ce que les postes en technologie, finance et conseil paient réellement avant de négocier.",
    "cd_uni_126": "Avis gratuits, fourchettes salariales et questions d'entretien pour des milliers d'entreprises — la lecture incontournable avant tout entretien.",
    "cd_uni_127": "Conseils de carrière gratuits axés sur le bien commun — guides fondés sur la recherche pour des parcours professionnels à fort impact.",
    "cd_uni_128": "CS183B gratuit de Stanford enseigné par Sam Altman et les partenaires de Y Combinator — 20 conférences gratuites sur la création d'une startup de zéro.",
    "cd_uni_129": "Communauté gratuite de fondateurs bootstrapped — interviews, podcasts et fils de discussion sur la création de projets parallèles rentables.",
    "cd_uni_130": "Certifications gratuites en marketing, vente, contenu et SEO — reconnues par les employeurs, réalisables en ligne en quelques heures chacune.",
    "cd_uni_131": "Certificats Google gratuits à auditer en support informatique, analyse de données, UX et gestion de projet — reconnus par plus de 150 employeurs.",
    "cd_uni_132": "Visualisations de données librement accessibles sur les plus grands enjeux mondiaux — climat, pauvreté et santé — réalisées par des chercheurs d'Oxford.",
    "cd_uni_133": "Explications gratuites sélectionnées par le MIT sur le changement climatique — la science, les solutions, les politiques — accessibles et rigoureusement documentées.",
    "cd_uni_134": "Liste classée gratuite des solutions climatiques les plus efficaces — base de données consultable avec des analyses techniques approfondies pour chacune.",
    "cd_uni_135": "Journalisme climatique gratuit quotidien de Yale — reportages précis et accessibles sur la science du climat, ses impacts et ses solutions.",
    "cd_uni_136": "Introduction complète et gratuite à la vie civique américaine — Constitution, branches du gouvernement, élections — utile même pour les non-Américains qui apprennent les bases de la démocratie.",
    "cd_uni_137": "Jeux et leçons gratuits sur la participation démocratique — développés par la juge O'Connor, utilisés dans plus de 50 000 classes.",
    "cd_uni_138": "Portail gratuit de ressources éthiques de l'Université Santa Clara — cadres de réflexion sur la technologie, les affaires, l'IA et l'éthique biomédicale.",
    "cd_uni_139": "Rapports, introductions et notes de politique gratuits de l'Institut HAI de Stanford — la principale source sur l'impact sociétal de l'IA.",
    "cd_uni_140": "Guide gratuit d'investigation open source — permet de vérifier des vidéos, de géolocaliser des photos et de vérifier des affirmations virales comme les professionnels.",
    "cd_uni_141": "Archive gratuite de reportages fondés sur des preuves sur ce qui fonctionne — antidote au défilement anxiogène, axé sur les réponses aux problèmes sociaux.",
    "cd_uni_142": "Guides gratuits de l'Electronic Frontier Foundation sur la liberté d'expression, la surveillance et les droits numériques — le principal groupe de défense des libertés civiles numériques.",
    "cd_uni_143": "Cours gratuits sur les Objectifs de développement durable des Nations Unies — climat, égalité, pauvreté et gouvernance, enseignés par les agences et partenaires de l'ONU.",
}
