FR_STUDENTS = {
    "cd_000": "Application primée d'alphabétisation précoce — lettres, phonétique, histoires et écriture, entièrement gratuite et sans publicités.",
    "cd_001": "Des acteurs célèbres lisent des livres pour enfants à voix haute — de belles vidéos qui développent l'écoute et la lecture dès le plus jeune âge.",
    "cd_002": "Plus de 40 000 livres numériques, livres audio et lectures accompagnées — gratuits pour les enseignants pendant les heures scolaires.",
    "cd_003": "Des milliers de passages de lecture de haute qualité avec des questions de compréhension, entièrement gratuits pour la maternelle au lycée.",
    "cd_004": "Bibliothèque numérique gratuite de plus de 2 000 textes fictifs et non fictifs avec lecture guidée, discussion et évaluation.",
    "cd_005": "Entraînement adaptatif à la grammaire et à l'écriture basé sur les propres intérêts de chaque élève — version de base gratuite.",
    "cd_006": "Leçons d'anglais structurées, vidéos et quiz pour le primaire et le secondaire, gratuites et sans publicités.",
    "cd_007": "Outil d'enrichissement du vocabulaire adaptatif — apprend ce que vous savez déjà et vous interroge sur les lacunes ; idéal pour préparer le SAT.",
    "cd_008": "Les élèves deviennent auteurs — écrire, illustrer et publier ses propres livres numériques directement dans le navigateur.",
    "cd_009": "Assistant d'écriture IA qui détecte les problèmes de grammaire, d'orthographe et de clarté — la version gratuite est largement suffisante pour les élèves.",
    "cd_010": "Plus de 70 000 ebooks gratuits du domaine public — littérature classique, poésie et essais, entièrement libres de téléchargement.",
    "cd_011": "Activités interactives gratuites d'écriture et de grammaire — retour immédiat sur la construction des phrases et la correction.",
    "cd_012": "Phonétique, chansons et activités de lecture précoce — un site gratuit apprécié depuis longtemps pour les lecteurs débutants.",
    "cd_013": "Bibliothèque gratuite de livres numériques d'Oxford — des centaines de lecteurs nivelés avec narration audio.",
    "cd_014": "Aventure phonétique primée — gratuite sur le web, utilisée en toute confiance par des écoles du monde entier.",
    "cd_015": "L'application de langues la plus populaire au monde — vocabulaire, grammaire et lecture sous forme de jeu, gratuite avec des publicités.",
    "cd_016": "Jeux de lecture et d'alphabet gratuits avec les personnages de PBS que les enfants adorent déjà.",
    "cd_017": "Un « Wonder of the Day » quotidien — de courts textes non fictifs qui développent la curiosité et le vocabulaire.",
    "cd_018": "Coach d'écriture dans le navigateur qui met en évidence les longues phrases et la voix passive — affine le style.",
    "cd_019": "Vidéos et jeux gratuits sur l'alphabet — Big Bird et ses amis enseignent les lettres aux enfants de 3 à 5 ans.",
    "cd_020": "Ressources gratuites de PBS pour l'alphabétisation — conseils de lecture, articles et activités imprimables pour les classes de maternelle au CE2.",
    "cd_021": "Programme complet de la maternelle au lycée avec des leçons vidéo, une pratique adaptative et un suivi de la maîtrise — la référence en matière de maths gratuits.",
    "cd_022": "Comptage, formes et numération précoce à travers des activités ludiques — la première application de maths idéale pour les tout-petits.",
    "cd_023": "Belle calculatrice graphique, calculatrice scientifique et activités interactives en classe — un classique moderne.",
    "cd_024": "Outils dynamiques pour la géométrie, l'algèbre, les statistiques et les graphiques 3D — gratuits dans n'importe quel navigateur.",
    "cd_025": "Manuels interactifs et espace de travail avec manipulatifs virtuels — ludique, visuel et aligné sur les normes.",
    "cd_026": "Série basée sur le jeu qui enseigne secrètement l'algèbre et les nombres — les enfants résolvent des équations sans même s'en rendre compte.",
    "cd_027": "RPG mathématique sous forme de jeu qui s'adapte au niveau de chaque élève et s'aligne sur le programme scolaire.",
    "cd_028": "Des centaines de jeux mathématiques gratuits, de puzzles logiques et d'activités de résolution de problèmes pour les élèves du primaire.",
    "cd_029": "Moteur de calcul qui résout — et explique — tout problème mathématique, des équations au calcul intégral.",
    "cd_030": "Manuels de mathématiques numériques adaptatifs gratuits avec exercices, vidéos et parcours personnalisés « FlexMath ».",
    "cd_031": "Cours interactifs de résolution de problèmes en mathématiques — accès gratuit au premier chapitre de dizaines de sujets.",
    "cd_032": "Superbes vidéos mathématiques animées qui rendent le calcul, l'algèbre linéaire et les probabilités visuellement accessibles.",
    "cd_033": "Jeux de comptage, de formes et de numération précoce avec les personnages préférés de PBS — entièrement gratuits.",
    "cd_034": "Leçons vidéo animées gratuites couvrant tous les sujets, de l'arithmétique à l'algèbre.",
    "cd_035": "Bibliothèque gratuite de l'Université de Cambridge — de riches problèmes mathématiques pour tous les âges.",
    "cd_036": "Des centaines de jeux mathématiques gratuits pour la pré-maternelle jusqu'au CM2 — version web financée par la publicité.",
    "cd_037": "Programme mathématique interactif aligné sur le programme scolaire — gratuit à la maison avec des comptes enseignants.",
    "cd_038": "Applications gratuites pour le web et l'iPad — boulier numérique, droite numérique, géoboard et outils sur les fractions.",
    "cd_039": "Tâches mathématiques ouvertes gratuites de Stanford — visuelles, créatives et favorisant un état d'esprit de croissance.",
    "cd_040": "Jeux gratuits de résolution de problèmes mathématiques avec Peg + Cat — comptage, formes et motifs.",
    "cd_041": "Série de comptage animée gratuite de la BBC avec des jeux — transforme les nombres en personnages pour les enfants de 3 à 6 ans.",
    "cd_042": "Cours de mathématiques de premier cycle gratuits du MIT — calcul, algèbre linéaire et plus, avec des conférences complètes.",
    "cd_043": "Accès gratuit en audit à des cours de mathématiques des meilleures universités — preuves, statistiques, calcul.",
    "cd_044": "Manipulatifs mathématiques virtuels et jeux gratuits et sans publicités pour le début du primaire — compteurs, fractions et plus.",
    "cd_045": "Plus de 150 simulations scientifiques interactives de l'Université du Colorado — le meilleur laboratoire gratuit au monde dans un navigateur.",
    "cd_046": "Leçons scientifiques de type « mystère » pour le primaire — vidéo, activité pratique et discussion dans chaque unité.",
    "cd_047": "Site gratuit de la NASA pour les jeunes apprenants — jeux, activités et vidéos sur le climat, la Terre et l'espace.",
    "cd_048": "De courtes vidéos scientifiques amusantes et riches en faits pour les jeunes enfants — parfaites pour répondre à chaque question « pourquoi ».",
    "cd_049": "Manuels numériques gratuits couvrant la physique, la chimie, la biologie, les sciences de la Terre et plus — avec exercices adaptatifs.",
    "cd_050": "Superbes films de biologie, activités d'analyse de données et leçons pour les classes de l'Howard Hughes Medical Institute.",
    "cd_051": "De courtes vidéos scientifiques dynamiques pour les classes de CM1-CM2 — sciences de la vie, de la Terre, physiques et spatiales.",
    "cd_052": "Leçons scientifiques structurées pour le primaire et le secondaire — vidéos, quiz et guides de révision.",
    "cd_053": "Activités scientifiques pratiques et démonstrations vidéo du légendaire musée des sciences de San Francisco.",
    "cd_054": "Cours de physique, chimie, biologie et NGSS avec exercices, vidéos et articles — entièrement gratuits.",
    "cd_055": "Leçons, activités, données et défis directement de la NASA — des fusées au climat en passant par les exoplanètes.",
    "cd_056": "Ressources scientifiques de qualité muséale — des millions de spécimens, d'images et de collections de leçons, tous gratuits.",
    "cd_057": "Jeux scientifiques gratuits avec SciGirls, Wild Kratts et plus — enquête amusante pour les enfants de 4 à 8 ans.",
    "cd_058": "Des faits extraordinaires, des expériences et des vidéos sur les animaux — éveille la curiosité des tout-petits aux préadolescents.",
    "cd_059": "Bases de la météo et de l'espace expliquées avec des jeux et des vidéos — gratuit de la NASA et de la NOAA.",
    "cd_060": "Investigations de type muséal et sciences créatives — gratuites et sans publicités pour les 5-12 ans.",
    "cd_061": "Encyclopédie scientifique adaptée aux enfants sur tous les sujets — gratuite, sécurisée et clairement rédigée.",
    "cd_062": "Laboratoires virtuels, vidéos et études de cas construits par des scientifiques en exercice — gratuits.",
    "cd_063": "Accès gratuit en audit à des cours scientifiques de niveau universitaire du MIT, de Harvard et d'autres établissements.",
    "cd_064": "Cours scientifiques de premier cycle gratuits du MIT — biologie, chimie, physique avec des conférences complètes.",
    "cd_065": "Accès gratuit en audit à des cours universitaires de physique, chimie et sciences de la Terre.",
    "cd_066": "Explorez la planète en 3D spectaculaire avec des visites guidées « Voyager » — histoire, culture et nature à portée de main.",
    "cd_067": "Plus de 300 quiz de géographie gratuits — pays, capitales, drapeaux, fleuves, montagnes et plus.",
    "cd_068": "Géographie, cultures, animaux et aventures adaptés aux enfants de National Geographic — gratuit en ligne.",
    "cd_069": "La série historique rapide, spirituelle et riche en faits de John Green — monde, Europe, États-Unis et plus.",
    "cd_070": "Leçons d'histoire structurées pour le primaire et le secondaire — Romains, Tudors, guerres mondiales et histoire mondiale.",
    "cd_071": "Jeux et leçons d'éducation civique gratuits fondés par la juge O'Connor — comment fonctionne le gouvernement, en jouant.",
    "cd_072": "« Reading Like a Historian » — leçons d'enquête gratuites qui enseignent les sources, la corroboration et l'argumentation.",
    "cd_073": "Cours interdisciplinaire couvrant 13,8 milliards d'années — du Big Bang à l'avenir de l'humanité.",
    "cd_074": "Articles d'histoire, cartes, chronologies et vidéos gratuits et validés par des pairs, couvrant chaque continent et chaque époque.",
    "cd_075": "Sources primaires prêtes pour la classe — photos historiques, lettres, cartes et enregistrements audio — tous libres d'utilisation.",
    "cd_076": "Des milliers d'activités et d'artefacts historiques gratuits provenant des musées du Smithsonian.",
    "cd_077": "L'outil gratuit des Archives nationales américaines pour enseigner avec des documents sources primaires et des photos.",
    "cd_078": "Articles adaptés aux enfants sur toutes les civilisations avec chronologies, jeux et quiz.",
    "cd_079": "Jeux gratuits de carte et de communauté — géographie précoce et éducation civique pour les jeunes apprenants.",
    "cd_080": "Égypte ancienne, Vikings, empires — articles illustrés et vidéos pour les enfants de 5 à 12 ans.",
    "cd_081": "Atlas interactif de l'histoire mondiale — voir n'importe quelle région à n'importe quel moment de 3500 av. J.-C. à aujourd'hui.",
    "cd_082": "Articles d'histoire clairs et précis rédigés pour les enfants — couvre toutes les époques.",
    "cd_083": "Collections gratuites de sources primaires avec des idées de leçons — manuscrits, cartes et plus.",
    "cd_084": "Accès gratuit en audit à des cours d'histoire de Harvard, Columbia et d'autres grandes universités.",
    "cd_085": "Jeux gratuits présentant les quartiers, les aidants et les notions civiques de base pour les enfants d'âge préscolaire.",
    "cd_086": "Boîte à outils gratuite enseignant la communauté, la famille et la culture aux enfants de 3 à 5 ans.",
    "cd_087": "Encyclopédie gratuite DK pour les enfants — civilisations anciennes, explorateurs et chronologies.",
    "cd_088": "Articles d'histoire gratuits au format magazine avec de vivantes illustrations pour les jeunes apprenants.",
    "cd_089": "Le langage de codage par blocs gratuit du MIT — la façon la plus populaire au monde pour les enfants de créer des jeux, de l'art et des histoires.",
    "cd_090": "Programme complet d'informatique de la maternelle au lycée — Hour of Code, CS Fundamentals, cours de niveau avancé — entièrement gratuit.",
    "cd_091": "Codage sur tablette pour les 5-7 ans — faire glisser des images pour donner vie aux personnages. Aucune lecture requise.",
    "cd_092": "Cours de codage de type aventure qui progressent des blocs vers Python et JavaScript étape par étape.",
    "cd_093": "JavaScript, HTML/CSS, SQL et théorie de l'informatique — leçons interactives avec retour immédiat.",
    "cd_094": "Le légendaire cours d'introduction à l'informatique de Harvard — entièrement gratuit sur edX, avec un vrai certificat.",
    "cd_095": "Plus de 3 000 heures de formation pratique gratuite en développement web, analyse de données et ML — avec des certifications à conserver.",
    "cd_096": "Environnement de codage dans le navigateur pour plus de 50 langages — configuration zéro, collaboration comme sur Google Docs.",
    "cd_097": "Éditeur en ligne gratuit (blocs + Python) pour programmer un petit ordinateur physique — des milliers de projets gratuits.",
    "cd_098": "Apprendre Python et JavaScript en jouant à un RPG — résoudre les niveaux en tapant de vrais codes.",
    "cd_099": "Référence de développement web conviviale avec des milliers d'éditeurs en direct « Try It Yourself » — HTML, CSS, JS, Python, SQL.",
    "cd_100": "Des « katas » de codage en petites bouchées dans plus de 50 langages — affine la résolution de problèmes avec de vrais défis de programmation.",
    "cd_101": "Introduit les concepts de programmation aux classes de maternelle-CE1 avec des personnages « fuzz » sympathiques — version lite gratuite.",
    "cd_102": "Puzzle gratuit dans le navigateur qui enseigne le séquençage, les boucles et les conditionnelles — convient à tous les niveaux.",
    "cd_103": "Série gratuite de puzzles de programmation de Google qui progressent des blocs glissés vers JavaScript.",
    "cd_104": "Jeux de codage gratuits construits autour des émissions PBS bien-aimées — première introduction à la logique de programmation.",
    "cd_105": "Tutoriels de codage d'une heure pour tous les âges — de Minecraft à Python, tous gratuits.",
    "cd_106": "Leçons mobiles en petites bouchées en Python, JS, SQL — communauté de codage social gratuite.",
    "cd_107": "Leçons de codage interactives dans le navigateur — la version gratuite couvre les bases de Python, HTML/CSS et JS.",
    "cd_108": "Application de codage gratuite pour débutants — faire glisser des commandes pour faire danser Daisy. Adapté à la pré-maternelle.",
    "cd_109": "Leçons gratuites pour les maternelle-CE1 qui développent la dactylographie et les habitudes de pensée computationnelle.",
    "cd_110": "Bee-Bot en ligne gratuit — une abeille programmable qui développe le séquençage pour les tout-jeunes codeurs.",
    "cd_111": "Programme gratuit de citoyenneté numérique de la maternelle au lycée — vie privée, sécurité, littératie médiatique et IA, par groupe d'âge.",
    "cd_112": "Entraîner une IA à trier la vie marine — première expérience des enfants avec l'apprentissage automatique supervisé et les biais.",
    "cd_113": "Le jeu gratuit « Interland » de Google et des ressources pédagogiques qui enseignent la sécurité sur Internet, la bienveillance et la vie privée.",
    "cd_114": "Le programme gratuit « Everyday Ethics » et de littératie en IA du MIT pour le collège et le lycée — biais, équité, agentivité.",
    "cd_115": "MOOC gratuit de l'Université d'Helsinki et Reaktor — ce qu'est vraiment l'IA, en langage simple.",
    "cd_116": "Entraîner son propre modèle d'apprentissage automatique à partir d'images, de sons ou de poses — directement dans le navigateur, sans codage.",
    "cd_117": "Les mini-cours gratuits d'Andrew Ng sur les LLM, le prompting et l'IA moderne — la façon la plus rapide de progresser.",
    "cd_118": "Le centre canadien de littératie numérique et médiatique — jeux, leçons et ressources contre la désinformation.",
    "cd_119": "Le cadre européen des compétences numériques — une liste de vérification des compétences numériques indispensables à chaque adulte.",
    "cd_120": "Activités gratuites d'IA pour la maternelle au lycée du MIT — expériences en classe d'une journée couvrant les biais, l'IA générative et plus.",
    "cd_121": "Le tuteur IA de Khan Academy qui ne donne jamais la réponse — lui demander de débattre, d'entraîner ou d'interroger.",
    "cd_122": "Leçons vidéo gratuites sur les tâches numériques du quotidien — documents, feuilles de calcul, présentations, recherche, budget et plus.",
    "cd_123": "Extension Scratch gratuite — entraîner des modèles avec du texte, des images ou des chiffres, puis les utiliser dans des jeux.",
    "cd_124": "Leçons et projets d'IA sélectionnés pour la maternelle au lycée — la version gratuite couvre les modules d'introduction.",
    "cd_125": "Leçons gratuites de la maternelle au lycée sur le fonctionnement de l'IA, les biais, les deepfakes et l'utilisation responsable.",
    "cd_126": "Modules d'IA gratuits avec des leçons débranchées, des vidéos et des activités de formation pour les classes de CE2 au lycée.",
    "cd_127": "Jeu de dessin amusant de 20 secondes qui montre comment un réseau de neurones reconnaît les croquis.",
    "cd_128": "Expériences ludiques dans le navigateur qui démystifient l'apprentissage automatique — toutes gratuites, sans inscription.",
    "cd_129": "Guide gratuit pour les élèves sur l'utilisation éthique de l'IA à l'école — amorces de conversation et conseils.",
    "cd_130": "Leçons d'introduction gratuites sur ce qu'est l'IA pour les enfants de 5 à 7 ans — utilise des chansons et des histoires.",
    "cd_131": "Application de création gratuite où les plus jeunes apprenants construisent des histoires interactives — premières habitudes de pensée en IA.",
    "cd_132": "Jeux gratuits qui construisent les bases pour l'IA/l'informatique — motifs, prédiction, décisions pour les enfants de 4 à 8 ans.",
    "cd_133": "Cours interactifs de résolution de problèmes en logique, probabilités, informatique et plus — la meilleure salle de sport intellectuelle.",
    "cd_134": "Courtes leçons animées avec questions et discussion — une bibliothèque de moments « Eureka » stimulants.",
    "cd_135": "Cours vidéo courts, intelligents et rapides sur la philosophie, les statistiques, les méthodes d'étude et la façon de penser.",
    "cd_136": "Vidéos scientifiques primées qui modélisent la curiosité, les idées reçues et la résolution de problèmes réels.",
    "cd_137": "Livres, vidéos gratuits et le célèbre entraîneur adaptatif Alcumus — résolution de problèmes de style olympique en mathématiques.",
    "cd_138": "Vidéos de concepts animées couvrant toutes les matières avec des quiz qui vérifient la vraie compréhension.",
    "cd_139": "Articles d'actualité à 5 niveaux de lecture — enseigne comment analyser les nouvelles et former des arguments.",
    "cd_140": "Informations côte à côte de la gauche, du centre et de la droite — repérer les biais et voir le tableau complet.",
    "cd_141": "Outil de débat structuré pour les classes — les élèves construisent des arbres d'arguments et apprennent à raisonner ensemble.",
    "cd_142": "Défis mathématiques en famille conçus pour que la logique et la résolution de problèmes ressemblent à un jeu.",
    "cd_143": "Boîte à outils de routines de pensée du Project Zero de Harvard (« See-Think-Wonder », « Claim-Support-Question »…).",
    "cd_144": "Plateforme gratuite de littératie médiatique du News Literacy Project — combattre la désinformation avec de vraies compétences journalistiques.",
    "cd_145": "Plans de discussion gratuits basés sur des questions qui développent le raisonnement — fonctionne dès la maternelle.",
    "cd_146": "Jeu gratuit au rythme rapide — savoir repérer les fausses nouvelles ? Développe les réflexes de littératie médiatique.",
    "cd_147": "Vidéos et leçons gratuites sur la détection des biais et de la désinformation — excellent point de départ pour la discussion.",
    "cd_148": "Ressources gratuites d'Ellen Galinsky sur les sept compétences de vie essentielles pour les enfants qui pensent.",
    "cd_149": "Vidéos gratuites de routines de pensée tirées de vraies classes — montre des séminaires socratiques en action.",
    "cd_150": "Problèmes non résolus et ouverts gratuits pour la maternelle au lycée — réflexion profonde, pas de réponses faciles.",
    "cd_151": "Activités gratuites de pensée critique sélectionnées pour tous les niveaux par Common Sense Education.",
    "cd_152": "Jeux gratuits développant le raisonnement précoce et la reconnaissance des motifs pour les enfants de 3 à 5 ans.",
    "cd_153": "Jeux gratuits de raisonnement et de résolution de problèmes avec les personnages préférés de PBS.",
    "cd_154": "Conseils gratuits pour développer les compétences de pensée précoces — pour les parents d'enfants de 0 à 5 ans.",
    "cd_155": "Ressource gratuite de la BBC — courtes vidéos, idées et jeux qui développent la pensée et le langage de la petite enfance.",
    "cd_156": "Articles gratuits avec des activités de pensée pour la petite enfance — observation, prédiction, tri.",
    "cd_157": "Application de pleine conscience totalement gratuite d'une organisation australienne à but non lucratif, avec des programmes pour les 3 ans jusqu'à l'âge adulte.",
    "cd_158": "Les aventures de yoga pour enfants bien-aimées de Jaime Amor — gratuites sur YouTube, utilisées par des millions de familles et d'écoles.",
    "cd_159": "Courtes vidéos de mouvement et de pleine conscience que les enseignants peuvent diffuser en classe — dépenser l'énergie, puis se reconcentrer.",
    "cd_160": "Méditations guidées pour les jeunes enfants du Committee for Children — de courtes « séances » pour calmer et concentrer.",
    "cd_161": "Plus de 150 000 méditations guidées, sons de sommeil et conférences gratuites — la plus grande bibliothèque gratuite de pleine conscience au monde.",
    "cd_162": "Headspace Premium — gratuit pour les enseignants du primaire au lycée dans le monde entier, incluant du contenu prêt pour la classe pour les élèves.",
    "cd_163": "Calm Premium gratuit pour les enseignants du primaire au lycée — méditation, histoires pour s'endormir et contenu apaisant pour les classes.",
    "cd_164": "Application gratuite et fondée sur les données probantes d'Anxiety Canada — outils TCC pour les ados pour gérer l'anxiété et l'inquiétude.",
    "cd_165": "Courtes vidéos SEL animées sur le « vocabulaire émotionnel » — faire le point, exprimer les émotions, se reconcentrer.",
    "cd_166": "Le cadre de référence en matière d'apprentissage socio-émotionnel — ressources gratuites pour les enseignants, les écoles et les familles.",
    "cd_167": "Informations gratuites et fondées sur les données probantes sur la santé mentale des jeunes concernant le stress, l'identité, la famille et plus — d'Australie.",
    "cd_168": "Informations confidentielles gratuites, outils d'adaptation et ligne d'assistance pour les enfants — un endroit sûr quand les choses semblent trop grandes.",
    "cd_169": "Vidéos et imprimables gratuits sur les émotions, les routines et la résilience pour les jeunes enfants.",
    "cd_170": "Leçons de prévisualisation gratuites sur l'anxiété et la pleine conscience pour les enfants et les préadolescents — animées et apaisantes.",
    "cd_171": "Pleine conscience gratuite adaptée aux enfants — faire le point sur les émotions, puis choisir une activité apaisante.",
    "cd_172": "Ressources gratuites de santé mentale pour les ados — stress, sommeil, relations et demande d'aide.",
    "cd_173": "Programme de résilience gratuit pour les écoles primaires — fondé sur des données probantes reconnues.",
    "cd_174": "Guides gratuits et fondés sur les données probantes pour les parents et les enfants sur l'anxiété, le TOC et l'inquiétude.",
    "cd_175": "Ressource gouvernementale gratuite — ce à quoi ressemble l'intimidation et exactement quoi faire.",
    "cd_176": "Boîte à outils gratuite sur l'anxiété et animations de respiration conçues pour les ados de 13 à 18 ans.",
    "cd_177": "Dépistage gratuit de la santé mentale pour les ados et ressources d'auto-assistance, sans jugement.",
    "cd_178": "Le programme de référence gratuit d'éducation aux finances personnelles — cours complets, projets et unités interactives.",
    "cd_179": "Simulateur financier réaliste — les élèves s'entraînent à épargner, à établir un budget et à prendre des décisions en situation de crise dans un environnement sécurisé.",
    "cd_180": "Leçons gratuites d'économie et de finances personnelles pour la maternelle au lycée du Council for Economic Education.",
    "cd_181": "Les jalons financiers par âge du CFPB américain pour les familles — de simples conversations qui construisent des habitudes pour toute la vie.",
    "cd_182": "Jeux gratuits, calculatrices et plans de leçons de Visa — sujets financiers par étape de vie pour tous les âges.",
    "cd_183": "Cours gratuit de finances personnelles — bases des impôts, du crédit, des prêts, du logement, des assurances et de la retraite.",
    "cd_184": "Programmes mondiaux de maternelle au lycée en littératie financière, préparation au travail et entrepreneuriat — souvent dispensés gratuitement.",
    "cd_185": "Programme gratuit d'éducation financière fédérale américaine — bases de la banque, du crédit, des dettes et des assurances.",
    "cd_186": "Sujets financiers du programme britannique — comment fonctionnent les banques, budget, impôts, assurances et intérêts.",
    "cd_187": "Programme financier produit par des pairs et à l'esprit critique — apprend aux ados comment les marchés essaient de leur vendre des produits.",
    "cd_188": "Définitions gratuites en langage clair de chaque terme bancaire, d'assurance et d'investissement que l'on puisse rencontrer.",
    "cd_189": "Émission gratuite de PBS et matériel de classe enseignant aux enfants l'argent, les affaires et l'entrepreneuriat.",
    "cd_190": "Tour d'horizon gratuit des meilleurs jeux d'argent en ligne pour le primaire jusqu'au lycée.",
    "cd_191": "Leçons d'argent gratuites par étape d'âge — des tirelires aux cartes de crédit — du blog Mint.",
    "cd_192": "Jeux gratuits sur l'argent avec les personnages préférés de PBS — première introduction aux pièces et aux échanges.",
    "cd_193": "Leçons et quiz gratuits sur la littératie financière mondiale de l'Université George Washington.",
    "cd_194": "Jeu de quiz gratuit sur l'argent sur le thème de la NFL — plusieurs niveaux de compétence, idéal pour les ados.",
    "cd_195": "Leçons gratuites d'économie et d'argent conçues pour les classes de maternelle-CE1 avec des livres d'histoires.",
    "cd_196": "Programme gratuit de Wells Fargo couvrant les enfants, les ados et les adultes — sans inscription requise.",
    "cd_197": "Jeux gratuits de comptage et d'échanges — développe le premier sens de l'argent pour les enfants d'âge préscolaire.",
    "cd_198": "Boîte à outils gratuite sur l'épargne, les dépenses et le partage — conçue pour les enfants de 3 à 5 ans.",
    "cd_199": "Activités familiales gratuites qui introduisent les concepts de l'argent aux jeunes enfants.",
    "cd_200": "Conseils gratuits par âge sur l'enseignement de l'argent aux enfants — incluant les 3-5 ans.",
    "cd_201": "Programme FDIC gratuit pour la pré-maternelle jusqu'au CE1 — bases de l'argent avec des histoires.",
    "cd_202": "Informations de santé révisées par des médecins en trois voix — pour les enfants, les ados et les parents. Corps, esprit, nutrition, sécurité.",
    "cd_203": "Recettes testées par des enfants d'America's Test Kitchen, compétences culinaires et vidéos sur la science de la cuisine — gratuites.",
    "cd_204": "Recettes sécurisées pour enfants par âge et niveau — des pizzas rigolottes aux dîners familiaux complets, étape par étape.",
    "cd_205": "Le site gratuit de nutrition de l'USDA — planifier des repas équilibrés et apprendre les cinq groupes alimentaires avec des jeux et des leçons.",
    "cd_206": "Le guide gratuit du NHS britannique sur l'alimentation, l'exercice, le sommeil, la santé sexuelle et le bien-être mental — fiable et clair.",
    "cd_207": "Applications gratuites de premiers secours et d'urgence de la Croix-Rouge — pratiquer la RCP, la réponse à l'étouffement et la préparation aux catastrophes.",
    "cd_208": "Jeux gratuits de préparation aux catastrophes de la FEMA et plans familiaux — incendies, tempêtes, tremblements de terre, pannes de courant.",
    "cd_209": "Entraînements gratuits, routines de 7 minutes et Couch to 5K — mouvement fondé sur les données probantes pour tout le monde.",
    "cd_210": "Plus de 600 vidéos d'entraînement complets gratuits à tous les niveaux — la plupart ne nécessitent aucun équipement.",
    "cd_211": "Conseils gratuits et fondés sur les données probantes sur le sommeil adaptés aux ados — pourquoi c'est important et comment vraiment mieux dormir.",
    "cd_212": "Le site parental gratuit de l'American Academy of Pediatrics — réponses fiables sur la santé, la sécurité et la croissance.",
    "cd_213": "Leçons gratuites du Royaume-Uni sur la cuisine, les compétences ménagères, le bien-être et les essentiels de la vie adulte.",
    "cd_214": "Jeux et vidéos gratuits sur les routines, les émotions et les soins personnels pour les enfants d'âge préscolaire.",
    "cd_215": "Projets pratiques gratuits sur les compétences domestiques — circuits, couture, jardinage et plus.",
    "cd_216": "Conseils officiels gratuits en matière de nutrition avec des jeux, des conseils pour faire les courses et des menus types.",
    "cd_217": "Pages gratuites destinées aux enfants sur les amitiés, le respect et la gestion des conflits.",
    "cd_218": "Bibliothèque gratuite de recettes conçues pour les enfants — simples, sûres et délicieusement équilibrées.",
    "cd_219": "Articles gratuits et fondés sur les données probantes sur les défis de la vie quotidienne pour les enfants et les ados.",
    "cd_220": "Blog gratuit de recettes économiques — enseigne la cuisine et la gestion du budget alimentaire avec des coûts transparents.",
    "cd_221": "« Playbooks » gratuits et fondés sur la recherche de l'équipe d'Angela Duckworth — persévérance, bienveillance, curiosité, maîtrise de soi.",
    "cd_222": "Leçons gratuites anti-discrimination et de justice sociale et magazines pour élèves du Southern Poverty Law Center.",
    "cd_223": "Ressources gratuites sur l'histoire, l'éthique et la participation civique — comment les choix ordinaires façonnent la société.",
    "cd_224": "Leçons gratuites soutenues par l'ONU sur les 17 Objectifs de Développement Durable — pour tous les âges et toutes les langues.",
    "cd_225": "Programme gratuit de bienveillance pour la maternelle au lycée, plans de leçons et imprimables — SEL fondé sur les données probantes par l'action.",
    "cd_226": "Pratiques gratuites et fondées sur la recherche de l'UC Berkeley pour cultiver l'empathie, la gratitude et le bien-être des élèves.",
    "cd_227": "Cadre gratuit des « Six Pillars of Character » — fiabilité, respect, responsabilité, équité, sollicitude, citoyenneté.",
    "cd_228": "Jeux civiques gratuits et plans de leçons — droit, droits, politiques publiques. La citoyenneté active rendue engageante.",
    "cd_229": "Courts métrages gratuits, essais photographiques et leçons de classe sur les cultures, la résilience et notre monde commun.",
    "cd_230": "Des histoires de vraies personnes qui « tendent le cou » pour le bien commun — plus un programme d'apprentissage par le service.",
    "cd_231": "Leçons et activités gratuites d'Amnesty International — comprendre et défendre les droits humains universels.",
    "cd_232": "Programme gratuit SEL et de citoyenneté mondiale où l'activité des enfants aide à livrer de la nourriture thérapeutique aux enfants dans le besoin.",
    "cd_233": "Vidéos et jeux gratuits de PBS modélisant la bienveillance, le respect et l'amitié pour les jeunes enfants.",
    "cd_234": "Leçons gratuites de la maternelle au lycée sur les droits humains, l'équité et la citoyenneté mondiale de l'UNICEF.",
    "cd_235": "Leçons gratuites de la maternelle au lycée sur l'identité, la diversité, la justice et l'action.",
    "cd_236": "Articles et vidéos gratuits sur l'enseignement de l'empathie, de l'intégrité et de la responsabilité.",
    "cd_237": "Activités gratuites de bienveillance, imprimables et idées de projets de service pour tous les âges.",
    "cd_238": "Ressources gratuites des Objectifs de Développement Durable de l'ONU — dessins animés, affiches et leçons.",
    "cd_239": "Programme gratuit utilisant de vraies interviews pour développer l'empathie et les compétences d'écoute.",
    "cd_240": "Une douzaine d'expériences gratuites dans le navigateur qui enseignent le rythme, l'harmonie et le son — sans compte, sans installation.",
    "cd_241": "Studio de musique complet dans le navigateur — enregistrement, mixage et partage illimités et gratuits, utilisé dans des milliers d'écoles.",
    "cd_242": "Application de peinture numérique professionnelle open source — 100 % gratuite sur toutes les plateformes, sans filigrane.",
    "cd_243": "Créer des affiches, des présentations, des vidéos et plus — la suite complète Canva Pro est gratuite pour les élèves et enseignants du primaire au lycée.",
    "cd_244": "L'outil gratuit d'Autodesk dans le navigateur pour la conception 3D, les circuits et les blocs de code — la première application CAO la plus simple.",
    "cd_245": "Modélisation 3D, animation et rendu de niveau professionnel — entièrement gratuit et open source.",
    "cd_246": "Envoyer un emoji, une humeur ou un mot par texto à SFMOMA et recevoir en retour une œuvre surprise de sa collection de 45 000 œuvres.",
    "cd_247": "Visiter virtuellement plus de 2 000 musées — zoomer sur des peintures, explorer des expositions, jouer à des jeux d'art.",
    "cd_248": "Activités artistiques gratuites, guides audio et ressources pédagogiques du Museum of Modern Art.",
    "cd_249": "Projets d'invention gratuits — transformer des bananes en touches de piano. Combine créativité, fabrication et pensée computationnelle.",
    "cd_250": "Site interactif gratuit qui enseigne les fondamentaux de la création musicale — rythme, accords, mélodie — dans le navigateur.",
    "cd_251": "Adobe Express Premium gratuit pour la maternelle au lycée — créer des vidéos, des graphiques, des flyers et des pages web comme un designer.",
    "cd_252": "Tutoriels de dessin étape par étape gratuits sur YouTube — des formes aux personnages détaillés.",
    "cd_253": "Le site gratuit du Met axé sur les enfants — explorer l'art, voyager dans le temps et réaliser des projets créatifs.",
    "cd_254": "Expositions en ligne gratuites et guides d'activités créatives pour le monde du jeu.",
    "cd_255": "Activités gratuites d'art et de photographie de National Geographic — éveille la curiosité.",
    "cd_256": "Programmation visuelle gratuite pour créer des animations, de l'art et des histoires — immense communauté créative.",
    "cd_257": "Leçons de dessin gratuites — crayon, perspective, portraits — organisées du niveau grand débutant vers le haut.",
    "cd_258": "Cours gratuits d'histoire de l'art, de théorie musicale et de design avec des vidéos et des projets.",
    "cd_259": "Activités artistiques gratuites pour les 4-8 ans — imprimables, idées, gribouillage en ligne.",
    "cd_260": "Imprimables gratuits et tutoriels de bricolage étape par étape — parfaits pour les ateliers d'art à la maternelle.",
    "cd_261": "Le MOOC mondialement célèbre de Barbara Oakley sur les techniques d'étude fondées sur les neurosciences — gratuit en audit, transformateur pour les élèves plus âgés.",
    "cd_262": "L'application de flashcards à répétition espacée de référence — scientifiquement prouvée pour ancrer les faits dans la mémoire à long terme.",
    "cd_263": "Créer des jeux de flashcards, jouer à des jeux d'apprentissage et passer des tests d'entraînement — utilisé par des centaines de millions d'élèves dans le monde.",
    "cd_264": "Minuteur Pomodoro propre dans le navigateur — blocs de concentration de 25 minutes avec de courtes pauses, prouvé pour vaincre la procrastination.",
    "cd_265": "Agenda étudiant gratuit — suivre les cours, examens, tâches et devoirs sur tous les appareils dans un calendrier intelligent.",
    "cd_266": "Affiches gratuites, podcasts et guides de stratégies d'étude fondés sur la recherche en sciences cognitives — pratique de récupération, élaboration et plus.",
    "cd_267": "Leçons et activités sur l'état d'esprit de croissance de Carol Dweck, gratuites pour tous les âges — apprend aux enfants que l'intelligence peut se développer.",
    "cd_268": "Outil gratuit de cartographie conceptuelle de l'IHMC — construire des cartes de connaissances visuelles qui rendent les idées complexes claires et mémorables.",
    "cd_269": "Prise de notes et répétition espacée combinées — transformer n'importe quel paragraphe en flashcard instantanément pendant l'étude.",
    "cd_270": "Application gratuite de notes « second cerveau » — relier les idées comme un Wikipedia personnel pour voir comment les connaissances se connectent.",
    "cd_271": "Rester loin de son téléphone en faisant pousser un arbre virtuel — si l'on arrête trop tôt, l'arbre meurt. Gamifie les sessions d'étude concentrées.",
    "cd_272": "Plateforme d'étude propulsée par l'IA — transformer des PDF et des notes en flashcards, cartes mentales et quiz automatiquement.",
    "cd_273": "Stratégies d'étude gratuites testées par des élèves — prise de notes, récupération, pratique espacée.",
    "cd_274": "Flashcards, plans d'étude et notes gratuits — fonctionne pour toutes les matières et tous les âges.",
    "cd_275": "Chaîne YouTube gratuite — stratégies de productivité, d'étude et de prise de notes qui fonctionnent.",
    "cd_276": "Flashcards et jeux d'étude gratuits — plus de 800 sujets couverts par de vrais élèves.",
    "cd_277": "Flashcards, cartes mentales et quiz gratuits — web et mobile, idéal pour la révision.",
    "cd_278": "Cours vidéo gratuit en 10 épisodes sur la façon d'apprendre à apprendre — conçu pour les ados.",
    "cd_279": "Activités gratuites d'apprentissage précoce couvrant l'ABC, le comptage, les routines et les habitudes de curiosité.",
    "cd_280": "Conseils gratuits pour les parents sur le soutien aux habitudes d'apprentissage précoce chez les enfants de 0 à 5 ans.",
    "cd_281": "Articles gratuits sur la façon dont le jeu développe l'apprentissage précoce, la concentration et la formation des habitudes.",
    "cd_282": "Routines gratuites et activités d'autorégulation pour développer les premières habitudes d'apprentissage.",
    "cd_283": "Guides gratuits pour les parents et les enseignants sur les routines d'apprentissage pour les classes de maternelle-CE1.",
    "cd_284": "Activités gratuites d'apprentissage précoce — concentration, routines et curiosité pour les enfants de 3 à 7 ans.",
    "cd_285": "Chansons et routines gratuites qui ancrent les premières habitudes de lecture et de numération.",
    "cd_286": "Essai gratuit d'un programme de lecture adaptative précoce — développe la fluidité d'apprentissage dès la maternelle.",
    "cd_287": "Gratuit pour les éducateurs — une habitude quotidienne de lecture de 20 minutes fait progresser les plus jeunes apprenants.",
    "cd_s01": "Vidéos de mouvement et de pleine conscience favorites en classe qui font lever les enfants — danse, yoga et pauses cérébrales en clips de 3 à 5 minutes.",
    "cd_s02": "Aventures de yoga narratives pour les jeunes enfants — poses intégrées dans des récits imaginatifs sur des dragons, des super-héros et des mondes magiques.",
    "cd_s03": "Des centaines de tutoriels de jeux EPS et d'idées d'activités physiques pour l'école — faciles à mettre en place sans équipement et adaptables à n'importe quel groupe.",
    "cd_s04": "Vaste bibliothèque de plans de leçons EPS, d'idées d'échauffement et d'activités physiques organisées par âge, compétence et équipement — une référence pour les enseignants d'EPS.",
    "cd_s05": "Articles adaptés aux enfants sur la science de l'exercice, la nutrition, le sommeil et la sécurité sportive — rédigés par des médecins et conçus pour développer des habitudes saines durables.",
    "cd_s06": "Routines d'entraînement vidéo guidées spécialement conçues pour les enfants — circuits de force, de flexibilité et de cardio adaptables au temps et à l'espace disponibles.",
    "cd_s07": "Boîtes à outils, fiches d'activités et guides de programme pour intégrer le mouvement quotidien dans la vie scolaire — 60 minutes d'activité par jour, rendues praticables.",
    "cd_s08": "Plus de 600 vidéos d'entraînement complets gratuits en cardio, musculation, HIIT et étirements — filtrables par durée, niveau et équipement nécessaire.",
    "cd_s09": "Le plan de course pour débutants le plus populaire au monde — 9 semaines pour courir 5 km sans s'arrêter, avec une application gratuite et des guides audio animés par des entraîneurs reconnus.",
    "cd_s10": "Articles d'entraînement spécifiques aux sports rédigés avec des entraîneurs professionnels — vitesse, agilité, force et science de la récupération pour les jeunes athlètes sérieux.",
    "cd_s11": "Bibliothèque complète d'entraînements guidés par des coachs — séances au poids du corps, de musculation et de yoga de 15 à 60 minutes, toutes gratuites depuis que Nike a supprimé le paywall.",
    "cd_s12": "Cours gratuits de niveau universitaire sur la science du sport, l'activité physique et la performance humaine — idéal pour les élèves souhaitant poursuivre une carrière dans le sport.",
}
