FR_TEACHERS = {
    "cd_t_000": "Le MOOC de sciences de l'apprentissage le plus populaire au monde (4 M+ d'étudiants) — chunking, mémoire et pensée diffuse. Audit gratuit.",
    "cd_t_001": "Le podcast et blog de Jennifer Gonzalez — des centaines d'analyses approfondies gratuites sur les stratégies pédagogiques, l'engagement et les techniques de classe.",
    "cd_t_002": "Six stratégies d'étude fondées sur des données probantes (pratique espacée, récupération, élaboration, etc.) expliquées clairement pour les enseignants et les élèves.",
    "cd_t_003": "Le guide gratuit de référence de Vanderbilt sur la taxonomie révisée de Bloom — listes de verbes, amorces de questions et modèles de planification de cours.",
    "cd_t_004": "Lignes directrices gratuites sur la conception universelle de l'apprentissage (UDL) — planifier des cours adaptés à tous les apprenants dès le départ, sans ajout après coup.",
    "cd_t_005": "Les 63 techniques de classe de Doug Lemov — extraits vidéo gratuits, lectures accompagnées et guides de terrain sur le cold calling, le rythme et bien plus.",
    "cd_t_006": "Articles de recherche appliquée sur la différenciation, l'apprentissage par projet, l'intégration socio-émotionnelle et la conception de l'évaluation.",
    "cd_t_007": "Articles gratuits sur les modèles pédagogiques modernes — taxonomies de l'apprentissage, cadres innovants et outils de pensée prêts à l'emploi en classe.",
    "cd_t_008": "Ressources gratuites de Jim Knight sur le cycle d'impact — un cadre pratique que tout enseignant peut utiliser pour son développement professionnel autonome.",
    "cd_t_009": "Recherches et outils gratuits du MIT sur la formation des enseignants — simulations, études de cas et cours sur la conception pédagogique.",
    "cd_t_010": "Des centaines d'articles gratuits évalués par des pairs sur le curriculum, l'enseignement et l'évaluation, issus de la principale association d'éducateurs au monde.",
    "cd_t_011": "Rapports gratuits traduisant les sciences cognitives en principes de formation des enseignants — La science de l'apprentissage rendue accessible.",
    "cd_t_012": "Articles gratuits d'un scientifique cognitif sur la mémoire, l'attention et la motivation — traduits du laboratoire de recherche à la pratique en classe.",
    "cd_t_013": "Mindset Works de Carol Dweck — résumés de recherche gratuits et stratégies prêtes à l'emploi pour instaurer une culture de l'état d'esprit de développement.",
    "cd_t_014": "La SDT de Deci et Ryan expliquée — pourquoi l'autonomie, la compétence et l'appartenance sont les trois clés de la motivation des élèves.",
    "cd_t_015": "La boîte à outils gratuite de routines de pensée de Project Zero — See-Think-Wonder, Claim-Support-Question et plus de 20 protocoles prêts à l'emploi en classe.",
    "cd_t_016": "Les guides pédagogiques gratuits d'Angela Duckworth sur le courage, la curiosité, la gratitude et la maîtrise de soi — fondés sur la recherche et immédiatement utilisables.",
    "cd_t_017": "Pratiques SEL gratuites du Berkeley Science Center ancrées dans la psychologie positive — bienveillance, pleine conscience et résilience.",
    "cd_t_018": "Podcast et articles gratuits sur le fonctionnement de l'apprentissage — neurosciences, motivation, équité et avenir de l'éducation.",
    "cd_t_019": "Articles de recherche gratuits de la Harvard Graduate School of Education — équité, sciences de l'apprentissage, leadership scolaire et politique éducative.",
    "cd_t_020": "Résumé gratuit en langage clair de l'EEF sur la théorie de la charge cognitive — ce qu'elle implique pour la conception des cours, les exemples guidés et la pratique.",
    "cd_t_021": "Guide gratuit clair sur la Zone de Développement Proximal de Vygotsky — comment l'étayage et l'apprentissage social façonnent la classe.",
    "cd_t_022": "Synthèse fondée sur des données probantes d'Edutopia sur ce que la recherche dit d'un enseignement efficace — accessible et pratique.",
    "cd_t_023": "Le projet Visible Thinking gratuit de Harvard PZ — des routines qui rendent la pensée des élèves visible, discutable et transférable.",
    "cd_t_024": "Vidéothèque d'enseignement réel en classe — observation d'enseignants experts en action dans différentes matières et groupes d'âge, avec des guides de réflexion.",
    "cd_t_025": "La ressource de référence sur l'apprentissage par projet — kits de démarrage, rubriques et idées de projets gratuits fondés sur la recherche.",
    "cd_t_026": "La boîte à outils gratuite d'IDEO sur la pensée design pour les éducateurs — un processus centré sur l'humain pour résoudre les défis de la classe et de l'école.",
    "cd_t_027": "Ressources gratuites d'Expeditionary Learning — caractère, esprit d'équipe et évaluation basée sur la maîtrise, ancrés dans des décennies de données scolaires.",
    "cd_t_028": "Articles gratuits de recherche appliquée avec vidéo de classe — chaque stratégie expliquée, étayée et illustrée en action.",
    "cd_t_029": "Les 250+ tailles d'effet de Hattie avec téléchargements gratuits — comprendre quelles pratiques d'enseignement ont le plus fort impact et pourquoi.",
    "cd_t_030": "Protocoles gratuits de Harvard PZ pour rendre visible la compréhension des élèves — routines de pensée avec guides d'application en classe.",
    "cd_t_031": "Cadre gratuit pour adapter l'enseignement en temps réel — faire le lien entre la théorie de l'évaluation formative et la pratique moment par moment.",
    "cd_t_032": "Cours en audit gratuit sur la conception pour l'apprentissage — design des environnements, théorie de l'engagement et pensée systémique en conception pédagogique.",
    "cd_t_033": "Plans de cours, stratégies et outils de gestion de classe fondés sur la recherche — tous liés aux standards d'apprentissage.",
    "cd_t_034": "Articles pédagogiques, webinaires et guides fondés sur la recherche issus du principal média journalistique éducatif américain.",
    "cd_t_035": "Ressources pratiques gratuites issues de la recherche en sciences de l'apprentissage financée par la NSF — traduction des neurosciences en actions pédagogiques.",
    "cd_t_036": "Teacher Center gratuit avec formations, parcours de certification et guides d'intégration en classe — la plateforme gratuite la plus utilisée par les enseignants.",
    "cd_t_037": "Parcours d'apprentissage gratuits avec badges sur Teams, OneNote, Minecraft Edu et les outils d'IA pour les classes.",
    "cd_t_038": "Articles, vidéos et guides de développement professionnel gratuits et sélectionnés sur tous les aspects de l'enseignement — le meilleur point de départ gratuit pour les enseignants.",
    "cd_t_039": "Parcours structurés gratuits vers la pédagogie moderne — par où commencer, quoi lire et comment développer sa pratique enseignante.",
    "cd_t_040": "Les guides gratuits du New Teacher Project — à quoi ressemble un enseignement de qualité et comment y parvenir de manière systématique.",
    "cd_t_041": "Le portail de développement professionnel gratuit de la National Education Association — cours, webinaires et ressources pour chaque étape de carrière.",
    "cd_t_042": "Ressources ASCD gratuites et sélectionnées spécifiquement pour les enseignants en début de carrière — mise en place de la classe, état d'esprit et survie en première année.",
    "cd_t_043": "Ressources de cours gratuites, articles de conseil et forums communautaires adaptés aux enseignants dans leurs premières années d'exercice.",
    "cd_t_044": "Points de départ pratiques gratuits pour les nouveaux enseignants — gestion de la charge de travail, stratégies de correction et gestion de sa première classe.",
    "cd_t_045": "Intégration gratuite des enseignants sur Khan Academy — mettre en place sa classe, attribuer des travaux et suivre les progrès des élèves dès le premier jour.",
    "cd_t_046": "Programme gratuit de reconnaissance Apple Teacher en autonomie — obtenir des badges pour iPad, Mac et les compétences en apprentissage créatif.",
    "cd_t_047": "L'adhésion associée gratuite donne accès à la revue Impact, aux digests de recherche et au forum communautaire pour les enseignants britanniques.",
    "cd_t_048": "Leçons de lecture gratuites alignées sur les standards pour les classes 3-12 — textes, questions, évaluations et unités ELA complètes, tout en un.",
    "cd_t_049": "Curriculum ELA et mathématiques gratuit PK-12 de l'État de New York — modules sur l'année complète, guides pédagogiques et cahiers d'élèves.",
    "cd_t_050": "Curricula ouverts gratuits les mieux notés en mathématiques et ELA (Illustrative Math, EL Education ELA) — cours complets sur l'année rédigés par des équipes de référence.",
    "cd_t_051": "Plus de 420 000 plans de cours, activités et unités gratuites partagés par les enseignants AFT — recherche par matière, niveau et standard.",
    "cd_t_052": "La section gratuite de Teachers Pay Teachers — des millions de fiches de travail, d'unités et d'imprimables créés par des enseignants, filtrés sur la piste sans frais.",
    "cd_t_053": "Ressources gratuites alignées sur le curriculum britannique issues de la plus grande communauté pédagogique mondiale — plans de cours complets et packs de séances.",
    "cd_t_054": "Extraits vidéo alignés sur le curriculum et cours prêts à l'emploi gratuits de la BBC — solides en histoire, sciences et littérature anglaise.",
    "cd_t_055": "Planificateur de cours numérique gratuit avec vue grille hebdomadaire, alignement sur les standards et vues par unité — niveau gratuit robuste pour les enseignants individuels.",
    "cd_t_056": "Planificateur de cours numérique léger — essai gratuit de 30 jours puis un niveau payant peu coûteux ; vue grille hebdomadaire appréciée des enseignants en classe.",
    "cd_t_057": "Bibliothèque gratuite de plans de cours de maîtres enseignants pour toutes les matières K-12 — vérifiés, testés en classe et alignés sur le Common Core.",
    "cd_t_058": "Bibliothèque de médias numériques K-12 gratuite de PBS — plus de 100 000 vidéos, cours et contenus interactifs alignés sur les standards dans toutes les matières.",
    "cd_t_059": "Manuels numériques personnalisables gratuits (FlexBooks) pour toutes les matières K-12 — adapter le contenu, ajouter des notes, partager avec les élèves.",
    "cd_t_060": "Leçons sur tableau blanc interactif et activités prêtes à l'emploi pour les enseignants du primaire — grande bibliothèque gratuite d'outils de cours en glisser-déposer.",
    "cd_t_061": "Création de cours interactifs combinant diapositives, quiz, vidéo et sondages — niveau gratuit avec des milliers de cours partagés par des enseignants.",
    "cd_t_062": "Canva Pro entièrement gratuit pour les enseignants K-12 vérifiés — fiches de travail, affiches, vidéos, diapositives, animations et infographies dans un seul studio.",
    "cd_t_063": "Adobe Express gratuit pour les enseignants et élèves K-12 — flyers, publications sur les réseaux sociaux, vidéos et génération d'images par IA pour tout cours.",
    "cd_t_064": "Des millions d'icônes gratuites pour fiches de travail et diapositives — attribution obligatoire, mais qualité et variété excellentes.",
    "cd_t_065": "Photos gratuites de haute qualité pour tout support pédagogique — aucune attribution requise, entièrement utilisables dans les ressources de cours.",
    "cd_t_066": "Photos, vidéos, illustrations et musique gratuites — entièrement utilisables dans les supports pédagogiques sans attribution requise.",
    "cd_t_067": "Photos et vidéos gratuites sélectionnées par une communauté de photographes — haute qualité, entièrement gratuites pour un usage éducatif.",
    "cd_t_068": "Générateur de nuages de mots gratuit — transformer des listes de vocabulaire en visuels attractifs pour les affichages, les amorces et les vérifications formatives rapides.",
    "cd_t_069": "Fiches de travail configurables gratuites en mathématiques et lecture — générer, imprimer, régénérer. Aucune connexion requise, un classique enseignant vieux de plusieurs décennies.",
    "cd_t_070": "Générer jusqu'à 7 styles de jeux différents à partir d'une seule liste de mots — gratuit pour les enseignants, parfait pour les activités de vocabulaire et de révision.",
    "cd_t_071": "Créateur de vidéos animées pour vidéos explicatives — le niveau gratuit prend en charge des vidéos de 5 minutes avec une bibliothèque de personnages étendue.",
    "cd_t_072": "Éditeur audio open source gratuit — enregistrer des podcasts, éditer de l'audio pour les cours, travailler avec tout format de fichier audio.",
    "cd_t_073": "Éditeur vidéo de bureau open source gratuit — suffisamment simple pour les projets d'élèves, puissant pour les tutoriels enseignants.",
    "cd_t_074": "Outil d'auteurie open source gratuit — plus de 50 types de contenus interactifs (quiz, scénarios à embranchements, glisser-les-mots) intégrables partout.",
    "cd_t_075": "Adaptation de n'importe quel texte à n'importe quel niveau de lecture instantanément — passages nivelés, vocabulaire et questions ; l'IA de différenciation de référence.",
    "cd_t_076": "Articles d'actualité nivelés gratuits — chaque article disponible en 5 niveaux de lecture pour un accès différencié au contenu dans toutes les matières.",
    "cd_t_077": "Bibliothèque de lecture K-12 complète et gratuite — des milliers de passages nivelés et de textes couplés avec des questions de compréhension.",
    "cd_t_078": "Coller n'importe quel texte difficile — Rewordify remplace les mots complexes par des termes plus simples en ligne, avec des définitions au survol.",
    "cd_t_079": "Imprimables gratuits alignés sur le curriculum pour différentes tranches d'âge et niveaux — adapter toute fiche de travail vers le haut ou le bas en quelques secondes.",
    "cd_t_080": "Outil gratuit de Microsoft — lire n'importe quel texte à voix haute avec mise au point sur les lignes, décomposition en syllabes, dictionnaire illustré et plus de 60 langues.",
    "cd_t_081": "Synthèse vocale gratuite avec des voix naturelles — lire des PDF, pages web et documents Word à voix haute pour favoriser l'accès à la lecture.",
    "cd_t_082": "Police de caractères open source gratuite et adaptée aux dyslexiques — conçue pour réduire la rotation des lettres, inclut des extensions de navigateur.",
    "cd_t_083": "Essai gratuit de 30 jours du principal outil de soutien à la littératie — synthèse vocale, saisie prédictive, dictionnaire illustré.",
    "cd_t_084": "Gratuit pour les élèves américains ayant des difficultés de lecture — plus de 1,4 M de livres audio et livres numériques accessibles avec synthèse vocale.",
    "cd_t_085": "Le cadre de référence de la conception universelle de l'apprentissage — lignes directrices gratuites, exemples et outils de mise en œuvre pour chaque classe.",
    "cd_t_086": "Ressources gratuites complètes pour les enseignants et les parents sur la dyslexie, le TDAH et les difficultés d'apprentissage — fondées sur la recherche et pratiques.",
    "cd_t_087": "Tâches, cours et outils de planification d'unités gratuits alignés sur le Common Core, issus de l'équipe qui a rédigé les standards — ELA et mathématiques.",
    "cd_t_088": "Le portail officiel des Common Core State Standards — standards complets en anglais et en mathématiques, gratuits et consultables.",
    "cd_t_089": "Portail gratuit des Next Generation Science Standards — attentes de performance, énoncés de preuves et cours exemplaires.",
    "cd_t_090": "Portail gratuit des standards ISTE — cadre pour un enseignement innovant avec la technologie, avec descripteurs et rubriques.",
    "cd_t_091": "Standards gratuits WIDA pour le développement de la langue anglaise — utilisés dans plus de 40 États américains pour la planification et l'évaluation des ELL/EAL.",
    "cd_t_092": "Modèles et articles Understanding by Design de Wiggins et McTighe — conception à rebours depuis les objectifs d'apprentissage vers les preuves puis l'enseignement.",
    "cd_t_093": "Roues de référence et de verbes gratuites pour la taxonomie révisée de Bloom — rédiger des objectifs d'ordre supérieur en quelques secondes avec des verbes d'action.",
    "cd_t_094": "Ressources gratuites de la taxonomie SOLO de Pam Hook — la Structure des Résultats d'Apprentissage Observés pour une progression claire des objectifs.",
    "cd_t_095": "Cadres de cours réutilisables gratuits liés à des objectifs d'apprentissage — Cyber Sandwich, Iron Chef, Worst Preso Ever et bien d'autres.",
    "cd_t_096": "Bibliothèque gratuite de ressources éducatives ouvertes — plus de 50 000 cours, unités et formations complètes étiquetés par standard.",
    "cd_t_097": "Le plus grand dépôt gratuit de REL — plus de 70 000 ressources étiquetées par Common Core, NGSS et standards d'État, avec avis de qualité.",
    "cd_t_098": "Base de données gratuite de John Hattie de 320+ influences sur la réussite des élèves, classées par taille d'effet — choisir les stratégies à fort impact.",
    "cd_t_099": "Cours interactifs en diapositives avec sondages, quiz, dessins et VR intégrés — le niveau Silver gratuit couvre la plupart des besoins de la classe.",
    "cd_t_100": "Intégrer des questions et des notes directement dans n'importe quelle vidéo — gratuit pour les enseignants (jusqu'à 20 vidéos stockées) avec analyse complète.",
    "cd_t_101": "Enregistrement d'écran illimité gratuit pour les enseignants vérifiés — enregistrer des vidéos de classe inversée avec engagement intégré des spectateurs.",
    "cd_t_102": "Outil de screencasting gratuit avec sous-titres adaptés à la classe et hébergement simple — utilisé par des millions d'éducateurs.",
    "cd_t_103": "Affichage de classe numérique gratuit tout-en-un — minuterie, sélecteur aléatoire de noms, feu de circulation, symboles de travail et sonomètre sur un seul écran.",
    "cd_t_104": "Outil de curation gratuit — organiser des vidéos, des articles, des tweets et des travaux d'élèves en collections partageables pour n'importe quel cours.",
    "cd_t_105": "Créer des présentations interactives, des escape rooms et des infographies — niveau gratuit avec des centaines de modèles pour les éducateurs.",
    "cd_t_106": "Ajouter des points chauds aux images et vidéos avec du texte, de l'audio et des liens — le niveau Basic gratuit couvre les petites classes.",
    "cd_t_107": "Cours vidéo K-12 gratuits avec pratique de la maîtrise — calcul, biologie, histoire, finance et préparation au SAT, tout gratuit pour toujours.",
    "cd_t_108": "Vidéos éducatives animées gratuites avec outils de cours intégrés — questions Think, Dig Deeper et Discuss associées à chaque clip.",
    "cd_t_109": "Série de conférences YouTube gratuite en histoire, sciences, littérature et économie — production exceptionnelle, animée par des experts.",
    "cd_t_110": "Vidéos animées alignées sur le curriculum avec quiz et cartes conceptuelles dans toutes les matières K-12 — essai gratuit et sujets gratuits.",
    "cd_t_111": "Logiciel de cours interactif gratuit pour tout écran tactile — diapositives, outils et modèles pour l'enseignement en classe entière, interface en anglais.",
    "cd_t_112": "Plus de 160 simulations interactives gratuites en physique, chimie, biologie et mathématiques de l'Université du Colorado — traduites en plus de 90 langues.",
    "cd_t_113": "Mathématiques dynamiques gratuites — géométrie, algèbre, calcul, 3D et statistiques dans un seul outil. Utilisé par plus de 100 M d'élèves dans le monde.",
    "cd_t_114": "Plateforme gratuite de conception 3D, simulation électronique et code par blocs d'Autodesk — conçue spécifiquement pour les classes.",
    "cd_t_115": "Plateforme de codage par blocs gratuite du MIT — plus de 100 M de projets dans le monde, la porte d'entrée à la programmation pour les enfants de 8 ans et plus.",
    "cd_t_116": "Expériences musicales ludiques gratuites de Google — Song Maker, Rhythm, Spectrogram, Kandinsky. Aucune connexion requise, fonctionne dans tout navigateur.",
    "cd_t_117": "Logiciel de notation musicale open source gratuit — écrire, jouer et imprimer des partitions pour tout instrument ou ensemble.",
    "cd_t_118": "DAW collaboratif en navigateur — enregistrer des podcasts et de la musique avec les élèves en temps réel. Niveau gratuit généreux.",
    "cd_t_119": "Logiciel gratuit open source de peinture numérique et d'animation professionnelle — moteur de pinceaux complet, utilisé dans les écoles d'art.",
    "cd_t_120": "Planétarium gratuit dans le navigateur — montrer le ciel nocturne aux élèves depuis n'importe où et n'importe quand, parfait pour les cours d'astronomie.",
    "cd_t_121": "Calculatrice graphique gratuite et activités de classe — la référence absolue pour visualiser les fonctions en cours de mathématiques.",
    "cd_t_122": "Curriculum gratuit d'informatique K-12 — Hour of Code, cours annuels complets, AI Lab et Dance Party. Utilisé par plus de 60 M d'élèves.",
    "cd_t_123": "Globe 3D gratuit dans le navigateur — visites Voyager de culture, d'histoire et de sciences ; créer ses propres repères géographiques pour tout cours de géographie.",
    "cd_t_124": "Plan Education gratuit avec tableaux et modèles illimités pour les enseignants vérifiés — l'outil de collaboration visuelle le plus apprécié.",
    "cd_t_125": "FigJam gratuit pour les éducateurs et les élèves — tableau blanc collaboratif avec des modèles délicieux et des fonctionnalités d'engagement.",
    "cd_t_126": "Mur de notes adhésives gratuites pour poster des idées, photos, liens et audio — trois padlets gratuits, adoré des enseignants.",
    "cd_t_127": "Tableau blanc virtuel gratuit open source au style dessiné à la main — collaboration instantanée, aucune connexion requise, chiffrement de bout en bout.",
    "cd_t_128": "Tableau de bord enseignant instantané gratuit — chaque élève dispose de son propre tableau blanc, que l'enseignant voit tous en temps réel.",
    "cd_t_129": "3 cartes mentales gratuites avec collaboration — idéal pour la cartographie conceptuelle en classe et les projets de groupe.",
    "cd_t_130": "Cartes mentales publiques illimitées gratuites — hiérarchie visuelle claire, collaboration en temps réel et intégration d'images.",
    "cd_t_131": "Niveau éducation gratuit du tableau blanc de Lucid — notes adhésives, votes et canvas infini pour le brainstorming en classe.",
    "cd_t_132": "Gratuit pour les étudiants et instructeurs du supérieur vérifiés — espace de travail visuel collaboratif pour la pensée design et le travail en groupe.",
    "cd_t_133": "Diagrammes gratuits open source — organigrammes, diagrammes ER, UML, cartes mentales. Sauvegarde directement dans Drive ou OneDrive.",
    "cd_t_134": "Tableau blanc interactif gratuit open source pour les écoles — fonctionne avec tout projecteur ou écran interactif, sans abonnement.",
    "cd_t_135": "Tableau blanc collaboratif gratuit dans Teams et Office — notes adhésives, encre, images et modèles avec sauvegarde automatique.",
    "cd_t_136": "Cartographie mentale visuelle simple pour les classes — les élèves font du brainstorming, organisent leurs idées et partagent des tableaux en temps réel.",
    "cd_t_137": "Le format de quiz télévisé classique — le niveau Basic gratuit prend en charge jusqu'à 40 joueurs pour une évaluation formative en direct.",
    "cd_t_138": "Quiz et cours alimentés par l'IA en mode auto-rythmé — gratuit pour les enseignants avec de nombreuses banques de questions et un mode en direct.",
    "cd_t_139": "Sondages en direct, nuages de mots et questions-réponses du public — le niveau gratuit couvre parfaitement l'évaluation formative en petite classe.",
    "cd_t_140": "Ajouter des questions interactives à Google Slides ou PowerPoint — le niveau gratuit prend en charge les formats d'évaluation formative les plus appréciés.",
    "cd_t_141": "Sondages en direct, enquêtes et Q&A en superposition pour toute réunion ou classe — le niveau gratuit prend en charge jusqu'à 100 participants.",
    "cd_t_142": "Quiz rapides, tickets de sortie et jeu Space Race — gratuit pour jusqu'à 50 élèves par salle.",
    "cd_t_143": "Cartes QR papier plus scan par téléphone — évaluation formative sans aucun appareil élève, gratuit pour jusqu'à 60 cartes.",
    "cd_t_144": "Jeux de quiz modélisés — correspondance, anagramme, jeu télévisé — générer toute activité à partir d'une seule liste de mots ; gratuit jusqu'à 5 sauvegardés.",
    "cd_t_145": "Voir les réponses des élèves en direct pendant qu'ils tapent — dessins, équations, paragraphes. Le niveau Bronze gratuit couvre l'usage formatif essentiel.",
    "cd_t_146": "Outil de rétroaction instantanée gratuit par nuage de mots — poser une question, les élèves répondent en 20 caractères maximum, regarder les réponses se construire en direct.",
    "cd_t_147": "Sondages de réponse d'audience en direct intégrés dans PowerPoint ou Google Slides — le niveau gratuit prend en charge jusqu'à 25 réponses par sondage.",
    "cd_t_148": "Plateforme de quiz ludique très populaire auprès des adolescents — organiser des jeux en direct ou attribuer des séries en mode auto-rythmé. Le niveau gratuit couvre toute la classe.",
    "cd_t_149": "Plus de 40 modèles de widgets interactifs prêts à l'emploi — quiz, mots croisés, tickets de sortie, roues aléatoires — auto-notés et intégrables.",
    "cd_t_150": "Le LMS gratuit par défaut pour des millions d'enseignants — devoirs, notation, communication et partage de fichiers en un seul endroit.",
    "cd_t_151": "Plan éducation gratuit avec classes, devoirs, cahiers de cours OneNote et 1 To de stockage OneDrive par élève.",
    "cd_t_152": "Version gratuite du principal LMS de l'enseignement supérieur — devoirs complets, notation et rubriques pour les enseignants individuels.",
    "cd_t_153": "LMS gratuit open source utilisé par les universités du monde entier — auto-hébergement ou niveau gratuit MoodleCloud pour les petites classes.",
    "cd_t_154": "LMS gratuit pour les enseignants individuels — devoirs, carnet de notes, quiz et communication avec les parents sur une seule plateforme.",
    "cd_t_155": "Carnet de notes basé sur les standards approuvé par plus de 5 M d'élèves — gratuit pour les enseignants individuels ; plans payants pour les écoles et les districts.",
    "cd_t_156": "Carnet de notes et outil de reporting en ligne — le niveau gratuit couvre les besoins de la classe ; s'intègre aux principaux systèmes LMS.",
    "cd_t_157": "Quiz auto-notés gratuits avec rétroaction instantanée et analyse — le cheval de bataille de la notation dans Google Classroom.",
    "cd_t_158": "Quiz et enquêtes gratuits avec auto-notation et logique de branchement — inclus avec tout compte Microsoft.",
    "cd_t_159": "Créateur de rubriques gratuit — choisir un modèle, personnaliser les critères, imprimer ou sauvegarder. Utilisé par les enseignants depuis plus de 20 ans.",
    "cd_t_160": "Constructeur de rubriques gratuit et galerie avec des milliers de modèles partagés par des enseignants — adapter et réutiliser avec attribution.",
    "cd_t_161": "Système d'information scolaire K-12 avec carnet de notes et reporting basé sur les standards — essai gratuit ; de nombreux districts offrent l'accès.",
    "cd_t_162": "Niveau gratuit Grammarly — suggestions de grammaire, de clarté et de ton pour les rédactions d'élèves dans le navigateur, Word et Docs.",
    "cd_t_163": "Application web gratuite qui surligne les phrases complexes, la voix passive et les adverbes — des rédactions d'élèves plus claires en quelques secondes.",
    "cd_t_164": "Annotation gratuite de PDF et de documents — déposer des commentaires, des notes vocales, des dessins et des stickers directement sur les travaux des élèves en quelques secondes.",
    "cd_t_165": "Module complémentaire gratuit Google Sheets pour l'évaluation par rubriques auto-, pair- et enseignant — génère une rétroaction personnalisée par élève.",
    "cd_t_166": "Extension Chrome gratuite ajoutant une barre latérale IA à Google Docs et Slides — rétroaction instantanée, nivellement et rubriques.",
    "cd_t_167": "Extension Chrome gratuite de commentaires vocaux pour Google Docs, Slides et Classroom — laisser des commentaires audio de 30 secondes en quelques secondes.",
    "cd_t_168": "Outil gratuit de rétroaction vocale pour les rédactions d'élèves — lier des étiquettes de rubriques à des commentaires et réutiliser la rétroaction courante entre les élèves.",
    "cd_t_169": "Rétroaction ultra-rapide pour les mathématiques et les sciences — les élèves téléchargent leurs travaux, les enseignants commentent avec une banque de rétroaction réutilisable.",
    "cd_t_170": "Module complémentaire gratuit Google Docs pour la rétroaction en masse sur les rédactions — insérer des commentaires standards depuis une bibliothèque de rétroaction enseignant.",
    "cd_t_171": "Pratique adaptative de la grammaire et de la rédaction — gratuit pour les enseignants avec une rétroaction auto-notée sur chaque réponse d'élève.",
    "cd_t_172": "Outils interactifs gratuits d'écriture et de grammaire — pratique adaptative au niveau de la phrase pour les classes 3-12 avec rétroaction instantanée.",
    "cd_t_173": "Éditeur de style gratuit avec plus de 25 rapports d'écriture — grammaire, lisibilité, transitions et mots suremployés pour les rédactions d'élèves.",
    "cd_t_174": "Plateforme gratuite Microsoft de discussion vidéo — les élèves publient de courtes réflexions vidéo ; les enseignants créent des sujets sécurisés en quelques secondes.",
    "cd_t_175": "Portfolios numériques créés par les élèves avec visibilité parentale — le niveau Seesaw for Schools gratuit couvre les classes individuelles.",
    "cd_t_176": "Les élèves conçoivent des livres numériques pour la réflexion ou les projets — gratuit pour une bibliothèque de 40 livres par enseignant.",
    "cd_t_177": "Outil gratuit Microsoft — chaque élève dispose d'un cahier privé pour les journaux et les réflexions, plus une bibliothèque de contenu partagé et un espace de collaboration.",
    "cd_t_178": "Outil gratuit de bilan émotionnel dans Teams for Education — les élèves choisissent leur ressenti ; les enseignants voient les tendances de bien-être de la classe.",
    "cd_t_179": "Plateforme de création gratuite pour les histoires d'élèves et les réflexions numériques — combiner texte, voix, vidéo et animation sur un seul canvas.",
    "cd_t_180": "Plan Plus gratuit pour les éducateurs vérifiés — journaux de réflexion, carnets d'apprentissage et portfolios de projets dans un seul espace de travail.",
    "cd_t_181": "Blogs de classe et d'élèves gratuits sous WordPress — idéal pour les journaux de réflexion, avec modération enseignant intégrée.",
    "cd_t_182": "Chronologies interactives gratuites et histoires pour les réflexions construites par les élèves et les récits de projets — collaboratifs et imprimables.",
    "cd_t_183": "Canal de communication anonyme gratuit pour les discussions en classe — recueillir des réflexions rapides en texte et image depuis n'importe quel appareil.",
    "cd_t_184": "Histoires géographiques gratuites d'ArcGIS — les élèves réfléchissent sur un sujet en combinant texte, photos, vidéo et données géographiques.",
    "cd_t_185": "Outil gratuit de réflexion par questions-réponses vidéo — poser une question, les élèves enregistrent de courtes réponses, la classe examine ensemble.",
    "cd_t_186": "Tableaux de bord parentaux gratuits dans toutes les matières K-12 — suivre les progrès, voir les points forts et faibles, partager avec les enseignants.",
    "cd_t_187": "Révision gratuite alignée sur le curriculum britannique par année scolaire — guides pour les parents sur le soutien aux devoirs et la préparation aux examens.",
    "cd_t_188": "10 questions gratuites par jour dans plus de 8 500 compétences — pratique complète K-12 avec des rapports de progrès adaptés aux parents.",
    "cd_t_189": "Avis gratuits sur toutes les applications, jeux et films pour enfants — aider les familles à faire des choix médiatiques éclairés, soutenus par la recherche.",
    "cd_t_190": "Essai gratuit de 30 jours du curriculum d'apprentissage précoce complet — phonétique, mathématiques, art et musique pour les 2-8 ans.",
    "cd_t_191": "Essai gratuit du principal programme de lecture précoce — phonétique, mots courants et livres décodables pour les 3-13 ans.",
    "cd_t_192": "Pratique adaptative des mathématiques K-12 avec tournois mondiaux — essais gratuits à domicile et suivi des progrès par les parents.",
    "cd_t_193": "Mathématiques gratuites et ludiques pour les classes 1-8 — les enfants combattent des monstres en répondant à des questions, les parents voient des rapports hebdomadaires.",
    "cd_t_194": "Plateforme gratuite de révision GCSE/A-level pour les familles britanniques — cours interactifs basés sur la recherche en sciences cognitives.",
    "cd_t_195": "Flashcards gratuites et modes d'étude — plus d'un demi-milliard de séries couvrant toutes les matières et tous les programmes d'examen.",
    "cd_t_196": "Imprimables, fiches de travail et packs d'activités gratuits alignés sur le curriculum — basés au Royaume-Uni mais utilisés dans plus de 200 pays.",
    "cd_t_197": "Plus de 40 000 livres numériques, livres audio et vidéos pour enfants — gratuit pour les éducateurs vérifiés, peu coûteux pour les familles.",
    "cd_t_198": "Instaurer une culture de classe positive — points, messages aux parents et portfolios d'élèves. Gratuit pour tous les enseignants et parents.",
    "cd_t_199": "Plateforme de gestion de classe gamifiée — les élèves gagnent des XP et des pouvoirs pour leur bonne conduite. Niveau gratuit généreux.",
    "cd_t_200": "Sonomètre visuel de classe animé selon les niveaux sonores — la version Lite gratuite est appréciée des enseignants du primaire.",
    "cd_t_201": "Sonomètre visuel amusant et gratuit — des balles rebondissantes réagissent au volume de la classe. Outil de fond parfait pendant les travaux en groupe.",
    "cd_t_202": "Sélecteur aléatoire de noms gratuit — faire tourner la roue pour choisir les élèves équitablement. Listes sauvegardées, couleurs personnalisées et sans publicité.",
    "cd_t_203": "Minuteries de classe amusantes gratuites — bombes, bougies, voitures de course — maintenir les activités dans les temps avec des visuels attractifs.",
    "cd_t_204": "Générateur gratuit de plans de classe avec suivi des points de comportement — utilisé dans des milliers d'écoles britanniques, gratuit pour les enseignants individuels.",
    "cd_t_205": "Plateforme de renforcement positif du comportement à l'échelle scolaire — essai gratuit ; de nombreuses ressources PBIS gratuites disponibles sur le site.",
    "cd_t_206": "Vidéos gratuites de mouvement et de pleine conscience — courtes pauses cérébrales prouvées pour recentrer les élèves de la maternelle au CM2 en milieu de cours.",
    "cd_t_207": "Idées gratuites de salutations, d'activités et de messages pour les réunions matinales — communauté de classe socio-émotionnelle basée sur la recherche.",
    "cd_t_208": "Ressources SEL gratuites et webinaires hebdomadaires de l'organisation de référence en matière de recherche sur l'apprentissage socio-émotionnel.",
    "cd_t_209": "Le blog d'enseignement le plus suivi au Royaume-Uni — stratégies pratiques gratuites sur le comportement, l'engagement et les routines.",
    "cd_t_210": "Sélecteur aléatoire gratuit d'élèves — sélection animée et équitable qui maintient l'interrogation à froid imprévisible et engageante pour toute la classe.",
    "cd_t_211": "Envoi de messages sécurisés à sens unique aux élèves et aux parents — le niveau gratuit couvre les annonces de classe quotidiennes avec traduction automatique.",
    "cd_t_212": "Messagerie gratuite d'engagement familial qui traduit automatiquement entre enseignants et parents dans plus de 100 langues.",
    "cd_t_213": "Messagerie parentale sécurisée gratuite avec partage de photos et vidéos — traduit automatiquement les messages dans plus de 35 langues.",
    "cd_t_214": "Communication gratuite avec les parents et planification des conférences — favori de la petite enfance et du primaire avec partage de photos.",
    "cd_t_215": "Newsletters de classe en glisser-déposer et visuellement attrayantes — le niveau gratuit prend en charge 5 newsletters avec des outils de design complets.",
    "cd_t_216": "Plateforme de communication scolaire avec traduction automatique — de nombreux districts offrent des comptes enseignants gratuits via les plans scolaires.",
    "cd_t_217": "Traduction instantanée gratuite dans plus de 130 langues — texte, photos, conversations et documents pour la communication avec les parents.",
    "cd_t_218": "Traductions de meilleure qualité que Google pour les langues européennes — le niveau gratuit couvre la plupart des besoins de communication des enseignants.",
    "cd_t_219": "Traduction gratuite de conversation en temps réel pour les réunions parents — les téléphones parlent chaque langue et l'application sous-titre en direct.",
    "cd_t_220": "Planification gratuite des conférences, inscriptions aux fêtes de classe et listes de bénévoles — le cheval de bataille de la coordination parentale.",
    "cd_t_221": "Niveau email gratuit (jusqu'à 500 contacts) — idéal pour les newsletters de classe, les mises à jour parentales et la communication APE.",
    "cd_t_222": "Outil Microsoft gratuit pour des newsletters et rapports interactifs — modèles magnifiques, mise en page automatique, aucune mise en forme manuelle requise.",
    "cd_t_223": "Stockage cloud gratuit de 15 Go avec Docs, Sheets et Slides — partager les ressources de cours et collecter les devoirs en toute simplicité.",
    "cd_t_224": "Stockage cloud gratuit de 5 Go avec Office en ligne — Word, Excel, PowerPoint avec des contrôles de partage complets adaptés à la classe.",
    "cd_t_225": "Niveau gratuit de 2 Go avec partage en classe et dossiers collaboratifs — plans éducatifs à tarif réduit disponibles.",
    "cd_t_226": "Niveau de stockage gratuit de 10 Go — solide en matière de permissions et de pistes d'audit, populaire auprès des administrateurs de district et de l'enseignement supérieur.",
    "cd_t_227": "Plan Plus gratuit pour les éducateurs vérifiés — wikis, notes de cours, suivis d'élèves et hubs de classe collaboratifs dans un seul espace.",
    "cd_t_228": "Base de données flexible gratuite — idéale pour le suivi des données d'élèves, des objectifs IEP, des portfolios de projets et des cartographies de curriculum.",
    "cd_t_229": "Tableaux kanban gratuits — suivre la planification des cours, les projets d'élèves, les comités scolaires et les tâches personnelles des enseignants.",
    "cd_t_230": "Gratuit pour les équipes jusqu'à 15 personnes — gérer les projets d'amélioration scolaire, les flux de travail des départements et les tâches administratives.",
    "cd_t_231": "Outil de réservation gratuit — partager un lien, les parents choisissent un créneau pour les conférences parents-enseignants. Plus de va-et-vient par email.",
    "cd_t_232": "Sondage gratuit de disponibilité pour le personnel et les parents — trouver quand tout le monde peut se réunir sans fils d'emails interminables.",
    "cd_t_233": "Espace de travail gratuit pour les équipes du personnel — canaux par département, messageries directes et intégrations avec Drive, Calendar et plus.",
    "cd_t_234": "Stockage cloud Apple gratuit de 5 Go avec Pages, Numbers et Keynote dans le navigateur — idéal pour les classes utilisant Apple.",
    "cd_t_235": "Initiative gratuite de l'application Calm pour les enseignants K-12 — accès complet à l'application incluant les histoires pour s'endormir, les méditations et la musique.",
    "cd_t_236": "Headspace Plus gratuit pour les enseignants K-12 vérifiés aux États-Unis, au Royaume-Uni, au Canada et en Australie — pleine conscience et méditation.",
    "cd_t_237": "Application de méditation gratuite avec la plus grande bibliothèque gratuite — plus de 200 000 méditations guidées et pistes spécifiques aux enseignants.",
    "cd_t_238": "Articles gratuits, pratiques guidées et recherches sur la pleine conscience — introduction accessible pour les enseignants stressés.",
    "cd_t_239": "Ressources SEL gratuites fondées sur la science de Berkeley pour les enseignants — pratiques de gratitude, de bienveillance et de résilience dans les classes.",
    "cd_t_240": "Podcast et articles gratuits de Daniela Falecki — stratégies pratiques de bien-être et prévention du burnout pour les enseignants.",
    "cd_t_241": "Organisme de bienfaisance britannique — ligne d'assistance gratuite 24h/24, conseil et ressources en santé mentale pour tout enseignant, quel que soit le pays.",
    "cd_t_242": "Mouvement mondial gratuit de réunions de soutien à la santé mentale des enseignants — plus de 100 sections dans le monde, en ligne et en personne.",
    "cd_t_243": "Articles gratuits et épisodes de podcast de Jennifer Gonzalez sur l'autosoin des enseignants — pratiques, honnêtes, sans positivité toxique.",
    "cd_t_244": "Blog gratuit avec des stratégies réalistes pour gérer le stress, les parents et l'administration — rédigé par des enseignants en classe.",
    "cd_t_245": "Boîtes à outils gratuites de MHA — auto-dépistage du burnout, stratégies d'adaptation fondées sur des données probantes et répertoires de soutien en cas de crise.",
    "cd_t_246": "Programme gratuit interactif de thérapie cognitivo-comportementale — auto-assistance éprouvée pour le stress et le moral bas, utilisée dans le monde entier.",
    "cd_t_247": "Plus de 60 outils IA conçus par des enseignants — plans de cours, objectifs IEP, rubriques, différenciation et rétroaction. Niveau gratuit généreux pour les éducateurs.",
    "cd_t_248": "Cours interactifs générés par IA en 30 secondes — diapositives, sondages, dessins et tickets de sortie, avec un solide plan gratuit pour les enseignants.",
    "cd_t_249": "Plus de 100 générateurs de plans de cours, d'évaluations et d'aménagements — le niveau gratuit couvre la plupart des besoins quotidiens en classe.",
    "cd_t_250": "Espaces de chat IA sécurisés et surveillés pour les élèves, plus un assistant IA pour les enseignants — niveau gratuit généreux pour le K-12.",
    "cd_t_251": "L'assistant IA phare d'Anthropic — exceptionnel pour la planification de cours, la rédaction de rubriques, les emails aux parents et la rétroaction.",
    "cd_t_252": "Le niveau gratuit d'OpenAI couvre GPT-4o mini — solide pour la génération de questions, les résumés et la création de fiches de travail.",
    "cd_t_253": "L'IA de Google profondément intégrée à Docs, Slides et Drive — idéale pour les enseignants déjà dans l'écosystème Google Workspace.",
    "cd_t_254": "IA gratuite dans Word, OneNote, PowerPoint — générer des plans de cours, des présentations et des documents d'élèves directement en place.",
    "cd_t_255": "Télécharger les chapitres de manuel et les notes — l'IA de Google répond strictement à partir de vos sources, avec des résumés audio pour la révision.",
    "cd_t_256": "Cours gratuit d'Anthropic sur les quatre compétences IA essentielles — délégation, description, discernement, diligence. Conçu pour les éducateurs.",
    "cd_t_257": "Le tuteur IA gratuit de Khan Academy pour les enseignants — planification de cours, emails aux parents et tutorat socratique des élèves dans toutes les matières K-12.",
    "cd_t_258": "Moteur de recherche IA qui cite chaque affirmation — parfait lorsque les enseignants ont besoin de sources vérifiables plutôt que de réponses hallucinées.",
    "cd_t_259": "Coller n'importe quel texte, obtenir des questions essentielles et des objectifs d'apprentissage alignés, plus des quiz auto-générés — niveau gratuit illimité.",
    "cd_t_260": "Guide gratuit du Teacher Development Trust — recherche sur ce qui améliore réellement l'enseignement et les résultats des élèves dans le développement professionnel.",
    "cd_t_261": "Les standards mondiaux pour un apprentissage professionnel efficace — un cadre clair pour évaluer et planifier son propre développement professionnel continu.",
    "cd_t_262": "Articles, vidéos et guides de développement professionnel gratuits et sélectionnés sur tous les aspects de l'enseignement — le meilleur point de départ tout-en-un.",
    "cd_t_263": "Parcours structurés gratuits vers la pédagogie moderne — quoi lire, regarder et essayer au fil du développement de sa pratique enseignante.",
    "cd_t_264": "La boîte à outils gratuite de l'Education Endowment Foundation pour les enseignants — stratégies évaluées par les preuves avec des conseils clairs sur les priorités.",
    "cd_t_265": "Les guides gratuits du New Teacher Project sur l'apparence d'un enseignement efficace et la manière d'y parvenir étape par étape.",
    "cd_t_266": "Enquête enseignante hebdomadaire de 3 questions + ressources de développement professionnel — voir comment des milliers de collègues pensent et comparer sa propre pratique.",
    "cd_t_267": "Commencer par soi-même — le MOOC gratuit de Barbara Oakley sur la mémoire, le chunking et la concentration. Essentiel avant de concevoir l'apprentissage pour les autres.",
    "cd_t_268": "Introduction gratuite au Cycle Réflexif de Gibbs et à d'autres modèles — transformer ses expériences d'enseignement en croissance structurée.",
    "cd_t_269": "Le portail de développement professionnel gratuit de la National Education Association — cours, webinaires et ressources cartographiés à chaque étape de carrière.",
    "cd_t_270": "Adhésion associée gratuite — accéder à la revue Impact, aux digests de recherche et à la communauté pédagogique pour les enseignants guidés par les preuves.",
    "cd_t_271": "Cours d'introduction gratuits de l'Open University en éducation — enseignement inclusif, mentorat et leadership scolaire. Aucun prérequis.",
    "cd_t_272": "Auditer gratuitement les cours d'enseignement de Stanford, Penn et Johns Hopkins — certificats payants disponibles, mais tout le contenu est gratuit.",
    "cd_t_273": "Cours d'éducation de Harvard, MIT et HarvardX — audit gratuit, avec MicroMasters payants optionnels pour le leadership scolaire.",
    "cd_t_274": "Courts cours d'enseignement gratuits d'universités britanniques — pédagogie pratique, EdTech et CPD spécifique aux matières.",
    "cd_t_275": "Formation gratuite menant aux examens Google Certified Educator niveau 1 et 2 — accréditation technologique de classe reconnue mondialement.",
    "cd_t_276": "Badges gratuits Microsoft Innovative Educator — Teams, OneNote, Minecraft Edu, outils IA et collaboration mondiale.",
    "cd_t_277": "Programme gratuit de reconnaissance Apple Teacher en mode auto-rythmé — obtenir des badges Swift et des accréditations en créativité pédagogique.",
    "cd_t_278": "Certificats d'enseignement et d'éducation gratuits et accrédités — gestion de classe, besoins spéciaux, petite enfance et plus.",
    "cd_t_279": "Cours gratuits de l'Open University avec attestations de participation — enseignement inclusif, mentorat, leadership scolaire et compétences numériques.",
    "cd_t_280": "Matériaux de cours complets du MIT disponibles gratuitement — vidéos de cours, exercices et notes d'enseignement des vraies classes MIT.",
    "cd_t_281": "Cours gratuits accrédités de niveau universitaire — compléter des cours complets et recevoir des relevés de notes sans frais.",
    "cd_t_282": "Certification gratuite Common Sense Educator en citoyenneté numérique — pratique et reconnue internationalement.",
    "cd_t_283": "Webinaires ISTE gratuits, articles et développement professionnel de la principale organisation EdTech mondiale — adhésion communautaire incluse.",
    "cd_t_284": "La ressource de référence sur l'apprentissage par projet — kits de démarrage gratuits, rubriques et bibliothèques de projets de l'autorité mondiale en PBL.",
    "cd_t_285": "Ressources gratuites sur la conception de la classe inversée — comment enregistrer, inverser et mieux utiliser le temps en classe pour l'apprentissage actif.",
    "cd_t_286": "Guide gratuit de la NSTA sur les sciences par investigation — comment passer de la démonstration à l'investigation menée par les élèves.",
    "cd_t_287": "Articles d'introduction gratuits sur les structures Kagan — Think-Pair-Share, Jigsaw et plus de 200 techniques d'apprentissage coopératif.",
    "cd_t_288": "Lignes directrices gratuites sur la conception universelle de l'apprentissage — comment concevoir chaque cours pour toute la diversité des apprenants.",
    "cd_t_289": "La boîte à outils gratuite d'IDEO pour les éducateurs — appliquer la pensée design centrée sur l'humain aux défis de classe et à la création de cours.",
    "cd_t_290": "Plus de 30 routines de pensée de Harvard PZ — protocoles structurés qui approfondissent la réflexion des élèves dans toutes les matières.",
    "cd_t_291": "Ressources gratuites de l'ASCD sur la différenciation pédagogique — comment moduler les tâches, la flexibilité des groupes et adapter le rythme à chaque apprenant.",
    "cd_t_292": "Ressources pédagogiques gratuites d'Expeditionary Learning — caractère, habitudes de travail et évaluation basée sur la maîtrise en action.",
    "cd_t_293": "Plus de 250 tailles d'effet — découvrir quelles méthodes d'enseignement ont le plus fort impact sur la réussite des élèves et pourquoi.",
    "cd_t_294": "Vidéothèque gratuite de techniques de classe — cold call, no opt out, vérification de la compréhension et plus de 60 stratégies supplémentaires.",
    "cd_t_295": "Articles pratiques sur chaque grande approche pédagogique — avec exemples vidéo en classe et conseils de mise en œuvre.",
    "cd_t_296": "Tâches gratuites d'enrichissement mathématique de Cambridge — des problèmes riches qui développent le raisonnement, pas seulement le calcul. Recherche par âge et sujet.",
    "cd_t_297": "Ressources gratuites pour l'enseignement de la littératie — stratégies de lecture, conseils phonétiques, outils de fluidité et ressources d'engagement familial.",
    "cd_t_298": "Simulations interactives gratuites de sciences et mathématiques de l'Université du Colorado — guides pédagogiques inclus pour chaque simulation.",
    "cd_t_299": "Ressources gratuites de mise en œuvre des Next Generation Science Standards — unités narratives, phénomènes et guides d'enseignement tridimensionnel.",
    "cd_t_300": "Cours gratuits de géographie, sciences et histoire de National Geographic — cartes, vidéos, articles et guides pédagogiques.",
    "cd_t_301": "Plateforme ELA gratuite pour les enseignants — textes alignés sur les standards, questions de discussion et évaluations pour les classes 3-12.",
    "cd_t_302": "Des milliers de ressources gratuites pour l'enseignement de l'anglais — poésie, théâtre, écriture créative et préparation aux examens pour les professeurs d'anglais du secondaire.",
    "cd_t_303": "Ressources gratuites pour l'enseignement de l'histoire issues du principal magazine d'histoire britannique — articles, documents sources et idées de cours.",
    "cd_t_304": "Ressources gratuites pour l'enseignement de la chimie de la Royal Society of Chemistry — plans de cours, développement professionnel et guides pratiques.",
    "cd_t_305": "Puzzles mathématiques gratuits et problèmes non résolus pour le K-12 — conçus pour créer une belle lutte intellectuelle et une réflexion profonde.",
    "cd_t_306": "Leçons animées TED-Ed sélectionnées dans toutes les matières — outils gratuits de planification de cours, guides de discussion et quiz.",
    "cd_t_307": "Photos d'inspiration à l'écriture et stimuli gratuits — utiliser de véritables productions d'élèves publiées comme modèles pour élever les standards rédactionnels.",
    "cd_t_308": "Ressources gratuites de Jim Knight sur le cycle d'impact — un cadre fondé sur la recherche pour le coaching des enseignants et l'amélioration personnelle.",
    "cd_t_309": "Ressources gratuites de mentorat du NTC — comment structurer les conversations de mentorat, observer efficacement et donner une rétroaction utile.",
    "cd_t_310": "Ressources gratuites de l'ASCD sur le leadership enseignant — comment diriger depuis la classe sans titre officiel.",
    "cd_t_311": "Articles et vidéos gratuits sur le coaching pédagogique — observation entre pairs, cycles de rétroaction et développement d'une culture du coaching.",
    "cd_t_312": "Ressources gratuites sur la construction d'une communauté d'apprentissage professionnel — comment les enseignants leaders stimulent l'amélioration à l'échelle de l'école.",
    "cd_t_313": "National Board for Professional Teaching Standards — ressources gratuites de préparation à l'accréditation de référence pour les enseignants.",
    "cd_t_314": "Standards gratuits pour l'apprentissage professionnel — comment concevoir et animer un développement professionnel qui améliore réellement l'enseignement et les résultats.",
    "cd_t_315": "Ressources gratuites Teach Like a Champion pour les responsables pédagogiques — cadres d'observation, outils de rétroaction et vidéos de coaching.",
    "cd_t_316": "Ressources gratuites pour les éducateurs prenant des responsabilités — cartographie du curriculum, planification collaborative et développement communautaire.",
    "cd_t_317": "Guides gratuits pour les responsables intermédiaires — gérer vers le haut, diriger une équipe, gestion de la charge de travail et mener des conversations difficiles.",
    "cd_t_318": "Ressources gratuites de leadership d'Education Week — recherche, études de cas et analyse politique pour les enseignants leaders et les directeurs.",
    "cd_t_319": "Cadre gratuit des standards ISTE pour les leaders EdTech — une feuille de route pour diriger l'apprentissage numérique dans toute école ou district.",
    "cd_t_320": "La référence absolue — évaluations gratuites de plus de 50 stratégies d'enseignement, avec taille d'effet, coût et conseils de mise en œuvre.",
    "cd_t_321": "Les 250+ tailles d'effet de Hattie sur la réussite des élèves — comprendre quelles stratégies fonctionnent et lesquelles sont des mythes éducatifs.",
    "cd_t_322": "Conférences gratuites, billets de blog et une communauté mondiale dédiée à l'amélioration de la culture de la recherche en éducation.",
    "cd_t_323": "Avis gratuits du Département américain de l'éducation sur les interventions éducatives — évaluations rigoureuses et impartiales des preuves pour les programmes et pratiques.",
    "cd_t_324": "Résumés gratuits de stratégies d'étude fondées sur des données probantes — pratique espacée, récupération, entrelacement et plus, expliqués pour les enseignants.",
    "cd_t_325": "Articles gratuits d'un scientifique cognitif sur les raisons pour lesquelles les élèves pensent et apprennent comme ils le font — directement applicables à la conception des cours.",
    "cd_t_326": "Rapports et résumés de recherche gratuits du NFER — recherche éducative britannique indépendante et rigoureuse sur l'enseignement, le bien-être et le leadership.",
    "cd_t_327": "Recherche éducative gratuite de la Brookings Institution — analyse politique fondée sur des preuves et digests de recherche accessibles aux enseignants.",
    "cd_t_328": "Recherche RAND gratuite sur l'efficacité des enseignants, le curriculum et les systèmes éducatifs — rigoureuse, évaluée par des pairs et libre d'accès.",
    "cd_t_329": "Recherche traduite en pratique de classe — chaque article indique clairement la base de preuves et les étapes de mise en œuvre.",
    "cd_t_330": "Ressources gratuites de Marzano sur les stratégies pédagogiques — neuf stratégies à fort rendement ancrées dans 35 ans de recherche en classe.",
    "cd_t_331": "Hub gratuit de recherche en éducation du gouvernement américain — base de données ERIC, guides de pratique et What Works Clearinghouse en un seul endroit.",
    "cd_t_332": "Enquête quotidienne de 3 questions pour les enseignants + contenu de développement professionnel hebdomadaire — voir comment répondent plus de 10 000 collègues et comparer ses propres points de vue.",
    "cd_t_333": "Forums gratuits pour toutes les matières et tous les groupes d'âge — partage de ressources, fils de conseils et discussions de carrière issus d'une communauté mondiale d'enseignants.",
    "cd_t_334": "Le plus grand PLN informel mondial des enseignants — #EduTwitter, #EduChat et des centaines de hashtags par matière connectent les éducateurs à l'échelle mondiale.",
    "cd_t_335": "Discussion enseignante anonyme et honnête — véritable échange sur la charge de travail, le comportement, l'administration et ce qui fonctionne vraiment en classe.",
    "cd_t_336": "Communauté mondiale gratuite d'enseignants guidés par les preuves — conférences annuelles, événements régionaux et discussions en ligne.",
    "cd_t_337": "Unconférences informelles gratuites d'enseignants — présentations enseignant-à-enseignant de 7 et 2 minutes, organisées localement et en ligne dans le monde entier.",
    "cd_t_338": "Google Educator Groups locaux et en ligne dans plus de 100 pays — apprentissage professionnel, événements et soutien entre pairs pour les enseignants utilisant Google.",
    "cd_t_339": "Communauté gratuite d'éducateurs Microsoft — partager des cours, gagner des badges et se connecter avec des innovateurs utilisant les outils Microsoft en éducation.",
    "cd_t_340": "Communauté de blogging et de discussion gratuite d'Edutopia — partager son expérience d'enseignement et lire ce qui fonctionne dans les classes du monde entier.",
    "cd_t_341": "Réseau gratuit des membres de la National Education Association — connexions professionnelles, outils de défense et soutien entre pairs pour les enseignants américains.",
    "cd_t_342": "Groupes gratuits d'éducateurs LinkedIn — réseautage professionnel, développement de carrière et leadership d'opinion en éducation.",
    "cd_t_343": "Le réseau des éducateurs de l'ISTE — espaces communautaires gratuits, groupes d'intérêt spécial et discussions sur l'EdTech et l'apprentissage innovant.",
}
