#!/usr/bin/env python3
"""French structural translations for i18n.js (all non-card keys)."""

FR_STRUCTURAL = {
    # Navbar
    "nav.about": "À propos",
    "nav.work": "Notre Action",
    "nav.resources": "Ressources",
    "nav.res.students": "Élèves K–12",
    "nav.res.teachers": "Enseignants",
    "nav.res.uni": "Université",
    "nav.support": "Soutenir",
    "nav.contact": "Contact",
    "nav.lab": "Notre Lab",
    # Hero
    "hero.badge": "Éducation Gratuite pour Chaque Apprenant",
    "hero.title": "Donner au monde les moyens par l\\'<em>Éducation</em>",
    "hero.subtitle": "CTWP Educational Empowerment comble le fossé entre les apprenants et le savoir libre et open source — en testant la technologie dans de vraies classes, pour un impact réel.",
    "hero.cta.resources": "Explorer les Ressources",
    "hero.cta.support": "Soutenir",
    "hero.cta.about": "À propos du Projet",
    # Stats
    "stat.countries": "Pays Visités",
    "stat.schools": "Écoles Visitées",
    "stat.students": "Élèves Atteints",
    "stat.labs": "Laboratoire Informatique Construit",
    "stat.labs.cta": "Voir le Lab →",
    "lab.btn": "Voir le Laboratoire Informatique →",
    "lab.banner": "Découvrez notre Laboratoire Informatique au Zimbabwe →",
    # Lab subpage
    "lab.hero.subtitle": "Un laboratoire numérique entièrement équipé pour les enfants défavorisés et handicapés — alimenté par l'énergie solaire, Internet Starlink et la conviction que chaque enfant mérite l'accès à la technologie.",
    "lab.hero.cta1": "Soutenir ce Projet",
    "lab.hero.cta2": "Voir ce que Nous Avons Construit",
    "lab.intro.label": "Rapport de Situation 2025",
    "lab.intro.title": "Merci pour votre Soutien !",
    "lab.intro.quote": "\"Pour les enfants défavorisés et handicapés du Zimbabwe, Bongai Shamwari est bien plus qu'un lieu d'apprentissage — c'est une source d'espoir, d'opportunité et de communauté.\"",
    "lab.intro.p1": "Votre généreuse contribution en 2025 a été déterminante pour faire avancer le projet de numérisation à l'école maternelle et primaire Bongai Shamwari. Grâce à votre soutien, nous avons construit une infrastructure numérique durable qui ouvre la porte au savoir et à de nouvelles opportunités d'apprentissage pour les enfants, leurs enseignants et la communauté au sens large.",
    "lab.intro.p2": "Votre engagement contribue à façonner un avenir où chaque enfant peut explorer son potentiel et participer pleinement au monde numérique. Chaque étape nous rapproche de notre objectif : rendre l'éducation accessible à tous, quels que soient les obstacles.",
    "lab.milestones.label": "Réalisé en 2025",
    "lab.milestones.title": "Ce que Nous Avons Construit Ensemble",
    "lab.milestones.subtitle": "Des fondations posées aux premières leçons d'informatique — chaque étape franchie grâce à votre soutien.",
    "lab.m1.title": "Installation Solaire",
    "lab.m1.desc": "Système d'énergie solaire complet installé, garantissant une électricité fiable et durable pour le laboratoire informatique.",
    "lab.m2.title": "Préparation de la Salle",
    "lab.m2.desc": "Intérieur du laboratoire entièrement aménagé, avec des tables et des chaises achetées localement pour soutenir la communauté.",
    "lab.m3.title": "Renforcement de la Sécurité",
    "lab.m3.desc": "Barreaux anti-intrusion et caméras de sécurité supplémentaires installés pour protéger tout le matériel.",
    "lab.m4.title": "Internet Starlink",
    "lab.m4.desc": "Système Starlink installé, offrant une connectivité haut débit fiable pour soutenir l'apprentissage numérique.",
    "lab.m5.title": "Ordinateurs Livrés",
    "lab.m5.desc": "Tous les ordinateurs avec leurs périphériques expédiés à l'école ; écrans achetés localement.",
    "lab.m6.title": "Configuration Technique",
    "lab.m6.desc": "Tout le matériel et les logiciels installés pour une utilisation en classe, incluant des outils pédagogiques et des contrôles d'accès adaptés aux enfants.",
    "lab.m7.title": "Enseignant Informatique Recruté",
    "lab.m7.desc": "Un enseignant informatique qualifié recruté après des entretiens approfondis pour garantir la meilleure adéquation avec le programme.",
    "lab.m8.title": "Premiers Cours d'Informatique",
    "lab.m8.desc": "Séances d'initiation pour élèves et enseignants lancées avec succès, introduisant les compétences fondamentales en culture numérique.",
    "lab.gallery.label": "Impressions",
    "lab.gallery.title": "À l'Intérieur du Laboratoire",
    "lab.gallery.subtitle": "Moments réels des premières leçons à l'école Bongai Shamwari, Zimbabwe.",
    "lab.nextsteps.label": "Perspectives",
    "lab.nextsteps.title": "Prochaines Étapes — 2026 et Au-delà",
    "lab.nextsteps.subtitle": "Le laboratoire fonctionne — nous devons maintenant le pérenniser et le développer. Voici ce qui vient ensuite.",
    "lab.ns1.title": "Sécuriser le Financement du Salaire de l'Enseignant Informatique",
    "lab.ns1.desc": "Identifier des donateurs, partenaires ou programmes RSE pour financer l'éducateur informatique à plein temps — assurant la durabilité à long terme du programme d'apprentissage numérique.",
    "lab.ns2.title": "Envoyer le Matériel Restant et Améliorer la Salle",
    "lab.ns2.desc": "Envoyer imprimante, projecteur, tapis de souris et clés USB ; acheter localement une étagère, des housses anti-poussière et des manuels d'informatique.",
    "lab.ns3.title": "Lancer le Programme Complet d'Informatique",
    "lab.ns3.desc": "Démarrer le premier trimestre officiel d'informatique en tant que matière structurée à Bongai Shamwari — transformant les leçons pilotes en programme complet d'éducation numérique.",
    "lab.contact.label": "Nous Contacter",
    "lab.contact.title": "Contacter l'Équipe Projet",
    "lab.contact.subtitle": "Des questions sur le laboratoire, des opportunités de partenariat ou comment contribuer ? Écrivez-nous directement.",
    "lab.contact.lars.role": "CDO de Bongai",
    "lab.contact.christa.role": "Président",
    "lab.cta.title": "Aidez-nous à Maintenir le Lab en Fonctionnement",
    "lab.cta.subtitle": "Votre don finance directement le salaire de l'enseignant informatique, le nouveau matériel et la formation continue d'enfants qui n'avaient jamais eu accès à un ordinateur.",
    "lab.cta.btn1": "Faire un Don",
    "lab.cta.btn2": "Site Bongai Shamwari",
    "lab.cta.btn3": "← Retour au CTWP",
    "lab.done": "Réalisé",
    "lab.needhelp": "Encore nécessaire — pouvez-vous aider ?",
    "lab.op1.title": "Salaire de l'Enseignant Informatique",
    "lab.op1.desc": "Nous avons besoin de sponsors réguliers pour financer l'éducateur informatique à plein temps chaque année.",
    "lab.op2.title": "Coûts Internet",
    "lab.op2.desc": "L'abonnement Starlink doit être financé mensuellement pour que le lab reste connecté au monde.",
    "lab.op3.title": "Imprimante et Projecteur",
    "lab.op3.desc": "Une imprimante, un projecteur et un écran de classe manquent encore dans le laboratoire.",
    "lab.op4.title": "Fournitures Restantes",
    "lab.op4.desc": "Tapis de souris, clés USB, housses anti-poussière, étagères et manuels d'informatique sont encore en attente.",
    "lab.op.sponsor": "Sponsoriser",
    "lab.op.donate": "Donner",
    # About
    "about.label": "À propos du Projet",
    "about.title": "Ce que Nous Faisons",
    "vision.title": "Notre Vision",
    "vision.text": "Donner à chaque enfant et individu sur cette planète les moyens d'accéder à une éducation (gratuite) grâce à la technologie et ainsi impacter positivement le monde de tous.",
    "mission.title": "Notre Mission",
    "mission.text": "Créer un concept scolaire innovant pour les enfants défavorisés qui combine l'apprentissage en ligne et hors ligne et intègre une éducation personnalisée et des expériences de la vie réelle.",
    "journey.title": "Notre Parcours vers l'Impact",
    "journey.subtitle": "Actuellement à la Phase 4 sur 5",
    "journey.desc": "De la découverte des besoins réels dans plus de 60 pays à la construction et l'amélioration d'une école pilote — suivez notre parcours ou explorez chaque phase ci-dessous.",
    # Phase labels
    "phase.label.1": "Découvrir",
    "phase.label.2": "Concevoir",
    "phase.label.3": "Construire",
    "phase.label.4": "Améliorer",
    "phase.label.5": "Déployer",
    # Phase badges
    "badge.completed": "Terminé",
    "badge.current": "Phase Actuelle",
    "badge.upcoming": "À venir",
    # Phase content
    "phase1.title": "Découvrir",
    "phase1.tagline": "Comprendre les besoins réels avant de créer des solutions",
    "phase1.li1": "Visite de plus de 150 écoles et universités dans plus de 60 pays",
    "phase1.li2": "Formation d'enseignants et d'élèves aux outils d'apprentissage numérique et d'IA",
    "phase1.li3": "Formation complète en pédagogie, sciences de l'apprentissage et EdTech",
    "phase2.title": "Concevoir",
    "phase2.tagline": "Transformer les enseignements en un modèle d'apprentissage puissant",
    "phase2.li1": "Élaboration d'un concept scolaire tourné vers l'avenir",
    "phase2.li2": "Combinaison d'expériences d'apprentissage en ligne et hors ligne",
    "phase2.li3": "Centré sur l'apprentissage personnalisé et les compétences pour la vie réelle",
    "phase3.title": "Construire",
    "phase3.tagline": "De la vision à l'impact concret",
    "phase3.li1": "Lancement de notre école pilote",
    "phase3.li2": "Création d'un environnement d'apprentissage sûr et inspirant",
    "phase3.li3": "Test du modèle dans la vie scolaire quotidienne",
    "phase4.title": "Améliorer",
    "phase4.tagline": "S'améliorer à travers des expériences réelles",
    "phase4.li1": "Test et perfectionnement continus du modèle",
    "phase4.li2": "Collecte de retours auprès des élèves, enseignants et communautés",
    "phase4.li3": "Adaptation du modèle pour accroître l'impact",
    "phase5.title": "Déployer",
    "phase5.tagline": "Déployer ce qui fonctionne pour atteindre plus d'enfants",
    "phase5.li1": "Construire des partenariats stratégiques avec des écoles et des organisations",
    "phase5.li2": "Préparer le modèle pour une réplication mondiale",
    "phase5.li3": "Élargir l'accès à une éducation de qualité partout dans le monde",
    # Gallery
    "gallery.label": "Voir l'Impact",
    "gallery.title": "Notre Action en Images",
    "gallery.subtitle": "Photos et vidéos de nos écoles, sessions de formation et travail communautaire.",
    "gallery.follow": "Suivre notre parcours",
    # Resources landing
    "res.label": "Trouvez ce dont Vous Avez Besoin",
    "res.title": "Ressources Éducatives Gratuites",
    "res.subtitle": "Plus de 700 outils sélectionnés — pour élèves K–12, enseignants et apprenants universitaires.",
    "res.k12.title": "Élèves K–12",
    "res.k12.tagline": "300 outils gratuits en 14 compétences de vie",
    "res.k12.desc": "Alphabétisation, mathématiques, sciences, codage, IA, pensée critique, santé mentale, finances et bien plus pour les 3–18 ans.",
    "res.k12.cta": "Explorer les Ressources K–12 →",
    "res.teachers.title": "Enseignants",
    "res.teachers.tagline": "344 outils gratuits en 6 phases d'enseignement",
    "res.teachers.desc": "Planification de cours, copilotos IA, gestion de classe, évaluation, labs STEM, arts et musique, apprentissage en famille et développement professionnel.",
    "res.teachers.cta": "Explorer les Ressources pour Enseignants →",
    "res.uni.title": "Université et Formation Continue",
    "res.uni.tagline": "144 outils gratuits en 12 compétences d'avenir",
    "res.uni.desc": "Maîtrise de l'IA, codage, pensée critique, santé mentale, finances, carrière et plus — pour étudiants universitaires, cadres et apprenants tout au long de la vie.",
    "res.uni.cta": "Explorer les Ressources Universitaires →",
    # Resources section (old style)
    "resources.label": "Ressources Éducatives Gratuites",
    "resources.title": "Ressources Éducatives",
    "resources.subtitle": "Ressources gratuites sélectionnées pour apprendre et enseigner mieux — explorez par public.",
    "resources.k12.title": "Élèves (K–12)",
    "resources.k12.desc": "Cours gratuits, outils interactifs de codage, sciences, langues, santé mentale et bien plus pour les 3–18 ans.",
    "resources.k12.link": "Découvrir les ressources scolaires",
    "resources.teacher.title": "Enseignants",
    "resources.teacher.desc": "Plans de cours, outils IA d'enseignement, gestion de classe, évaluation et développement professionnel.",
    "resources.teacher.link": "Découvrir les ressources pour enseignants",
    "resources.uni.title": "Étudiants Universitaires",
    "resources.uni.desc": "Outils de recherche académique, manuels gratuits, productivité et carrière pour étudiants et apprenants tout au long de la vie.",
    "resources.uni.link": "Découvrir les ressources universitaires",
    # Support
    "support.label": "Comment Vous Pouvez Aider",
    "support.title": "Soutenez notre Mission",
    "support.subtitle": "Il existe de nombreuses façons de faire la différence — des dons aux partenariats d'entreprise.",
    "support.donate.title": "Faire un Don",
    "support.donate.desc": "Chaque contribution finance directement l'accès à la technologie, la formation des enseignants et les matériels pédagogiques pour les enfants dans le besoin.",
    "support.donate.cta": "Donner Maintenant",
    "support.volunteer.title": "Bénévolat",
    "support.volunteer.desc": "Partagez vos compétences en tech, éducation, création de contenu ou marketing — à distance ou sur place au Zimbabwe.",
    "support.volunteer.cta": "Rejoindre l'Équipe",
    "support.member.title": "Devenir Membre",
    "support.member.desc": "Rejoignez la communauté Bongai Shamwari. Votre adhésion annuelle constitue la base financière sur laquelle nous construisons.",
    "support.spread.title": "Faire Passer le Message",
    "support.spread.desc": "Partagez notre mission sur les réseaux sociaux et dans votre réseau. La sensibilisation est le premier pas vers un changement réel.",
    "support.corp.title": "Partenariat Entreprise",
    "support.corp.desc": "Devenez sponsor principal comme Trelleborg. Financez l'infrastructure numérique, les laboratoires informatiques et les programmes éducatifs. Bénéficiez d'une visibilité et de rapports d'impact.",
    "support.tech.title": "Dons Technologiques",
    "support.tech.desc": "Faites don d'ordinateurs portables, de tablettes ou d'autres appareils pour équiper nos laboratoires informatiques et salles de classe.",
    "support.employee.title": "Bénévolat d'Entreprise",
    "support.employee.desc": "Envoyez des employés qualifiés former enseignants et élèves à la culture numérique, au codage et aux outils d'IA dans le cadre de votre programme RSE.",
    "support.employee.cta": "En Savoir Plus",
    "support.partner.title": "Partenariat Stratégique",
    "support.partner.desc": "Co-développez des programmes éducatifs, fournissez des licences logicielles ou soutenez notre stratégie de déploiement dans de nouvelles régions.",
    "support.partner.cta": "Contactez-nous",
    # Tabs
    "tab.hint": "Sélectionnez votre catégorie pour voir comment vous pouvez aider",
    "tab.individuals": "Pour les Particuliers",
    "tab.companies": "Pour les Entreprises",
    # CTA
    "cta.title": "Chaque Contribution Compte",
    "cta.desc": "100 % des dons vont directement aux programmes éducatifs. Les virements bancaires n'ont aucun frais de transaction.",
    "cta.donate": "Donner Maintenant",
    "cta.sponsor": "Devenir Sponsor",
    # Sponsors
    "sponsors.label": "Nos Partenaires et Sponsors",
    "sponsor.main_sponsor": "Sponsor Principal",
    "sponsor.main_partner": "Partenaire Principal",
    "sponsor.partner": "Partenaire",
    "sponsor.placeholder": "Votre logo pourrait être ici",
    # Contact
    "contact.label": "Prendre Contact",
    "contact.title": "Construisons Ensemble l'Éducation de Demain",
    "contact.desc": "Que vous soyez investisseur, éducateur, partenaire potentiel ou simplement curieux de notre travail — nous serions ravis de vous entendre.",
    "contact.location": "Zurich, Suisse (Siège)",
    "contact.form.title": "Envoyez-nous un Message",
    "contact.form.name": "Votre Nom",
    "contact.form.email": "Votre E-mail",
    "contact.form.interest": "Je suis intéressé(e) en tant que",
    "contact.form.interest.option1": "Donateur",
    "contact.form.interest.option2": "Partenariat / Collaboration",
    "contact.form.interest.option3": "Bénévole",
    "contact.form.interest.option4": "Autre",
    "contact.form.message": "Votre Message",
    "contact.form.submit": "Envoyer le Message",
    "contact.info.email.label": "Écrivez-nous",
    "contact.info.location.label": "Basé à",
    "contact.info.location.value": "Zurich, Suisse",
    # Form fields
    "form.name": "Nom",
    "form.name.ph": "Votre nom complet",
    "form.email": "E-mail",
    "form.email.ph": "votre@email.com",
    "form.interest": "Je suis intéressé(e) en tant que...",
    "form.select": "Sélectionner une option",
    "form.donor": "Donateur",
    "form.corp_sponsor": "Sponsor d'Entreprise",
    "form.teacher_role": "Enseignant",
    "form.student_role": "Élève",
    "form.volunteer": "Bénévole",
    "form.partner_role": "Organisation Partenaire",
    "form.other": "Autre",
    "form.message": "Message",
    "form.message.ph": "Dites-nous comment vous souhaitez vous impliquer...",
    "form.submit": "Envoyer le Message",
    # Footer
    "footer.desc": "Donner à chaque enfant les moyens d'accéder à une éducation gratuite grâce à la technologie.",
    "footer.nav": "Navigation",
    "footer.connect": "Se Connecter",
    "footer.about": "À propos",
    "footer.work": "Notre Action",
    "footer.resources": "Ressources",
    "footer.support": "Soutenir",
    "footer.contact": "Contact",
    "footer.copyright": "© 2026 CTWP Educational Empowerment. Tous droits réservés.",
    "footer.tagline": "Donner au monde les moyens par l'éducation.",
    "footer.nav.title": "Navigation",
    "footer.connect.title": "Se Connecter",
    "footer.legal": "© 2026 CTWP Educational Empowerment. Tous droits réservés.",
    "footer.tagline.small": "Fait avec ❤ pour l'éducation",
    # Students subpage
    "sub.students.badge": "Compétences K–12 pour l'Avenir",
    "sub.students.title": "Ressources pour Élèves (K–12)",
    "sub.students.desc": "300 outils gratuits sélectionnés pour 14 compétences de vie — de l'alphabétisation et des maths jusqu'à la santé mentale, les finances et le sport.",
    "sub.students.back": "Retour aux Ressources",
    "sub.k12.back": "Retour aux Ressources",
    "sub.k12.badge": "Outils Gratuits pour Élèves K–12",
    "sub.k12.title": "Ressources pour Élèves K–12",
    "sub.k12.desc": "300 outils gratuits sélectionnés en 14 compétences de vie — de l'alphabétisation et des maths jusqu'à l'IA, la santé mentale et le sport.",
    # Students chrome
    "students.stat.tools": "Outils Gratuits",
    "students.stat.skills": "Compétences de Vie",
    "students.stat.ages": "Tranches d'Âge",
    "students.stat.freestart": "Gratuit dès le Départ",
    "students.stat.free": "Gratuit",
    "students.picker.label": "Explorer par Compétence",
    "students.picker.heading": "Choisissez l'une des <em>14 compétences de vie</em> pour découvrir les meilleurs outils gratuits",
    "students.filter.label": "Filtrer par âge :",
    "students.filter.all": "Tous les Âges",
    # Skill chip labels
    "students.chip.literacy": "Alphabétisation",
    "students.chip.math": "Mathématiques",
    "students.chip.science": "Sciences",
    "students.chip.history": "Histoire",
    "students.chip.coding": "Codage",
    "students.chip.ai": "Culture Numérique",
    "students.chip.critical": "Esprit Critique",
    "students.chip.mental": "Santé Mentale",
    "students.chip.finance": "Finances",
    "students.chip.life": "Compétences de Vie",
    "students.chip.values": "Valeurs",
    "students.chip.creativity": "Créativité",
    "students.chip.learn": "Apprendre à Apprendre",
    "students.chip.sport": "Sport et Santé",
    # Section labels
    "students.sec.literacy.label": "Lire, Écrire, S'exprimer",
    "students.sec.math.label": "Nombres et Logique",
    "students.sec.science.label": "Curiosité et Exploration",
    "students.sec.history.label": "Passé et Lieux",
    "students.sec.coding.label": "Construire et Créer",
    "students.sec.ai.label": "Comprendre le Web et la Machine",
    "students.sec.critical.label": "Mieux Réfléchir",
    "students.sec.mental.label": "Se Sentir Bien, Apprendre Bien",
    "students.sec.finance.label": "Argent, Banque, Assurance",
    "students.sec.life.label": "Cuisiner, Bouger, Bien Vivre",
    "students.sec.values.label": "Caractère et Communauté",
    "students.sec.creativity.label": "Faire et Imaginer",
    "students.sec.learn.label": "Étudier Plus Intelligemment",
    "students.sec.sport.label": "Bouger et s'Épanouir",
    # Section headings
    "students.sec.literacy.title": "Alphabétisation et Communication",
    "students.sec.math.title": "Mathématiques",
    "students.sec.science.title": "Sciences",
    "students.sec.history.title": "Histoire et Géographie",
    "students.sec.coding.title": "Codage et Pensée Computationnelle",
    "students.sec.ai.title": "IA et Culture Numérique",
    "students.sec.critical.title": "Esprit Critique et Résolution de Problèmes",
    "students.sec.mental.title": "Santé Mentale et Pleine Conscience",
    "students.sec.finance.title": "Culture Financière",
    "students.sec.life.title": "Compétences de Vie et Santé",
    "students.sec.values.title": "Valeurs, Éthique et Citoyenneté",
    "students.sec.creativity.title": "Créativité, Arts et Fabrication",
    "students.sec.learn.title": "Apprendre à Apprendre",
    "students.sec.sport.title": "Sport et Santé Physique",
    # Section descriptions
    "students.sec.literacy.desc": "De la phonétique à la rédaction : entraînement à la lecture, grammaire, vocabulaire et expression pour tous les âges.",
    "students.sec.math.desc": "Du comptage au calcul intégral : entraînement interactif, outils visuels et explications expertes pour tous les âges.",
    "students.sec.science.desc": "Simulations, expériences et explications visuelles en physique, chimie, biologie, sciences de la Terre et de l'espace.",
    "students.sec.history.desc": "Explorez continents, cultures et siècles — cartes interactives, sources primaires et récits riches.",
    "students.sec.coding.desc": "Des blocs à glisser-déposer à la vraie programmation — logique, algorithmes et création avec du code.",
    "students.sec.ai.desc": "Utiliser l'IA avec discernement, repérer la désinformation en ligne et maîtriser les compétences numériques dont chaque adulte de demain aura besoin.",
    "students.sec.critical.desc": "Raisonner clairement, débattre efficacement et distinguer les faits du bruit — la compétence n°1 dans chaque rapport Future of Jobs.",
    "students.sec.mental.desc": "Esprits calmes, régulation émotionnelle et apprentissage socio-émotionnel — le fondement de tout le reste.",
    "students.sec.finance.desc": "Budgéter, épargner, investir, services bancaires et assurances — les compétences financières pratiques que l'école enseigne rarement.",
    "students.sec.life.desc": "Cuisine, nutrition, fitness, premiers secours, sommeil et compétences quotidiennes — ce que la vie adulte exige vraiment de vous.",
    "students.sec.values.desc": "Empathie, intégrité, conscience mondiale et citoyenneté active — les compétences de caractère qui soutiennent tout le reste.",
    "students.sec.creativity.desc": "Musique, art, design, 3D, cinéma et invention — des outils gratuits qui permettent aux enfants de créer de vraies choses.",
    "students.sec.learn.desc": "Techniques de mémorisation, outils de concentration, prise de notes et science de l'apprentissage — les méta-compétences qui facilitent toutes les autres matières.",
    "students.sec.sport.desc": "Routines de mouvement, entraînement sportif, yoga et science du fitness — des ressources gratuites pour construire des habitudes saines et actives à tout âge.",
    # Sport card descriptions
    "cd_s01": "Vidéos de mouvement et de pleine conscience préférées des classes qui font lever les enfants de leurs sièges — danse, yoga et pauses actives en clips de 3–5 min.",
    "cd_s02": "Aventures de yoga narrées pour les jeunes enfants — postures intégrées dans des histoires imaginatives avec des dragons, super-héros et mondes magiques.",
    "cd_s03": "Des centaines de tutoriels de jeux d'EPS et d'idées d'activité physique pour l'école — faciles à réaliser sans matériel et adaptables à n'importe quel groupe.",
    "cd_s04": "Immense bibliothèque de plans de cours d'EPS, d'idées d'échauffement et d'activités fitness organisés par âge, compétence et matériel — un incontournable pour les enseignants d'EPS.",
    "cd_s05": "Articles accessibles aux enfants sur la science de l'exercice, la nutrition, le sommeil et la sécurité sportive — rédigés par des médecins pour construire des habitudes saines pour la vie.",
    "cd_s06": "Routines d'entraînement vidéo conçues spécifiquement pour les enfants — circuits de force, flexibilité et cardio qui s'adaptent au temps et à l'espace disponibles.",
    "cd_s07": "Kits, fiches d'activités et guides de programme pour intégrer le mouvement quotidien dans la vie scolaire — 60 minutes d'activité par jour, rendues pratiques.",
    "cd_s08": "Plus de 600 vidéos d'entraînement complètes et gratuites en cardio, force, HIIT et stretching — filtrables par durée, difficulté et matériel nécessaire.",
    "cd_s09": "Le plan de course le plus populaire au monde pour débutants — 9 semaines pour courir 5 km sans s'arrêter, avec une app gratuite et des guides audio de coachs reconnus.",
    "cd_s10": "Articles d'entraînement par sport rédigés avec des entraîneurs professionnels — vitesse, agilité, force et science de la récupération pour les jeunes athlètes sérieux.",
    "cd_s11": "Bibliothèque complète d'entraînements guidés par des coachs — séances de poids corporel, force et yoga de 15 à 60 minutes, toutes gratuites depuis que Nike a supprimé le paywall.",
    "cd_s12": "Cours gratuits de niveau universitaire sur la science du sport, l'activité physique et la performance humaine — idéaux pour les étudiants intéressés par les carrières sportives.",
    # Pricing pills + Top Pick badge
    "pill.free": "Gratuit",
    "pill.free_signup": "Gratuit (inscription)",
    "pill.freemium": "Freemium",
    "top_pick": "Recommandé",
    # University subpage
    "sub.uni.badge": "Outils de Compétences d'Avenir pour l'Enseignement Supérieur et les Apprenants Tout au Long de la Vie",
    "sub.uni.title": "Ressources pour Étudiants Universitaires et Apprenants Tout au Long de la Vie",
    "sub.uni.desc": "144 outils gratuits sélectionnés en 12 clusters de compétences d'avenir. Choisissez un sujet ci-dessous pour explorer les 12 meilleures ressources.",
    "sub.uni.back": "Retour aux Ressources",
    # University stats
    "uni.stat.tools": "Outils Gratuits",
    "uni.stat.topics": "Sujets d'Avenir",
    "uni.stat.clusters": "Clusters",
    "uni.stat.levels.val": "Licence→Cadre",
    "uni.stat.levels.lbl": "Tous Niveaux",
    "uni.stat.free": "Gratuit",
    # University audience-grade badges
    "uni.grade.undergrad": "Licence",
    "uni.grade.grad": "Master",
    "uni.grade.phd": "Doctorat",
    "uni.grade.self": "Autodidacte",
    "uni.grade.all": "Tous Niveaux",
    "uni.grade.adult": "Cadre",
    "uni.grade.switcher": "Reconversion",
    # University skill-picker chrome + filter bar
    "uni.picker.label": "Explorer par Compétence",
    "uni.picker.heading": "Choisissez l'un des <em>12 clusters de compétences d'avenir</em> pour découvrir les meilleurs outils gratuits",
    "uni.filter.label": "Filtrer par public :",
    "uni.filter.all": "Tous les Publics",
    # University tab labels
    "uni.tab.ai": "Maîtrise IA",
    "uni.tab.coding": "Codage et Données",
    "uni.tab.security": "Cybersécurité",
    "uni.tab.critical": "Esprit Critique",
    "uni.tab.courseware": "Cours Ouverts",
    "uni.tab.research": "Recherche",
    "uni.tab.writing": "Écriture et Prise de Parole",
    "uni.tab.productivity": "Productivité",
    "uni.tab.mental": "Santé Mentale",
    "uni.tab.finance": "Finances Personnelles",
    "uni.tab.career": "Carrière et Entrepreneuriat",
    "uni.tab.civic": "Civisme, Médias et Climat",
    # University chip labels
    "uni.chip.ai": "Maîtrise IA",
    "uni.chip.coding": "Codage et Données",
    "uni.chip.security": "Cybersécurité",
    "uni.chip.critical": "Esprit Critique",
    "uni.chip.courseware": "Cours Ouverts",
    "uni.chip.research": "Recherche",
    "uni.chip.writing": "Écriture et Oratoire",
    "uni.chip.productivity": "Productivité",
    "uni.chip.mental": "Santé Mentale",
    "uni.chip.finance": "Finances",
    "uni.chip.career": "Carrière",
    "uni.chip.civic": "Civisme et Climat",
    # University section panel labels + headings + descriptions
    "uni.sec.ai.label": "Tuteurs IA et Copilotos",
    "uni.sec.ai.h2": "Maîtrise de l'IA et Collaboration avec l'IA",
    "uni.sec.ai.desc": "Les meilleurs assistants gratuits, des cours sur la conception de prompts et la culture dont vous avez besoin pour penser avec l'IA plutôt que contre elle.",
    "uni.sec.coding.label": "Programmation et Science des Données",
    "uni.sec.coding.h2": "Codage et Culture des Données",
    "uni.sec.coding.desc": "Apprenez à coder, pratiquez avec de vrais jeux de données et construisez un portfolio — cours gratuits, bacs à sable et certifications.",
    "uni.sec.security.label": "Confidentialité et Sécurité en Ligne",
    "uni.sec.security.h2": "Cybersécurité et Confidentialité Numérique",
    "uni.sec.security.desc": "Protégez vos comptes, données et identité en ligne — et apprenez les compétences en sécurité que personne d'autre ne vous enseigne.",
    "uni.sec.critical.label": "Raisonnement et Culture de l'Information",
    "uni.sec.critical.h2": "Esprit Critique et Culture de l'Information",
    "uni.sec.critical.desc": "Évaluer les preuves, reconnaître les biais et raisonner clairement face à l'incertitude — la compétence n°1 du WEF pour la prochaine décennie.",
    "uni.sec.courseware.label": "Cours et MOOCs",
    "uni.sec.courseware.h2": "Cours Ouverts et Formation Tout au Long de la Vie",
    "uni.sec.courseware.desc": "Cours complets du MIT, Harvard, Stanford, Yale et d'autres grandes universités — gratuits en audit, apprenez n'importe quoi depuis n'importe où.",
    "uni.sec.research.label": "Trouver et Citer des Sources",
    "uni.sec.research.h2": "Recherche, Citation et Savoir Ouvert",
    "uni.sec.research.desc": "Découvrez des articles évalués par les pairs, gérez vos citations et lisez des manuels ouverts gratuits — tout pour votre thèse ou article, gratuitement.",
    "uni.sec.writing.label": "Dissertations, Communication et Expression Orale",
    "uni.sec.writing.h2": "Écriture, Communication et Prise de Parole en Public",
    "uni.sec.writing.desc": "Rédigez des dissertations plus claires, présentez avec assurance et traduisez précisément — le complément humain à l'assistance IA.",
    "uni.sec.productivity.label": "Notes, Concentration, Délais",
    "uni.sec.productivity.h2": "Productivité, Concentration et Travail en Profondeur",
    "uni.sec.productivity.desc": "Systèmes de prise de notes, gestionnaires de tâches et outils de concentration pour reprendre le contrôle de votre attention — le prérequis de tout le reste.",
    "uni.sec.mental.label": "Bien-être et Résilience",
    "uni.sec.mental.h2": "Santé Mentale et Résilience",
    "uni.sec.mental.desc": "Sommeil, stress, anxiété et humeur — des ressources gratuites fondées sur des preuves pour soutenir l'actif le plus précieux que vous ayez.",
    "uni.sec.finance.label": "Argent, Impôts, Investissement",
    "uni.sec.finance.h2": "Finances Personnelles et Culture Économique",
    "uni.sec.finance.desc": "Budgéter, payer ses impôts, l'intérêt composé et les bases de l'investissement — les compétences financières que l'école enseigne rarement mais dont vous avez besoin à 25 ans.",
    "uni.sec.career.label": "Emploi, Réseau, Entrepreneuriat",
    "uni.sec.career.h2": "Carrière, Réseau et Entrepreneuriat",
    "uni.sec.career.desc": "Décrochez des stages, changez de carrière, faites du freelance ou créez une entreprise — les compétences pratiques pour une vie professionnelle en portefeuille.",
    "uni.sec.civic.label": "Citoyenneté et Durabilité",
    "uni.sec.civic.h2": "Civisme, Médias et Culture Climatique",
    "uni.sec.civic.desc": "Citoyenneté au sens large — comprendre la démocratie, évaluer les médias, saisir la science du climat et l'éthique de la technologie.",
    # Teachers subpage
    "sub.teachers.back": "Retour aux Ressources",
    "sub.teachers.badge": "Outils Gratuits pour Enseignants et Éducateurs",
    "sub.teachers.title": "Ressources pour Enseignants",
    "sub.teachers.desc": "344 outils gratuits sélectionnés et organisés selon le flux de travail de l'enseignant. Choisissez une phase puis un sujet pour trouver le bon outil.",
    # Teachers stats
    "teachers.stat.tools": "Outils Gratuits",
    "teachers.stat.topics": "Sujets",
    "teachers.stat.phases": "Phases de Travail",
    "teachers.stat.free": "Gratuit",
    # Teachers audience-grade badges
    "teachers.grade.prek": "Préélémentaire",
    "teachers.grade.primary": "Primaire",
    "teachers.grade.secondary": "Secondaire",
    "teachers.grade.higher": "Enseignement Supérieur",
    "teachers.grade.sen": "Éducation Spécialisée",
    "teachers.grade.all": "Tous les Niveaux",
    # Teachers picker
    "teachers.picker.label": "Explorer par Phase",
    "teachers.picker.heading": "Choisissez une <em>phase du flux de travail enseignant</em>, puis un sujet",
    "teachers.filter.label": "Filtrer par niveau :",
    "teachers.filter.all": "Tous les Niveaux",
    # Teachers phases
    "teachers.phase.fundamentals.name": "Fondements de l'Enseignant",
    "teachers.phase.fundamentals.tag": "Didactique et Pédagogie",
    "teachers.phase.before.name": "Avant la Classe",
    "teachers.phase.before.tag": "Conception et Préparation",
    "teachers.phase.during.name": "Pendant la Classe",
    "teachers.phase.during.tag": "Enseignement et Apprentissage",
    "teachers.phase.after.name": "Après la Classe",
    "teachers.phase.after.tag": "Évaluation et Suivi",
    "teachers.phase.supp.name": "Soutien",
    "teachers.phase.supp.tag": "Toutes les phases",
    "teachers.phase.furtherdev.name": "Développement Professionnel",
    "teachers.phase.furtherdev.tag": "Progressez en tant qu'Enseignant",
    # Teachers chips + sections
    "teachers.chip.didactics": "Didactique",
    "teachers.sec.didactics.label": "Comment Enseigner",
    "teachers.sec.didactics.h2": "Didactique — Comment Vous Enseignez",
    "teachers.sec.didactics.desc": "Maîtrisez l'art d'enseigner : modèles d'instruction, structure de leçon, transmission de contenu et techniques fondées sur des preuves pour que chaque leçon fonctionne.",
    "teachers.chip.pedagogy": "Pédagogie",
    "teachers.sec.pedagogy.label": "Pourquoi Vous Enseignez Ainsi",
    "teachers.sec.pedagogy.h2": "Pédagogie — Pourquoi Vous Enseignez Ainsi",
    "teachers.sec.pedagogy.desc": "Explorez la théorie et la philosophie derrière le grand enseignement : psychologie de l'apprentissage, motivation, constructivisme et expérience de l'apprenant.",
    "teachers.chip.together": "Les Deux Ensemble",
    "teachers.sec.together.label": "La Théorie Rencontre la Pratique",
    "teachers.sec.together.h2": "Les Deux Ensemble — La Théorie Rencontre la Pratique",
    "teachers.sec.together.desc": "Ressources qui relient la recherche et la réalité de la classe — cadres, vidéos d'enseignement réel et kits qui fonctionnent parce qu'ils s'appuient sur les deux.",
    "teachers.chip.fund_start": "Par Où Commencer",
    "teachers.sec.fund_start.label": "Votre Point de Départ",
    "teachers.sec.fund_start.h2": "Par Où Commencer",
    "teachers.sec.fund_start.desc": "Nouveau dans l'exploration de votre pratique ? Commencez ici — un parcours guidé à travers les ressources gratuites les plus importantes pour les enseignants en développement.",
    "teachers.chip.planning": "Planification de Cours et Curriculum",
    "teachers.sec.planning.label": "Curriculum et Conception de Cours",
    "teachers.sec.planning.h2": "Planification de Cours et Curriculum",
    "teachers.sec.planning.desc": "Construisez des unités alignées sur les standards, des plans hebdomadaires et des leçons prêtes à enseigner en quelques minutes — modèles gratuits et curriculums ouverts complets.",
    "teachers.chip.materials": "Créer des Supports",
    "teachers.sec.materials.label": "Fiches, Diapositives, Vidéo et Visuels",
    "teachers.sec.materials.h2": "Créer des Supports — Diapositives, Fiches, Vidéo et Visuels",
    "teachers.sec.materials.desc": "Créez des fiches, diapositives, infographies et vidéos soignées en quelques minutes — sans compétences en design, tout gratuit pour les enseignants.",
    "teachers.chip.adapting": "Sélectionner et Adapter",
    "teachers.sec.adapting.label": "Différenciation, Accessibilité et Besoins Particuliers",
    "teachers.sec.adapting.h2": "Sélectionner et Adapter les Ressources",
    "teachers.sec.adapting.desc": "Sélectionnez des ressources existantes et adaptez-les à chaque élève — outils de niveau de texte, bibliothèques nivelées, lecteurs accessibles et outils adaptés à la dyslexie.",
    "teachers.chip.objectives": "Objectifs et Alignement sur les Standards",
    "teachers.sec.objectives.label": "Standards, Cadres et Structure de Leçon",
    "teachers.sec.objectives.h2": "Fixer des Objectifs et Aligner sur les Standards",
    "teachers.sec.objectives.desc": "Ancrez chaque leçon dans des standards et des objectifs clairs — cadres officiels, taxonomies et bibliothèques OER alignées sur les standards.",
    "teachers.chip.explaining": "Expliquer le Contenu",
    "teachers.sec.explaining.label": "Diapositives, Vidéo et Screencast",
    "teachers.sec.explaining.h2": "Expliquer le Contenu — Diapositives, Vidéo et Screencast",
    "teachers.sec.explaining.desc": "Dispensez des leçons mémorables — diapositives interactives, questions en vidéo, screencasts et mini-cours sélectionnés.",
    "teachers.chip.interactive": "Activités Interactives",
    "teachers.sec.interactive.label": "Labs STEM, Ateliers d'Art et de Musique",
    "teachers.sec.interactive.h2": "Activités Interactives — Labs STEM, Art et Musique",
    "teachers.sec.interactive.desc": "Simulations pratiques, laboratoires virtuels et ateliers créatifs — laissez les élèves FAIRE de la physique, biologie, musique et art dans votre leçon.",
    "teachers.chip.collab": "Collaboration",
    "teachers.sec.collab.label": "Tableaux Blancs, Cartes Mentales et Brainstorming",
    "teachers.sec.collab.h2": "Collaboration — Pensée Visuelle et Brainstorming",
    "teachers.sec.collab.desc": "Rendez visible la pensée des élèves — tableaux blancs collaboratifs, cartes mentales, tableaux de post-its et outils de cartographie conceptuelle.",
    "teachers.chip.instruction": "Instruction en Direct",
    "teachers.sec.instruction.label": "Sondages, Quiz et Systèmes de Réponse",
    "teachers.sec.instruction.h2": "Instruction en Classe — Réponse en Direct et Sondages",
    "teachers.sec.instruction.desc": "Menez des activités en direct engageantes — quiz concours, sondages, billets de sortie et systèmes de réponse qui maintiennent chaque élève actif.",
    "teachers.chip.grading": "Notation",
    "teachers.sec.grading.label": "LMS, Carnets de Notes et Auto-correction",
    "teachers.sec.grading.h2": "Notation — LMS, Carnets de Notes et Auto-correction",
    "teachers.sec.grading.desc": "Réduisez de moitié le temps de notation — carnets de notes LMS gratuits, quiz auto-corrigés, outils de rubrique et rapports basés sur les standards.",
    "teachers.chip.feedback": "Rétroaction",
    "teachers.sec.feedback.label": "Écriture, Grammaire et Notes Vocales",
    "teachers.sec.feedback.h2": "Rétroaction — Aide à l'Écriture, Grammaire et Commentaires",
    "teachers.sec.feedback.desc": "Donnez des retours significatifs et rapides sur l'écriture des élèves — correcteurs de grammaire, notes vocales, outils de rubrique et plateformes d'aide à l'écriture.",
    "teachers.chip.reflection": "Réflexion",
    "teachers.sec.reflection.label": "Billets de Sortie, Journaux et Portfolios",
    "teachers.sec.reflection.h2": "Réflexion — Billets de Sortie, Journaux et Portfolios",
    "teachers.sec.reflection.desc": "Aidez les élèves à réfléchir sur leur apprentissage — réflexions vidéo, journaux, billets de sortie, e-books et portfolios.",
    "teachers.chip.tracking": "Suivi des Progrès",
    "teachers.sec.tracking.label": "Devoirs, Pratique et Apprentissage en Famille",
    "teachers.sec.tracking.h2": "Suivi des Progrès — Devoirs et Apprentissage en Famille",
    "teachers.sec.tracking.desc": "Recommandez des ressources sûres et efficaces aux familles — soutien aux devoirs, outils de révision et apprentissage à domicile pour les parents.",
    "teachers.chip.mgmt": "Gestion de Classe",
    "teachers.sec.mgmt.label": "Comportement, Routines et Engagement",
    "teachers.sec.mgmt.h2": "Gestion de Classe et Engagement",
    "teachers.sec.mgmt.desc": "Construisez des routines positives, reconnaissez les bons comportements et gérez des systèmes quotidiens fluides — des outils gratuits qui respectent les élèves.",
    "teachers.chip.comms": "Communication",
    "teachers.sec.comms.label": "Parents, Élèves et Bulletins",
    "teachers.sec.comms.h2": "Communication — Parents, Élèves et Traduction",
    "teachers.sec.comms.desc": "Atteignez chaque famille dans sa langue et à sa manière — messagerie sécurisée, bulletins et outils de traduction.",
    "teachers.chip.admin": "Administration et Fichiers",
    "teachers.sec.admin.label": "Stockage Cloud, Tâches et Calendriers",
    "teachers.sec.admin.h2": "Administration et Stockage de Fichiers",
    "teachers.sec.admin.desc": "Réduisez la paperasse — stockage cloud gratuit, tableaux kanban, outils de planification et espaces de travail d'équipe.",
    "teachers.chip.wellbeing": "Gestion du Stress et Bien-être",
    "teachers.sec.wellbeing.label": "Santé Mentale, Pleine Conscience et Prévention du Burnout",
    "teachers.sec.wellbeing.h2": "Gestion du Stress et Bien-être",
    "teachers.sec.wellbeing.desc": "Prenez soin de vous d'abord — ressources gratuites de santé mentale, pleine conscience et prévention du burnout spécialement pour les enseignants.",
    "teachers.chip.ai": "Copilotos IA",
    "teachers.sec.ai.label": "Assistants IA pour Enseignants",
    "teachers.sec.ai.h2": "Copilotos IA — Assistants à Toutes les Phases",
    "teachers.sec.ai.desc": "Générez des plans de cours, des rubriques, des fiches différenciées et des retours en quelques secondes — outils IA gratuits pour l'ensemble du flux de travail enseignant.",
    "teachers.chip.fd_start": "Par Où Commencer",
    "teachers.sec.fd_start.label": "Nouveau en formation continue ? Commencez ici",
    "teachers.sec.fd_start.h2": "Par Où Commencer avec le Développement Professionnel",
    "teachers.sec.fd_start.desc": "Vous ne savez pas par où commencer votre développement professionnel ? Ces points de départ fiables vous aideront à planifier un parcours adapté à vous.",
    "teachers.chip.fd_courses": "Cours et Certifications Gratuits",
    "teachers.sec.fd_courses.label": "MOOCs, Badges et Certificats",
    "teachers.sec.fd_courses.h2": "Cours et Certifications Gratuits",
    "teachers.sec.fd_courses.desc": "Obtenez gratuitement des certificats et badges reconnus — de Coursera, edX, Google, Microsoft, Apple et l'Open University.",
    "teachers.chip.fd_methods": "Méthodes d'Enseignement",
    "teachers.sec.fd_methods.label": "PAP, Classe Inversée, Investigation et Plus",
    "teachers.sec.fd_methods.h2": "Méthodes d'Enseignement — Comment Mieux Enseigner",
    "teachers.sec.fd_methods.desc": "Explorez des approches pédagogiques éprouvées, de l'apprentissage par projet à la classe inversée — guides, cours et ressources prêtes pour la classe.",
    "teachers.chip.fd_subject": "Votre Matière",
    "teachers.sec.fd_subject.label": "Approfondir Votre Discipline",
    "teachers.sec.fd_subject.h2": "Votre Matière — Approfondissez vos Connaissances",
    "teachers.sec.fd_subject.desc": "Approfondissez votre domaine — ressources gratuites, outils d'enrichissement et conseils spécifiques pour les maths, le français, les sciences, les sciences humaines et plus.",
    "teachers.chip.fd_lead": "Diriger et Mentorer",
    "teachers.sec.fd_lead.label": "Coaching Pédagogique et Leadership Enseignant",
    "teachers.sec.fd_lead.h2": "Diriger et Mentorer — Devenez Enseignant Leader",
    "teachers.sec.fd_lead.desc": "Franchissez le pas vers le leadership, le coaching et le mentorat — ressources gratuites pour les enseignants qui souhaitent soutenir leurs collègues et développer la pratique de leur école.",
    "teachers.chip.fd_evidence": "Preuves et Résultats",
    "teachers.sec.fd_evidence.label": "Recherche Utile pour les Enseignants",
    "teachers.sec.fd_evidence.h2": "Preuves et Résultats — Ce que Montre la Recherche",
    "teachers.sec.fd_evidence.desc": "Accédez à la meilleure recherche en éducation dans un langage clair — stratégies validées par les preuves, résultats clés et communautés de recherche pour les enseignants occupés.",
    "teachers.chip.fd_community": "Communautés Enseignantes",
    "teachers.sec.fd_community.label": "Forums, Groupes et Réseaux Professionnels",
    "teachers.sec.fd_community.h2": "Communautés Enseignantes — Trouvez Vos Pairs",
    "teachers.sec.fd_community.desc": "Connectez-vous avec des enseignants du monde entier — forums gratuits, communautés en ligne, réseaux par matière et événements en direct où se diffusent les grandes idées pédagogiques.",
    # GDPR
    "gdpr.title": "Avis sur les Cookies et le Stockage",
    "gdpr.text": "Nous utilisons le stockage local du navigateur uniquement pour mémoriser votre préférence de langue. Aucun cookie de suivi ni donnée personnelle n'est collecté ou partagé.",
    "gdpr.accept": "Accepter",
    "gdpr.decline": "Refuser",
}
