PT_TEACHERS = {
    "cd_t_000": "O MOOC de ciência da aprendizagem mais popular do mundo (mais de 4M de alunos) — chunking, memória, pensamento difuso. Grátis para auditar.",
    "cd_t_001": "Podcast e blog de Jennifer Gonzalez — centenas de análises gratuitas sobre estratégias de ensino, engajamento e técnicas de sala de aula.",
    "cd_t_002": "Seis estratégias de estudo baseadas em evidências (prática espaçada, recuperação, elaboração etc.) explicadas com clareza para professores e alunos.",
    "cd_t_003": "Guia gratuito definitivo da Vanderbilt sobre a Taxonomia de Bloom revisada — listas de verbos, perguntas-modelo e templates de planejamento de aulas.",
    "cd_t_004": "Diretrizes gratuitas do Desenho Universal para a Aprendizagem — planeje aulas que funcionem para todo aluno desde o início, não como reflexão posterior.",
    "cd_t_005": "As 63 técnicas de sala de aula de Doug Lemov — videoclipes gratuitos, leituras e guias práticos sobre cold calling, ritmo e mais.",
    "cd_t_006": "Artigos que conectam pesquisa e prática sobre diferenciação, aprendizagem baseada em projetos, integração socioemocional e desenho de avaliações.",
    "cd_t_007": "Artigos gratuitos sobre modelos pedagógicos modernos — taxonomias de aprendizagem, frameworks inovadores e ferramentas de pensamento prontas para a sala de aula.",
    "cd_t_008": "Recursos gratuitos de Jim Knight sobre o ciclo de impacto — um framework prático que qualquer professor pode usar para autoaperfeiçoamento.",
    "cd_t_009": "Pesquisa e ferramentas gratuitas do MIT sobre aprendizagem docente — simulações, estudos de caso e cursos sobre desenho instrucional.",
    "cd_t_010": "Centenas de artigos gratuitos revisados por pares sobre currículo, instrução e avaliação da maior associação de educadores do mundo.",
    "cd_t_011": "Relatórios gratuitos que traduzem a ciência cognitiva em princípios de formação docente — A Ciência da Aprendizagem tornada acessível.",
    "cd_t_012": "Artigos gratuitos do cientista cognitivo sobre memória, atenção e motivação — traduzidos do laboratório para a prática em sala de aula.",
    "cd_t_013": "Mindset Works de Carol Dweck — resumos gratuitos de pesquisa e estratégias prontas para construir uma cultura de mentalidade de crescimento.",
    "cd_t_014": "A Teoria da Autodeterminação de Deci e Ryan explicada — por que autonomia, competência e relacionamento são as três chaves da motivação do aluno.",
    "cd_t_015": "Kit gratuito de rotinas de pensamento do Project Zero — Ver-Pensar-Perguntar, Afirmação-Apoio-Pergunta e mais de 20 protocolos prontos para a sala.",
    "cd_t_016": "Manuais gratuitos de Angela Duckworth para professores sobre garra, curiosidade, gratidão e autocontrole — apoiados em pesquisa, prontos para uso.",
    "cd_t_017": "Práticas SEL gratuitas do Berkeley Science Center baseadas em psicologia positiva — gentileza, mindfulness e resiliência.",
    "cd_t_018": "Podcast e artigos gratuitos sobre como a aprendizagem funciona — neurociência, motivação, equidade e o futuro da educação.",
    "cd_t_019": "Artigos gratuitos de pesquisa da Harvard Graduate School of Education — equidade, ciência da aprendizagem, liderança escolar e políticas.",
    "cd_t_020": "Resumo gratuito da EEF em linguagem clara sobre teoria da carga cognitiva — o que isso significa para desenho de aulas, exemplos resolvidos e prática.",
    "cd_t_021": "Guia gratuito claro sobre a Zona de Desenvolvimento Proximal de Vygotsky — como a mediação e a aprendizagem social moldam a sala de aula.",
    "cd_t_022": "Síntese da Edutopia, baseada em evidências, sobre o que a pesquisa diz tornar o ensino eficaz — acessível e prática.",
    "cd_t_023": "Projeto gratuito Visible Thinking do Project Zero de Harvard — rotinas que tornam o pensamento dos alunos visível, discutível e transferível.",
    "cd_t_024": "Videoteca de aulas reais — assista professores experientes em ação em diversas disciplinas e faixas etárias, com guias de reflexão.",
    "cd_t_025": "Recurso de referência em Aprendizagem Baseada em Projetos — kits iniciais gratuitos, rubricas e ideias de projetos baseados em pesquisa.",
    "cd_t_026": "Kit gratuito de design thinking da IDEO para educadores — um processo centrado no humano para resolver desafios em sala e na escola.",
    "cd_t_027": "Recursos gratuitos da Expeditionary Learning — caráter, equipe e avaliação por domínio, fundamentados em décadas de evidência escolar.",
    "cd_t_028": "Artigos gratuitos que conectam pesquisa e prática com vídeo de sala de aula — cada estratégia explicada, evidenciada e mostrada em ação.",
    "cd_t_029": "Mais de 250 tamanhos de efeito de Hattie com downloads gratuitos — entenda quais práticas têm o maior impacto e por quê.",
    "cd_t_030": "Protocolos gratuitos do Project Zero de Harvard para tornar visível a compreensão dos alunos — rotinas com guias de aplicação.",
    "cd_t_031": "Framework gratuito para adaptar o ensino em tempo real — conectando teoria de avaliação formativa à prática momento a momento.",
    "cd_t_032": "Cursos gratuitos para auditar sobre desenho de aprendizagem — desenho de ambientes, teoria do engajamento e pensamento sistêmico instrucional.",
    "cd_t_033": "Planos de aula, estratégias e ferramentas de gestão apoiados em pesquisa — todos conectados a padrões de aprendizagem.",
    "cd_t_034": "Artigos, webinars e guias de ensino baseados em pesquisa do principal veículo de jornalismo educacional dos EUA.",
    "cd_t_035": "Recursos práticos gratuitos da pesquisa em ciência da aprendizagem financiada pela NSF — traduzindo neurociência em ação na sala de aula.",
    "cd_t_036": "Centro Gratuito do Professor com formação, certificações e guias de integração em sala — a plataforma docente gratuita mais usada.",
    "cd_t_037": "Trilhas gratuitas com badges sobre Teams, OneNote, Minecraft Edu e ferramentas de IA para sala de aula.",
    "cd_t_038": "Artigos, vídeos e guias gratuitos selecionados sobre todos os aspectos do ensino — o melhor ponto de partida único para professores.",
    "cd_t_039": "Trilhas gratuitas estruturadas para a pedagogia moderna — por onde começar, o que ler e como evoluir sua prática docente.",
    "cd_t_040": "Guias gratuitos do The New Teacher Project — como é um ensino excelente e como construí-lo de forma sistemática.",
    "cd_t_041": "Portal gratuito de PD da National Education Association — cursos, webinars e recursos para todas as etapas da carreira.",
    "cd_t_042": "Recursos gratuitos da ASCD selecionados para professores em início de carreira — organização da sala, mentalidade e sobrevivência no primeiro ano.",
    "cd_t_043": "Recursos de aulas, artigos e fóruns gratuitos voltados a professores nos primeiros anos de docência.",
    "cd_t_044": "Pontos de partida práticos e gratuitos para novos professores — gestão de carga, estratégias de correção e como lidar com a primeira turma.",
    "cd_t_045": "Onboarding gratuito de professores na Khan Academy — configure sua sala, atribua tarefas e acompanhe o progresso desde o primeiro dia.",
    "cd_t_046": "Programa gratuito Apple Teacher autoguiado — conquiste badges em iPad, Mac e habilidades de aprendizagem criativa.",
    "cd_t_047": "Filiação associada gratuita dá acesso ao Impact journal, resumos de pesquisa e fórum comunitário para professores do Reino Unido.",
    "cd_t_048": "Aulas de leitura alinhadas a padrões para 3º a 12º ano — textos, perguntas, avaliações e unidades completas de ELA, tudo num só lugar.",
    "cd_t_049": "Currículo PK-12 gratuito de ELA e matemática do estado de Nova York — módulos anuais completos, guias do professor e cadernos do aluno.",
    "cd_t_050": "Currículos abertos top de matemática e ELA (Illustrative Math, EL Education ELA) — cursos anuais completos escritos por equipes de referência.",
    "cd_t_051": "Mais de 420.000 planos de aula, atividades e unidades gratuitos compartilhados por professores da AFT — pesquisáveis por disciplina, ano e padrão.",
    "cd_t_052": "A seção gratuita do Teachers Pay Teachers — milhões de fichas, unidades e impressos feitos por professores filtrados pela trilha sem custo.",
    "cd_t_053": "Recursos gratuitos alinhados ao currículo do Reino Unido da maior comunidade docente do mundo — esquemas completos e pacotes de aulas.",
    "cd_t_054": "Videoclipes gratuitos alinhados ao currículo e aulas prontas da BBC — fortes em história, ciências e literatura inglesa.",
    "cd_t_055": "Planejador de aulas digital gratuito com visão semanal em grade, alinhamento a padrões e visões por unidade — boa camada gratuita para professor solo.",
    "cd_t_056": "Planejador de aulas digital leve — teste gratuito de 30 dias, depois plano pago de baixo custo; visão semanal em grade adorada por professores.",
    "cd_t_057": "Biblioteca gratuita de planos de aula de professores-mestres em todo K-12 — verificados, testados em sala e alinhados ao Common Core.",
    "cd_t_058": "Biblioteca gratuita de mídia digital K-12 da PBS — mais de 100.000 vídeos, aulas e recursos interativos alinhados a padrões em todas as disciplinas.",
    "cd_t_059": "Livros didáticos digitais gratuitos personalizáveis (FlexBooks) para todas as disciplinas K-12 — adapte conteúdo, adicione notas e compartilhe com alunos.",
    "cd_t_060": "Aulas em lousa interativa e atividades prontas para professores do fundamental — grande biblioteca gratuita de ferramentas de arrastar e soltar.",
    "cd_t_061": "Crie aulas interativas combinando slides, quizzes, vídeo e enquetes — camada gratuita com milhares de aulas compartilhadas por professores.",
    "cd_t_062": "Canva Pro gratuito para professores K-12 verificados — fichas, pôsteres, vídeos, slides, animações e infográficos num só estúdio.",
    "cd_t_063": "Adobe Express gratuito para professores e alunos K-12 — flyers, posts sociais, vídeos e geração de imagens por IA para qualquer aula.",
    "cd_t_064": "Milhões de ícones gratuitos para fichas e slides — atribuição completa exigida, mas excelente qualidade e variedade.",
    "cd_t_065": "Fotos gratuitas de alta qualidade para qualquer material de aula — sem necessidade de atribuição, totalmente utilizáveis em recursos de aula.",
    "cd_t_066": "Fotos, vídeos, ilustrações e músicas gratuitas — totalmente utilizáveis em materiais de sala sem necessidade de atribuição.",
    "cd_t_067": "Fotos e vídeos gratuitos de banco curados por uma comunidade de fotógrafos — alta qualidade, totalmente livres para uso educacional.",
    "cd_t_068": "Gerador gratuito de nuvem de palavras — transforme listas de vocabulário em visuais envolventes para painéis, aquecimentos e checagens formativas.",
    "cd_t_069": "Fichas configuráveis gratuitas de matemática e leitura — gere, imprima, regenere. Sem login, um clássico docente de décadas.",
    "cd_t_070": "Gere até 7 estilos de jogo a partir de uma lista de palavras — gratuito para professores, perfeito para vocabulário e revisão.",
    "cd_t_071": "Criador de vídeos animados explicativos — camada gratuita suporta vídeos de 5 minutos com extensa biblioteca de personagens.",
    "cd_t_072": "Editor de áudio gratuito e open-source — grave podcasts, edite áudio para aulas e trabalhe com qualquer formato de som.",
    "cd_t_073": "Editor de vídeo desktop gratuito e open-source — direto o suficiente para projetos de alunos, poderoso para tutoriais de professor.",
    "cd_t_074": "Ferramenta de autoria gratuita e open-source — mais de 50 tipos de conteúdo interativo (quizzes, cenários ramificados, arrastar palavras) embedáveis em qualquer lugar.",
    "cd_t_075": "Adapte qualquer texto a qualquer nível de leitura instantaneamente — passagens niveladas, vocabulário e perguntas; a IA padrão-ouro para diferenciação.",
    "cd_t_076": "Artigos de notícias gratuitos em níveis — cada artigo disponível em 5 níveis de leitura para acesso diferenciado em todas as disciplinas.",
    "cd_t_077": "Biblioteca abrangente gratuita de leitura K-12 — milhares de passagens niveladas e textos pareados com perguntas de compreensão.",
    "cd_t_078": "Cole qualquer texto difícil — Rewordify substitui palavras complexas por mais simples no próprio texto, com definições ao passar o cursor.",
    "cd_t_079": "Impressos gratuitos alinhados ao currículo para várias idades e habilidades — adapte qualquer ficha para mais ou menos em segundos.",
    "cd_t_080": "Ferramenta gratuita da Microsoft — leia qualquer texto em voz alta com foco de linha, divisão silábica, dicionário ilustrado e mais de 60 idiomas.",
    "cd_t_081": "Conversão de texto em fala gratuita com vozes naturais — leia PDFs, páginas web e documentos Word em voz alta para apoiar o acesso à leitura.",
    "cd_t_082": "Tipografia gratuita open-source amigável a dislexia — desenhada para reduzir rotação de letras, inclui extensões para navegador.",
    "cd_t_083": "Teste gratuito de 30 dias da principal ferramenta de apoio à alfabetização — texto-fala, digitação preditiva, dicionário ilustrado.",
    "cd_t_084": "Gratuito para alunos dos EUA com deficiências de leitura — mais de 1,4M de audiolivros e ebooks acessíveis com texto-fala.",
    "cd_t_085": "O framework definitivo de Desenho Universal para a Aprendizagem — diretrizes gratuitas, exemplos e ferramentas de implementação para qualquer sala.",
    "cd_t_086": "Recursos abrangentes gratuitos para professores e pais sobre dislexia, TDAH e diferenças de aprendizagem — apoiados em pesquisa e práticos.",
    "cd_t_087": "Tarefas, aulas e ferramentas de planejamento de unidades alinhadas ao Common Core, da equipe que escreveu os padrões — ELA e matemática.",
    "cd_t_088": "Portal oficial dos Common Core State Standards — padrões completos de Língua Inglesa e Matemática, gratuitos e pesquisáveis.",
    "cd_t_089": "Portal gratuito dos Next Generation Science Standards — expectativas de desempenho, declarações de evidência e aulas exemplares.",
    "cd_t_090": "Portal gratuito dos Padrões ISTE — framework para ensino inovador com tecnologia, com descritores e rubricas.",
    "cd_t_091": "Padrões gratuitos WIDA de Desenvolvimento de Língua Inglesa — usados em mais de 40 estados dos EUA para planejamento e avaliação de ELL/EAL.",
    "cd_t_092": "Templates e artigos do Understanding by Design de Wiggins e McTighe — desenho reverso, das metas às evidências e à instrução.",
    "cd_t_093": "Rodas gratuitas de referência e verbos para a Taxonomia de Bloom revisada — escreva objetivos de ordem superior em segundos com verbos de ação.",
    "cd_t_094": "Recursos gratuitos da Taxonomia SOLO de Pam Hook — Estrutura dos Resultados de Aprendizagem Observados, para clareza de progressão nos objetivos.",
    "cd_t_095": "Frames de aulas gratuitos e reutilizáveis ligados a metas de aprendizagem — Cyber Sandwich, Iron Chef, Worst Preso Ever e mais.",
    "cd_t_096": "Biblioteca gratuita de recursos educacionais abertos — mais de 50.000 aulas, unidades e cursos completos marcados por padrão.",
    "cd_t_097": "Maior repositório gratuito de OER — mais de 70.000 recursos marcados por Common Core, NGSS e padrões estaduais, além de avaliações de qualidade.",
    "cd_t_098": "Banco de dados gratuito de John Hattie com mais de 320 influências no rendimento estudantil, classificadas por tamanho de efeito — escolha estratégias de alto impacto.",
    "cd_t_099": "Aulas em slides interativos com enquetes, quizzes, desenhos e VR integrados — camada Silver gratuita cobre a maioria das necessidades de sala.",
    "cd_t_100": "Insira perguntas e notas diretamente em qualquer vídeo — gratuito para professores (até 20 vídeos armazenados) com analytics completas.",
    "cd_t_101": "Gravação de tela ilimitada e gratuita para professores verificados — grave vídeos para aula invertida com engajamento integrado do espectador.",
    "cd_t_102": "Ferramenta de screencasting gratuita com legendas amigáveis para sala e hospedagem fácil — usada por milhões de educadores.",
    "cd_t_103": "Display de sala completo e gratuito — timer, sorteador de nomes, semáforo, símbolos de trabalho e medidor de ruído numa só tela.",
    "cd_t_104": "Ferramenta gratuita de curadoria — organize vídeos, artigos, tweets e trabalhos de alunos em coleções compartilháveis para qualquer aula.",
    "cd_t_105": "Crie apresentações interativas, escape rooms e infográficos — camada gratuita com centenas de templates para educadores.",
    "cd_t_106": "Adicione hotspots a imagens e vídeos com texto, áudio e links — camada Basic gratuita atende uso de turmas pequenas.",
    "cd_t_107": "Aulas em vídeo K-12 gratuitas com prática por domínio — cálculo, biologia, história, finanças e preparação para o SAT, gratuitas para sempre.",
    "cd_t_108": "Vídeos educativos animados gratuitos com ferramentas de aula integradas — perguntas Pense, Aprofunde e Discuta anexadas a cada clipe.",
    "cd_t_109": "Séries gratuitas de palestras no YouTube em história, ciências, literatura e economia — produção excepcional, conduzidas por especialistas.",
    "cd_t_110": "Vídeos animados alinhados ao currículo com quizzes e mapas conceituais em todas as disciplinas K-12 — teste gratuito mais tópicos gratuitos.",
    "cd_t_111": "Software gratuito de aulas interativas para qualquer tela sensível ao toque — slides, ferramentas e templates para ensino com a turma toda, UI em inglês.",
    "cd_t_112": "Mais de 160 simulações interativas gratuitas de física, química, biologia e matemática da Universidade do Colorado — traduzidas para mais de 90 idiomas.",
    "cd_t_113": "Matemática dinâmica gratuita — geometria, álgebra, cálculo, 3D e estatística numa só ferramenta. Usada por mais de 100M de alunos no mundo.",
    "cd_t_114": "Plataforma gratuita de design 3D, simulação eletrônica e blocos de código da Autodesk — feita especificamente para salas de aula.",
    "cd_t_115": "Plataforma gratuita de programação em blocos do MIT — mais de 100M de projetos no mundo, a porta de entrada para programação para crianças a partir de 8 anos.",
    "cd_t_116": "Experimentos musicais gratuitos e divertidos do Google — Song Maker, Rhythm, Spectrogram, Kandinsky. Sem login, roda em qualquer navegador.",
    "cd_t_117": "Software gratuito open-source de notação musical — escreva, toque e imprima partituras para qualquer instrumento ou conjunto.",
    "cd_t_118": "DAW colaborativa baseada em navegador — grave podcasts e música com alunos em tempo real. Camada gratuita generosa.",
    "cd_t_119": "Software gratuito open-source profissional de pintura digital e animação — motor de pincéis abrangente, usado em escolas de arte.",
    "cd_t_120": "Planetário gratuito no navegador — mostre o céu noturno aos alunos de qualquer lugar e a qualquer hora, perfeito para aulas de astronomia.",
    "cd_t_121": "Calculadora gráfica e atividades de sala gratuitas — o padrão-ouro para visualizar funções nas aulas de matemática.",
    "cd_t_122": "Currículo gratuito de ciência da computação K-12 — Hour of Code, cursos anuais completos, AI Lab e Dance Party. Usado por mais de 60M de alunos.",
    "cd_t_123": "Globo 3D gratuito no navegador — tours Voyager de cultura, história e ciência; crie marcadores próprios para qualquer aula de geografia.",
    "cd_t_124": "Plano Education gratuito com quadros e templates ilimitados para professores verificados — a ferramenta de colaboração visual mais querida.",
    "cd_t_125": "FigJam gratuito para educadores e alunos — quadro branco colaborativo com templates encantadores e recursos de engajamento.",
    "cd_t_126": "'Mural de post-its' gratuito para postar ideias, fotos, links e áudio — três padlets gratuitos e amados por professores.",
    "cd_t_127": "Quadro branco virtual gratuito open-source com estética desenhada à mão — colaboração instantânea, sem login, criptografado de ponta a ponta.",
    "cd_t_128": "Painel instantâneo gratuito do professor — cada aluno tem seu próprio quadro branco, e o professor vê todos ao vivo.",
    "cd_t_129": "3 mapas mentais gratuitos com colaboração — ideal para mapeamento conceitual em turma e projetos em grupo.",
    "cd_t_130": "Mapas mentais públicos gratuitos e ilimitados — hierarquia visual limpa, colaboração em tempo real e incorporação de imagens.",
    "cd_t_131": "Camada educacional gratuita do quadro branco da Lucid — post-its, votação e tela infinita para brainstorming em turma.",
    "cd_t_132": "Gratuito para alunos e professores verificados de ensino superior — espaço visual colaborativo para design thinking e trabalho em grupo.",
    "cd_t_133": "Diagramação gratuita open-source — fluxogramas, diagramas ER, UML, mapas mentais. Salva direto no Drive ou OneDrive.",
    "cd_t_134": "Quadro interativo gratuito open-source para escolas — funciona com qualquer projetor ou tela interativa, sem assinatura.",
    "cd_t_135": "Quadro branco colaborativo gratuito dentro do Teams e Office — post-its, tinta, imagens e templates com salvamento automático.",
    "cd_t_136": "Mapeamento mental visual simples para salas de aula — alunos brainstormam, organizam ideias e compartilham quadros em tempo real.",
    "cd_t_137": "O clássico formato de quiz tipo show — camada Basic gratuita suporta até 40 jogadores para avaliação formativa ao vivo.",
    "cd_t_138": "Quizzes e aulas autoguiados com IA — gratuito para professores com bancos extensos de questões e modo ao vivo.",
    "cd_t_139": "Enquetes ao vivo, nuvens de palavras e perguntas e respostas do público — camada gratuita atende perfeitamente a avaliação formativa em turmas pequenas.",
    "cd_t_140": "Adicione perguntas interativas ao Google Slides ou PowerPoint — camada gratuita suporta os formatos mais queridos de avaliação formativa.",
    "cd_t_141": "Enquetes, pesquisas e perguntas e respostas em qualquer reunião ou aula — camada gratuita suporta até 100 participantes.",
    "cd_t_142": "Quizzes rápidos, exit tickets e jogo Space Race — gratuito para até 50 alunos por sala.",
    "cd_t_143": "Cartões em papel com QR e leitura por celular — avaliação formativa sem nenhum dispositivo do aluno, gratuito para até 60 cartões.",
    "cd_t_144": "Jogos de quiz com templates — match-up, anagrama, gameshow — gere qualquer atividade a partir de uma lista de palavras; gratuito até 5 salvos.",
    "cd_t_145": "Veja respostas dos alunos ao vivo enquanto digitam — desenhos, equações, parágrafos. Camada Bronze gratuita atende uso formativo central.",
    "cd_t_146": "Ferramenta gratuita de feedback instantâneo em nuvem de palavras — faça uma pergunta, alunos respondem em até 20 caracteres, veja respostas crescerem ao vivo.",
    "cd_t_147": "Enquetes de resposta ao vivo embutidas em PowerPoint ou Google Slides — camada gratuita suporta até 25 respostas por enquete.",
    "cd_t_148": "Plataforma de quiz baseada em jogo super popular entre adolescentes — partidas ao vivo ou conjuntos autoguiados. Camada gratuita atende uso completo de turma.",
    "cd_t_149": "Mais de 40 templates de widgets interativos prontos — quizzes, palavras cruzadas, exit tickets, roletas — autocorrigidos e embedáveis.",
    "cd_t_150": "O LMS gratuito padrão para milhões de professores — atribuições, correção, comunicação e compartilhamento de arquivos num só lugar.",
    "cd_t_151": "Plano educacional gratuito com classes, atribuições, OneNote class notebooks e 1TB de OneDrive por aluno.",
    "cd_t_152": "Versão gratuita do principal LMS de ensino superior — atribuições completas, correção e rubricas para professores individuais.",
    "cd_t_153": "LMS gratuito open-source usado por universidades no mundo todo — auto-hospede ou use a camada gratuita do MoodleCloud para turmas pequenas.",
    "cd_t_154": "LMS gratuito para professores individuais — atribuições, livro de notas, quizzes e comunicação com pais numa só plataforma.",
    "cd_t_155": "Livro de notas baseado em padrões usado por mais de 5M de alunos — gratuito para professores solo; planos pagos para escolas e distritos.",
    "cd_t_156": "Livro de notas e ferramenta de relatórios baseada na web — camada gratuita atende necessidades de sala; integra-se aos principais LMS.",
    "cd_t_157": "Quizzes autocorrigidos gratuitos com feedback instantâneo e analytics — o cavalo de batalha para avaliação no Google Classroom.",
    "cd_t_158": "Quizzes e pesquisas gratuitos com correção automática e lógica de ramificação — incluídos em qualquer conta Microsoft.",
    "cd_t_159": "Criador gratuito de rubricas — escolha um template, personalize critérios, imprima ou salve. Usado por professores há mais de 20 anos.",
    "cd_t_160": "Construtor gratuito de rubricas e galeria com milhares de templates compartilhados por professores — adapte e reutilize com atribuição.",
    "cd_t_161": "Sistema de informações estudantis K-12 com livro de notas e relatórios baseados em padrões — teste gratuito; muitos distritos oferecem acesso.",
    "cd_t_162": "Camada gratuita do Grammarly — sugestões de gramática, clareza e tom para a escrita dos alunos no navegador, Word e Docs.",
    "cd_t_163": "App web gratuito que destaca frases complexas, voz passiva e advérbios — escrita estudantil mais clara em segundos.",
    "cd_t_164": "Anotação gratuita de PDFs e documentos — adicione comentários, notas de voz, desenhos e adesivos diretamente nos trabalhos dos alunos em segundos.",
    "cd_t_165": "Add-on gratuito do Google Sheets para autoavaliação, avaliação por pares e por rubrica — gera feedback personalizado por aluno.",
    "cd_t_166": "Extensão gratuita do Chrome que adiciona uma barra lateral de IA ao Google Docs e Slides — feedback instantâneo, nivelamento e rubricas.",
    "cd_t_167": "Extensão gratuita de comentários por voz para Google Docs, Slides e Classroom — deixe feedback de áudio de 30 segundos em segundos.",
    "cd_t_168": "Ferramenta gratuita de feedback por voz para a escrita do aluno — vincule tags de rubrica a comentários e reutilize feedback comum entre alunos.",
    "cd_t_169": "Feedback rápido para matemática e ciências — alunos enviam o trabalho, professores comentam com banco reutilizável de feedback.",
    "cd_t_170": "Add-on gratuito do Google Docs para feedback de escrita em lote — insira comentários padrão de uma biblioteca de feedback do professor.",
    "cd_t_171": "Prática adaptativa de gramática e escrita — gratuito para professores com feedback autocorrigido em cada resposta do aluno.",
    "cd_t_172": "Ferramentas interativas gratuitas de escrita e gramática — prática adaptativa em nível de frase para 3º a 12º ano, com feedback instantâneo.",
    "cd_t_173": "Editor de estilo gratuito com mais de 25 relatórios de escrita — gramática, legibilidade, transições e palavras repetidas para escrita do aluno.",
    "cd_t_174": "Plataforma gratuita Microsoft de discussão em vídeo — alunos postam reflexões em vídeo curto; professores criam tópicos seguros em segundos.",
    "cd_t_175": "Portfólios digitais criados pelo aluno com visibilidade dos pais — camada Seesaw for Schools gratuita atende salas individuais.",
    "cd_t_176": "Alunos criam ebooks para reflexão ou projetos — gratuito para uma biblioteca de 40 livros por professor.",
    "cd_t_177": "Ferramenta gratuita da Microsoft — cada aluno recebe um caderno privado para diários e reflexões, mais uma biblioteca de conteúdo compartilhada e espaço colaborativo.",
    "cd_t_178": "Ferramenta gratuita de check-in emocional dentro do Teams for Education — alunos escolhem sentimentos; professores veem tendências de bem-estar da turma.",
    "cd_t_179": "Plataforma gratuita de criação para histórias e reflexões digitais dos alunos — combine texto, voz, vídeo e animação em uma só tela.",
    "cd_t_180": "Plano Plus gratuito para educadores verificados — diários de reflexão, registros de aprendizagem e portfólios de projetos num só workspace.",
    "cd_t_181": "Blogs gratuitos de turma e de aluno em WordPress — ótimos para diários de reflexão, com moderação do professor integrada.",
    "cd_t_182": "Linhas do tempo e histórias interativas gratuitas para reflexões e narrativas de projetos dos alunos — colaborativas e imprimíveis.",
    "cd_t_183": "Backchannel anônimo gratuito para discussão em sala — colete reflexões rápidas em texto e imagem de qualquer dispositivo.",
    "cd_t_184": "Histórias gratuitas baseadas em mapa do ArcGIS — alunos refletem sobre um tema combinando texto, fotos, vídeo e dados geográficos.",
    "cd_t_185": "Ferramenta gratuita de perguntas e respostas em vídeo para reflexão — faça uma pergunta, alunos gravam respostas curtas e a turma revê em conjunto.",
    "cd_t_186": "Painéis gratuitos para pais em todas as disciplinas K-12 — acompanhe o progresso, veja pontos fortes e fracos e compartilhe com professores.",
    "cd_t_187": "Revisão alinhada ao currículo do Reino Unido por ano escolar — guias para pais sobre como apoiar dever de casa e preparação para provas.",
    "cd_t_188": "10 questões/dia gratuitas em 8.500 habilidades — prática abrangente K-12 com relatórios de progresso amigáveis a pais.",
    "cd_t_189": "Avaliações gratuitas de todo app, jogo e filme infantil — ajude famílias a fazer escolhas de mídia inteligentes apoiadas em pesquisa.",
    "cd_t_190": "Teste gratuito de 30 dias do currículo abrangente da primeira infância — fonologia, matemática, arte e música para crianças de 2 a 8 anos.",
    "cd_t_191": "Teste gratuito do principal programa de leitura inicial — fonologia, palavras de uso frequente e livros decodificáveis para 3 a 13 anos.",
    "cd_t_192": "Prática adaptativa de matemática K-12 com torneios mundiais — testes domésticos gratuitos e acompanhamento do progresso pelos pais.",
    "cd_t_193": "Matemática gratuita baseada em jogo para 1º a 8º ano — crianças enfrentam monstros respondendo perguntas, pais recebem relatórios semanais.",
    "cd_t_194": "Plataforma gratuita de revisão GCSE/A-level para famílias do Reino Unido — cursos interativos baseados em pesquisa em ciência cognitiva.",
    "cd_t_195": "Flashcards gratuitos e modos de estudo — mais de meio bilhão de conjuntos de estudo cobrindo qualquer disciplina e currículo de prova.",
    "cd_t_196": "Impressos, fichas e pacotes de atividades gratuitos alinhados ao currículo — feitos no Reino Unido, mas usados em mais de 200 países.",
    "cd_t_197": "Mais de 40.000 ebooks, audiolivros e vídeos infantis — gratuitos para educadores verificados, baixo custo para famílias.",
    "cd_t_198": "Construa uma cultura de sala positiva — pontos, mensagens aos pais e portfólios de alunos. Gratuito para todos os professores e pais.",
    "cd_t_199": "Plataforma gamificada de gestão de sala — alunos ganham XP e poderes por bom comportamento. Camada gratuita generosa.",
    "cd_t_200": "Medidor visual de ruído de sala que se anima com o som — versão Lite gratuita é amada por professores do fundamental.",
    "cd_t_201": "Medidor visual gratuito e divertido de ruído — bolinhas saltitantes reagem ao volume da sala. Ferramenta de fundo perfeita durante trabalho em grupo.",
    "cd_t_202": "Sorteador gratuito de nomes — gire a roleta para escolher alunos com justiça. Listas salvas, cores personalizadas e sem anúncios.",
    "cd_t_203": "Cronômetros gratuitos divertidos para sala — bombas, velas, carros de corrida — mantenha as atividades no tempo com visuais envolventes.",
    "cd_t_204": "Gerador gratuito de mapa de assentos com rastreamento de pontos de comportamento — usado em milhares de escolas do Reino Unido, gratuito para professores individuais.",
    "cd_t_205": "Plataforma escolar de reforço positivo de comportamento — teste gratuito; muitos recursos gratuitos de PBIS disponíveis no site.",
    "cd_t_206": "Vídeos gratuitos de movimento e mindfulness — pausas mentais curtas comprovadamente refocam alunos K-5 no meio da aula.",
    "cd_t_207": "Saudações, atividades e ideias de mensagem gratuitas para reuniões matinais — comunidade socioemocional de sala baseada em pesquisa.",
    "cd_t_208": "Recursos SEL gratuitos e webinars semanais da organização padrão-ouro em pesquisa de aprendizagem socioemocional.",
    "cd_t_209": "O blog de ensino mais seguido do Reino Unido — estratégias práticas gratuitas para comportamento, engajamento e rotinas.",
    "cd_t_210": "Sorteador aleatório gratuito de alunos — seleção de nomes justa e animada que mantém o cold-calling imprevisível e envolvente para toda a turma.",
    "cd_t_211": "Envie mensagens unidirecionais seguras a alunos e pais — camada gratuita atende avisos diários da sala com tradução automática.",
    "cd_t_212": "Mensageiro gratuito de engajamento familiar que traduz automaticamente entre professores e pais em mais de 100 idiomas.",
    "cd_t_213": "Mensagens seguras gratuitas para pais com compartilhamento de fotos e vídeos — traduz mensagens automaticamente para mais de 35 idiomas.",
    "cd_t_214": "Comunicação gratuita com pais e agendador de reuniões — favorito da educação infantil e fundamental com compartilhamento de fotos.",
    "cd_t_215": "Newsletters de sala lindas com arrastar e soltar — camada gratuita suporta 5 newsletters com ferramentas completas de design.",
    "cd_t_216": "Plataforma de comunicação escolar com tradução automática — muitos distritos oferecem contas gratuitas de professor via planos da escola.",
    "cd_t_217": "Tradução instantânea gratuita em mais de 130 idiomas — texto, fotos, conversas e documentos para comunicação com pais.",
    "cd_t_218": "Traduções de qualidade superior ao Google para idiomas europeus — camada gratuita atende a maioria das necessidades de comunicação docente.",
    "cd_t_219": "Tradução gratuita de conversas em tempo real para reuniões com pais — celulares falam cada idioma e o app legenda ao vivo.",
    "cd_t_220": "Agendamento de reuniões, inscrições para festas de turma e listas de voluntários gratuitos — o cavalo de batalha da coordenação com os pais.",
    "cd_t_221": "Camada gratuita de e-mail (até 500 contatos) — ótima para newsletters de turma, atualizações para pais e comunicação da APM.",
    "cd_t_222": "Ferramenta gratuita Microsoft para newsletters e relatórios interativos — templates lindos, autoflow de design, sem necessidade de formatação.",
    "cd_t_223": "15GB gratuitos de armazenamento em nuvem com Docs, Sheets e Slides — compartilhe materiais e colete tarefas sem fricção.",
    "cd_t_224": "5GB gratuitos de armazenamento em nuvem com Office Online — Word, Excel, PowerPoint com controles de compartilhamento amigáveis à sala.",
    "cd_t_225": "Camada gratuita de 2GB com compartilhamento em sala e pastas colaborativas — planos educacionais com desconto disponíveis.",
    "cd_t_226": "Camada gratuita de 10GB — forte em permissões e trilhas de auditoria, popular entre administradores distritais e ensino superior.",
    "cd_t_227": "Plano Plus gratuito para educadores verificados — wikis, notas de aula, rastreadores de alunos e hubs colaborativos de sala.",
    "cd_t_228": "Banco de dados flexível gratuito — ótimo para rastrear dados de alunos, metas de IEP, portfólios de projetos e mapas curriculares.",
    "cd_t_229": "Quadros kanban gratuitos — acompanhe planejamento de aulas, projetos de alunos, comissões escolares e tarefas pessoais do professor.",
    "cd_t_230": "Gratuito para equipes de até 15 pessoas — gerencie projetos de melhoria escolar, fluxos de departamento e tarefas administrativas.",
    "cd_t_231": "Ferramenta gratuita de agendamento — compartilhe um link, pais escolhem horário para reunião de pais e mestres. Sem mais idas e voltas por e-mail.",
    "cd_t_232": "Enquete gratuita de horário de reunião para equipe e pais — descubra quando todos podem encontrar sem threads infinitas de e-mail.",
    "cd_t_233": "Workspace gratuito para equipes — canais por departamento, DMs e integrações com Drive, Calendar e mais.",
    "cd_t_234": "5GB gratuitos de armazenamento na Apple cloud com Pages, Numbers e Keynote no navegador — ótimo para salas que usam Apple.",
    "cd_t_235": "Iniciativa gratuita do app Calm para professores K-12 — acesso completo ao app, incluindo histórias para dormir, meditações e músicas.",
    "cd_t_236": "Headspace Plus gratuito para professores K-12 verificados nos EUA, Reino Unido, Canadá e Austrália — mindfulness e meditação.",
    "cd_t_237": "App de meditação gratuito com a maior biblioteca grátis — mais de 200.000 meditações guiadas e trilhas específicas para professores.",
    "cd_t_238": "Artigos, práticas guiadas e pesquisa gratuitos sobre mindfulness — introdução acessível para professores estressados.",
    "cd_t_239": "Recursos gratuitos SEL baseados em ciência da Berkeley para professores — práticas de gratidão, gentileza e resiliência em sala.",
    "cd_t_240": "Podcast e artigos gratuitos de Daniela Falecki — estratégias práticas de bem-estar e prevenção de burnout para professores.",
    "cd_t_241": "Instituição beneficente do Reino Unido — linha gratuita 24/7, aconselhamento e recursos de saúde mental para qualquer professor, em qualquer país.",
    "cd_t_242": "Movimento global gratuito de encontros de apoio à saúde mental docente — mais de 100 capítulos no mundo, online e presenciais.",
    "cd_t_243": "Artigos e episódios de podcast gratuitos de Jennifer Gonzalez sobre autocuidado docente — práticos, honestos, sem positividade tóxica.",
    "cd_t_244": "Blog gratuito com estratégias realistas para gerenciar estresse, pais e administração — escrito por professores de sala.",
    "cd_t_245": "Kits gratuitos da MHA — autoavaliação de burnout, estratégias de enfrentamento baseadas em evidências e diretórios de apoio em crise.",
    "cd_t_246": "Programa gratuito interativo de terapia cognitivo-comportamental — autoajuda comprovada para estresse e humor baixo, usada no mundo todo.",
    "cd_t_247": "Mais de 60 ferramentas de IA criadas por professores — planos de aula, metas IEP, rubricas, diferenciação e feedback. Camada gratuita generosa para educadores.",
    "cd_t_248": "Aulas interativas geradas por IA em 30 segundos — slides, enquetes, desenhos e exit tickets, com plano gratuito robusto para professores.",
    "cd_t_249": "Mais de 100 geradores para planos de aula, avaliações e adaptações — camada gratuita atende a maioria das necessidades cotidianas em sala.",
    "cd_t_250": "'Espaços' de chat de IA seguros e monitorados para alunos, mais um assistente de IA para professores — camada gratuita generosa para K-12.",
    "cd_t_251": "Assistente de IA principal da Anthropic — excepcional para planejamento de aulas, escrita de rubricas, e-mails para pais e rascunhos de feedback.",
    "cd_t_252": "Camada gratuita da OpenAI cobre GPT-4o mini — forte para geração de questões, resumos e criação de fichas.",
    "cd_t_253": "IA do Google profundamente integrada a Docs, Slides e Drive — ideal para professores que já vivem no Google Workspace.",
    "cd_t_254": "IA gratuita dentro do Word, OneNote, PowerPoint — gere esboços de aula, decks e materiais para alunos no próprio app.",
    "cd_t_255": "Carregue capítulos do livro didático e suas notas — a IA do Google responde estritamente a partir das suas fontes, com resumos em áudio para revisão.",
    "cd_t_256": "Curso gratuito da Anthropic sobre as quatro competências centrais de IA — delegação, descrição, discernimento, diligência. Feito para educadores.",
    "cd_t_257": "Tutor de IA gratuito da Khan Academy para professores — planejamento de aulas, e-mails para pais e tutoria socrática para alunos em todas as disciplinas K-12.",
    "cd_t_258": "Mecanismo de busca com IA que cita cada afirmação — perfeito quando professores precisam de fontes verificáveis, não respostas alucinadas.",
    "cd_t_259": "Cole qualquer texto, obtenha perguntas essenciais alinhadas e objetivos de aprendizagem mais quizzes autogerados — camada gratuita ilimitada.",
    "cd_t_260": "Guia gratuito do Teacher Development Trust — pesquisa sobre quais práticas de desenvolvimento profissional realmente melhoram ensino e resultados.",
    "cd_t_261": "Os padrões globais de aprendizagem profissional eficaz — um framework claro para avaliar e planejar seu próprio CPD.",
    "cd_t_262": "Artigos, vídeos e guias de PD gratuitos selecionados sobre todos os aspectos do ensino — o melhor ponto de partida tudo-em-um.",
    "cd_t_263": "Trilhas estruturadas gratuitas para a pedagogia moderna — o que ler, assistir e experimentar conforme evolui sua prática.",
    "cd_t_264": "Toolkit gratuito da Education Endowment Foundation — estratégias avaliadas por evidência com orientação clara sobre onde focar.",
    "cd_t_265": "Guias gratuitos do The New Teacher Project sobre como é um ensino eficaz e como construí-lo passo a passo.",
    "cd_t_266": "Pesquisa semanal de 3 perguntas + recursos de PD — veja como milhares de colegas pensam e compare com sua própria prática.",
    "cd_t_267": "Comece por você — MOOC gratuito de Barbara Oakley sobre memória, chunking e foco. Essencial antes de desenhar aprendizagem para outros.",
    "cd_t_268": "Introdução gratuita ao Ciclo Reflexivo de Gibbs e outros modelos — transforme suas experiências docentes em crescimento estruturado.",
    "cd_t_269": "Portal gratuito de PD da National Education Association — cursos, webinars e recursos mapeados para todas as etapas da carreira.",
    "cd_t_270": "Filiação associada gratuita — acesso ao Impact journal, resumos de pesquisa e comunidade de ensino para professores baseados em evidência.",
    "cd_t_271": "Cursos gratuitos da Open University em educação — ensino inclusivo, mentoria e liderança escolar. Sem requisitos de entrada.",
    "cd_t_272": "Audite cursos de Stanford, Penn e Johns Hopkins gratuitamente — certificados pagos disponíveis, mas todo o conteúdo é gratuito.",
    "cd_t_273": "Cursos de educação de Harvard, MIT e HarvardX — gratuitos para auditar, com MicroMasters pagos opcionais para liderança escolar.",
    "cd_t_274": "Cursos curtos gratuitos de universidades do Reino Unido — pedagogia prática, EdTech e CPD por disciplina.",
    "cd_t_275": "Treinamento gratuito que leva aos exames Google Certified Educator Nível 1 e 2 — credencial de tecnologia educacional reconhecida globalmente.",
    "cd_t_276": "Badges gratuitos do Microsoft Innovative Educator — Teams, OneNote, Minecraft Edu, ferramentas de IA e colaboração global.",
    "cd_t_277": "Programa gratuito autoguiado Apple Teacher — conquiste badges Swift e credenciais de criatividade em sala.",
    "cd_t_278": "Certificados gratuitos credenciados de ensino e educação — gestão de sala, necessidades especiais, primeira infância e mais.",
    "cd_t_279": "Cursos gratuitos da OU com declarações de participação — ensino inclusivo, mentoria, liderança escolar e habilidades digitais.",
    "cd_t_280": "Materiais completos de cursos do MIT disponíveis gratuitamente — vídeos de aulas, problemas e notas de ensino das aulas reais do MIT.",
    "cd_t_281": "Cursos gratuitos credenciados de nível universitário — conclua cursos completos e receba históricos sem custo.",
    "cd_t_282": "Certificação gratuita Common Sense Educator em cidadania digital — prática e reconhecida internacionalmente.",
    "cd_t_283": "Webinars, artigos e PD gratuitos da ISTE — a principal organização de EdTech do mundo, com filiação à comunidade incluída.",
    "cd_t_284": "Recurso padrão-ouro de aprendizagem baseada em projetos — kits iniciais gratuitos, rubricas e bibliotecas de projetos da autoridade global em PBL.",
    "cd_t_285": "Recursos gratuitos sobre desenho de sala invertida — como gravar, inverter e aproveitar melhor o tempo em sala para aprendizagem ativa.",
    "cd_t_286": "Guia gratuito da NSTA para ciência baseada em investigação — como passar da demonstração à investigação conduzida pelo aluno.",
    "cd_t_287": "Artigos introdutórios gratuitos sobre Estruturas Kagan — Pense-Pareie-Compartilhe, Jigsaw e mais de 200 técnicas de aprendizagem cooperativa.",
    "cd_t_288": "Diretrizes gratuitas de Desenho Universal para a Aprendizagem — como desenhar cada aula para funcionar para toda a faixa de alunos.",
    "cd_t_289": "Toolkit educador gratuito da IDEO — aplique design thinking centrado no humano a desafios de sala e à criação de aulas.",
    "cd_t_290": "Mais de 30 rotinas de pensamento do Project Zero de Harvard — protocolos estruturados que aprofundam o pensamento dos alunos em qualquer disciplina.",
    "cd_t_291": "Recursos gratuitos da ASCD sobre instrução diferenciada — como gerar tarefas em níveis, agrupamento flexível e ajuste de ritmo para cada aluno.",
    "cd_t_292": "Recursos instrucionais gratuitos da Expeditionary Learning — caráter, hábitos de trabalho e avaliação por domínio em ação.",
    "cd_t_293": "Mais de 250 tamanhos de efeito — descubra quais métodos de ensino têm o maior impacto no rendimento estudantil e por quê.",
    "cd_t_294": "Videoteca gratuita de técnicas de sala — cold call, no opt out, checagem de compreensão e mais de 60 outras estratégias.",
    "cd_t_295": "Artigos práticos sobre como fazer cada grande abordagem de ensino — com exemplos em vídeo e dicas de implementação.",
    "cd_t_296": "Tarefas gratuitas de enriquecimento matemático de Cambridge — problemas ricos que desenvolvem raciocínio, não apenas cálculo. Pesquisáveis por idade e tópico.",
    "cd_t_297": "Recursos gratuitos de ensino de leitura — estratégias, orientação fonológica, ferramentas de fluência e recursos de engajamento familiar.",
    "cd_t_298": "Simulações interativas gratuitas de ciências e matemática da Universidade do Colorado — guias do professor para cada simulação incluídos.",
    "cd_t_299": "Recursos gratuitos de implementação dos Next Generation Science Standards — unidades em storyline, fenômenos e guias de ensino tridimensional.",
    "cd_t_300": "Aulas gratuitas de geografia, ciência e história da National Geographic — mapas, vídeos, artigos e guias do professor.",
    "cd_t_301": "Plataforma gratuita de ELA para professores — textos alinhados a padrões, perguntas de discussão e avaliações para 3º a 12º ano.",
    "cd_t_302": "Milhares de recursos gratuitos de ensino de inglês — poesia, drama, escrita criativa e preparação para provas para professores do ensino médio.",
    "cd_t_303": "Recursos gratuitos de ensino de história da principal revista de história do Reino Unido — artigos, fontes documentais e ideias de aula.",
    "cd_t_304": "Recursos gratuitos de ensino de química da Royal Society of Chemistry — planos de aula, CPD e guias práticos.",
    "cd_t_305": "Quebra-cabeças e problemas matemáticos desafiadores gratuitos não resolvidos para K-12 — desenhados para criar belos desafios e pensamento profundo.",
    "cd_t_306": "Aulas animadas TED-Ed selecionadas em todas as disciplinas — ferramentas gratuitas de planejamento, guias de discussão e quizzes.",
    "cd_t_307": "Fotos e estímulos gratuitos para inspirar a escrita — use trabalhos publicados de alunos como modelos para elevar padrões de escrita.",
    "cd_t_308": "Recursos gratuitos de Jim Knight sobre o ciclo de impacto — framework apoiado em pesquisa para coaching docente e autoaperfeiçoamento.",
    "cd_t_309": "Recursos gratuitos de mentoria do NTC — como estruturar conversas de mentoria, observar com eficácia e dar feedback útil.",
    "cd_t_310": "Recursos gratuitos da ASCD sobre liderança docente — como liderar a partir da sala sem um cargo formal.",
    "cd_t_311": "Artigos e vídeos gratuitos sobre coaching instrucional — observação por pares, ciclos de feedback e construção de uma cultura de coaching.",
    "cd_t_312": "Recursos gratuitos sobre como construir uma comunidade de aprendizagem profissional — como líderes docentes impulsionam a melhoria de toda a escola.",
    "cd_t_313": "National Board for Professional Teaching Standards — recursos gratuitos de preparação para a credencial docente padrão-ouro.",
    "cd_t_314": "Padrões gratuitos para aprendizagem profissional — como desenhar e liderar CPD que realmente melhora ensino e resultados.",
    "cd_t_315": "Recursos gratuitos Teach Like a Champion para líderes instrucionais — frameworks de observação, ferramentas de feedback e vídeos de coaching.",
    "cd_t_316": "Recursos gratuitos para educadores assumindo liderança — mapeamento curricular, planejamento colaborativo e construção de comunidade.",
    "cd_t_317": "Guias gratuitos para média liderança — gestão para cima, liderança de equipe, gestão de carga e como conduzir conversas difíceis.",
    "cd_t_318": "Recursos gratuitos de liderança da Education Week — pesquisa, estudos de caso e análise de políticas para líderes docentes e diretores.",
    "cd_t_319": "Framework gratuito de padrões ISTE para líderes de EdTech — um roteiro para liderar a aprendizagem digital em qualquer escola ou distrito.",
    "cd_t_320": "O padrão-ouro — avaliações gratuitas baseadas em evidência para mais de 50 estratégias de ensino, com tamanho de efeito, custo e orientação de implementação.",
    "cd_t_321": "Os mais de 250 tamanhos de efeito de Hattie sobre rendimento estudantil — entenda quais estratégias funcionam e quais são mitos da educação.",
    "cd_t_322": "Palestras de conferências gratuitas, posts de blog e uma comunidade global dedicada a melhorar a alfabetização em pesquisa na educação.",
    "cd_t_323": "Avaliações gratuitas do Departamento de Educação dos EUA sobre intervenções educacionais — classificações de evidência rigorosas e imparciais para programas e práticas.",
    "cd_t_324": "Resumos gratuitos de estratégias de estudo baseadas em evidência — prática espaçada, recuperação, intercalação e mais, explicados para professores.",
    "cd_t_325": "Artigos gratuitos do cientista cognitivo sobre por que alunos pensam e aprendem como pensam — diretamente aplicáveis ao desenho de aulas.",
    "cd_t_326": "Relatórios e resumos gratuitos de pesquisa do NFER — pesquisa educacional independente e rigorosa do Reino Unido sobre ensino, bem-estar e liderança.",
    "cd_t_327": "Pesquisa educacional gratuita da Brookings Institution — análise de políticas baseada em evidência e resumos de pesquisa voltados a professores.",
    "cd_t_328": "Pesquisa gratuita da RAND sobre eficácia docente, currículo e sistemas educacionais — rigorosa, revisada por pares e gratuita.",
    "cd_t_329": "Pesquisa traduzida em prática de sala — cada artigo declara claramente a base de evidência e os passos de implementação.",
    "cd_t_330": "Recursos gratuitos de Marzano sobre estratégias instrucionais — nove estratégias de alto rendimento fundamentadas em 35 anos de pesquisa em sala.",
    "cd_t_331": "Hub gratuito de pesquisa educacional do governo dos EUA — banco ERIC, guias práticos e What Works Clearinghouse num só lugar.",
    "cd_t_332": "Pesquisa diária de 3 perguntas + conteúdo semanal de PD — veja como mais de 10.000 colegas respondem e compare com seus próprios pontos de vista.",
    "cd_t_333": "Fóruns gratuitos para todas as disciplinas e idades — compartilhamento de recursos, threads de conselhos e discussões de carreira de uma comunidade global.",
    "cd_t_334": "A maior PLN docente informal do mundo — #EduTwitter, #EduChat e centenas de hashtags de disciplina conectam educadores globalmente.",
    "cd_t_335": "Discussão docente anônima e honesta — conversa real sobre carga, comportamento, administração e o que realmente funciona em sala.",
    "cd_t_336": "Comunidade global gratuita de professores baseados em evidência — conferências anuais, eventos regionais e discussões online.",
    "cd_t_337": "Unconferences docentes informais e gratuitas — compartilhamentos professor-a-professor de 7 e 2 minutos, locais e online no mundo todo.",
    "cd_t_338": "Google Educator Groups locais e online em mais de 100 países — aprendizagem profissional, eventos e apoio entre pares para professores que usam Google.",
    "cd_t_339": "Comunidade gratuita Microsoft de educadores — compartilhe aulas, conquiste badges e conecte-se com inovadores que usam ferramentas Microsoft na educação.",
    "cd_t_340": "Comunidade gratuita de blogs e discussão da Edutopia — compartilhe sua história docente e leia o que funciona em salas pelo mundo.",
    "cd_t_341": "Rede gratuita de filiados da National Education Association — conexões profissionais, ferramentas de advocacy e apoio entre pares para professores dos EUA.",
    "cd_t_342": "Grupos gratuitos de educadores no LinkedIn — networking profissional, desenvolvimento de carreira e liderança intelectual em educação.",
    "cd_t_343": "Rede de educadores da ISTE — espaços comunitários gratuitos, grupos de interesse especial e discussões sobre EdTech e aprendizagem inovadora.",
}
