PT_STUDENTS = {
    "cd_000": "App premiado de alfabetização inicial — letras, fonética, histórias e escrita, tudo gratuito e sem anúncios.",
    "cd_001": "Atores famosos leem livros infantis em voz alta — vídeos lindos que desenvolvem a escuta e a leitura desde cedo.",
    "cd_002": "40.000+ livros digitais, audiolivros e leituras guiadas — gratuito para professores durante o horário escolar.",
    "cd_003": "Milhares de textos de leitura de alta qualidade com perguntas de compreensão, todos gratuitos para K-12.",
    "cd_004": "Biblioteca digital gratuita com 2.000+ textos de ficção e não-ficção, com leitura guiada, discussão e avaliação.",
    "cd_005": "Prática adaptativa de gramática e escrita baseada nos interesses de cada aluno — versão básica gratuita.",
    "cd_006": "Aulas estruturadas de inglês, vídeos e quizzes para o ensino fundamental e médio, gratuitos e sem anúncios.",
    "cd_007": "Construtor de vocabulário adaptativo — aprende o que você sabe e testa o que falta; ótimo para preparação SAT.",
    "cd_008": "Os alunos viram autores — escreva, ilustre e publique seus próprios livros digitais direto no navegador.",
    "cd_009": "Assistente de escrita por IA que detecta erros de gramática, ortografia e clareza — o plano gratuito basta para alunos.",
    "cd_010": "70.000+ ebooks gratuitos de domínio público — literatura clássica, poesia e não-ficção, totalmente grátis para baixar.",
    "cd_011": "Atividades interativas e gratuitas de escrita e gramática — feedback imediato sobre construção de frases e revisão.",
    "cd_012": "Fonética, músicas e atividades de leitura inicial — site gratuito amado há anos por leitores iniciantes.",
    "cd_013": "Biblioteca gratuita de e-books da Oxford — centenas de livros nivelados com narração em áudio.",
    "cd_014": "Aventura premiada de fonética — gratuita na web e adotada por escolas no mundo todo.",
    "cd_015": "App de idiomas mais popular do mundo — vocabulário, gramática e leitura gamificados, gratuito com anúncios.",
    "cd_016": "Jogos gratuitos de leitura e alfabeto com personagens da PBS que as crianças já adoram.",
    "cd_017": "Uma \"Maravilha do Dia\" diária — leituras curtas de não-ficção que despertam curiosidade e ampliam o vocabulário.",
    "cd_018": "Treinador de escrita no navegador que destaca frases longas e voz passiva — refina o estilo.",
    "cd_019": "Vídeos e jogos gratuitos do alfabeto — Big Bird e amigos ensinam letras para crianças de 3 a 5 anos.",
    "cd_020": "Recursos gratuitos de alfabetização da PBS — dicas de leitura, artigos e atividades imprimíveis para K-3.",
    "cd_021": "Currículo K-12 completo com videoaulas, prática adaptativa e acompanhamento por domínio — referência em matemática gratuita.",
    "cd_022": "Contagem, formas e numeracia inicial por meio de atividades lúdicas — o primeiro app de matemática perfeito para os pequenos.",
    "cd_023": "Calculadora gráfica linda, calculadora científica e atividades interativas de sala — um clássico moderno.",
    "cd_024": "Ferramentas dinâmicas de geometria, álgebra, estatística e gráficos 3D — gratuito em qualquer navegador.",
    "cd_025": "Livros didáticos interativos e um espaço virtual de manipuláveis — lúdico, visual e alinhado a padrões.",
    "cd_026": "Série em formato de jogo que ensina álgebra e números sem que se perceba — as crianças resolvem equações sem saber.",
    "cd_027": "RPG gamificado de matemática que se adapta ao nível de cada aluno e segue o currículo escolar.",
    "cd_028": "Centenas de jogos gratuitos de matemática, quebra-cabeças lógicos e atividades de resolução de problemas para o fundamental.",
    "cd_029": "Mecanismo computacional que resolve — e explica — qualquer problema de matemática, de equações a cálculo.",
    "cd_030": "Livros didáticos digitais gratuitos e adaptativos com prática, vídeos e trilhas personalizadas \"FlexMath\".",
    "cd_031": "Cursos interativos de resolução de problemas em matemática — primeiros capítulos gratuitos em dezenas de tópicos.",
    "cd_032": "Vídeos animados de matemática deslumbrantes que tornam cálculo, álgebra linear e probabilidade visualmente claros.",
    "cd_033": "Jogos de contagem, formas e numeracia inicial com personagens favoritos da PBS — totalmente gratuito.",
    "cd_034": "Videoaulas animadas gratuitas que cobrem desde aritmética até álgebra.",
    "cd_035": "Biblioteca gratuita de problemas matemáticos ricos da Universidade de Cambridge para todas as idades.",
    "cd_036": "Centenas de jogos gratuitos de matemática para a pré-escola até o 6º ano — versão web com anúncios.",
    "cd_037": "Programa de matemática interativo alinhado ao currículo — gratuito em casa com contas de professor.",
    "cd_038": "Apps gratuitos para web e iPad — ábaco, reta numérica, geoplano e ferramentas de frações.",
    "cd_039": "Tarefas matemáticas abertas e gratuitas de Stanford — visuais, criativas e formadoras de mentalidade.",
    "cd_040": "Jogos gratuitos de resolução de problemas matemáticos com Peg + Cat — contagem, formas e padrões.",
    "cd_041": "Série gratuita da BBC sobre contagem com jogos — transforma números em personagens para crianças de 3 a 6 anos.",
    "cd_042": "Cursos gratuitos de matemática de graduação do MIT — cálculo, álgebra linear e mais, com aulas completas.",
    "cd_043": "Acesso gratuito como ouvinte a cursos de matemática de universidades de ponta — provas, estatística, cálculo.",
    "cd_044": "Manipuláveis virtuais e jogos gratuitos, sem anúncios, para o início do fundamental — fichas, frações e mais.",
    "cd_045": "150+ simulações interativas de ciências da Universidade do Colorado — o melhor laboratório gratuito do mundo no navegador.",
    "cd_046": "Aulas práticas de \"mistério\" científico para o fundamental — vídeo, atividade prática e discussão em cada unidade.",
    "cd_047": "Site gratuito da NASA para crianças — jogos, atividades e vídeos sobre clima, Terra e espaço.",
    "cd_048": "Vídeos curtos, divertidos e cheios de fatos científicos para crianças pequenas — perfeitos para responder a cada \"por quê\".",
    "cd_049": "Livros didáticos digitais gratuitos cobrindo física, química, biologia, ciências da Terra e mais — com prática adaptativa inclusa.",
    "cd_050": "Filmes deslumbrantes de biologia, atividades de análise de dados e aulas do Howard Hughes Medical Institute.",
    "cd_051": "Vídeos curtos e energéticos de ciências para os 5º e 6º anos — vida, Terra, ciências físicas e do espaço.",
    "cd_052": "Aulas estruturadas de ciências para o fundamental e médio — vídeos, quizzes e guias de revisão.",
    "cd_053": "Atividades práticas e demonstrações em vídeo do lendário museu de ciências de São Francisco.",
    "cd_054": "Cursos de física, química, biologia e alinhados ao NGSS, com prática, vídeos e artigos — tudo gratuito.",
    "cd_055": "Aulas, atividades, dados e desafios direto da NASA — de foguetes ao clima e exoplanetas.",
    "cd_056": "Recursos científicos com qualidade de museu — milhões de espécimes, imagens e coleções de aulas, tudo gratuito.",
    "cd_057": "Jogos científicos gratuitos com SciGirls, Wild Kratts e mais — investigação divertida para 4 a 8 anos.",
    "cd_058": "Fatos curiosos, experimentos e vídeos de animais — desperta a curiosidade de bebês a pré-adolescentes.",
    "cd_059": "Noções de clima e espaço explicadas com jogos e vídeos — gratuito da NASA e da NOAA.",
    "cd_060": "Investigações no estilo museu e ciência criativa — gratuito e sem anúncios para 5 a 12 anos.",
    "cd_061": "Enciclopédia infantil de todos os temas científicos — gratuita, segura e escrita com clareza.",
    "cd_062": "Laboratórios virtuais, vídeos e estudos de caso criados por cientistas em atuação — gratuito.",
    "cd_063": "Acesso gratuito como ouvinte a cursos universitários de ciências do MIT, Harvard e mais.",
    "cd_064": "Cursos gratuitos de ciências de graduação do MIT — biologia, química e física com aulas completas.",
    "cd_065": "Acesso gratuito como ouvinte a cursos universitários de física, química e ciências da Terra.",
    "cd_066": "Explore o planeta em 3D impressionante com tours guiados \"Voyager\" — história, cultura e natureza ao alcance.",
    "cd_067": "300+ quizzes gratuitos de geografia — países, capitais, bandeiras, rios, montanhas e mais.",
    "cd_068": "Geografia, culturas, animais e aventuras para crianças, da National Geographic — gratuito online.",
    "cd_069": "Série de história rápida, espirituosa e cheia de fatos do John Green — mundial, europeia, dos EUA e mais.",
    "cd_070": "Aulas estruturadas de história para o fundamental e médio — romanos, Tudors, guerras mundiais e história global.",
    "cd_071": "Jogos e aulas gratuitas de civismo fundadas pela juíza O'Connor — entenda como o governo funciona jogando.",
    "cd_072": "\"Reading Like a Historian\" — aulas gratuitas de investigação que ensinam fontes, corroboração e argumentação.",
    "cd_073": "Curso interdisciplinar de 13,8 bilhões de anos — do Big Bang ao futuro da humanidade.",
    "cd_074": "Artigos, mapas, linhas do tempo e vídeos de história, gratuitos e revisados por pares, cobrindo todos os continentes e eras.",
    "cd_075": "Fontes primárias prontas para a sala — fotos históricas, cartas, mapas e áudios — todas gratuitas para uso.",
    "cd_076": "Milhares de atividades e artefatos históricos gratuitos dos museus do Smithsonian.",
    "cd_077": "Ferramenta gratuita do Arquivo Nacional dos EUA para ensinar com documentos e fotos primárias.",
    "cd_078": "Artigos infantis sobre cada civilização, com linhas do tempo, jogos e quizzes.",
    "cd_079": "Mapas e jogos comunitários gratuitos — geografia inicial e civismo para os pequenos.",
    "cd_080": "Egito antigo, vikings, impérios — artigos ilustrados e vídeos para crianças de 5 a 12 anos.",
    "cd_081": "Atlas interativo da história mundial — veja qualquer região em qualquer ponto entre 3500 a.C. e hoje.",
    "cd_082": "Artigos de história claros e precisos escritos para crianças — cobre todas as épocas.",
    "cd_083": "Coleções gratuitas de fontes primárias com ideias de aulas — manuscritos, mapas e mais.",
    "cd_084": "Acesso gratuito como ouvinte a cursos de história de Harvard, Columbia e outras universidades de ponta.",
    "cd_085": "Jogos gratuitos que apresentam bairros, profissões e civismo básico para a pré-escola.",
    "cd_086": "Kit gratuito que ensina comunidade, família e cultura para crianças de 3 a 5 anos.",
    "cd_087": "Enciclopédia infantil DK gratuita — civilizações antigas, exploradores e linhas do tempo.",
    "cd_088": "Artigos de história em estilo de revista, com ilustrações vivas, gratuitos para os mais novos.",
    "cd_089": "Linguagem de programação em blocos do MIT — a forma mais popular do mundo de crianças criarem jogos, arte e histórias.",
    "cd_090": "Currículo K-12 completo de ciência da computação — Hour of Code, CS Fundamentals, cursos AP — tudo gratuito.",
    "cd_091": "Programação só para tablet, para crianças de 5 a 7 anos — arraste figuras para dar vida a personagens. Sem leitura.",
    "cd_092": "Cursos de programação em estilo aventura que avançam de blocos para Python e JavaScript passo a passo.",
    "cd_093": "JavaScript, HTML/CSS, SQL e teoria de ciência da computação — aulas interativas com feedback instantâneo.",
    "cd_094": "Lendário curso introdutório de ciência da computação de Harvard — totalmente gratuito no edX, com certificado real.",
    "cd_095": "3.000+ horas de treinamento prático gratuito em web dev, análise de dados e ML — com certificações que ficam com você.",
    "cd_096": "Ambiente de programação no navegador para 50+ linguagens — sem instalação, colabore como no Google Docs.",
    "cd_097": "Editor online gratuito (blocos + Python) para programar um pequeno computador físico — milhares de projetos grátis.",
    "cd_098": "Aprenda Python e JavaScript jogando um RPG — resolva fases digitando código de verdade.",
    "cd_099": "Referência amigável de web dev com milhares de editores ao vivo \"Try It Yourself\" — HTML, CSS, JS, Python, SQL.",
    "cd_100": "\"Katas\" curtos de programação em 50+ linguagens — afie a resolução de problemas com desafios reais.",
    "cd_101": "Apresenta conceitos de programação para K-2 com personagens \"fuzz\" amigáveis — versão lite gratuita.",
    "cd_102": "Quebra-cabeça gratuito no navegador que ensina sequências, loops e condicionais — funciona do K ao 12.",
    "cd_103": "Série gratuita do Google de quebra-cabeças de programação que vai do arrastar de blocos ao JavaScript.",
    "cd_104": "Jogos de programação gratuitos com programas amados da PBS — primeiro contato com a lógica da programação.",
    "cd_105": "Tutoriais de programação de uma hora para todas as idades — de Minecraft a Python, todos gratuitos.",
    "cd_106": "Aulas curtas no celular em Python, JS, SQL — comunidade gratuita de programação social.",
    "cd_107": "Aulas interativas de programação no navegador — o plano gratuito cobre Python, HTML/CSS e fundamentos de JS.",
    "cd_108": "App gratuito para introduzir à programação — arraste comandos para fazer Daisy dançar. Ideal para a pré-escola.",
    "cd_109": "Aulas gratuitas para K-2 que constroem hábitos de digitação e pensamento computacional.",
    "cd_110": "Bee-Bot online gratuito — uma abelha programável que ensina sequências aos programadores mais jovens.",
    "cd_111": "Currículo K-12 gratuito de cidadania digital — privacidade, segurança, alfabetização midiática e IA, por faixa etária.",
    "cd_112": "Ensine uma IA a classificar a vida marinha — primeiro contato das crianças com aprendizado de máquina supervisionado e viés.",
    "cd_113": "Jogo gratuito \"Interland\" do Google e materiais de aula sobre segurança na internet, gentileza e privacidade.",
    "cd_114": "Currículo gratuito do MIT \"Everyday Ethics\" e alfabetização em IA para o fundamental e médio — viés, justiça, agência.",
    "cd_115": "MOOC gratuito da Universidade de Helsinki e Reaktor — o que a IA realmente é, em linguagem simples.",
    "cd_116": "Treine seu próprio modelo de machine learning com imagens, sons ou poses — direto no navegador, sem código.",
    "cd_117": "Cursos curtos e gratuitos do Andrew Ng sobre LLMs, prompts e IA moderna — a forma mais rápida de evoluir.",
    "cd_118": "Centro canadense de alfabetização digital e midiática — jogos, aulas e recursos contra a desinformação.",
    "cd_119": "O quadro europeu de competências digitais — um checklist das habilidades digitais que todo adulto precisa.",
    "cd_120": "Atividades gratuitas de IA do MIT para K-12 — experiências de um dia em sala sobre viés, IA generativa e mais.",
    "cd_121": "Tutor de IA da Khan Academy que nunca entrega a resposta — peça para ele debater, ensinar ou questionar você.",
    "cd_122": "Videoaulas gratuitas sobre tarefas digitais do dia a dia — documentos, planilhas, slides, pesquisa, orçamento e mais.",
    "cd_123": "Extensão gratuita do Scratch — treine modelos com texto, imagens ou números e use-os em jogos.",
    "cd_124": "Aulas e projetos de IA selecionados para K-12 — o nível gratuito cobre os módulos introdutórios.",
    "cd_125": "Aulas gratuitas K-12 sobre como a IA funciona, viés, deepfakes e uso responsável.",
    "cd_126": "Módulos gratuitos de IA com aulas \"unplugged\", vídeos e atividades de treinamento para o 3º ao 12º ano.",
    "cd_127": "Jogo divertido de 20 segundos para desenhar que mostra como uma rede neural reconhece seus rabiscos.",
    "cd_128": "Experimentos lúdicos no navegador que desmistificam o aprendizado de máquina — todos gratuitos, sem cadastro.",
    "cd_129": "Guia gratuito para alunos sobre como usar a IA com ética na escola — tópicos de conversa e dicas.",
    "cd_130": "Aulas introdutórias gratuitas sobre o que é IA para crianças de 5 a 7 anos — usa músicas e histórias.",
    "cd_131": "App criador gratuito onde os menores constroem histórias interativas — primeiros hábitos de pensamento em IA.",
    "cd_132": "Jogos gratuitos que constroem fundamentos para IA/CS — padrões, previsões e decisões para 4 a 8 anos.",
    "cd_133": "Cursos interativos de resolução de problemas em lógica, probabilidade, CS e mais — a melhor academia para pensadores.",
    "cd_134": "Aulas animadas curtas com perguntas e debates — uma biblioteca de momentos \"aha\" que expandem a mente.",
    "cd_135": "Cursos em vídeo inteligentes, divertidos e ágeis sobre filosofia, estatística, técnicas de estudo e como pensar.",
    "cd_136": "Vídeos científicos premiados que mostram curiosidade, equívocos e resolução de problemas reais.",
    "cd_137": "Livros, vídeos gratuitos e o renomado treinador adaptativo Alcumus — resolução de problemas estilo olimpíadas de matemática.",
    "cd_138": "Vídeos animados de conceitos em todas as disciplinas com quizzes que avaliam o entendimento real.",
    "cd_139": "Artigos reais de atualidades em 5 níveis de leitura — ensina a analisar notícias e formar argumentos.",
    "cd_140": "Notícias lado a lado da esquerda, do centro e da direita — identifique vieses e veja o quadro completo.",
    "cd_141": "Ferramenta estruturada de debate para sala de aula — alunos constroem árvores de argumentos e aprendem a raciocinar juntos.",
    "cd_142": "Desafios matemáticos em estilo familiar feitos para tornar lógica e resolução de problemas um jogo.",
    "cd_143": "Caixa de ferramentas do Project Zero de Harvard com rotinas de pensamento (\"Veja-Pense-Pergunte\", \"Afirme-Sustente-Questione\"…).",
    "cd_144": "Plataforma gratuita de alfabetização midiática do News Literacy Project — combata a desinformação com jornalismo de verdade.",
    "cd_145": "Planos de discussão gratuitos baseados em perguntas que constroem raciocínio — funciona desde a educação infantil.",
    "cd_146": "Jogo gratuito e ágil — você consegue identificar a notícia falsa? Treina os reflexos da alfabetização midiática.",
    "cd_147": "Vídeos e aulas gratuitas sobre como identificar viés e desinformação — ótimos para iniciar uma discussão.",
    "cd_148": "Recursos gratuitos de Ellen Galinsky sobre as sete habilidades essenciais para crianças que pensam.",
    "cd_149": "Vídeos gratuitos de rotinas de pensamento em salas reais — mostram seminários socráticos em ação.",
    "cd_150": "Problemas abertos e sem solução, gratuitos para K-12 — pensamento profundo, sem respostas fáceis.",
    "cd_151": "Atividades gratuitas e curadas de pensamento crítico para cada série, da Common Sense Education.",
    "cd_152": "Jogos gratuitos que constroem raciocínio inicial e reconhecimento de padrões para crianças de 3 a 5 anos.",
    "cd_153": "Jogos gratuitos de raciocínio e resolução de problemas com personagens favoritos da PBS.",
    "cd_154": "Orientações gratuitas para construir habilidades de pensamento iniciais — para pais de crianças de 0 a 5 anos.",
    "cd_155": "Recurso gratuito da BBC — vídeos curtos, ideias e jogos que constroem pensamento e linguagem na primeira infância.",
    "cd_156": "Artigos gratuitos com atividades de pensamento para a primeira infância — observação, previsão e classificação.",
    "cd_157": "App de mindfulness 100% gratuito de uma ONG australiana, com programas para crianças a partir dos 3 anos até adultos.",
    "cd_158": "As queridas aventuras de yoga infantil de Jaime Amor — gratuitas no YouTube e usadas por milhões de famílias e escolas.",
    "cd_159": "Vídeos curtos de movimento e mindfulness que professores podem usar em aula — gastam energia e depois retomam o foco.",
    "cd_160": "Meditações guiadas para crianças pequenas, do Committee for Children — \"sessões\" curtas para acalmar e focar.",
    "cd_161": "150.000+ meditações guiadas, sons para dormir e palestras gratuitas — a maior biblioteca de mindfulness gratuita do mundo.",
    "cd_162": "Headspace Premium — gratuito para professores K-12 no mundo todo, com conteúdo pronto para usar com alunos em sala.",
    "cd_163": "Calm premium gratuito para professores K-12 — meditação, histórias para dormir e conteúdo relaxante para a sala de aula.",
    "cd_164": "App gratuito e baseado em evidências da Anxiety Canada — ferramentas de TCC para adolescentes lidarem com ansiedade e preocupações.",
    "cd_165": "Vídeos animados curtos de SEL com \"vocabulário emocional\" — confira como está, expresse sentimentos e retome o foco.",
    "cd_166": "O principal quadro para aprendizagem socioemocional — recursos gratuitos para professores, escolas e famílias.",
    "cd_167": "Informações gratuitas e baseadas em evidências sobre saúde mental jovem — estresse, identidade, família e mais — da Austrália.",
    "cd_168": "Informação confidencial gratuita, ferramentas para lidar e telefone de ajuda para crianças — um lugar seguro quando tudo parece demais.",
    "cd_169": "Vídeos e imprimíveis gratuitos sobre sentimentos, rotinas e resiliência para crianças pequenas.",
    "cd_170": "Aulas iniciais gratuitas sobre ansiedade e mindfulness para crianças e pré-adolescentes — animadas e calmantes.",
    "cd_171": "Mindfulness gratuito e amigável para crianças — confira os sentimentos e escolha uma atividade calmante.",
    "cd_172": "Recursos gratuitos de saúde mental para adolescentes — estresse, sono, relacionamentos e como pedir ajuda.",
    "cd_173": "Currículo gratuito de resiliência para escolas do ensino fundamental — comprovado e baseado em evidências.",
    "cd_174": "Guias gratuitos baseados em evidências para pais e crianças sobre ansiedade, TOC e preocupação.",
    "cd_175": "Recurso governamental gratuito — como o bullying se manifesta e exatamente o que fazer.",
    "cd_176": "Kit gratuito para ansiedade e animações de respiração voltado a adolescentes de 13 a 18 anos.",
    "cd_177": "Triagem gratuita de saúde mental para adolescentes e recursos de autoajuda, sem julgamentos.",
    "cd_178": "Currículo gratuito padrão-ouro de educação financeira pessoal — cursos completos, projetos e unidades interativas.",
    "cd_179": "Simulador de finanças realista — alunos praticam poupar, fazer orçamento e tomar decisões em crises num ambiente seguro.",
    "cd_180": "Aulas gratuitas K-12 de economia e educação financeira pessoal do Council for Economic Education.",
    "cd_181": "Marcos financeiros por idade, do CFPB dos EUA, para famílias — conversas simples que constroem hábitos para a vida toda.",
    "cd_182": "Jogos, calculadoras e planos de aula gratuitos da Visa — temas financeiros por fase da vida para todas as idades.",
    "cd_183": "Curso gratuito de finanças pessoais — impostos, crédito, empréstimos, moradia, seguros e noções de aposentadoria.",
    "cd_184": "Programas K-12 globais de educação financeira, preparação para o trabalho e empreendedorismo — frequentemente oferecidos gratuitamente.",
    "cd_185": "Currículo gratuito de educação financeira federal dos EUA — fundamentos de bancos, crédito, dívida e seguros.",
    "cd_186": "Tópicos financeiros do currículo do Reino Unido — como os bancos funcionam, orçamento, impostos, seguros e juros.",
    "cd_187": "Currículo financeiro produzido por colegas e com olhar cético — ensina adolescentes a entender como o mercado tenta vender para eles.",
    "cd_188": "Definições gratuitas e em linguagem simples de cada termo bancário, de seguros e de investimentos que você vai encontrar.",
    "cd_189": "Programa gratuito da PBS e materiais de sala que ensinam crianças sobre dinheiro, negócios e empreendedorismo.",
    "cd_190": "Compilação gratuita dos melhores jogos online sobre dinheiro, do fundamental ao ensino médio.",
    "cd_191": "Aulas gratuitas sobre dinheiro por faixa etária — do cofrinho aos cartões de crédito — do blog Mint.",
    "cd_192": "Jogos gratuitos sobre dinheiro com personagens amados da PBS — primeira introdução a moedas e trocas.",
    "cd_193": "Aulas e quizzes gratuitos de educação financeira global da George Washington University.",
    "cd_194": "Quiz gratuito de dinheiro com tema da NFL — vários níveis, ótimo para adolescentes.",
    "cd_195": "Aulas gratuitas de economia e dinheiro para crianças do K ao 2º ano com livros de histórias.",
    "cd_196": "Currículo gratuito da Wells Fargo abrangendo crianças, adolescentes e adultos — sem necessidade de cadastro.",
    "cd_197": "Jogos gratuitos de contagem e troca — constroem a primeira noção de dinheiro para a pré-escola.",
    "cd_198": "Kit gratuito sobre poupar, gastar e compartilhar — feito para crianças de 3 a 5 anos.",
    "cd_199": "Atividades familiares gratuitas que apresentam conceitos de dinheiro a crianças pequenas.",
    "cd_200": "Orientações gratuitas por faixa etária sobre como ensinar dinheiro às crianças — incluindo de 3 a 5 anos.",
    "cd_201": "Currículo gratuito da FDIC para a pré-escola até o 2º ano — fundamentos do dinheiro com histórias.",
    "cd_202": "Informações de saúde revisadas por médicos em três tons — para crianças, adolescentes e pais. Corpo, mente, nutrição e segurança.",
    "cd_203": "Receitas testadas com crianças, habilidades de cozinha e vídeos da ciência do cozinhar, gratuitos da America's Test Kitchen.",
    "cd_204": "Receitas seguras para crianças por idade e habilidade — de pizzas com carinha a jantares completos, passo a passo.",
    "cd_205": "Site gratuito de nutrição do USDA — planeje refeições equilibradas e aprenda sobre os cinco grupos alimentares com jogos e aulas.",
    "cd_206": "Guia gratuito do NHS do Reino Unido sobre alimentação, exercício, sono, saúde sexual e bem-estar mental — confiável e claro.",
    "cd_207": "Apps gratuitos de primeiros socorros e emergência da Cruz Vermelha — pratique RCP, manobras de engasgo e preparo para desastres.",
    "cd_208": "Jogos gratuitos da FEMA sobre preparo para desastres e planos familiares — incêndios, tempestades, terremotos e apagões.",
    "cd_209": "Treinos gratuitos, rotinas de 7 minutos e Couch to 5K — movimento baseado em evidências para todos.",
    "cd_210": "600+ vídeos completos de treino gratuitos para todos os níveis — a maioria sem precisar de equipamento.",
    "cd_211": "Orientação gratuita e baseada em evidências sobre o sono adaptada para adolescentes — por que importa e como dormir melhor.",
    "cd_212": "Site gratuito da American Academy of Pediatrics para pais — respostas confiáveis sobre saúde, segurança e desenvolvimento.",
    "cd_213": "Aulas gratuitas do Reino Unido sobre cozinha, habilidades domésticas, bem-estar e essenciais da vida adulta.",
    "cd_214": "Jogos e vídeos gratuitos sobre rotinas, sentimentos e autocuidado para a pré-escola.",
    "cd_215": "Projetos práticos gratuitos de habilidades domésticas — circuitos, costura, jardinagem e mais.",
    "cd_216": "Orientação oficial gratuita sobre nutrição com jogos, dicas de compras e cardápios de exemplo.",
    "cd_217": "Páginas gratuitas para crianças sobre amizades, respeito e como lidar com conflitos.",
    "cd_218": "Biblioteca de receitas gratuita feita para crianças — simples, segura e deliciosamente equilibrada.",
    "cd_219": "Artigos gratuitos baseados em evidências sobre desafios do dia a dia para crianças e adolescentes.",
    "cd_220": "Blog gratuito de receitas econômicas — ensina cozinha e orçamento alimentar com custos transparentes.",
    "cd_221": "\"Playbooks\" gratuitos baseados em pesquisa do time de Angela Duckworth — perseverança, gentileza, curiosidade e autocontrole.",
    "cd_222": "Aulas gratuitas antirracistas e de justiça social, e revistas para alunos, do Southern Poverty Law Center.",
    "cd_223": "Recursos gratuitos sobre história, ética e participação cívica — como escolhas comuns moldam a sociedade.",
    "cd_224": "Aulas gratuitas com apoio da ONU sobre os 17 Objetivos de Desenvolvimento Sustentável — para todas as idades e idiomas.",
    "cd_225": "Currículo K-12 gratuito de gentileza, planos de aula e imprimíveis — SEL baseado em evidências por meio da ação.",
    "cd_226": "Práticas gratuitas baseadas em pesquisa da UC Berkeley para cultivar empatia, gratidão e bem-estar dos alunos.",
    "cd_227": "Quadro gratuito \"Six Pillars of Character\" — confiabilidade, respeito, responsabilidade, justiça, cuidado e cidadania.",
    "cd_228": "Jogos e planos de aula gratuitos sobre civismo — leis, direitos e políticas públicas. Cidadania ativa de forma envolvente.",
    "cd_229": "Curtas-metragens gratuitos, ensaios fotográficos e aulas sobre culturas, resiliência e nosso mundo compartilhado.",
    "cd_230": "Histórias de pessoas reais que \"se arriscam\" pelo bem comum — além de um programa de aprendizagem por serviço.",
    "cd_231": "Aulas e atividades gratuitas da Anistia Internacional — entenda e defenda os direitos humanos universais.",
    "cd_232": "Programa gratuito de SEL e cidadania global em que a atividade das crianças ajuda a entregar alimentos terapêuticos a quem precisa.",
    "cd_233": "Vídeos e jogos gratuitos da PBS que mostram gentileza, respeito e amizade para crianças pequenas.",
    "cd_234": "Aulas K-12 gratuitas sobre direitos humanos, equidade e cidadania global, do UNICEF.",
    "cd_235": "Aulas K-12 gratuitas sobre identidade, diversidade, justiça e ação.",
    "cd_236": "Artigos e vídeos gratuitos sobre como ensinar empatia, integridade e responsabilidade.",
    "cd_237": "Atividades gratuitas de gentileza, imprimíveis e ideias de projetos de serviço para todas as idades.",
    "cd_238": "Recursos gratuitos sobre os Objetivos de Desenvolvimento Sustentável da ONU — desenhos, pôsteres e aulas.",
    "cd_239": "Currículo gratuito que usa entrevistas reais para construir empatia e habilidades de escuta.",
    "cd_240": "Uma dúzia de experimentos gratuitos no navegador que ensinam ritmo, harmonia e som — sem conta nem instalação.",
    "cd_241": "Estúdio musical completo no navegador — gravação, mixagem e compartilhamento ilimitados, usado em milhares de escolas.",
    "cd_242": "App profissional de pintura digital de código aberto — 100% gratuito em todas as plataformas e sem marcas d'água.",
    "cd_243": "Crie pôsteres, apresentações, vídeos e mais — o pacote Canva Pro completo é gratuito para alunos e professores K-12.",
    "cd_244": "Ferramenta gratuita da Autodesk no navegador para design 3D, circuitos e blocos de código — o app de CAD mais fácil de começar.",
    "cd_245": "Modelagem 3D, animação e renderização profissionais — totalmente gratuito e de código aberto.",
    "cd_246": "Mande um emoji, humor ou palavra para o SFMOMA e receba uma obra-surpresa de sua coleção de 45.000 peças.",
    "cd_247": "Visite virtualmente 2.000+ museus — dê zoom em pinturas, explore exposições e jogue jogos de arte.",
    "cd_248": "Atividades artísticas, áudio-guias e recursos de sala de aula gratuitos do Museu de Arte Moderna (MoMA).",
    "cd_249": "Projetos gratuitos de invenção — transforme bananas em teclas de piano. Combina criatividade, fazer e pensamento computacional.",
    "cd_250": "Site interativo gratuito que ensina os fundamentos da criação musical — ritmo, acordes e melodia — direto no navegador.",
    "cd_251": "Adobe Express Premium gratuito para K-12 — crie vídeos, gráficos, panfletos e páginas web como um designer.",
    "cd_252": "Tutoriais gratuitos de desenho passo a passo no YouTube — de formas a personagens detalhados.",
    "cd_253": "Site gratuito do Met voltado para crianças — explore arte, viaje no tempo e crie projetos.",
    "cd_254": "Exposições online e guias de atividades criativas gratuitos sobre o universo da brincadeira.",
    "cd_255": "Atividades gratuitas de arte e fotografia da National Geographic — desperta a curiosidade.",
    "cd_256": "Programação visual gratuita para criar animações, arte e histórias — enorme comunidade criativa.",
    "cd_257": "Aulas gratuitas de desenho — lápis, perspectiva e retratos — organizadas do iniciante absoluto em diante.",
    "cd_258": "Cursos gratuitos de história da arte, teoria musical e design com vídeos e projetos.",
    "cd_259": "Atividades artísticas gratuitas para crianças de 4 a 8 anos — imprimíveis, ideias e desenho online.",
    "cd_260": "Imprimíveis gratuitos e tutoriais de artesanato passo a passo — perfeitos para o tempo de arte na pré-escola.",
    "cd_261": "Famoso MOOC de Barbara Oakley sobre técnicas de estudo baseadas em neurociência — gratuito para ouvinte, transformador para alunos mais velhos.",
    "cd_262": "App padrão-ouro de flashcards com repetição espaçada — comprovado cientificamente para fixar fatos na memória de longo prazo.",
    "cd_263": "Crie conjuntos de flashcards, jogue jogos de aprendizagem e faça testes de prática — usado por centenas de milhões de alunos no mundo.",
    "cd_264": "Timer Pomodoro limpo no navegador — blocos de foco de 25 minutos com pausas curtas, comprovado contra a procrastinação.",
    "cd_265": "Agenda gratuita para alunos — organize aulas, provas, tarefas e lições em todos os dispositivos num calendário inteligente.",
    "cd_266": "Pôsteres, podcasts e guias de estratégias de estudo, gratuitos e baseados em pesquisa cognitiva — prática de evocação, elaboração e mais.",
    "cd_267": "Aulas e atividades de mentalidade de crescimento de Carol Dweck, gratuitas para todas as idades — ensina que a inteligência pode crescer.",
    "cd_268": "Ferramenta gratuita do IHMC para mapas conceituais — construa mapas visuais de conhecimento que tornam ideias complexas claras e duradouras.",
    "cd_269": "Anotações combinadas com repetição espaçada — transforme qualquer parágrafo em flashcard instantaneamente enquanto estuda.",
    "cd_270": "App gratuito de \"segundo cérebro\" para anotações — ligue ideias como uma Wikipédia pessoal e veja como o conhecimento se conecta.",
    "cd_271": "Fique longe do celular cultivando uma árvore virtual — se você sair antes, a árvore morre. Gamifica sessões de estudo focado.",
    "cd_272": "Plataforma de estudo com IA — transforma PDFs e anotações em flashcards, mapas mentais e quizzes automaticamente.",
    "cd_273": "Estratégias gratuitas de estudo testadas por alunos — anotações, evocação e prática espaçada.",
    "cd_274": "Flashcards, planos de estudo e anotações gratuitos — funciona em todas as disciplinas e idades.",
    "cd_275": "Canal gratuito no YouTube — produtividade, estudo e estratégias de anotação que funcionam.",
    "cd_276": "Flashcards e jogos de estudo gratuitos — mais de 800 disciplinas cobertas por alunos de verdade.",
    "cd_277": "Flashcards, mapas mentais e quizzes gratuitos — web e celular, ótimo para revisar.",
    "cd_278": "Curso gratuito em vídeo de 10 episódios sobre como aprender a aprender — feito para adolescentes.",
    "cd_279": "Atividades gratuitas de aprendizagem inicial cobrindo o ABC, contagem, rotinas e hábitos de curiosidade.",
    "cd_280": "Orientações gratuitas para pais sobre como apoiar hábitos de aprendizagem em crianças de 0 a 5 anos.",
    "cd_281": "Artigos gratuitos sobre como a brincadeira constrói aprendizagem inicial, foco e formação de hábitos.",
    "cd_282": "Rotinas e atividades gratuitas de autorregulação para construir hábitos de aprendizagem desde cedo.",
    "cd_283": "Guias gratuitos para pais e professores sobre rotinas de aprendizagem para K-2.",
    "cd_284": "Atividades gratuitas de aprendizagem inicial — foco, rotinas e curiosidade para crianças de 3 a 7 anos.",
    "cd_285": "Músicas e rotinas gratuitas que sustentam hábitos de alfabetização e contagem desde cedo.",
    "cd_286": "Teste gratuito de um programa adaptativo de leitura inicial — constrói fluência de aprendizagem desde o K.",
    "cd_287": "Gratuito para educadores — um hábito diário de leitura de 20 minutos que faz crescer os menores aprendizes.",
}
