#!/usr/bin/env python3
"""Inject the Spanish (es) translation block into i18n.js, just before the closing }; of translations."""
from pathlib import Path
import re

ES = {
    # Navbar
    "nav.about": "Acerca de", "nav.work": "Nuestro Trabajo", "nav.resources": "Recursos",
    "nav.res.students": "Estudiantes K–12", "nav.res.teachers": "Docentes", "nav.res.uni": "Universidad",
    "nav.support": "Apóyanos", "nav.contact": "Contacto", "nav.lab": "Nuestro Lab",
    # Hero
    "hero.badge": "Educación Gratuita para Cada Estudiante",
    "hero.title": "Empoderando al mundo a través de la <em>Educación</em>",
    "hero.subtitle": "CTWP Educational Empowerment cierra la brecha entre los estudiantes y el conocimiento libre y de código abierto, probando tecnología en aulas reales para un impacto real.",
    "hero.cta.resources": "Explorar Recursos", "hero.cta.support": "Apóyanos", "hero.cta.about": "Sobre el Proyecto",
    "stat.countries": "Países Visitados", "stat.schools": "Escuelas Visitadas",
    "stat.students": "Estudiantes Alcanzados", "stat.labs": "Laboratorio Informático Construido",
    "stat.labs.cta": "Ver el Lab →",
    "lab.btn": "Ver el Laboratorio Informático →",
    "lab.banner": "Explora nuestro Laboratorio Informático en Zimbabue →",
    # Lab subpage
    "lab.hero.subtitle": "Un laboratorio digital totalmente equipado para niños desfavorecidos y con discapacidad, alimentado por energía solar, internet Starlink y la convicción de que cada niño merece acceso a la tecnología.",
    "lab.hero.cta1": "Apoya este Proyecto", "lab.hero.cta2": "Ver lo que Construimos",
    "lab.intro.label": "Informe de Estado 2025", "lab.intro.title": "¡Gracias por tu Apoyo!",
    "lab.intro.quote": "\"Para los niños desfavorecidos y con discapacidad en Zimbabue, Bongai Shamwari es mucho más que un lugar de aprendizaje: es una fuente de esperanza, oportunidad y comunidad.\"",
    "lab.intro.p1": "Tu generosa contribución en 2025 ha sido fundamental para impulsar el proyecto de digitalización en el jardín de infancia y la escuela Bongai Shamwari. Gracias a tu apoyo hemos construido infraestructura digital sostenible que abre la puerta al conocimiento y a nuevas oportunidades de aprendizaje para los niños, sus docentes y la comunidad en general.",
    "lab.intro.p2": "Tu compromiso ayuda a moldear un futuro en el que cada niño pueda explorar su potencial y participar plenamente en el mundo digital. Cada paso nos acerca a nuestro objetivo: hacer la educación accesible para todos, sin importar los desafíos externos.",
    "lab.milestones.label": "Completado en 2025", "lab.milestones.title": "Lo que Construimos Juntos",
    "lab.milestones.subtitle": "Desde sentar las bases hasta las primeras clases de TIC — cada hito alcanzado gracias a tu apoyo.",
    "lab.m1.title": "Instalación de Energía Solar",
    "lab.m1.desc": "Sistema completo de energía solar instalado, garantizando electricidad fiable y sostenible para el laboratorio informático.",
    "lab.m2.title": "Preparación de la Sala",
    "lab.m2.desc": "Interior del laboratorio totalmente preparado, incluyendo mesas y sillas compradas localmente para apoyar a la comunidad.",
    "lab.m3.title": "Mejoras de Seguridad",
    "lab.m3.desc": "Rejas antirrobo y cámaras de seguridad adicionales instaladas para proteger todo el equipo.",
    "lab.m4.title": "Internet Starlink",
    "lab.m4.desc": "Sistema Starlink instalado, proporcionando conectividad fiable de alta velocidad para apoyar el aprendizaje digital.",
    "lab.m5.title": "Computadoras Entregadas",
    "lab.m5.desc": "Todas las computadoras incluyendo periféricos enviadas a la escuela; monitores comprados localmente.",
    "lab.m6.title": "Configuración Técnica",
    "lab.m6.desc": "Todo el hardware y software instalado para uso en aula, incluyendo herramientas educativas y controles de acceso adaptados a los niños.",
    "lab.m7.title": "Profesor de TIC Contratado",
    "lab.m7.desc": "Un profesor de TIC cualificado contratado tras entrevistas exhaustivas para asegurar el mejor encaje con el programa.",
    "lab.m8.title": "Primeras Clases de TIC",
    "lab.m8.desc": "Sesiones introductorias para estudiantes y docentes iniciadas con éxito, introduciendo habilidades fundamentales de alfabetización digital.",
    "lab.gallery.label": "Impresiones", "lab.gallery.title": "Dentro del Laboratorio",
    "lab.gallery.subtitle": "Momentos reales de las primeras lecciones en la escuela Bongai Shamwari, Zimbabue.",
    "lab.nextsteps.label": "Mirando al Futuro", "lab.nextsteps.title": "Próximos Pasos — 2026 y más allá",
    "lab.nextsteps.subtitle": "El laboratorio está en marcha — ahora necesitamos sostenerlo y hacerlo crecer. Esto es lo que viene a continuación.",
    "lab.ns1.title": "Asegurar Patrocinio para el Salario del Profesor de TIC",
    "lab.ns1.desc": "Identificar donantes, socios o programas de RSC que financien al educador de TIC a tiempo completo, garantizando la sostenibilidad a largo plazo del programa de aprendizaje digital.",
    "lab.ns2.title": "Enviar Equipo Restante y Mejoras del Aula",
    "lab.ns2.desc": "Enviar impresora, proyector, alfombrillas para ratón y memorias USB; comprar localmente una estantería, fundas antipolvo y libros escolares de TIC.",
    "lab.ns3.title": "Lanzar el Currículo Completo de TIC",
    "lab.ns3.desc": "Comenzar el primer trimestre oficial de enseñanza de TIC como asignatura estructurada en Bongai Shamwari, convirtiendo las clases piloto en un programa completo de educación digital.",
    "lab.contact.label": "Ponte en Contacto", "lab.contact.title": "Contacta con el Equipo del Proyecto",
    "lab.contact.subtitle": "¿Preguntas sobre el laboratorio, oportunidades de colaboración o cómo contribuir? Escríbenos directamente.",
    "lab.contact.lars.role": "CDO de Bongai", "lab.contact.christa.role": "Presidente",
    "lab.cta.title": "Ayúdanos a Mantener el Laboratorio en Marcha",
    "lab.cta.subtitle": "Tu donación financia directamente el salario del profesor de TIC, nuevo equipamiento y la educación continua de niños que nunca antes han tenido acceso a una computadora.",
    "lab.cta.btn1": "Dona Ahora", "lab.cta.btn2": "Web de Bongai Shamwari", "lab.cta.btn3": "← Volver a CTWP",
    # About
    "about.label": "Sobre el Proyecto", "about.title": "Lo que Hacemos",
    "vision.title": "Nuestra Visión",
    "vision.text": "Empoderar a cada niño y persona del planeta mediante el acceso a educación (gratuita) usando tecnología, impactando positivamente el mundo de todos.",
    "mission.title": "Nuestra Misión",
    "mission.text": "Crear un concepto escolar innovador para niños desfavorecidos que combine el aprendizaje en línea y presencial e integre educación personalizada y experiencias de la vida real.",
    "journey.title": "Nuestro Camino hacia el Impacto", "journey.subtitle": "Actualmente en la Fase 4 de 5",
    "journey.desc": "Desde descubrir necesidades reales en más de 60 países hasta construir y mejorar una escuela piloto — observa cómo se desarrolla nuestro camino o explora cada fase abajo.",
    "phase.label.1": "Descubrir", "phase.label.2": "Diseñar", "phase.label.3": "Construir",
    "phase.label.4": "Mejorar", "phase.label.5": "Escalar",
    "badge.completed": "Completado", "badge.current": "Fase Actual", "badge.upcoming": "Próxima",
    "phase1.title": "Descubrir", "phase1.tagline": "Entender necesidades reales antes de crear soluciones",
    "phase1.li1": "Visitamos más de 150 escuelas y universidades en más de 60 países",
    "phase1.li2": "Formamos a docentes y estudiantes en aprendizaje digital y herramientas de IA",
    "phase1.li3": "Completamos formación en pedagogía, ciencia del aprendizaje y EdTech",
    "phase2.title": "Diseñar", "phase2.tagline": "Convertir hallazgos en un modelo de aprendizaje potente",
    "phase2.li1": "Construimos un concepto escolar preparado para el futuro",
    "phase2.li2": "Combinamos experiencias de aprendizaje en línea y presencial",
    "phase2.li3": "Nos centramos en aprendizaje personalizado y habilidades para la vida real",
    "phase3.title": "Construir", "phase3.tagline": "De la visión al impacto real",
    "phase3.li1": "Lanzamos nuestra escuela piloto",
    "phase3.li2": "Creamos un entorno de aprendizaje seguro e inspirador",
    "phase3.li3": "Probamos el modelo en la vida escolar diaria",
    "phase4.title": "Mejorar", "phase4.tagline": "Mejorar a través de experiencias reales",
    "phase4.li1": "Probamos y refinamos el modelo continuamente",
    "phase4.li2": "Recopilamos feedback de estudiantes, docentes y comunidades",
    "phase4.li3": "Adaptamos el modelo para aumentar el impacto",
    "phase5.title": "Escalar", "phase5.tagline": "Escalar lo que funciona para llegar a más niños",
    "phase5.li1": "Construir alianzas estratégicas con escuelas y organizaciones",
    "phase5.li2": "Preparar el modelo para replicación global",
    "phase5.li3": "Ampliar el acceso a educación significativa en todo el mundo",
    # Gallery
    "gallery.label": "Ver el Impacto", "gallery.title": "Nuestro Trabajo en Acción",
    "gallery.subtitle": "Fotos y videos de nuestras escuelas, sesiones de formación y trabajo comunitario.",
    # Resources hub (index page)
    "res.label": "Encuentra lo que Necesitas", "res.title": "Recursos Educativos Gratuitos",
    "res.subtitle": "Más de 700 herramientas curadas — para estudiantes K–12, docentes y aprendices universitarios.",
    "res.k12.title": "Estudiantes K–12", "res.k12.tagline": "300 herramientas gratuitas en 14 habilidades para la vida",
    "res.k12.desc": "Alfabetización, matemáticas, ciencias, codificación, IA, pensamiento crítico, salud mental, finanzas y mucho más para edades de 3 a 18.",
    "res.k12.cta": "Explorar Recursos K–12 →",
    "res.teachers.title": "Docentes", "res.teachers.tagline": "344 herramientas gratuitas en 6 fases de enseñanza",
    "res.teachers.desc": "Planificación de lecciones, copilotos de IA, gestión del aula, evaluación, laboratorios STEM, arte y música, aprendizaje familiar y desarrollo profesional.",
    "res.teachers.cta": "Explorar Recursos para Docentes →",
    "res.uni.title": "Universidad y Aprendizaje Permanente",
    "res.uni.tagline": "144 herramientas gratuitas en 12 habilidades del futuro",
    "res.uni.desc": "Fluidez en IA, codificación, pensamiento crítico, salud mental, finanzas, carrera y más — para estudiantes universitarios, ejecutivos y aprendices permanentes.",
    "res.uni.cta": "Explorar Recursos Universitarios →",
    # Support
    "support.label": "Cómo Puedes Ayudar", "support.title": "Apoya nuestra Misión",
    "support.subtitle": "Hay muchas formas de marcar la diferencia — desde donaciones hasta colaboraciones corporativas.",
    "support.donate.title": "Dona", "support.donate.desc": "Apoya nuestros programas con una donación única o recurrente — cada euro va directamente a los niños y a sus oportunidades de aprendizaje.",
    "support.donate.cta": "Donar Ahora",
    "support.partner.title": "Asóciate con Nosotros", "support.partner.desc": "Empresas, universidades y ONG: colaboremos en programas de educación digital, becas y construcción de laboratorios.",
    "support.partner.cta": "Contáctanos",
    "support.volunteer.title": "Voluntariado", "support.volunteer.desc": "Comparte tu experiencia — formando docentes, asesorando a estudiantes o aportando habilidades técnicas a nuestros programas.",
    "support.volunteer.cta": "Únete al Equipo",
    "support.employee.title": "Programa de RSC para Empresas", "support.employee.desc": "Envía empleados cualificados para formar a docentes y estudiantes en alfabetización digital, codificación y herramientas de IA como parte de tu programa de RSC.",
    "support.employee.cta": "Saber Más",
    # Contact
    "contact.label": "Ponte en Contacto", "contact.title": "Trabajemos Juntos",
    "contact.subtitle": "¿Tienes preguntas, ideas o quieres colaborar? Nos encantaría escucharte.",
    "contact.form.name": "Tu Nombre", "contact.form.email": "Tu Correo Electrónico",
    "contact.form.interest": "Estoy interesado/a en", "contact.form.interest.option1": "Donar",
    "contact.form.interest.option2": "Asociación / Colaboración", "contact.form.interest.option3": "Voluntariado",
    "contact.form.interest.option4": "Otra cosa",
    "contact.form.message": "Tu Mensaje", "contact.form.submit": "Enviar Mensaje",
    "contact.info.email.label": "Envíanos un correo", "contact.info.location.label": "Con sede en",
    "contact.info.location.value": "Basilea, Suiza",
    # Footer
    "footer.tagline": "Empoderando al mundo a través de la educación.",
    "footer.nav.title": "Navegación", "footer.connect.title": "Conecta",
    "footer.legal": "© 2026 CTWP Educational Empowerment. Todos los derechos reservados.",
    "footer.tagline.small": "Hecho con ❤ para la educación",
    # Pricing pills + Top Pick
    "pill.free": "Gratis", "pill.free_signup": "Gratis (registro)", "pill.freemium": "Freemium",
    "top_pick": "Recomendado",
    # Subpage backs
    "sub.uni.back": "Volver a Recursos",
    "sub.uni.badge": "Herramientas de Habilidades del Futuro para Educación Superior y Aprendices Permanentes",
    "sub.uni.title": "Recursos para Estudiantes Universitarios y Aprendices Permanentes",
    "sub.uni.desc": "144 herramientas gratuitas curadas en 12 clusters de habilidades del futuro. Elige un tema abajo para explorar los 12 mejores recursos.",
    "uni.stat.tools": "Herramientas Gratuitas", "uni.stat.clusters": "Clusters", "uni.stat.free": "Gratis",
    "uni.stat.levels.val": "Universidad→Ejecutivo", "uni.stat.levels.lbl": "Todos los Niveles",
    "uni.filter.label": "Filtrar por audiencia:", "uni.filter.all": "Todas las Audiencias",
    "uni.grade.undergrad": "Universidad", "uni.grade.grad": "Posgrado", "uni.grade.phd": "Doctorado",
    "uni.grade.self": "Autodidacta", "uni.grade.adult": "Ejecutivo", "uni.grade.switcher": "Cambio de Carrera",
    "uni.grade.all": "Todos los Niveles",
    "uni.picker.label": "Explorar por Habilidad",
    "uni.picker.heading": "Elige uno de los <em>12 clusters de habilidades del futuro</em> para descubrir las mejores herramientas gratuitas",
    # University section labels (12 clusters)
    "uni.sec.ai.label": "Tutores de IA y Copilotos", "uni.sec.ai.h2": "Fluidez en IA y Trabajo Conjunto con IA",
    "uni.sec.ai.desc": "Los mejores asistentes gratuitos, cursos sobre diseño de prompts y la alfabetización que necesitas para pensar con IA en lugar de contra ella.",
    "uni.sec.coding.label": "Programación y Ciencia de Datos", "uni.sec.coding.h2": "Codificación y Alfabetización de Datos",
    "uni.sec.coding.desc": "Aprende a programar, practica con datos reales y construye un portafolio — cursos, sandboxes y certificaciones gratuitas.",
    "uni.sec.security.label": "Privacidad, Seguridad y Bienestar Digital", "uni.sec.security.h2": "Privacidad y Seguridad Digital",
    "uni.sec.security.desc": "Protege tus datos, comprende la vigilancia y construye hábitos digitales seguros — guías de las principales ONGs de derechos digitales.",
    "uni.sec.critical.label": "Pensar con Claridad", "uni.sec.critical.h2": "Pensamiento Crítico y Alfabetización Mediática",
    "uni.sec.critical.desc": "Razonar bien, detectar la desinformación y entender los sesgos cognitivos — la habilidad #1 en cada informe del Foro Económico Mundial.",
    "uni.sec.research.label": "Investigar Mejor", "uni.sec.research.h2": "Investigación, Escritura y Citación",
    "uni.sec.research.desc": "Encuentra fuentes mejores, escribe artículos más claros y cita correctamente — las herramientas que los estudiantes universitarios usan de verdad.",
    "uni.sec.writing.label": "Escribir con Claridad", "uni.sec.writing.h2": "Escritura, Comunicación y Hablar en Público",
    "uni.sec.writing.desc": "Escribir mejor, presentar con confianza y comunicar tus ideas — herramientas y cursos del nivel de las mejores escuelas de negocios.",
    "uni.sec.productivity.label": "Hacer las Cosas", "uni.sec.productivity.h2": "Productividad y Aprendizaje Profundo",
    "uni.sec.productivity.desc": "Concentrarte, organizar tus tareas y aprender más rápido — la pila de productividad que realmente funciona para los estudiantes.",
    "uni.sec.courseware.label": "Universidad Gratuita", "uni.sec.courseware.h2": "Material Universitario Abierto y MOOCs",
    "uni.sec.courseware.desc": "Auditar cursos de Stanford, MIT y Harvard gratis. Cursos abiertos, libros de texto y materiales de las mejores universidades del mundo.",
    "uni.sec.career.label": "Entrar al Trabajo", "uni.sec.career.h2": "Carrera, Networking y Pasantías",
    "uni.sec.career.desc": "Encontrar pasantías, hacer networking efectivo y dar el salto al primer empleo — recursos gratuitos para la carrera profesional.",
    "uni.sec.finance.label": "Dinero", "uni.sec.finance.h2": "Educación Financiera para Adultos Jóvenes",
    "uni.sec.finance.desc": "Presupuestar, ahorrar, invertir y construir riqueza — las habilidades de dinero que la universidad casi nunca enseña.",
    "uni.sec.mental.label": "Estar Bien", "uni.sec.mental.h2": "Salud Mental y Bienestar",
    "uni.sec.mental.desc": "Estrés, ansiedad y burnout — apoyos prácticos para que los estudiantes universitarios prosperen, no solo sobrevivan.",
    "uni.sec.civic.label": "Ciudadanía Global", "uni.sec.civic.h2": "Conciencia Global y Participación Ciudadana",
    "uni.sec.civic.desc": "Ver más allá del bucle informativo — comprende geopolítica, historia y cómo participar como ciudadano.",
    # University tab labels
    "uni.tab.ai": "IA", "uni.tab.coding": "Programación", "uni.tab.security": "Seguridad",
    "uni.tab.critical": "Crítico", "uni.tab.research": "Investigación", "uni.tab.writing": "Escritura",
    "uni.tab.productivity": "Productividad", "uni.tab.courseware": "Cursos", "uni.tab.career": "Carrera",
    "uni.tab.finance": "Finanzas", "uni.tab.mental": "Bienestar", "uni.tab.civic": "Cívico",
    "tab.hint": "Selecciona un tema",
    # Students page
    "sub.k12.back": "Volver a Recursos", "sub.k12.badge": "Herramientas Gratuitas para Estudiantes K–12",
    "sub.k12.title": "Recursos para Estudiantes K–12",
    "sub.k12.desc": "300 herramientas gratuitas curadas en 14 habilidades para la vida — desde alfabetización y matemáticas hasta IA, salud mental y deporte.",
    "students.stat.tools": "Herramientas Gratuitas", "students.stat.skills": "Habilidades para la Vida",
    "students.stat.ages": "Edades", "students.stat.free": "Gratis",
    "students.picker.label": "Explorar por Habilidad",
    "students.picker.heading": "Elige una de las <em>14 habilidades para la vida</em> para descubrir las mejores herramientas gratuitas",
    "students.filter.label": "Filtrar por edad:", "students.filter.all": "Todas las Edades",
    # Skill chip labels
    "students.chip.literacy": "Lectoescritura", "students.chip.math": "Matemáticas",
    "students.chip.science": "Ciencias", "students.chip.history": "Historia",
    "students.chip.coding": "Programación", "students.chip.ai": "Alfabetización Digital",
    "students.chip.critical": "Pensamiento Crítico", "students.chip.mental": "Salud Mental",
    "students.chip.finance": "Finanzas", "students.chip.life": "Habilidades de Vida",
    "students.chip.values": "Valores", "students.chip.creativity": "Creatividad",
    "students.chip.learn": "Aprender a Aprender", "students.chip.sport": "Deporte y Salud",
    # Section labels (orange badges)
    "students.sec.literacy.label": "Leer, Escribir, Hablar",
    "students.sec.math.label": "Números y Lógica",
    "students.sec.science.label": "Curiosidad e Indagación",
    "students.sec.history.label": "Pasado y Lugares",
    "students.sec.coding.label": "Construir y Crear",
    "students.sec.ai.label": "Entender la Web y la Máquina",
    "students.sec.critical.label": "Pensar Mejor",
    "students.sec.mental.label": "Sentirse Bien, Aprender Bien",
    "students.sec.finance.label": "Dinero, Bancos, Seguros",
    "students.sec.life.label": "Cocinar, Moverse, Vivir Bien",
    "students.sec.values.label": "Carácter y Comunidad",
    "students.sec.creativity.label": "Hacer e Imaginar",
    "students.sec.learn.label": "Estudiar Mejor",
    "students.sec.sport.label": "Moverse y Florecer",
    # Section headings
    "students.sec.literacy.title": "Lectoescritura y Comunicación",
    "students.sec.math.title": "Matemáticas",
    "students.sec.science.title": "Ciencias",
    "students.sec.history.title": "Historia y Geografía",
    "students.sec.coding.title": "Programación y Pensamiento Computacional",
    "students.sec.ai.title": "IA y Alfabetización Digital",
    "students.sec.critical.title": "Pensamiento Crítico y Resolución de Problemas",
    "students.sec.mental.title": "Salud Mental y Mindfulness",
    "students.sec.finance.title": "Educación Financiera",
    "students.sec.life.title": "Habilidades de Vida y Salud",
    "students.sec.values.title": "Valores, Ética y Ciudadanía",
    "students.sec.creativity.title": "Creatividad, Arte y Hacer",
    "students.sec.learn.title": "Aprender a Aprender",
    "students.sec.sport.title": "Deporte y Salud Física",
    # Section descriptions
    "students.sec.literacy.desc": "Desde fonética hasta redacción de ensayos: práctica de lectura, gramática, vocabulario y lenguaje expresivo para cada edad.",
    "students.sec.math.desc": "Desde contar hasta cálculo: práctica interactiva, herramientas visuales y explicaciones expertas para cada edad.",
    "students.sec.science.desc": "Simulaciones, experimentos y explicadores visuales en física, química, biología, ciencias de la tierra y espacio.",
    "students.sec.history.desc": "Explora continentes, culturas y siglos — mapas interactivos, fuentes primarias y narrativa rica.",
    "students.sec.coding.desc": "Desde bloques de arrastrar y soltar hasta programación real — lógica, algoritmos y crear con código.",
    "students.sec.ai.desc": "Usar la IA con sabiduría, detectar desinformación en línea y dominar las habilidades digitales que necesita cada adulto futuro.",
    "students.sec.critical.desc": "Razonar con claridad, debatir bien y separar hechos del ruido — la habilidad #1 en cada informe Future of Jobs.",
    "students.sec.mental.desc": "Mente tranquila, regulación emocional y aprendizaje socioemocional — la base para todo lo demás.",
    "students.sec.finance.desc": "Presupuestar, ahorrar, invertir, banca y seguros — las habilidades prácticas de dinero que las escuelas rara vez enseñan.",
    "students.sec.life.desc": "Cocinar, nutrición, fitness, primeros auxilios, sueño y habilidades cotidianas — lo que la vida adulta realmente exige.",
    "students.sec.values.desc": "Empatía, integridad, conciencia global y ciudadanía activa — las habilidades de carácter que sostienen todo lo demás.",
    "students.sec.creativity.desc": "Música, arte, diseño, 3D, cine e invención — herramientas gratuitas para que los niños creen cosas reales.",
    "students.sec.learn.desc": "Técnicas de memoria, herramientas de enfoque, toma de notas y ciencia del aprendizaje — las metahabilidades que facilitan todo lo demás.",
    "students.sec.sport.desc": "Rutinas de movimiento, entrenamiento deportivo, yoga y ciencia del fitness — recursos gratuitos para construir hábitos saludables y activos a cualquier edad.",
    # Teachers page
    "sub.teachers.back": "Volver a Recursos",
    "sub.teachers.badge": "Herramientas Gratuitas para Docentes y Educadores",
    "sub.teachers.title": "Recursos para Docentes",
    "sub.teachers.desc": "344 herramientas gratuitas curadas y organizadas según el flujo de trabajo docente. Elige una fase y luego un tema para encontrar la herramienta adecuada.",
    "teachers.stat.tools": "Herramientas Gratuitas", "teachers.stat.topics": "Temas",
    "teachers.stat.phases": "Fases del Flujo de Trabajo", "teachers.stat.free": "Gratis",
    "teachers.grade.prek": "Preescolar", "teachers.grade.primary": "Primaria",
    "teachers.grade.secondary": "Secundaria", "teachers.grade.higher": "Educación Superior",
    "teachers.grade.sen": "Educación Especial", "teachers.grade.all": "Todas las Etapas",
    "teachers.picker.label": "Explorar por Fase",
    "teachers.picker.heading": "Elige una <em>fase del flujo de trabajo docente</em>, luego un tema",
    "teachers.filter.label": "Filtrar por etapa:", "teachers.filter.all": "Todas las Etapas",
    # Teachers phases
    "teachers.phase.fundamentals.name": "Fundamentos del Docente", "teachers.phase.fundamentals.tag": "Didáctica y Pedagogía",
    "teachers.phase.before.name": "Antes de Clase", "teachers.phase.before.tag": "Diseño y Preparación",
    "teachers.phase.during.name": "Durante la Clase", "teachers.phase.during.tag": "Enseñanza y Aprendizaje",
    "teachers.phase.after.name": "Después de Clase", "teachers.phase.after.tag": "Evaluación y Seguimiento",
    "teachers.phase.supp.name": "Apoyo", "teachers.phase.supp.tag": "En todas las fases",
    "teachers.phase.furtherdev.name": "Desarrollo Profesional", "teachers.phase.furtherdev.tag": "Crece como Docente",
    # Teachers chips & sections
    "teachers.chip.didactics": "Didáctica",
    "teachers.sec.didactics.label": "Cómo Enseñar", "teachers.sec.didactics.h2": "Didáctica — Cómo Enseñas",
    "teachers.sec.didactics.desc": "Domina el oficio de enseñar: modelos instruccionales, estructura de la lección, transmisión de contenido y técnicas basadas en evidencia para que cada lección funcione.",
    "teachers.chip.pedagogy": "Pedagogía",
    "teachers.sec.pedagogy.label": "Por Qué Enseñas Como Lo Haces", "teachers.sec.pedagogy.h2": "Pedagogía — Por Qué Enseñas Como Lo Haces",
    "teachers.sec.pedagogy.desc": "Explora la teoría y filosofía detrás de la gran enseñanza: psicología del aprendizaje, motivación, constructivismo y la experiencia del estudiante.",
    "teachers.chip.together": "Ambas Juntas",
    "teachers.sec.together.label": "Teoría se Encuentra con la Práctica", "teachers.sec.together.h2": "Ambas Juntas — Teoría se Encuentra con la Práctica",
    "teachers.sec.together.desc": "Recursos que conectan investigación y realidad del aula — frameworks, videos de enseñanza real y kits que funcionan porque están basados en ambas.",
    "teachers.chip.fund_start": "Por Dónde Empezar",
    "teachers.sec.fund_start.label": "Tu Punto de Partida", "teachers.sec.fund_start.h2": "Por Dónde Empezar",
    "teachers.sec.fund_start.desc": "¿Nuevo en explorar tu práctica? Empieza aquí — un camino curado a través de los recursos gratuitos más importantes para docentes en desarrollo.",
    "teachers.chip.planning": "Planificación de Lecciones y Currículo",
    "teachers.sec.planning.label": "Currículo y Diseño de Lecciones", "teachers.sec.planning.h2": "Planificación de Lecciones y Currículo",
    "teachers.sec.planning.desc": "Construye unidades alineadas con estándares, planes semanales y lecciones listas para enseñar en minutos — plantillas gratuitas y currículos abiertos completos.",
    "teachers.chip.materials": "Crear Materiales",
    "teachers.sec.materials.label": "Hojas de Trabajo, Diapositivas, Video y Visuales", "teachers.sec.materials.h2": "Crear Materiales — Diapositivas, Hojas, Video y Visuales",
    "teachers.sec.materials.desc": "Crea hojas de trabajo, diapositivas, infografías y videos pulidos en minutos — sin habilidades de diseño, todo gratis para docentes.",
    "teachers.chip.adapting": "Seleccionar y Adaptar",
    "teachers.sec.adapting.label": "Nivelación, Accesibilidad y Necesidades Especiales", "teachers.sec.adapting.h2": "Seleccionar y Adaptar Recursos",
    "teachers.sec.adapting.desc": "Selecciona recursos existentes y adáptalos para cada estudiante — niveladores de texto, bibliotecas niveladas, lectores accesibles y herramientas amigables con la dislexia.",
    "teachers.chip.objectives": "Objetivos y Alineación de Estándares",
    "teachers.sec.objectives.label": "Estándares, Marcos y Estructura de Lección", "teachers.sec.objectives.h2": "Establecer Objetivos y Alinear Estándares",
    "teachers.sec.objectives.desc": "Ancla cada lección en estándares y objetivos claros — marcos oficiales, taxonomías y bibliotecas OER alineadas con estándares.",
    "teachers.chip.explaining": "Explicar Contenido",
    "teachers.sec.explaining.label": "Diapositivas, Video y Screencast", "teachers.sec.explaining.h2": "Explicar Contenido — Diapositivas, Video y Screencast",
    "teachers.sec.explaining.desc": "Imparte lecciones que se queden — diapositivas interactivas, preguntas en video, screencasts y miniclases curadas.",
    "teachers.chip.interactive": "Actividades Interactivas",
    "teachers.sec.interactive.label": "Laboratorios STEM, Estudios de Arte y Música", "teachers.sec.interactive.h2": "Actividades Interactivas — Laboratorios STEM, Arte y Música",
    "teachers.sec.interactive.desc": "Simulaciones prácticas, laboratorios virtuales y estudios creativos — deja que los estudiantes HAGAN física, biología, música y arte en tu lección.",
    "teachers.chip.collab": "Colaboración",
    "teachers.sec.collab.label": "Pizarras, Mapas Mentales y Brainstorming", "teachers.sec.collab.h2": "Colaboración — Pensamiento Visual y Brainstorming",
    "teachers.sec.collab.desc": "Haz visible el pensamiento de los estudiantes — pizarras colaborativas, mapas mentales, tableros de notas adhesivas y herramientas de mapeo conceptual.",
    "teachers.chip.instruction": "Instrucción en Vivo",
    "teachers.sec.instruction.label": "Encuestas, Quizzes y Sistemas de Respuesta", "teachers.sec.instruction.h2": "Instrucción en Aula — Respuesta en Vivo y Encuestas",
    "teachers.sec.instruction.desc": "Realiza actividades en vivo atractivas — quizzes tipo concurso, encuestas, exit tickets y sistemas de respuesta que mantienen a cada estudiante activo.",
    "teachers.chip.grading": "Calificación",
    "teachers.sec.grading.label": "LMS, Libros de Notas y Auto-corrección", "teachers.sec.grading.h2": "Calificación — LMS, Libros de Notas y Auto-corrección",
    "teachers.sec.grading.desc": "Reduce a la mitad el tiempo de calificación — libros de notas LMS gratuitos, quizzes auto-corregidos, herramientas de rúbrica e informes basados en estándares.",
    "teachers.chip.feedback": "Retroalimentación",
    "teachers.sec.feedback.label": "Escritura, Gramática y Notas de Voz", "teachers.sec.feedback.h2": "Retroalimentación — Ayuda de Escritura, Gramática y Comentarios",
    "teachers.sec.feedback.desc": "Da retroalimentación significativa y rápida sobre la escritura de los estudiantes — correctores gramaticales, notas de voz, herramientas de rúbrica y plataformas de ayuda a la escritura.",
    "teachers.chip.reflection": "Reflexión",
    "teachers.sec.reflection.label": "Exit Tickets, Diarios y Portafolios", "teachers.sec.reflection.h2": "Reflexión — Exit Tickets, Diarios y Portafolios",
    "teachers.sec.reflection.desc": "Ayuda a los estudiantes a pensar sobre su aprendizaje — reflexiones en video, diarios, exit tickets, libros electrónicos y portafolios.",
    "teachers.chip.tracking": "Seguimiento del Progreso",
    "teachers.sec.tracking.label": "Tareas, Práctica y Aprendizaje en Familia", "teachers.sec.tracking.h2": "Seguimiento del Progreso — Tareas y Aprendizaje en Familia",
    "teachers.sec.tracking.desc": "Recomienda recursos seguros y eficaces a las familias — apoyo a tareas, herramientas de repaso y aprendizaje en casa para padres.",
    "teachers.chip.mgmt": "Gestión del Aula",
    "teachers.sec.mgmt.label": "Comportamiento, Rutinas y Compromiso", "teachers.sec.mgmt.h2": "Gestión del Aula y Compromiso",
    "teachers.sec.mgmt.desc": "Construye rutinas positivas, reconoce el buen comportamiento y dirige sistemas diarios fluidos — herramientas gratuitas que respetan a los estudiantes.",
    "teachers.chip.comms": "Comunicación",
    "teachers.sec.comms.label": "Padres, Estudiantes y Boletines", "teachers.sec.comms.h2": "Comunicación — Padres, Estudiantes y Traducción",
    "teachers.sec.comms.desc": "Llega a cada familia en su idioma y a su manera — mensajería segura, boletines y herramientas de traducción.",
    "teachers.chip.admin": "Administración y Archivos",
    "teachers.sec.admin.label": "Almacenamiento en la Nube, Tareas y Calendarios", "teachers.sec.admin.h2": "Administración y Almacenamiento de Archivos",
    "teachers.sec.admin.desc": "Reduce el papeleo — almacenamiento en la nube gratuito, tableros kanban, herramientas de programación y espacios de trabajo en equipo.",
    "teachers.chip.wellbeing": "Gestión del Estrés y Bienestar",
    "teachers.sec.wellbeing.label": "Salud Mental, Mindfulness y Prevención del Burnout", "teachers.sec.wellbeing.h2": "Gestión del Estrés y Bienestar",
    "teachers.sec.wellbeing.desc": "Cuídate primero — recursos gratuitos de salud mental, mindfulness y prevención del burnout especialmente para docentes.",
    "teachers.chip.ai": "Copilotos de IA",
    "teachers.sec.ai.label": "Asistentes de IA para Docentes", "teachers.sec.ai.h2": "Copilotos de IA — Ayudantes en Todas las Fases",
    "teachers.sec.ai.desc": "Genera planes de lección, rúbricas, hojas diferenciadas y retroalimentación en segundos — herramientas gratuitas de IA para todo el flujo docente.",
    "teachers.chip.fd_start": "Por Dónde Empezar",
    "teachers.sec.fd_start.label": "¿Nuevo en formación continua? Empieza aquí", "teachers.sec.fd_start.h2": "Por Dónde Empezar con el Desarrollo Profesional",
    "teachers.sec.fd_start.desc": "¿Sin saber por dónde empezar tu desarrollo profesional? Estos puntos de partida fiables te ayudarán a planificar un camino que se adapte a ti.",
    "teachers.chip.fd_courses": "Cursos y Certificaciones Gratis",
    "teachers.sec.fd_courses.label": "MOOCs, Insignias y Certificados", "teachers.sec.fd_courses.h2": "Cursos y Certificaciones Gratis",
    "teachers.sec.fd_courses.desc": "Obtén certificados e insignias reconocidos gratis — de Coursera, edX, Google, Microsoft, Apple y la Open University.",
    "teachers.chip.fd_methods": "Métodos de Enseñanza",
    "teachers.sec.fd_methods.label": "PBL, Flipped, Indagación y Más", "teachers.sec.fd_methods.h2": "Métodos de Enseñanza — Cómo Enseñar Mejor",
    "teachers.sec.fd_methods.desc": "Explora enfoques instruccionales probados, desde aprendizaje basado en proyectos hasta flipped — guías, cursos y recursos listos para el aula.",
    "teachers.chip.fd_subject": "Tu Asignatura",
    "teachers.sec.fd_subject.label": "Profundizar en tu Materia", "teachers.sec.fd_subject.h2": "Tu Asignatura — Profundiza tu Conocimiento",
    "teachers.sec.fd_subject.desc": "Profundiza en tu área — recursos gratuitos, herramientas de enriquecimiento y orientación específica para matemáticas, lengua, ciencias, humanidades y más.",
    "teachers.chip.fd_lead": "Liderar y Mentorizar",
    "teachers.sec.fd_lead.label": "Coaching Instruccional y Liderazgo Docente", "teachers.sec.fd_lead.h2": "Liderar y Mentorizar — Conviértete en Docente Líder",
    "teachers.sec.fd_lead.desc": "Da el salto al liderazgo, coaching y mentoría — recursos gratuitos para docentes que quieren apoyar a colegas y desarrollar la práctica de su escuela.",
    "teachers.chip.fd_evidence": "Evidencia y Hallazgos",
    "teachers.sec.fd_evidence.label": "Investigación Útil para Docentes", "teachers.sec.fd_evidence.h2": "Evidencia y Hallazgos — Lo que Muestra la Investigación",
    "teachers.sec.fd_evidence.desc": "Accede a la mejor investigación educativa en lenguaje claro — estrategias evaluadas por evidencia, hallazgos clave y comunidades de investigación para docentes ocupados.",
    "teachers.chip.fd_community": "Comunidades Docentes",
    "teachers.sec.fd_community.label": "Foros, Grupos y Redes Profesionales", "teachers.sec.fd_community.h2": "Comunidades Docentes — Encuentra a tu Gente",
    "teachers.sec.fd_community.desc": "Conecta con docentes de todo el mundo — foros gratuitos, comunidades sociales, redes por asignatura y eventos en vivo donde se difunden grandes ideas docentes.",
    # GDPR
    "gdpr.title": "Aviso de Cookies y Almacenamiento",
    "gdpr.text": "Usamos el almacenamiento local del navegador exclusivamente para guardar tu preferencia de idioma. No se recogen ni comparten cookies de seguimiento ni datos personales.",
    "gdpr.accept": "Aceptar", "gdpr.decline": "Rechazar",
}

src_path = Path(r"C:\Users\larsg\OneDrive\Claude Code\01_website ctwp\assets\js\i18n.js")
src = src_path.read_text(encoding="utf-8")

# Build the ES block
lines = ["  es: {"]
lines.append('    /* ─────────────── Spanish translations (es) — structural ─────────────── */')
for k, v in ES.items():
    # Escape backslashes and double quotes for JS
    v_esc = v.replace('\\', '\\\\').replace('"', '\\"')
    lines.append(f'    "{k}": "{v_esc}",')
lines.append("  }")
es_block = "\n".join(lines) + "\n"

# Find the closing }; of translations object (the line after DE block ends)
# DE block ends with "  }" then "};" — we want to insert "  es: { ... }," before the "};"
# Actually we need to add a comma after the "}" that closes DE block, then insert es block, then "};"
marker = "    \"cd_uni_143\": \"Kostenlose Kurse zu den UN-Nachhaltigkeitszielen — Klima, Gleichheit, Armut und Governance, unterrichtet von UN-Agenturen und Partnern.\",\n  }\n};"
if marker not in src:
    # Try a more flexible approach: find the closing "  }\n};"
    raise SystemExit("DE-end marker not found, can't safely inject ES block")

replacement = (
    "    \"cd_uni_143\": \"Kostenlose Kurse zu den UN-Nachhaltigkeitszielen — Klima, Gleichheit, Armut und Governance, unterrichtet von UN-Agenturen und Partnern.\",\n"
    "  },\n"
    + es_block
    + "};"
)

new_src = src.replace(marker, replacement, 1)
if new_src == src:
    raise SystemExit("Replacement made no change")

src_path.write_text(new_src, encoding="utf-8")
print(f"Inserted ES block with {len(ES)} keys")
