#!/usr/bin/env python3
"""Inject DE translations for all 344 cd_t_* card descriptions into i18n.js."""
from pathlib import Path
import re

DE = {
    "cd_t_000": "Der weltweit beliebteste Lernwissenschafts-MOOC (4 Mio.+ Teilnehmende) — Chunking, Gedächtnis, diffuses Denken. Kostenlos zum Auditieren.",
    "cd_t_001": "Jennifer Gonzalez' Podcast und Blog — Hunderte kostenlose Tiefenanalysen zu Unterrichtsstrategien, Engagement und Klassenraumtechniken.",
    "cd_t_002": "Sechs evidenzbasierte Lernstrategien (verteiltes Üben, Abruf, Elaboration usw.) — klar erklärt für Lehrkräfte und Schüler:innen.",
    "cd_t_003": "Vanderbilts definitiver kostenloser Leitfaden zu Blooms überarbeiteter Taxonomie — Verblisten, Fragenstämme und Stundenplanvorlagen.",
    "cd_t_004": "Kostenlose Universal-Design-for-Learning-Richtlinien — Stunden planen, die für alle Lernenden funktionieren, von Anfang an.",
    "cd_t_005": "Doug Lemovs 63 Klassenraumtechniken — kostenlose Videoclips, Read-alongs und Feldhandbücher zu Cold Calling, Pacing und mehr.",
    "cd_t_006": "Forschung-zu-Praxis-Artikel zu Differenzierung, projektbasiertem Lernen, sozio-emotionaler Integration und Assessmentdesign.",
    "cd_t_007": "Kostenlose Artikel zu modernen pädagogischen Modellen — Lerntaxonomien, innovative Frameworks und unterrichtsfertige Denkwerkzeuge.",
    "cd_t_008": "Jim Knights kostenlose Ressourcen zum Impact Cycle — ein praktisches Framework für selbstgesteuerte Verbesserung.",
    "cd_t_009": "Kostenlose MIT-Forschung und Tools zum Lehrerlernen — Simulationen, Fallstudien und Kurse zum Instruktionsdesign.",
    "cd_t_010": "Hunderte kostenlose Peer-Review-Artikel zu Curriculum, Unterricht und Assessment vom weltweit führenden Pädagogenverband.",
    "cd_t_011": "Kostenlose Berichte, die Kognitionswissenschaft in Lehrerausbildungsprinzipien übersetzen — Science of Learning zugänglich gemacht.",
    "cd_t_012": "Kostenlose Artikel eines Kognitionswissenschaftlers zu Gedächtnis, Aufmerksamkeit und Motivation — Forschung in Klassenraumpraxis übersetzt.",
    "cd_t_013": "Carol Dwecks Mindset Works — kostenlose Forschungszusammenfassungen und unterrichtsfertige Strategien für eine Growth-Mindset-Kultur.",
    "cd_t_014": "Deci & Ryans Selbstbestimmungstheorie erklärt — warum Autonomie, Kompetenz und Verbundenheit die drei Schlüssel zur Schülermotivation sind.",
    "cd_t_015": "Project Zeros kostenloses Thinking-Routine-Toolkit — See-Think-Wonder, Claim-Support-Question und 20+ unterrichtsfertige Protokolle.",
    "cd_t_016": "Angela Duckworths kostenlose Lehrer-Playbooks zu Grit, Neugier, Dankbarkeit und Selbstkontrolle — forschungsgestützt und einsatzbereit.",
    "cd_t_017": "Kostenlose SEL-Praktiken vom Berkeley Science Center — Freundlichkeit, Achtsamkeit und Resilienz auf Basis positiver Psychologie.",
    "cd_t_018": "Kostenloser Podcast und Artikel darüber, wie Lernen funktioniert — Neurowissenschaft, Motivation, Equity und die Zukunft der Bildung.",
    "cd_t_019": "Kostenlose Forschungsartikel der Harvard Graduate School of Education — Equity, Lernwissenschaft, Schulleitung und Bildungspolitik.",
    "cd_t_020": "EEFs kostenlose, leicht verständliche Zusammenfassung der Cognitive Load Theory — was sie für Stundenplanung und Übung bedeutet.",
    "cd_t_021": "Klarer kostenloser Leitfaden zu Vygotskys Zone der proximalen Entwicklung — wie Scaffolding und soziales Lernen den Klassenraum prägen.",
    "cd_t_022": "Edutopias evidenzbasierte Synthese dazu, was Forschung zu effektivem Unterricht sagt — zugänglich und praktisch.",
    "cd_t_023": "Harvard PZs kostenloses Visible-Thinking-Projekt — Routinen, die Schülerdenken sichtbar, diskutierbar und übertragbar machen.",
    "cd_t_024": "Videobibliothek echten Klassenraumunterrichts — Expertenlehrkräfte in Aktion über Fächer und Altersgruppen, mit Reflexionsleitfäden.",
    "cd_t_025": "Die Goldstandard-Ressource für projektbasiertes Lernen — kostenlose Starter-Kits, Rubriken und forschungsbasierte Projektideen.",
    "cd_t_026": "IDEOs kostenloses Design-Thinking-Toolkit für Pädagogen — ein menschenzentrierter Prozess für Klassenraum- und Schulherausforderungen.",
    "cd_t_027": "Kostenlose Expeditionary-Learning-Ressourcen — Charakter, Crew und Mastery-basiertes Assessment, gestützt auf jahrzehntelange Schulpraxis.",
    "cd_t_028": "Kostenlose Forschung-zu-Praxis-Artikel mit Klassenraumvideo — jede Strategie erklärt, belegt und in Aktion gezeigt.",
    "cd_t_029": "Hatties 250+ Effektgrößen mit kostenlosen Downloads — verstehe, welche Lehrpraktiken den größten Einfluss haben und warum.",
    "cd_t_030": "Harvard PZs kostenlose Protokolle, um Schülerverständnis sichtbar zu machen — Denkroutinen mit Anwendungsleitfäden für den Klassenraum.",
    "cd_t_031": "Kostenloses Framework zur Echtzeit-Anpassung des Unterrichts — verbindet formative Bewertungstheorie mit Moment-zu-Moment-Praxis.",
    "cd_t_032": "Auditierbare Kurse zum Lerndesign — Umgebungsdesign, Engagement-Theorie und systemisches Denken im Instruktionsdesign.",
    "cd_t_033": "Forschungsbasierte Stundenpläne, Strategien und Klassenmanagement-Tools — alle mit Lernstandards verknüpft.",
    "cd_t_034": "Forschungsinformierte Unterrichtsartikel, Webinare und Leitfäden vom führenden US-Bildungsjournalismus.",
    "cd_t_035": "Kostenlose praktische Ressourcen aus NSF-geförderter Lernwissenschaftsforschung — Neurowissenschaft in Klassenraumhandeln übersetzt.",
    "cd_t_036": "Kostenloses Teacher Center mit Schulungen, Zertifizierungspfaden und Integrationsleitfäden — die meistgenutzte kostenlose Lehrerplattform.",
    "cd_t_037": "Kostenlose Lernpfade mit Badge-Erwerb für Teams, OneNote, Minecraft Edu und KI-Tools für den Unterricht.",
    "cd_t_038": "Kuratierte kostenlose PD-Artikel, Videos und Leitfäden zu jedem Aspekt des Unterrichtens — der beste kostenlose Einstiegspunkt.",
    "cd_t_039": "Kostenlose strukturierte Pfade in moderne Pädagogik — wo zuerst hingehen, was lesen und wie deine Praxis weiterentwickeln.",
    "cd_t_040": "The New Teacher Projects kostenlose Leitfäden — wie großartiger Unterricht aussieht und wie man systematisch dorthin baut.",
    "cd_t_041": "Kostenlose Weiterbildungsplattform der National Education Association — Kurse, Webinare und Ressourcen für jede Karrierestufe.",
    "cd_t_042": "Kostenlose kuratierte ASCD-Ressourcen speziell für Junglehrkräfte — Klassenraumeinrichtung, Mindset und Überleben im ersten Jahr.",
    "cd_t_043": "Kostenlose Stundenressourcen, Beratungsartikel und Community-Foren für Lehrkräfte in den ersten Berufsjahren.",
    "cd_t_044": "Kostenlose praktische Starter für neue Lehrkräfte — Workload-Management, Korrekturstrategien und der Umgang mit der ersten Klasse.",
    "cd_t_045": "Kostenloses Khan-Academy-Onboarding für Lehrkräfte — Klassenzimmer einrichten, Aufgaben verteilen und Schülerfortschritt verfolgen.",
    "cd_t_046": "Kostenloses selbstgesteuertes Apple-Teacher-Anerkennungsprogramm — Badges für iPad, Mac und kreative Lernkompetenzen.",
    "cd_t_047": "Kostenlose Mitgliedschaft mit Zugang zum Impact Journal, Forschungs-Digests und Community-Forum für britische Lehrkräfte.",
    "cd_t_048": "Kostenlose standardausgerichtete Leseunterrichtseinheiten Klasse 3-12 — Texte, Fragen, Tests und vollständige ELA-Einheiten an einem Ort.",
    "cd_t_049": "Kostenloses ELA- und Mathematik-Curriculum aus dem Bundesstaat New York (PK-12) — vollständige Jahresmodule, Lehrer- und Schülerhefte.",
    "cd_t_050": "Kostenlose top-bewertete offene Mathematik- und ELA-Curricula — vollständige Jahreskurse, geschrieben von führenden Teams.",
    "cd_t_051": "Über 420.000 kostenlose Stundenpläne, Aktivitäten und Einheiten von AFT-Lehrkräften — durchsuchbar nach Fach, Klasse und Standard.",
    "cd_t_052": "Der kostenlose Bereich von Teachers Pay Teachers — Millionen lehrer-erstellte Arbeitsblätter, Einheiten und Druckvorlagen.",
    "cd_t_053": "Kostenlose UK-curriculumkonforme Ressourcen aus der weltweit größten Lehrercommunity — vollständige Stoffverteilungen und Stundenpakete.",
    "cd_t_054": "Kostenlose curriculumbezogene Videoclips und fertige Stunden von der BBC — stark in Geschichte, Naturwissenschaften und Englisch.",
    "cd_t_055": "Kostenloser digitaler Stundenplaner mit Wochengitter, Standardausrichtung und Einheitenansichten — solide Free-Stufe für Einzellehrkräfte.",
    "cd_t_056": "Schlanker digitaler Stundenplaner — kostenlose 30-Tage-Testversion, dann günstige Bezahlstufe; Wochengitter für Klassenlehrkräfte.",
    "cd_t_057": "Kostenlose Bibliothek mit Stundenplänen erfahrener Lehrkräfte über K-12-Fächer — geprüft, klassenraumgetestet und Common-Core-konform.",
    "cd_t_058": "Kostenlose digitale PBS-K-12-Medienbibliothek — über 100.000 standardausgerichtete Videos, Stunden und interaktive Inhalte.",
    "cd_t_059": "Kostenlose anpassbare digitale Lehrbücher (FlexBooks) für jedes K-12-Fach — Inhalte anpassen, Notizen hinzufügen, mit Schüler:innen teilen.",
    "cd_t_060": "Interaktive Whiteboard-Stunden und fertige Aktivitäten für Grundschullehrkräfte — große kostenlose Bibliothek mit Drag-and-Drop-Tools.",
    "cd_t_061": "Interaktive Stunden mit Folien, Quiz, Video und Umfragen — kostenlose Stufe mit Tausenden von Lehrkräften geteilten Stunden.",
    "cd_t_062": "Volles Canva Pro kostenlos für verifizierte K-12-Lehrkräfte — Arbeitsblätter, Poster, Videos, Folien, Animationen und Infografiken.",
    "cd_t_063": "Kostenloses Adobe Express für K-12-Lehrkräfte und -Schüler:innen — Flyer, Social-Posts, Videos und KI-Bildgenerierung.",
    "cd_t_064": "Millionen kostenlose Icons für Arbeitsblätter und Folien — Quellenangabe nötig, aber hervorragende Qualität und Vielfalt.",
    "cd_t_065": "Kostenlose hochwertige Fotos für jedes Klassenraummaterial — keine Quellenangabe nötig, voll nutzbar in Lernressourcen.",
    "cd_t_066": "Kostenlose Fotos, Videos, Illustrationen und Musik — voll nutzbar in Klassenraummaterialien ohne Quellenangabe.",
    "cd_t_067": "Kostenlose Stockfotos und Videos, kuratiert von einer Fotograf:innen-Community — hohe Qualität, voll kostenlos für den Unterricht.",
    "cd_t_068": "Kostenloser Wortwolken-Generator — Vokabellisten in ansprechende Visualisierungen für Anzeigen, Einstiege und schnelle Checks.",
    "cd_t_069": "Kostenlose konfigurierbare Mathematik- und Lese-Arbeitsblätter — generieren, drucken, neu generieren. Kein Login nötig.",
    "cd_t_070": "Generiere bis zu 7 verschiedene Spielstile aus einer Wortliste — kostenlos für Lehrkräfte, perfekt für Vokabel- und Wiederholungsübungen.",
    "cd_t_071": "Animierter Videoersteller für Erklärvideos — kostenlose Stufe für 5-Minuten-Videos mit umfangreicher Charakterbibliothek.",
    "cd_t_072": "Kostenloser Open-Source-Audio-Editor — Podcasts aufnehmen, Audio für Stunden bearbeiten, mit jedem Soundformat arbeiten.",
    "cd_t_073": "Kostenloser Open-Source-Desktop-Videoeditor — einfach genug für Schülerprojekte, mächtig für Lehrer-Tutorials.",
    "cd_t_074": "Kostenloses Open-Source-Autorentool — 50+ interaktive Inhaltstypen (Quiz, Verzweigungsszenarien, Drag-the-Words) überall einbettbar.",
    "cd_t_075": "Jeden Text sofort an jedes Leseniveau anpassen — gestufte Passagen, Vokabular und Fragen; die Goldstandard-Differenzierungs-KI.",
    "cd_t_076": "Kostenlose gestufte Nachrichtenartikel — jeder Artikel auf 5 Lesestufen verfügbar für differenzierten Inhaltszugang.",
    "cd_t_077": "Kostenlose umfassende K-12-Lesebibliothek — Tausende gestufter Passagen und Paartexte mit Verständnisfragen.",
    "cd_t_078": "Schwierigen Text einfügen — Rewordify ersetzt schwere Wörter inline durch einfachere, mit Definitionen beim Hovern.",
    "cd_t_079": "Kostenlose curriculumkonforme Druckvorlagen für alle Altersstufen und Fähigkeiten — Arbeitsblätter in Sekunden anpassen.",
    "cd_t_080": "Kostenloses Microsoft-Tool — jeden Text vorlesen mit Zeilenfokus, Silbentrennung, Bildwörterbuch und 60+ Sprachen.",
    "cd_t_081": "Kostenlose Text-zu-Sprache mit natürlichen Stimmen — PDFs, Webseiten und Word-Dokumente vorlesen für besseren Lesezugang.",
    "cd_t_082": "Kostenlose Open-Source-Schriftart für Dyslexie — entwickelt zur Reduzierung von Buchstabenrotation, mit Browser-Erweiterungen.",
    "cd_t_083": "Kostenlose 30-Tage-Testversion des führenden Lese-Support-Tools — Text-zu-Sprache, prädiktives Tippen, Bildwörterbuch.",
    "cd_t_084": "Kostenlos für US-Schüler:innen mit Lesebehinderungen — über 1,4 Mio. zugängliche Hörbücher und E-Books mit Text-zu-Sprache.",
    "cd_t_085": "Das definitive UDL-Framework — kostenlose Richtlinien, Beispiele und Implementierungstools für jeden Klassenraum.",
    "cd_t_086": "Umfassende kostenlose Ressourcen für Lehrkräfte und Eltern zu Dyslexie, ADHS und Lernunterschieden — forschungsbasiert und praktisch.",
    "cd_t_087": "Kostenlose Common-Core-konforme Aufgaben, Stunden und Einheitenplanung vom Team, das die Standards geschrieben hat — ELA und Mathe.",
    "cd_t_088": "Das offizielle Common-Core-State-Standards-Portal — vollständige Englisch- und Mathestandards, kostenlos und durchsuchbar.",
    "cd_t_089": "Kostenloses Next-Generation-Science-Standards-Portal — Leistungserwartungen, Evidenzstatements und Beispielstunden.",
    "cd_t_090": "Kostenloses ISTE-Standards-Portal — Framework für innovativen Unterricht mit Technologie, mit Deskriptoren und Rubriken.",
    "cd_t_091": "Kostenlose WIDA English Language Development Standards — in 40+ US-Bundesstaaten für ELL/EAL-Planung und Bewertung verwendet.",
    "cd_t_092": "Wiggins & McTighes Understanding-by-Design-Vorlagen und Artikel — Backward-Design von Lernzielen über Evidenz zum Unterricht.",
    "cd_t_093": "Kostenlose Referenz- und Verbräder für Blooms überarbeitete Taxonomie — Higher-Order-Lernziele in Sekunden mit Aktionsverben.",
    "cd_t_094": "Pam Hooks kostenlose SOLO-Taxonomie-Ressourcen — die Structure of Observed Learning Outcomes für klare Lernzielprogression.",
    "cd_t_095": "Kostenlose wiederverwendbare Stundenrahmen, an Lernziele gebunden — Cyber Sandwich, Iron Chef, Worst Preso Ever und mehr.",
    "cd_t_096": "Kostenlose Open-Educational-Resources-Bibliothek — 50.000+ kostenlose Stunden, Einheiten und vollständige Kurse nach Standard markiert.",
    "cd_t_097": "Größtes kostenloses OER-Repository — 70.000+ Ressourcen markiert nach Common Core, NGSS und State Standards, plus Qualitätsbewertungen.",
    "cd_t_098": "John Hatties kostenlose Datenbank mit 320+ Einflüssen auf Schülererfolg, nach Effektgröße bewertet — wähle Hochimpakt-Strategien.",
    "cd_t_099": "Interaktive Folienstunden mit eingebauten Umfragen, Quiz, Zeichnungen und VR — kostenlose Silver-Stufe für die meisten Bedürfnisse.",
    "cd_t_100": "Fragen und Notizen direkt in jedes Video einbetten — kostenlos für Lehrkräfte (bis 20 gespeicherte Videos) mit voller Analytik.",
    "cd_t_101": "Kostenlose unbegrenzte Bildschirmaufzeichnung für verifizierte Lehrkräfte — Flipped-Classroom-Videos mit Engagement-Funktionen.",
    "cd_t_102": "Kostenloses Screencasting-Tool mit klassenraumfreundlichen Untertiteln und einfachem Hosting — von Millionen Pädagogen genutzt.",
    "cd_t_103": "Kostenloses All-in-One-Klassenraumdisplay — Timer, Zufallsnamen-Picker, Ampel, Arbeitssymbole und Geräuschmesser auf einem Bildschirm.",
    "cd_t_104": "Kostenloses Kurations-Tool — Videos, Artikel, Tweets und Schülerarbeit in teilbare Sammlungen für jede Stunde organisieren.",
    "cd_t_105": "Erstelle interaktive Präsentationen, Escape Rooms und Infografiken — kostenlose Stufe mit hunderten Pädagogen-Vorlagen.",
    "cd_t_106": "Hotspots zu Bildern und Videos mit Text, Audio und Links hinzufügen — kostenlose Basic-Stufe für kleine Klassen.",
    "cd_t_107": "Kostenlose K-12-Videostunden mit Mastery-Übung — Analysis, Biologie, Geschichte, Finanzen und SAT-Vorbereitung, immer kostenlos.",
    "cd_t_108": "Kostenlose animierte Bildungsvideos mit eingebauten Stunden-Tools — Think-, Dig-Deeper- und Discuss-Prompts an jedem Clip.",
    "cd_t_109": "Kostenlose YouTube-Vortragsreihen zu Geschichte, Naturwissenschaften, Literatur und Wirtschaft — exzellente Produktion, von Experten.",
    "cd_t_110": "Animierte curriculumbezogene Videos mit Quiz und Concept Maps für jedes K-12-Fach — kostenlose Testversion plus kostenlose Themen.",
    "cd_t_111": "Kostenlose interaktive Stundensoftware für jeden Touchscreen — Folien, Tools und Vorlagen für Klassenunterricht (englische UI).",
    "cd_t_112": "Kostenlose 160+ interaktive Physik-, Chemie-, Biologie- und Mathesimulationen der University of Colorado — übersetzt in 90+ Sprachen.",
    "cd_t_113": "Kostenlose dynamische Mathematik — Geometrie, Algebra, Analysis, 3D und Statistik in einem Tool. Von 100M+ Schüler:innen weltweit genutzt.",
    "cd_t_114": "Kostenlose 3D-Design-, Elektronik-Simulation und Code-Block-Plattform von Autodesk — speziell für Klassenzimmer entwickelt.",
    "cd_t_115": "MITs kostenlose blockbasierte Coding-Plattform — 100M+ Projekte weltweit, der Einstiegspunkt zum Programmieren für Kinder ab 8.",
    "cd_t_116": "Kostenlose spielerische Musikexperimente von Google — Song Maker, Rhythm, Spectrogram, Kandinsky. Kein Login, läuft im Browser.",
    "cd_t_117": "Kostenlose Open-Source-Notensatzsoftware — Notenblätter für jedes Instrument oder Ensemble schreiben, abspielen und drucken.",
    "cd_t_118": "Browserbasierte kollaborative DAW — Podcasts und Musik in Echtzeit mit Schüler:innen aufnehmen. Großzügige kostenlose Stufe.",
    "cd_t_119": "Kostenlose professionelle Open-Source-Software für digitales Malen und Animation — umfangreiche Brush-Engine, in Kunstschulen genutzt.",
    "cd_t_120": "Kostenloses Planetarium im Browser — Schüler:innen den Nachthimmel von überall zeigen, perfekt für Astronomiestunden.",
    "cd_t_121": "Kostenloser Funktionsplotter und Klassenraum-Aktivitäten — der Goldstandard zur Visualisierung von Funktionen im Mathematikunterricht.",
    "cd_t_122": "Kostenloses K-12-Informatik-Curriculum — Hour of Code, Jahreskurse, KI-Lab und Dance Party. Von 60M+ Schüler:innen genutzt.",
    "cd_t_123": "Kostenloser 3D-Globus im Browser — Voyager-Touren zu Kultur, Geschichte und Wissenschaft; Markierungen für Geografiestunden bauen.",
    "cd_t_124": "Kostenloser Education-Plan mit unbegrenzten Boards und Vorlagen für verifizierte Lehrkräfte — das beliebteste Visualisierungstool.",
    "cd_t_125": "Kostenloses FigJam für Pädagogen und Schüler:innen — kollaboratives Whiteboarding mit Vorlagen und Engagement-Features.",
    "cd_t_126": "Kostenlose 'Klebezettelwand' für Ideen, Fotos, Links und Audio — drei kostenlose Padlets, von Lehrkräften geliebt.",
    "cd_t_127": "Kostenloses Open-Source-Whiteboard mit handgezeichneter Ästhetik — sofortige Kollaboration, kein Login, Ende-zu-Ende-verschlüsselt.",
    "cd_t_128": "Kostenloses Lehrer-Dashboard — jede:r Schüler:in bekommt ein eigenes Whiteboard, die Lehrkraft sieht alle live.",
    "cd_t_129": "Kostenlose 3 Mindmaps mit Kollaboration — ideal für Klassen-Concept-Mapping und Schülergruppenprojekte.",
    "cd_t_130": "Kostenlose unbegrenzte öffentliche Mindmaps — klare visuelle Hierarchie, Echtzeit-Kollaboration und Bildeinbettung.",
    "cd_t_131": "Kostenlose Education-Stufe von Lucids Whiteboard — Klebezettel, Voting und unendliche Leinwand für Klassenbrainstorming.",
    "cd_t_132": "Kostenlos für verifizierte Hochschulstudierende und Dozierende — kollaborativer visueller Workspace für Design Thinking und Gruppenarbeit.",
    "cd_t_133": "Kostenloses Open-Source-Diagramm-Tool — Flowcharts, ER-Diagramme, UML, Mindmaps. Speichert direkt in Drive oder OneDrive.",
    "cd_t_134": "Kostenloses Open-Source-Whiteboard für Schulen — funktioniert mit jedem Beamer oder interaktivem Bildschirm, kein Abo.",
    "cd_t_135": "Kostenloses kollaboratives Whiteboard in Teams und Office — Klebezettel, Tinte, Bilder und Vorlagen mit Auto-Speichern.",
    "cd_t_136": "Einfaches visuelles Mind-Mapping für Klassenzimmer — Schüler:innen brainstormen, organisieren Ideen und teilen Boards in Echtzeit.",
    "cd_t_137": "Das klassische Game-Show-Quiz-Format — kostenlose Basic-Stufe für bis zu 40 Spieler:innen für Live-Formative-Assessment.",
    "cd_t_138": "Selbstgesteuertes KI-gestütztes Quiz und Stunden — kostenlos für Lehrkräfte mit umfangreichen Fragenpools und Live-Modus.",
    "cd_t_139": "Live-Umfragen, Wortwolken und Q&A vom Publikum — kostenlose Stufe deckt Formative-Assessment in kleinen Klassen perfekt ab.",
    "cd_t_140": "Interaktive Fragen zu Google Slides oder PowerPoint hinzufügen — kostenlose Stufe für die beliebtesten Formative-Assessment-Formate.",
    "cd_t_141": "Live-Umfragen, Surveys und Q&A-Overlay für jedes Meeting oder jede Klasse — kostenlose Stufe für bis zu 100 Teilnehmende.",
    "cd_t_142": "Schnelle Quiz, Exit Tickets und Space-Race-Spiel — kostenlos für bis zu 50 Schüler:innen pro Raum.",
    "cd_t_143": "Papier-QR-Karten plus Telefon-Scan — Formative-Assessment ohne Schülergeräte, kostenlos für bis zu 60 Karten.",
    "cd_t_144": "Vorlagenbasierte Quiz-Spiele — Match-Up, Anagramm, Game Show — jede Aktivität aus einer Wortliste; kostenlos bis zu 5 gespeichert.",
    "cd_t_145": "Schülerantworten live beim Tippen sehen — Zeichnungen, Gleichungen, Absätze. Kostenlose Bronze-Stufe für formative Nutzung.",
    "cd_t_146": "Kostenloses sofortiges Wortwolken-Feedback — Frage stellen, Schüler:innen antworten in 20 Zeichen, Antworten live wachsen sehen.",
    "cd_t_147": "Live-Audience-Response-Umfragen eingebettet in PowerPoint oder Google Slides — kostenlose Stufe für bis zu 25 Antworten pro Umfrage.",
    "cd_t_148": "Spielbasierte Quiz-Plattform, bei Teens beliebt — Live-Spiele oder selbstgesteuerte Sets. Kostenlose Stufe deckt Klassennutzung ab.",
    "cd_t_149": "40+ fertige interaktive Widget-Vorlagen — Quiz, Kreuzworträtsel, Exit Tickets, Glücksräder — auto-bewertet, einbettbar.",
    "cd_t_150": "Das Standard-LMS für Millionen Lehrkräfte — Aufgaben, Bewertung, Kommunikation und Datei-Sharing an einem Ort.",
    "cd_t_151": "Kostenloser Education-Plan mit Klassen, Aufgaben, OneNote-Klassennotizbüchern und 1TB OneDrive-Speicher pro Schüler:in.",
    "cd_t_152": "Kostenlose Version des führenden Hochschul-LMS — vollständige Aufgaben, Bewertung und Rubriken für einzelne Lehrkräfte.",
    "cd_t_153": "Kostenloses Open-Source-LMS, weltweit von Universitäten genutzt — selbst hosten oder MoodleCloud-Free für kleine Klassen.",
    "cd_t_154": "Kostenloses LMS für einzelne Lehrkräfte — Aufgaben, Notenbuch, Quiz und Elternkommunikation in einer Plattform.",
    "cd_t_155": "Standardbasiertes Notenbuch, dem 5M+ Schüler:innen vertrauen — kostenlos für Einzellehrkräfte; Bezahlpläne für Schulen.",
    "cd_t_156": "Webbasiertes Notenbuch und Reporting-Tool — kostenlose Stufe deckt Klassenraumbedürfnisse ab; integriert mit großen LMS.",
    "cd_t_157": "Kostenlose auto-bewertete Quiz mit sofortigem Feedback und Analytik — das Arbeitspferd für Bewertung in Google Classroom.",
    "cd_t_158": "Kostenlose Quiz und Surveys mit Auto-Bewertung und Verzweigungslogik — in jedem Microsoft-Konto enthalten.",
    "cd_t_159": "Kostenloser Rubrik-Maker — Vorlage wählen, Kriterien anpassen, drucken oder speichern. Seit 20+ Jahren von Lehrkräften genutzt.",
    "cd_t_160": "Kostenloser Rubrik-Builder und Galerie mit Tausenden lehrer-geteilten Vorlagen — anpassen und mit Quellenangabe wiederverwenden.",
    "cd_t_161": "K-12-Schülerinformationssystem mit Notenbuch und standardbasiertem Reporting — kostenlose Testversion; viele Bezirke bieten Zugang.",
    "cd_t_162": "Kostenlose Grammarly-Stufe — Grammatik, Klarheit und Tonvorschläge für Schülerschreiben in Browser, Word und Docs.",
    "cd_t_163": "Kostenlose Web-App, die komplexe Sätze, Passiv und Adverbien hervorhebt — klareres Schülerschreiben in Sekunden.",
    "cd_t_164": "Kostenlose PDF- und Dokument-Annotation — Kommentare, Sprachnotizen, Zeichnungen und Sticker direkt auf Schülerarbeit.",
    "cd_t_165": "Kostenloses Google-Sheets-Add-on für Selbst-, Peer- und Lehrer-Rubrikbewertung — generiert personalisiertes Feedback pro Schüler:in.",
    "cd_t_166": "Kostenlose Chrome-Erweiterung mit KI-Sidebar in Google Docs und Slides — sofortiges Feedback, Levelung und Rubriken.",
    "cd_t_167": "Kostenlose Sprachkommentar-Chrome-Erweiterung für Google Docs, Slides und Classroom — 30-Sek-Audio-Feedback in Sekunden.",
    "cd_t_168": "Kostenloses Sprach-Feedback-Tool für Schülerschreiben — Rubrik-Tags mit Kommentaren verknüpfen und häufiges Feedback wiederverwenden.",
    "cd_t_169": "Blitzschnelles Feedback für Mathe und Naturwissenschaften — Schüler:innen laden Arbeit hoch, Lehrkräfte kommentieren mit Feedback-Bank.",
    "cd_t_170": "Kostenloses Google-Docs-Add-on für Batch-Schreibfeedback — Standard-Kommentare aus einer Lehrer-Feedback-Bibliothek einfügen.",
    "cd_t_171": "Adaptive Grammatik- und Schreibübung — kostenlos für Lehrkräfte mit auto-bewertetem Feedback auf jede Schülerantwort.",
    "cd_t_172": "Kostenlose interaktive Schreib- und Grammatiktools — adaptive Übung auf Satzebene für Klassen 3-12 mit sofortigem Feedback.",
    "cd_t_173": "Kostenloser Stil-Editor mit 25+ Schreibberichten — Grammatik, Lesbarkeit, Übergänge und überstrapazierte Wörter im Schülerschreiben.",
    "cd_t_174": "Kostenlose Microsoft-Videodiskussionsplattform — Schüler:innen posten kurze Videoreflexionen; Lehrkräfte erstellen sichere Themen.",
    "cd_t_175": "Schüler-erstellte digitale Portfolios mit Eltern-Sichtbarkeit — kostenlose Seesaw-for-Schools-Stufe für einzelne Klassen.",
    "cd_t_176": "Schüler:innen gestalten E-Books für Reflexion oder Projekte — kostenlos für eine Bibliothek mit 40 Büchern pro Lehrkraft.",
    "cd_t_177": "Kostenloses Microsoft-Tool — jede:r Schüler:in hat ein privates Notizbuch für Tagebücher und Reflexionen, plus eine Inhalts-Bibliothek.",
    "cd_t_178": "Kostenloses emotionales Check-in-Tool in Teams for Education — Schüler:innen wählen Gefühle; Lehrkräfte sehen Klassentrends.",
    "cd_t_179": "Kostenlose Erstellungsplattform für Schülergeschichten und digitale Reflexionen — Text, Stimme, Video und Animation kombinieren.",
    "cd_t_180": "Kostenloser Plus-Plan für verifizierte Pädagogen — Reflexionstagebücher, Lernlogs und Projektportfolios in einem Workspace.",
    "cd_t_181": "Kostenlose WordPress-betriebene Klassen- und Schülerblogs — perfekt für Reflexionstagebücher mit eingebauter Lehrer-Moderation.",
    "cd_t_182": "Kostenlose interaktive Zeitleisten und Geschichten für schülergebaute Reflexionen und Projektnarrative — kollaborativ und druckbar.",
    "cd_t_183": "Kostenloser anonymer Backchannel für Klassendiskussionen — schnelle Text- und Bildreflexionen von jedem Gerät sammeln.",
    "cd_t_184": "Kostenlose kartenbasierte Geschichten von ArcGIS — Schüler:innen reflektieren mit Text, Fotos, Video und Geodaten.",
    "cd_t_185": "Kostenloses Video-Q&A-Reflexions-Tool — Frage stellen, Schüler:innen antworten kurz, Klasse schaut gemeinsam.",
    "cd_t_186": "Kostenlose Eltern-Dashboards für alle Fächer K-12 — Fortschritt verfolgen, Stärken und Schwächen sehen, mit Lehrkräften teilen.",
    "cd_t_187": "Kostenlose UK-curriculumkonforme Wiederholung nach Jahrgängen — Leitfäden für Eltern zur Hausaufgaben- und Prüfungsunterstützung.",
    "cd_t_188": "Kostenlos 10 Fragen/Tag in 8.500 Kompetenzen — umfassende K-12-Übung mit elternfreundlichen Fortschrittsberichten.",
    "cd_t_189": "Kostenlose Bewertungen jeder Kinder-App, jedes Spiels und Films — Familien helfen, kluge Medienentscheidungen zu treffen.",
    "cd_t_190": "Kostenlose 30-Tage-Testversion des umfassenden Frühlern-Curriculums — Phonik, Mathe, Kunst und Musik für Alter 2-8.",
    "cd_t_191": "Kostenlose Testversion des führenden Frühlese-Programms — Phonik, Sichtwörter und entcodbare Bücher für Alter 3-13.",
    "cd_t_192": "Adaptive Mathe-Übung für K-12 mit weltweiten Turnieren — kostenlose Heimtests und Eltern-Fortschrittsverfolgung.",
    "cd_t_193": "Kostenloses spielbasiertes Mathe für Klassen 1-8 — Kinder kämpfen gegen Monster durch Antworten, Eltern sehen Wochenberichte.",
    "cd_t_194": "Kostenlose GCSE/A-Level-Wiederholungsplattform für UK-Familien — interaktive Kurse basierend auf Kognitionswissenschaft.",
    "cd_t_195": "Kostenlose Karteikarten und Lernmodi — über eine halbe Milliarde Lernsets für jedes Fach und jeden Prüfungslehrplan.",
    "cd_t_196": "Kostenlose curriculumkonforme Druckvorlagen, Arbeitsblätter und Aktivitätspakete — UK-basiert, in 200+ Ländern genutzt.",
    "cd_t_197": "40.000+ Kinder-E-Books, Hörbücher und Videos — kostenlos für verifizierte Pädagogen, kostengünstig für Familien.",
    "cd_t_198": "Positive Klassenkultur aufbauen — Punkte, Elternnachrichten und Schülerportfolios. Kostenlos für alle Lehrkräfte und Eltern.",
    "cd_t_199": "Gamifizierte Klassenmanagement-Plattform — Schüler:innen verdienen XP und Kräfte für gutes Verhalten. Großzügige kostenlose Stufe.",
    "cd_t_200": "Visueller Klassenraum-Geräuschmesser, der mit Lautstärke animiert — kostenlose Lite-Version, von Grundschullehrkräften geliebt.",
    "cd_t_201": "Kostenloser lustiger visueller Geräuschmesser — springende Bälle reagieren auf Klassenlautstärke. Perfekt für Gruppenarbeit.",
    "cd_t_202": "Kostenloser zufälliger Namenspicker — Rad drehen, um Schüler:innen fair auszuwählen. Gespeicherte Listen, Farben, werbefrei.",
    "cd_t_203": "Kostenlose lustige Klassenraum-Timer — Bomben, Kerzen, Rennautos — Aktivitäten mit ansprechenden Visuals im Zeitplan halten.",
    "cd_t_204": "Kostenloser Sitzplangenerator mit Verhaltenspunkte-Tracking — in Tausenden britischer Schulen genutzt, kostenlos für Einzellehrkräfte.",
    "cd_t_205": "Schulweite positive Verhaltensverstärkungs-Plattform — kostenlose Testversion; viele kostenlose PBIS-Ressourcen verfügbar.",
    "cd_t_206": "Kostenlose Bewegungs- und Achtsamkeitsvideos — kurze Gehirnpausen, die K-5-Schüler:innen in der Stunde refokussieren.",
    "cd_t_207": "Kostenlose Morgenkreis-Begrüßungen, Aktivitäten und Nachrichtenideen — forschungsbasierte sozio-emotionale Klassengemeinschaft.",
    "cd_t_208": "Kostenlose SEL-Ressourcen und wöchentliche Webinare von der Goldstandard-Org für Forschung zum sozio-emotionalen Lernen.",
    "cd_t_209": "Der meistgefolgte britische Lehrer-Blog — kostenlose praktische Strategien für Verhalten, Engagement und Routinen.",
    "cd_t_210": "Kostenloser zufälliger Schülerpicker — fair, animierte Namensauswahl, die Cold-Calling unvorhersehbar und ansprechend hält.",
    "cd_t_211": "Sichere Einweg-Nachrichten an Schüler:innen und Eltern senden — kostenlose Stufe deckt tägliche Ankündigungen mit Auto-Übersetzung.",
    "cd_t_212": "Kostenloser Familien-Engagement-Messenger, der zwischen Lehrkräften und Eltern in 100+ Sprachen automatisch übersetzt.",
    "cd_t_213": "Kostenlose sichere Elternnachrichten mit Foto- und Videoteilen — übersetzt Nachrichten automatisch in 35+ Sprachen.",
    "cd_t_214": "Kostenlose Elternkommunikation und Konferenzplaner — Favorit für Frühkindbildung und Grundschule mit Fotoaustausch.",
    "cd_t_215": "Schöne Drag-and-Drop-Klassenraum-Newsletter — kostenlose Stufe für 5 Newsletter mit vollen Designtools.",
    "cd_t_216": "Schulweite Kommunikationsplattform mit Auto-Übersetzung — viele Bezirke bieten kostenlose Lehrerkonten via Schulpläne.",
    "cd_t_217": "Kostenlose sofortige Übersetzung in 130+ Sprachen — Text, Fotos, Gespräche und Dokumente für Elternkommunikation.",
    "cd_t_218": "Bessere Übersetzungen als Google für europäische Sprachen — kostenlose Stufe deckt die meisten Lehrer-Kommunikation ab.",
    "cd_t_219": "Kostenlose Echtzeit-Gesprächsübersetzung für Elterngespräche — Telefone sprechen jeweilige Sprache, App untertitelt live.",
    "cd_t_220": "Kostenlose Konferenzplanung, Klassenfeier-Anmeldungen und Freiwilligenlisten — das Eltern-Koordinations-Arbeitspferd.",
    "cd_t_221": "Kostenlose E-Mail-Stufe (bis 500 Kontakte) — toll für Klassen-Newsletter, Eltern-Updates und PTA-Kommunikation.",
    "cd_t_222": "Kostenloses Microsoft-Tool für interaktive Newsletter und Berichte — schöne Vorlagen, Autoflow-Design, keine Formatierung.",
    "cd_t_223": "Kostenlose 15GB Cloud-Speicher mit Docs, Sheets und Slides — Lernmaterialien teilen und Aufgaben nahtlos sammeln.",
    "cd_t_224": "Kostenlose 5GB Cloud-Speicher mit Office Online — Word, Excel, PowerPoint mit klassenraumfreundlichen Sharing-Kontrollen.",
    "cd_t_225": "Kostenlose 2GB-Stufe mit Klassenraum-Sharing und kollaborativen Ordnern — vergünstigte Education-Pläne verfügbar.",
    "cd_t_226": "Kostenlose 10GB-Speicherstufe — stark in Berechtigungen und Audit-Trails, beliebt bei Bezirksverwaltung und Hochschulen.",
    "cd_t_227": "Kostenloser Plus-Plan für verifizierte Pädagogen — Wikis, Stundennotizen, Schüler-Tracker und kollaborative Klassen-Hubs.",
    "cd_t_228": "Kostenlose flexible Datenbank — toll zum Tracken von Schülerdaten, IEP-Zielen, Projektportfolios und Curriculum-Maps.",
    "cd_t_229": "Kostenlose Kanban-Boards — Stundenplanung, Schülerprojekte, Schulausschüsse und persönliche Lehrer-To-Dos verfolgen.",
    "cd_t_230": "Kostenlos für Teams bis 15 Personen — Schulverbesserungsprojekte, Abteilungsworkflows und Verwaltungsaufgaben verwalten.",
    "cd_t_231": "Kostenloses Buchungstool — Link teilen, Eltern wählen Slot für Eltern-Lehrer-Konferenzen. Kein E-Mail-Hin-und-Her mehr.",
    "cd_t_232": "Kostenlose Meeting-Zeit-Umfrage für Personal und Eltern — finden, wann alle treffen können, ohne endlose E-Mail-Threads.",
    "cd_t_233": "Kostenloser Workspace für Teams — Kanäle für Abteilungen, DMs und Integrationen mit Drive, Calendar und mehr.",
    "cd_t_234": "Kostenlose 5GB Apple Cloud-Speicher mit Pages, Numbers und Keynote im Browser — toll für Apple-nutzende Klassenzimmer.",
    "cd_t_235": "Calm-Apps kostenlose Initiative für K-12-Lehrkräfte — voller App-Zugang inkl. Sleep Stories, Meditationen und Musik.",
    "cd_t_236": "Kostenloses Headspace Plus für verifizierte K-12-Lehrkräfte in USA, UK, Kanada und Australien — Achtsamkeit und Meditation.",
    "cd_t_237": "Kostenlose Meditations-App mit der größten kostenlosen Bibliothek — über 200.000 geführte Meditationen und Lehrer-Tracks.",
    "cd_t_238": "Kostenlose Artikel, geführte Übungen und Forschung zu Achtsamkeit — zugängliche Einführung für gestresste Lehrkräfte.",
    "cd_t_239": "Berkeleys kostenlose wissenschaftsbasierte SEL-Ressourcen — Praktiken für Dankbarkeit, Freundlichkeit und Resilienz.",
    "cd_t_240": "Kostenloser Podcast und Artikel von Daniela Falecki — praktische Wohlbefinden-Strategien und Burnout-Prävention für Lehrkräfte.",
    "cd_t_241": "UK-Charity — kostenlose 24/7-Hotline, Beratung und Ressourcen zur mentalen Gesundheit für jede Lehrkraft, unabhängig vom Land.",
    "cd_t_242": "Kostenlose globale Bewegung für Lehrer-Mental-Health-Support-Meetings — 100+ Chapter weltweit, online und in Person.",
    "cd_t_243": "Jennifer Gonzalez' kostenlose Artikel und Podcast-Folgen zur Lehrer-Selbstfürsorge — praktisch, ehrlich, ohne toxische Positivität.",
    "cd_t_244": "Kostenloser Blog mit realistischen Strategien für Stress, Eltern und Verwaltung — von Klassenraumlehrkräften geschrieben.",
    "cd_t_245": "Kostenlose MHA-Toolkits — Burnout-Selbst-Screening, evidenzbasierte Bewältigungsstrategien und Krisensupport-Verzeichnisse.",
    "cd_t_246": "Kostenloses interaktives Programm der kognitiven Verhaltenstherapie — bewährte Selbsthilfe bei Stress und schlechter Stimmung.",
    "cd_t_247": "60+ lehrer-gebaute KI-Tools — Stundenpläne, IEP-Ziele, Rubriken, Differenzierung und Feedback. Großzügige kostenlose Stufe.",
    "cd_t_248": "KI-generierte interaktive Stunden in 30 Sekunden — Folien, Umfragen, Zeichnungen und Exit Tickets, mit starkem Free-Plan.",
    "cd_t_249": "100+ Generatoren für Stundenpläne, Bewertungen und Anpassungen — kostenlose Stufe für die meisten Klassenraumbedürfnisse.",
    "cd_t_250": "Sichere, überwachte KI-Chat-'Spaces' für Schüler:innen plus KI-Assistent für Lehrkräfte — großzügige kostenlose Stufe für K-12.",
    "cd_t_251": "Anthropics führender KI-Assistent — exzellent für Stundenplanung, Rubrikschreiben, Eltern-E-Mails und Feedback-Drafting.",
    "cd_t_252": "OpenAIs kostenlose Stufe deckt GPT-4o mini ab — stark für Fragengenerierung, Zusammenfassungen und Arbeitsblattstellung.",
    "cd_t_253": "Googles KI tief in Docs, Slides und Drive integriert — ideal für Lehrkräfte, die bereits in Google Workspace leben.",
    "cd_t_254": "Kostenlose KI in Word, OneNote, PowerPoint — Stundenoutlines, Foliendecks und Schülerhandouts an Ort und Stelle generieren.",
    "cd_t_255": "Lehrbuchkapitel und Notizen hochladen — Googles KI antwortet strikt aus deinen Quellen, mit Audio-Zusammenfassungen.",
    "cd_t_256": "Anthropics kostenloser Kurs zu den vier Kern-KI-Kompetenzen — Delegation, Beschreibung, Unterscheidung, Sorgfalt. Für Pädagogen.",
    "cd_t_257": "Khan Academys kostenloser KI-Tutor für Lehrkräfte — Stundenplanung, Eltern-E-Mails und sokratisches Tutoring über K-12-Fächer.",
    "cd_t_258": "KI-Suchmaschine, die jeden Anspruch zitiert — perfekt, wenn Lehrkräfte verifizierbare Quellen statt Halluzinationen brauchen.",
    "cd_t_259": "Beliebigen Text einfügen, abgestimmte essenzielle Fragen und Lernziele plus auto-generierte Quiz erhalten — kostenlos unbegrenzt.",
    "cd_t_260": "Teacher Development Trusts kostenloser Leitfaden — Forschung dazu, welche professionelle Entwicklung Unterricht und Ergebnisse verbessert.",
    "cd_t_261": "Die globalen Standards für effektives professionelles Lernen — ein klares Framework zur Bewertung und Planung deiner CPD.",
    "cd_t_262": "Kostenlose kuratierte PD-Artikel, Videos und Leitfäden zu jedem Aspekt des Unterrichtens — der beste All-in-One-Einstieg.",
    "cd_t_263": "Kostenlose strukturierte Pfade in moderne Pädagogik — was lesen, schauen und ausprobieren, während du deine Praxis weiterentwickelst.",
    "cd_t_264": "Education Endowment Foundations kostenloses Lehrertoolkit — evidenzbewertete Strategien mit klarer Anleitung zum Fokus.",
    "cd_t_265": "The New Teacher Projects kostenlose Leitfäden, wie effektiver Unterricht aussieht und wie man Schritt für Schritt dorthin baut.",
    "cd_t_266": "Wöchentliche 3-Fragen-Lehrerumfrage + PD-Ressourcen — sehe, wie Tausende Kolleg:innen denken, und benchmarke deine Praxis.",
    "cd_t_267": "Beginne mit dir selbst — Barbara Oakleys kostenloser MOOC zu Gedächtnis, Chunking und Fokus. Essentiell vor Lerngestaltung.",
    "cd_t_268": "Kostenlose Einführung in Gibbs' Reflektionszyklus und andere Modelle — Lehrerfahrungen in strukturiertes Wachstum verwandeln.",
    "cd_t_269": "Kostenloses PD-Portal der National Education Association — Kurse, Webinare und Ressourcen für jede Karrierestufe.",
    "cd_t_270": "Kostenlose Mitgliedschaft — Zugang zum Impact Journal, Forschungs-Digests und Lehr-Community für evidenzgeleitete Lehrkräfte.",
    "cd_t_271": "Kostenlose Open-University-Schnupperkurse in Bildung — inklusiver Unterricht, Mentoring und Schulleitung. Keine Voraussetzungen.",
    "cd_t_272": "Stanford-, Penn- und Johns-Hopkins-Lehrkurse kostenlos auditieren — bezahlte Zertifikate verfügbar, aber alle Inhalte kostenlos.",
    "cd_t_273": "Harvard-, MIT- und HarvardX-Bildungskurse — kostenlos zum Auditieren, mit optionalen Bezahl-MicroMasters für Schulleitung.",
    "cd_t_274": "Kostenlose Kurzlehrgänge britischer Universitäten — praktische Pädagogik, EdTech und fachspezifische CPD.",
    "cd_t_275": "Kostenlose Schulung führend zu Level 1 und 2 Google Certified Educator Prüfungen — global anerkannte Klassenraum-Tech-Berechtigung.",
    "cd_t_276": "Kostenlose Microsoft Innovative Educator Badges — Teams, OneNote, Minecraft Edu, KI-Tools und globale Kollaboration.",
    "cd_t_277": "Kostenloses selbstgesteuertes Apple-Teacher-Anerkennungsprogramm — Swift-Badges und Klassenraum-Kreativitäts-Berechtigungen.",
    "cd_t_278": "Kostenlose akkreditierte Lehr- und Bildungszertifikate — Klassenmanagement, Sonderpädagogik, Frühkindbildung und mehr.",
    "cd_t_279": "Kostenlose OU-Kurse mit Teilnahmebescheinigungen — inklusiver Unterricht, Mentoring, Schulleitung und digitale Kompetenzen.",
    "cd_t_280": "MITs vollständige Kursmaterialien frei verfügbar — Vorlesungsvideos, Aufgabensätze und Lehrnotizen aus echten MIT-Klassen.",
    "cd_t_281": "Kostenlose akkreditierte Hochschulkurse — vollständige Kurse abschließen und kostenlos Transkripte erhalten.",
    "cd_t_282": "Kostenlose Common-Sense-Educator-Zertifizierung in Digital Citizenship — praktisch und international anerkannt.",
    "cd_t_283": "Kostenlose ISTE-Webinare, Artikel und PD von der weltweit führenden EdTech-Organisation — Community-Mitgliedschaft inklusive.",
    "cd_t_284": "Goldstandard-Ressource für projektbasiertes Lernen — kostenlose Starter-Kits, Rubriken und Projektbibliotheken vom PBL-Verband.",
    "cd_t_285": "Kostenlose Ressourcen zu Flipped Classroom Design — wie aufnehmen, flippen und Unterrichtszeit für aktives Lernen besser nutzen.",
    "cd_t_286": "NSTAs kostenloser Leitfaden zu forschendem Naturwissenschaftsunterricht — von Demonstration zu schülergeleiteter Untersuchung.",
    "cd_t_287": "Kostenlose Einführungsartikel zu Kagan-Strukturen — Think-Pair-Share, Jigsaw und 200+ kooperative Lerntechniken.",
    "cd_t_288": "Kostenlose Universal-Design-for-Learning-Richtlinien — wie jede Stunde für die volle Bandbreite Lernender designt wird.",
    "cd_t_289": "IDEOs kostenloses Pädagogen-Toolkit — menschenzentriertes Design Thinking auf Klassenraumherausforderungen und Stundengestaltung.",
    "cd_t_290": "Harvard PZs 30+ Denkroutinen — strukturierte Protokolle, die Schülerdenken in jedem Fach vertiefen.",
    "cd_t_291": "Kostenlose ASCD-Ressourcen zu differenziertem Unterricht — wie Aufgaben stufen, Gruppen flexibel bilden und Pacing anpassen.",
    "cd_t_292": "Kostenlose Expeditionary-Learning-Unterrichtsressourcen — Charakter, Arbeitsgewohnheiten und Mastery-basiertes Assessment in Aktion.",
    "cd_t_293": "250+ Effektgrößen — entdecke, welche Unterrichtsmethoden den größten Einfluss auf Schülererfolg haben und warum.",
    "cd_t_294": "Kostenlose Videobibliothek von Klassenraumtechniken — Cold Call, No Opt Out, Check for Understanding und 60+ weitere Strategien.",
    "cd_t_295": "Praktische Anleitungen zu allen großen Unterrichtsansätzen — mit Klassenraum-Videobeispielen und Implementierungstipps.",
    "cd_t_296": "Cambridges kostenlose Mathematik-Bereicherungsaufgaben — reiche Probleme zur Förderung von Argumentation, durchsuchbar nach Alter.",
    "cd_t_297": "Kostenlose Lese- und Schreibressourcen — Lesestrategien, Phonik-Anleitung, Flüssigkeitstools und Familien-Engagement-Ressourcen.",
    "cd_t_298": "Kostenlose interaktive Wissenschafts- und Mathesimulationen der University of Colorado — Lehrerleitfäden für jede Simulation enthalten.",
    "cd_t_299": "Kostenlose NGSS-Implementierungsressourcen — Storyline-Einheiten, Phänomene und dreidimensionale Unterrichtsleitfäden.",
    "cd_t_300": "Kostenlose Geografie-, Wissenschafts- und Geschichtsstunden von National Geographic — Karten, Videos, Artikel und Lehrerleitfäden.",
    "cd_t_301": "Kostenlose ELA-Plattform für Lehrkräfte — standardausgerichtete Texte, Diskussionsfragen und Bewertungen für Klassen 3-12.",
    "cd_t_302": "Tausende kostenlose Englischlernressourcen — Lyrik, Drama, kreatives Schreiben und Prüfungsvorbereitung für Sek-Englischlehrkräfte.",
    "cd_t_303": "Kostenlose Geschichtslernressourcen vom führenden britischen Geschichtsmagazin — Artikel, Quellen und Stundenideen.",
    "cd_t_304": "Kostenlose Chemielernressourcen der Royal Society of Chemistry — Stundenpläne, CPD und praktische Leitfäden.",
    "cd_t_305": "Kostenlose anspruchsvolle Mathe-Rätsel und ungelöste Probleme für K-12 — entwickelt, um schönes Ringen und tiefes Denken zu schaffen.",
    "cd_t_306": "Kuratierte TED-Ed-animierte Stunden über jedes Fach — kostenlose Stundenplanungstools, Diskussionsleitfäden und Quiz.",
    "cd_t_307": "Kostenlose Schreibinspirationsfotos und -stimuli — echte veröffentlichte Schülerarbeit als Modelle nutzen, um Standards anzuheben.",
    "cd_t_308": "Jim Knights kostenlose Ressourcen zum Impact Cycle — ein forschungsbasiertes Framework für Lehrer-Coaching und Selbstverbesserung.",
    "cd_t_309": "Kostenlose Mentoring-Ressourcen von NTC — wie Mentoring-Gespräche strukturieren, effektiv beobachten und nützliches Feedback geben.",
    "cd_t_310": "Kostenlose ASCD-Ressourcen zur Lehrerleitschaft — wie aus dem Klassenraum heraus ohne formellen Titel führen.",
    "cd_t_311": "Kostenlose Artikel und Videos zum Instructional Coaching — Peer-Beobachtung, Feedback-Zyklen und Coaching-Kultur aufbauen.",
    "cd_t_312": "Kostenlose Ressourcen zum Aufbau einer professionellen Lerngemeinschaft — wie Lehrerleiter:innen schulweite Verbesserung antreiben.",
    "cd_t_313": "National Board for Professional Teaching Standards — kostenlose Vorbereitung für die Goldstandard-Lehrer-Zertifizierung.",
    "cd_t_314": "Kostenlose Standards für professionelles Lernen — wie CPD designen und leiten, die Unterricht und Ergebnisse verbessert.",
    "cd_t_315": "Kostenlose Teach-Like-a-Champion-Ressourcen für Instructional Leader — Beobachtungsframeworks, Feedback-Tools und Coaching-Videos.",
    "cd_t_316": "Kostenlose Ressourcen für Pädagogen in Führungsrollen — Curriculum-Mapping, kollaborative Planung und Community-Aufbau.",
    "cd_t_317": "Kostenlose Mittlere-Führung-Leitfäden — nach oben managen, Team führen, Workload und schwierige Gespräche führen.",
    "cd_t_318": "Education Weeks kostenlose Führungsressourcen — Forschung, Fallstudien und Politikanalyse für Lehrerleiter:innen und Schulleitungen.",
    "cd_t_319": "Kostenloses ISTE-Standards-Framework für EdTech-Leiter:innen — Roadmap zur Führung digitalen Lernens in jeder Schule.",
    "cd_t_320": "Der Goldstandard — kostenlose Evidenzbewertungen für 50+ Unterrichtsstrategien mit Effektgröße, Kosten und Implementierung.",
    "cd_t_321": "Hatties 250+ Effektgrößen auf Schülererfolg — verstehe, welche Strategien funktionieren und welche Bildungsmythen sind.",
    "cd_t_322": "Kostenlose Konferenzvorträge, Blogposts und globale Community zur Verbesserung der Forschungskompetenz in der Bildung.",
    "cd_t_323": "Kostenlose Reviews von Bildungsinterventionen des US-Bildungsministeriums — rigorose, unparteiische Evidenzbewertungen.",
    "cd_t_324": "Kostenlose evidenzbasierte Lernstrategie-Zusammenfassungen — verteiltes Üben, Abrufen, Verschachtelung und mehr für Lehrkräfte.",
    "cd_t_325": "Kostenlose Artikel eines Kognitionswissenschaftlers, warum Schüler:innen so denken und lernen — direkt anwendbar auf Stundengestaltung.",
    "cd_t_326": "Kostenlose NFER-Forschungsberichte und Zusammenfassungen — unabhängige, rigorose britische Bildungsforschung.",
    "cd_t_327": "Kostenlose Brookings-Institution-Bildungsforschung — evidenzbasierte Politikanalyse und lehrerorientierte Forschungs-Digests.",
    "cd_t_328": "Kostenlose RAND-Forschung zu Lehrer-Effektivität, Curriculum und Bildungssystemen — rigoros, peer-reviewed und kostenlos.",
    "cd_t_329": "Forschung in Klassenraumpraxis übersetzt — jeder Artikel nennt klar Evidenzbasis und Implementierungsschritte.",
    "cd_t_330": "Kostenlose Marzano-Ressourcen zu Unterrichtsstrategien — neun hochwirksame Strategien, basierend auf 35 Jahren Forschung.",
    "cd_t_331": "Kostenloser Bildungsforschungs-Hub der US-Regierung — ERIC-Datenbank, Praxisleitfäden und What Works Clearinghouse.",
    "cd_t_332": "Tägliche 3-Fragen-Lehrerumfrage + wöchentliche PD-Inhalte — sehe, wie 10.000+ Kolleg:innen antworten und benchmarke deine Sicht.",
    "cd_t_333": "Kostenlose Foren für jedes Fach und jede Altersgruppe — Ressourcenaustausch, Beratungsthreads und Karrierediskussionen.",
    "cd_t_334": "Das weltweit größte informelle Lehrer-PLN — #EduTwitter, #EduChat und Hunderte Fach-Hashtags verbinden Pädagogen global.",
    "cd_t_335": "Anonyme, ehrliche Lehrerdiskussion — echtes Reden über Workload, Verhalten, Verwaltung und was wirklich im Klassenzimmer funktioniert.",
    "cd_t_336": "Kostenlose globale Community evidenzgeleiteter Lehrkräfte — Jahreskonferenzen, regionale Events und Online-Diskussionen.",
    "cd_t_337": "Kostenlose informelle Lehrer-Unkonferenzen — 7-Minuten- und 2-Minuten-Lehrer-zu-Lehrer-Shares, lokal und online weltweit.",
    "cd_t_338": "Lokale und Online-Google-Educator-Groups in 100+ Ländern — professionelles Lernen, Events und Peer-Support für Google-Lehrkräfte.",
    "cd_t_339": "Kostenlose Microsoft-Pädagogen-Community — Stunden teilen, Badges verdienen und mit Innovator:innen vernetzen.",
    "cd_t_340": "Kostenlose Edutopia-Blogging- und Diskussions-Community — eigene Lehrgeschichte teilen und lesen, was in Klassenzimmern weltweit funktioniert.",
    "cd_t_341": "Kostenloses Mitgliedernetzwerk der National Education Association — professionelle Verbindungen, Advocacy-Tools und Peer-Support.",
    "cd_t_342": "Kostenlose LinkedIn-Pädagogen-Gruppen — professionelles Networking, Karriereentwicklung und Thought Leadership in der Bildung.",
    "cd_t_343": "ISTEs Pädagogen-Netzwerk — kostenlose Community-Spaces, Special Interest Groups und Diskussionen zu EdTech und innovativem Lernen.",
}

assert len(DE) == 344, f"Expected 344 entries, got {len(DE)}"

src = Path(r"C:\Users\larsg\OneDrive\Claude Code\01_website ctwp\assets\js\i18n.js").read_text(encoding="utf-8")

# Build the German block as JS lines
lines = ['    /* Resource card descriptions for teachers (cd_t_000 – cd_t_343) */']
for k in sorted(DE.keys()):
    v = DE[k].replace('\\', '\\\\').replace('"', '\\"')
    lines.append(f'    "{k}": "{v}",')
de_block = '\n'.join(lines) + '\n'

# Insert just before "/* Pricing pills + Top Pick badge */" in DE section,
# but only the SECOND occurrence (the DE one)
marker = "    /* Pricing pills + Top Pick badge */\n    'pill.free': 'Kostenlos'"
if marker not in src:
    raise SystemExit("DE pricing pills marker not found")

new_src = src.replace(marker, de_block + marker, 1)

if new_src == src:
    raise SystemExit("No replacement made")

Path(r"C:\Users\larsg\OneDrive\Claude Code\01_website ctwp\assets\js\i18n.js").write_text(new_src, encoding="utf-8")
print(f"Inserted {len(DE)} DE card descriptions for teachers")
