#!/usr/bin/env python3
"""
Splice the new EN teachers i18n keys (4 phases, 18 sub-clusters, 216 cards)
into assets/js/i18n.js.

Strategy:
  - The previous build inserted an EN teachers block beginning with
    "/* ─────────────── Teachers page (16 clusters × 12 cards) ─────────────── */"
    and ending with the cd_t_191 key. Replace that ENTIRE block with the
    fresh 314-key set generated by _build_teachers.py.
  - Remove the old short sub.teachers.* keys (60-tool era) on the EN side
    so they don't shadow the new ones.
  - Remove the old DE short sub.teachers.* keys for the same reason.
  - Update the gb-* class handlers to also handle teacher stages, with
    gb-all locale-aware (uni page vs teachers page).
  - DE translations for the new keys are added in a later pass.
"""
import json, re
from pathlib import Path

ROOT = Path(__file__).parent
I18N = ROOT / "assets" / "js" / "i18n.js"
KEYS = json.loads((ROOT / "_teachers_i18n_keys.json").read_text(encoding="utf-8"))

src = I18N.read_text(encoding="utf-8")

# ── 1. Build the new EN block ──────────────────────────────────────────
def js_escape(s):
    return json.dumps(s, ensure_ascii=False)

en_lines = ['    /* ─────────────── Teachers page (4 phases × 18 sub-clusters × 12 cards) ─────────────── */']
for k, v in KEYS.items():
    en_lines.append(f'    {js_escape(k)}: {js_escape(v)},')
en_block = "\n".join(en_lines) + "\n"

# ── 2. Replace the old EN teachers block ───────────────────────────────
# Anchor: from the previous header comment up to (but not including) the closing
# brace of the EN object, which is the line "  },\n  de: {".
header_pattern = re.compile(r'    /\* ─+ Teachers page[^\n]*\*/\n')
end_pattern = re.compile(r'^  \},\n  de:\s*\{', flags=re.MULTILINE)
m_header = header_pattern.search(src)
if not m_header:
    raise SystemExit("Could not find existing EN teachers header comment.")
m_end = end_pattern.search(src, pos=m_header.end())
if not m_end:
    raise SystemExit("Could not find EN block closing brace (}, de: {) after teachers header.")
old_block_len = m_end.start() - m_header.start()
src = src[:m_header.start()] + en_block + src[m_end.start():]
print(f"Replaced EN teachers block (was {old_block_len} chars; new {len(en_block)} chars).")

# ── 3. Remove old EN short sub.teachers.* lines (60-tool era) ──────────
old_short_en = re.compile(
    r"    'sub\.teachers\.badge':[^\n]*\n"
    r"    'sub\.teachers\.desc':[^\n]*\n"
    r"    'sub\.teachers\.back':[^\n]*\n"
)
src, n = old_short_en.subn("", src)
print(f"Removed {n} old EN short sub.teachers.* block(s).")

# ── 4. Remove old DE short sub.teachers.* lines (60-tool era) ──────────
old_short_de = re.compile(
    r"    'sub\.teachers\.badge': 'Für Lehrerinnen & Lehrer'[^\n]*\n"
    r"    'sub\.teachers\.desc':[^\n]*\n"
    r"    'sub\.teachers\.back': 'Zurück zu Ressourcen',\n"
)
src, n = old_short_de.subn("", src)
print(f"Removed {n} old DE short sub.teachers.* block(s).")

# ── 5. Update gb-* class handlers (add teacher stages, locale-aware gb-all) ─
gb_anchor = "  /* University audience-grade badges */"
gb_replace = """  /* University audience-grade badges */
  document.querySelectorAll('.grade-badge.gb-undergrad').forEach(el => { el.textContent = t('uni.grade.undergrad'); });
  document.querySelectorAll('.grade-badge.gb-grad').forEach(el => { el.textContent = t('uni.grade.grad'); });
  document.querySelectorAll('.grade-badge.gb-phd').forEach(el => { el.textContent = t('uni.grade.phd'); });
  document.querySelectorAll('.grade-badge.gb-self').forEach(el => { el.textContent = t('uni.grade.self'); });
  document.querySelectorAll('.grade-badge.gb-adult').forEach(el => { el.textContent = t('uni.grade.adult'); });
  document.querySelectorAll('.grade-badge.gb-switcher').forEach(el => { el.textContent = t('uni.grade.switcher'); });
  /* Teachers audience-stage badges */
  document.querySelectorAll('.grade-badge.gb-prek').forEach(el => { el.textContent = t('teachers.grade.prek'); });
  document.querySelectorAll('.grade-badge.gb-primary').forEach(el => { el.textContent = t('teachers.grade.primary'); });
  document.querySelectorAll('.grade-badge.gb-secondary').forEach(el => { el.textContent = t('teachers.grade.secondary'); });
  document.querySelectorAll('.grade-badge.gb-higher').forEach(el => { el.textContent = t('teachers.grade.higher'); });
  document.querySelectorAll('.grade-badge.gb-sen').forEach(el => { el.textContent = t('teachers.grade.sen'); });
  /* gb-all is locale-aware: 'All Levels' on uni page, 'All Stages' on teachers page */
  const _gbAllKey = location.pathname.includes('teachers.html') ? 'teachers.grade.all' : 'uni.grade.all';
  document.querySelectorAll('.grade-badge.gb-all').forEach(el => { el.textContent = t(_gbAllKey); });"""

gb_block_pattern = re.compile(
    re.escape(gb_anchor) + r'\n'
    r'(?:  document\.querySelectorAll\(\'\.grade-badge\.gb-[a-z]+\'\)[^\n]*\n)+',
)
m2 = gb_block_pattern.search(src)
if not m2:
    raise SystemExit("Could not find existing gb-* handler block.")
src = src[:m2.start()] + gb_replace + "\n" + src[m2.end():]
print("Updated gb-* handler block.")

I18N.write_text(src, encoding="utf-8")
print(f"Wrote {I18N} ({len(src):,} chars)")
