#!/usr/bin/env python3
"""Inject the Portuguese (pt-BR) translation block into i18n.js.
Structural keys + sport (12) + uni (144) cards. Teacher and student cards come from background agents."""
from pathlib import Path

PT = {
    # Navbar
    "nav.about": "Sobre", "nav.work": "Nosso Trabalho", "nav.resources": "Recursos",
    "nav.res.students": "Alunos K–12", "nav.res.teachers": "Professores", "nav.res.uni": "Universidade",
    "nav.support": "Apoie-nos", "nav.contact": "Contato", "nav.lab": "Nosso Lab",
    # Hero
    "hero.badge": "Educação Gratuita para Todos os Alunos",
    "hero.title": "Empoderando o mundo através da <em>Educação</em>",
    "hero.subtitle": "A CTWP Educational Empowerment conecta alunos a conhecimento livre e de código aberto, testando tecnologia em salas de aula reais para gerar impacto real.",
    "hero.cta.resources": "Explorar Recursos", "hero.cta.support": "Apoie-nos", "hero.cta.about": "Sobre o Projeto",
    "stat.countries": "Países Visitados", "stat.schools": "Escolas Visitadas",
    "stat.students": "Alunos Alcançados", "stat.labs": "Laboratório Construído",
    "stat.labs.cta": "Ver o Lab →",
    "lab.btn": "Ver o Laboratório de Informática →",
    "lab.banner": "Conheça nosso Laboratório de Informática no Zimbábue →",
    # Lab subpage
    "lab.hero.subtitle": "Um laboratório digital totalmente equipado para crianças em situação de vulnerabilidade e com deficiência — alimentado por energia solar, internet Starlink e a convicção de que toda criança merece acesso à tecnologia.",
    "lab.hero.cta1": "Apoie este Projeto", "lab.hero.cta2": "Veja o que Construímos",
    "lab.intro.label": "Relatório de Status 2025", "lab.intro.title": "Obrigado pelo seu Apoio!",
    "lab.intro.quote": "\"Para crianças em situação de vulnerabilidade e com deficiência no Zimbábue, a Bongai Shamwari é muito mais que um lugar de aprendizagem — é uma fonte de esperança, oportunidade e comunidade.\"",
    "lab.intro.p1": "Sua generosa contribuição em 2025 foi fundamental para impulsionar o projeto de digitalização no jardim de infância e na escola Bongai Shamwari. Graças ao seu apoio, construímos uma infraestrutura digital sustentável que abre as portas para o conhecimento e novas oportunidades de aprendizagem para as crianças, seus professores e a comunidade em geral.",
    "lab.intro.p2": "Seu compromisso ajuda a moldar um futuro em que toda criança possa explorar seu potencial e participar plenamente do mundo digital. Cada passo nos aproxima do nosso objetivo: tornar a educação acessível a todos, independentemente dos desafios externos.",
    "lab.milestones.label": "Concluído em 2025", "lab.milestones.title": "O que Construímos Juntos",
    "lab.milestones.subtitle": "Da preparação das bases às primeiras aulas de TIC — cada marco alcançado graças ao seu apoio.",
    "lab.m1.title": "Instalação de Energia Solar",
    "lab.m1.desc": "Sistema completo de energia solar instalado, garantindo eletricidade confiável e sustentável para o laboratório de informática.",
    "lab.m2.title": "Preparação da Sala",
    "lab.m2.desc": "Interior do laboratório totalmente preparado, incluindo mesas e cadeiras compradas localmente para apoiar a comunidade.",
    "lab.m3.title": "Melhorias de Segurança",
    "lab.m3.desc": "Grades antifurto e câmeras de segurança adicionais instaladas para proteger todos os equipamentos.",
    "lab.m4.title": "Internet Starlink",
    "lab.m4.desc": "Sistema Starlink instalado, fornecendo conectividade confiável de alta velocidade para apoiar a aprendizagem digital.",
    "lab.m5.title": "Computadores Entregues",
    "lab.m5.desc": "Todos os computadores e periféricos enviados à escola; monitores comprados localmente.",
    "lab.m6.title": "Configuração Técnica",
    "lab.m6.desc": "Todo o hardware e software instalado para uso em sala de aula, incluindo ferramentas educacionais e controles de acesso adaptados às crianças.",
    "lab.m7.title": "Professor de TIC Contratado",
    "lab.m7.desc": "Um professor de TIC qualificado contratado após entrevistas detalhadas para garantir o melhor encaixe com o programa.",
    "lab.m8.title": "Primeiras Aulas de TIC",
    "lab.m8.desc": "Sessões introdutórias para alunos e professores iniciadas com sucesso, apresentando habilidades fundamentais de letramento digital.",
    "lab.gallery.label": "Imagens", "lab.gallery.title": "Dentro do Laboratório",
    "lab.gallery.subtitle": "Momentos reais das primeiras aulas na escola Bongai Shamwari, Zimbábue.",
    "lab.nextsteps.label": "Olhando para o Futuro", "lab.nextsteps.title": "Próximos Passos — 2026 e além",
    "lab.nextsteps.subtitle": "O laboratório está em funcionamento — agora precisamos sustentá-lo e fazê-lo crescer. Veja o que vem a seguir.",
    "lab.ns1.title": "Garantir Patrocínio para o Salário do Professor de TIC",
    "lab.ns1.desc": "Identificar doadores, parceiros ou programas de RSC para financiar o educador de TIC em tempo integral, garantindo a sustentabilidade do programa de aprendizagem digital a longo prazo.",
    "lab.ns2.title": "Enviar Equipamento Restante e Melhorias da Sala",
    "lab.ns2.desc": "Enviar impressora, projetor, mouse pads e pen drives; comprar localmente uma estante para os equipamentos, capas antipoeira para computadores e livros didáticos de TIC.",
    "lab.ns3.title": "Lançar o Currículo Completo de TIC",
    "lab.ns3.desc": "Iniciar o primeiro semestre oficial de ensino de TIC como disciplina estruturada na Bongai Shamwari — transformando as aulas piloto em um programa completo de educação digital.",
    "lab.contact.label": "Entre em Contato", "lab.contact.title": "Fale com a Equipe do Projeto",
    "lab.contact.subtitle": "Tem perguntas sobre o laboratório, oportunidades de parceria ou como contribuir? Fale conosco diretamente.",
    "lab.contact.lars.role": "CDO da Bongai", "lab.contact.christa.role": "Presidente",
    "lab.cta.title": "Ajude-nos a Manter o Laboratório Funcionando",
    "lab.cta.subtitle": "Sua doação financia diretamente o salário do professor de TIC, novos equipamentos e a educação contínua de crianças que nunca tiveram acesso a um computador antes.",
    "lab.cta.btn1": "Doe Agora", "lab.cta.btn2": "Site da Bongai Shamwari", "lab.cta.btn3": "← Voltar para o CTWP",
    # About
    "about.label": "Sobre o Projeto", "about.title": "O que Fazemos",
    "vision.title": "Nossa Visão",
    "vision.text": "Empoderar cada criança e pessoa do planeta por meio do acesso à educação (gratuita) usando tecnologia, gerando impacto positivo no mundo de todos nós.",
    "mission.title": "Nossa Missão",
    "mission.text": "Criar um conceito escolar inovador para crianças em situação de vulnerabilidade que combine aprendizagem online e presencial e integre educação personalizada e experiências da vida real.",
    "journey.title": "Nossa Jornada de Impacto", "journey.subtitle": "Atualmente na Fase 4 de 5",
    "journey.desc": "De descobrir necessidades reais em mais de 60 países a construir e melhorar uma escola piloto — acompanhe nossa jornada ou explore cada fase abaixo.",
    "phase.label.1": "Descobrir", "phase.label.2": "Projetar", "phase.label.3": "Construir",
    "phase.label.4": "Melhorar", "phase.label.5": "Escalar",
    "badge.completed": "Concluído", "badge.current": "Fase Atual", "badge.upcoming": "Próxima",
    "phase1.title": "Descobrir", "phase1.tagline": "Entender necessidades reais antes de criar soluções",
    "phase1.li1": "Visitamos mais de 150 escolas e universidades em mais de 60 países",
    "phase1.li2": "Formamos professores e alunos em aprendizagem digital e ferramentas de IA",
    "phase1.li3": "Concluímos formação em pedagogia, ciência da aprendizagem e EdTech",
    "phase2.title": "Projetar", "phase2.tagline": "Transformar descobertas em um modelo de aprendizagem poderoso",
    "phase2.li1": "Construímos um conceito escolar pronto para o futuro",
    "phase2.li2": "Combinamos experiências de aprendizagem online e presencial",
    "phase2.li3": "Focamos em aprendizagem personalizada e habilidades para a vida real",
    "phase3.title": "Construir", "phase3.tagline": "Da visão ao impacto real",
    "phase3.li1": "Lançamos nossa escola piloto",
    "phase3.li2": "Criamos um ambiente de aprendizagem seguro e inspirador",
    "phase3.li3": "Testamos o modelo no dia a dia escolar",
    "phase4.title": "Melhorar", "phase4.tagline": "Melhorar por meio de experiências reais",
    "phase4.li1": "Testamos e refinamos o modelo continuamente",
    "phase4.li2": "Coletamos feedback de alunos, professores e comunidades",
    "phase4.li3": "Adaptamos o modelo para aumentar o impacto",
    "phase5.title": "Escalar", "phase5.tagline": "Escalar o que funciona para alcançar mais crianças",
    "phase5.li1": "Construir parcerias estratégicas com escolas e organizações",
    "phase5.li2": "Preparar o modelo para replicação global",
    "phase5.li3": "Ampliar o acesso à educação significativa em todo o mundo",
    # Gallery
    "gallery.label": "Veja o Impacto", "gallery.title": "Nosso Trabalho em Ação",
    "gallery.subtitle": "Fotos e vídeos de nossas escolas, sessões de formação e trabalho comunitário.",
    "gallery.follow": "Acompanhe nossa jornada",
    # Resources hub on index
    "resources.label": "Recursos Educacionais Gratuitos",
    "resources.title": "Recursos Educacionais",
    "resources.subtitle": "Recursos gratuitos curados para aprender e ensinar melhor — explore por público.",
    "resources.k12.title": "Alunos (K–12)",
    "resources.k12.desc": "Cursos gratuitos, ferramentas interativas de programação, ciências, idiomas, saúde mental e muito mais para idades de 3 a 18.",
    "resources.k12.link": "Descobrir recursos escolares",
    "resources.teacher.title": "Professores",
    "resources.teacher.desc": "Planos de aula, ferramentas de IA para ensinar, gestão de sala de aula, avaliação e desenvolvimento profissional.",
    "resources.teacher.link": "Descobrir recursos para professores",
    "resources.uni.title": "Universitários",
    "resources.uni.desc": "Ferramentas de pesquisa acadêmica, livros didáticos gratuitos, produtividade e carreira para estudantes e aprendizes ao longo da vida.",
    "resources.uni.link": "Descobrir recursos universitários",
    # Sponsors
    "sponsors.label": "Nossos Parceiros e Patrocinadores",
    "sponsor.main_partner": "Parceiro Principal",
    "sponsor.main_sponsor": "Patrocinador Principal",
    "sponsor.partner": "Parceiro",
    "sponsor.placeholder": "Sua logo poderia estar aqui",
    # Support tabs and cards
    "tab.individuals": "Para Pessoas Físicas",
    "tab.companies": "Para Empresas",
    "support.label": "Como Você Pode Ajudar", "support.title": "Apoie nossa Missão",
    "support.subtitle": "Há muitas formas de fazer a diferença — de doações a parcerias corporativas.",
    "support.donate.title": "Doe", "support.donate.desc": "Apoie nossos programas com uma doação única ou recorrente — cada euro vai diretamente para crianças e suas oportunidades de aprendizagem.",
    "support.donate.cta": "Doar Agora",
    "support.partner.title": "Faça Parceria Conosco", "support.partner.desc": "Empresas, universidades e ONGs: vamos colaborar em programas de educação digital, bolsas e construção de laboratórios.",
    "support.partner.cta": "Fale Conosco",
    "support.volunteer.title": "Voluntariado", "support.volunteer.desc": "Compartilhe sua experiência — formando professores, mentorando alunos ou contribuindo com habilidades técnicas para nossos programas.",
    "support.volunteer.cta": "Junte-se à Equipe",
    "support.employee.title": "Programa de RSC para Empresas", "support.employee.desc": "Envie funcionários qualificados para formar professores e alunos em letramento digital, programação e ferramentas de IA como parte do seu programa de RSC.",
    "support.employee.cta": "Saiba Mais",
    "support.member.title": "Torne-se Membro",
    "support.member.desc": "Junte-se à comunidade Bongai Shamwari. Sua contribuição anual apoia nossos programas e fortalece a comunidade.",
    "support.tech.title": "Doações de Tecnologia",
    "support.tech.desc": "Doe notebooks, tablets ou outros dispositivos para apoiar nossos laboratórios de informática na África.",
    "support.spread.title": "Espalhe a Palavra",
    "support.spread.desc": "Compartilhe nossa missão nas redes sociais e em sua rede. Cada novo olhar amplia nosso impacto.",
    "support.corp.title": "Parceria Corporativa",
    "support.corp.desc": "Torne-se patrocinador principal como a Trelleborg. Financie infraestrutura digital e construa um programa conosco.",
    # CTA
    "cta.title": "Cada Contribuição Conta",
    "cta.desc": "100% das doações vão diretamente para programas educacionais. Dados bancários e opções de patrocínio disponíveis sob solicitação.",
    "cta.donate": "Doar Agora",
    "cta.sponsor": "Tornar-se Patrocinador",
    # Contact
    "contact.label": "Entre em Contato", "contact.title": "Vamos Trabalhar Juntos",
    "contact.subtitle": "Tem perguntas, ideias ou quer colaborar? Adoraríamos ouvir você.",
    "contact.desc": "Seja você investidor, professor, organização parceira em potencial ou apenas curioso — fale conosco.",
    "contact.form.title": "Envie-nos uma Mensagem",
    "contact.location": "Zurique, Suíça (Sede)",
    "contact.form.name": "Seu Nome", "contact.form.email": "Seu Email",
    "contact.form.interest": "Tenho interesse em", "contact.form.interest.option1": "Doar",
    "contact.form.interest.option2": "Parceria / Colaboração", "contact.form.interest.option3": "Voluntariado",
    "contact.form.interest.option4": "Outra coisa",
    "contact.form.message": "Sua Mensagem", "contact.form.submit": "Enviar Mensagem",
    "contact.info.email.label": "Envie-nos um email", "contact.info.location.label": "Sediados em",
    "contact.info.location.value": "Basileia, Suíça",
    # Form fields
    "form.name": "Nome",
    "form.name.ph": "Nome completo",
    "form.email": "Email",
    "form.email.ph": "voce@email.com",
    "form.interest": "Tenho interesse como...",
    "form.select": "Selecione uma opção",
    "form.student_role": "Aluno",
    "form.teacher_role": "Professor",
    "form.partner_role": "Organização Parceira",
    "form.donor": "Doador",
    "form.corp_sponsor": "Patrocinador Corporativo",
    "form.volunteer": "Voluntário",
    "form.other": "Outro",
    "form.message": "Mensagem",
    "form.message.ph": "Como você gostaria de se envolver?",
    "form.submit": "Enviar Mensagem",
    # Footer
    "footer.tagline": "Empoderando o mundo através da educação.",
    "footer.nav.title": "Navegação", "footer.connect.title": "Conectar",
    "footer.legal": "© 2026 CTWP Educational Empowerment. Todos os direitos reservados.",
    "footer.tagline.small": "Feito com ❤ pela educação",
    "footer.about": "Sobre",
    "footer.work": "Nosso Trabalho",
    "footer.resources": "Recursos",
    "footer.support": "Apoie-nos",
    "footer.contact": "Contato",
    "footer.connect": "Conectar",
    "footer.nav": "Navegação",
    "footer.desc": "Empoderar cada criança e pessoa do planeta através do acesso à educação gratuita usando tecnologia.",
    "footer.copyright": "© 2026 CTWP Educational Empowerment. Todos os direitos reservados.",
    # Pricing pills + Top Pick
    "pill.free": "Grátis", "pill.free_signup": "Grátis (cadastro)", "pill.freemium": "Freemium",
    "top_pick": "Recomendado",
    # Subpage backs - Uni
    "sub.uni.back": "Voltar aos Recursos",
    "sub.uni.badge": "Ferramentas de Habilidades do Futuro para Ensino Superior e Aprendizes ao Longo da Vida",
    "sub.uni.title": "Recursos para Estudantes Universitários e Aprendizes ao Longo da Vida",
    "sub.uni.desc": "144 ferramentas gratuitas curadas em 12 clusters de habilidades do futuro. Escolha um tópico abaixo para explorar os 12 melhores recursos.",
    "uni.stat.tools": "Ferramentas Gratuitas", "uni.stat.clusters": "Clusters", "uni.stat.free": "Grátis",
    "uni.stat.levels.val": "Universidade→Executivo", "uni.stat.levels.lbl": "Todos os Níveis",
    "uni.stat.topics": "Tópicos do Futuro",
    "uni.filter.label": "Filtrar por público:", "uni.filter.all": "Todos os Públicos",
    "uni.grade.undergrad": "Graduação", "uni.grade.grad": "Mestrado", "uni.grade.phd": "Doutorado",
    "uni.grade.self": "Autodidata", "uni.grade.adult": "Executivo", "uni.grade.switcher": "Mudança de Carreira",
    "uni.grade.all": "Todos os Níveis",
    "uni.picker.label": "Explorar por Habilidade",
    "uni.picker.heading": "Escolha um dos <em>12 clusters de habilidades do futuro</em> para descobrir as melhores ferramentas gratuitas",
    # University tabs / chips
    "uni.tab.ai": "IA", "uni.tab.coding": "Programação", "uni.tab.security": "Segurança",
    "uni.tab.critical": "Crítico", "uni.tab.research": "Pesquisa", "uni.tab.writing": "Escrita",
    "uni.tab.productivity": "Produtividade", "uni.tab.courseware": "Cursos", "uni.tab.career": "Carreira",
    "uni.tab.finance": "Finanças", "uni.tab.mental": "Bem-estar", "uni.tab.civic": "Cívico",
    "tab.hint": "Selecione um tópico",
    "uni.chip.ai": "Fluência em IA",
    "uni.chip.coding": "Programação e Dados",
    "uni.chip.security": "Cibersegurança",
    "uni.chip.critical": "Pensamento Crítico",
    "uni.chip.research": "Pesquisa",
    "uni.chip.writing": "Escrita e Oratória",
    "uni.chip.productivity": "Produtividade",
    "uni.chip.courseware": "Cursos Abertos",
    "uni.chip.career": "Carreira",
    "uni.chip.finance": "Finanças",
    "uni.chip.mental": "Saúde Mental",
    "uni.chip.civic": "Democracia e Clima",
    # University 12 sections
    "uni.sec.ai.label": "Tutores de IA e Copilotos", "uni.sec.ai.h2": "Fluência em IA e Trabalhar com IA",
    "uni.sec.ai.desc": "Os melhores assistentes gratuitos, cursos sobre design de prompts e o letramento que você precisa para pensar com a IA em vez de contra ela.",
    "uni.sec.coding.label": "Programação e Ciência de Dados", "uni.sec.coding.h2": "Programação e Letramento de Dados",
    "uni.sec.coding.desc": "Aprenda a programar, pratique com dados reais e construa um portfólio — cursos, sandboxes e certificações gratuitas.",
    "uni.sec.security.label": "Privacidade, Segurança e Bem-estar Digital", "uni.sec.security.h2": "Privacidade e Segurança Digital",
    "uni.sec.security.desc": "Proteja seus dados, entenda a vigilância e construa hábitos digitais seguros — guias das principais ONGs de direitos digitais.",
    "uni.sec.critical.label": "Pensar com Clareza", "uni.sec.critical.h2": "Pensamento Crítico e Letramento Midiático",
    "uni.sec.critical.desc": "Raciocinar bem, detectar desinformação e entender vieses cognitivos — a habilidade #1 em todo relatório do Fórum Econômico Mundial.",
    "uni.sec.research.label": "Pesquisar Melhor", "uni.sec.research.h2": "Pesquisa, Escrita e Citação",
    "uni.sec.research.desc": "Encontre melhores fontes, escreva artigos mais claros e cite corretamente — as ferramentas que estudantes universitários realmente usam.",
    "uni.sec.writing.label": "Escrever com Clareza", "uni.sec.writing.h2": "Escrita, Comunicação e Oratória",
    "uni.sec.writing.desc": "Escreva melhor, apresente com confiança e comunique suas ideias — ferramentas e cursos no nível das melhores escolas de negócios.",
    "uni.sec.productivity.label": "Fazer as Coisas", "uni.sec.productivity.h2": "Produtividade e Aprendizagem Profunda",
    "uni.sec.productivity.desc": "Concentre-se, organize suas tarefas e aprenda mais rápido — o stack de produtividade que realmente funciona para estudantes.",
    "uni.sec.courseware.label": "Universidade Gratuita", "uni.sec.courseware.h2": "Material Universitário Aberto e MOOCs",
    "uni.sec.courseware.desc": "Audite cursos de Stanford, MIT e Harvard de graça. Cursos abertos, livros didáticos e materiais das melhores universidades do mundo.",
    "uni.sec.career.label": "Entrar no Mercado", "uni.sec.career.h2": "Carreira, Networking e Estágios",
    "uni.sec.career.desc": "Encontre estágios, faça networking eficaz e dê o salto para o primeiro emprego — recursos gratuitos para a carreira profissional.",
    "uni.sec.finance.label": "Dinheiro", "uni.sec.finance.h2": "Educação Financeira para Adultos Jovens",
    "uni.sec.finance.desc": "Faça orçamento, poupe, invista e construa riqueza — as habilidades de dinheiro que a universidade quase nunca ensina.",
    "uni.sec.mental.label": "Estar Bem", "uni.sec.mental.h2": "Saúde Mental e Bem-estar",
    "uni.sec.mental.desc": "Estresse, ansiedade e burnout — apoios práticos para que estudantes universitários floresçam, não apenas sobrevivam.",
    "uni.sec.civic.label": "Cidadania Global", "uni.sec.civic.h2": "Consciência Global e Participação Cívica",
    "uni.sec.civic.desc": "Veja além do ciclo de notícias — entenda geopolítica, história e como participar como cidadão.",
    # Students subpage
    "sub.k12.back": "Voltar aos Recursos",
    "sub.k12.badge": "Ferramentas Gratuitas para Alunos K–12",
    "sub.k12.title": "Recursos para Alunos K–12",
    "sub.k12.desc": "300 ferramentas gratuitas curadas em 14 habilidades para a vida — de letramento e matemática a IA, saúde mental e esporte.",
    "students.stat.tools": "Ferramentas Gratuitas", "students.stat.skills": "Habilidades para a Vida",
    "students.stat.ages": "Idades", "students.stat.free": "Grátis",
    "students.stat.freestart": "Início Gratuito",
    "students.picker.label": "Explorar por Habilidade",
    "students.picker.heading": "Escolha uma das <em>14 habilidades para a vida</em> para descobrir as melhores ferramentas gratuitas",
    "students.filter.label": "Filtrar por idade:", "students.filter.all": "Todas as Idades",
    "sub.students.back": "Voltar aos Recursos",
    "sub.students.badge": "Habilidades K–12 para o Futuro",
    "sub.students.title": "Recursos para Alunos (K–12)",
    "sub.students.desc": "300 ferramentas gratuitas curadas para 14 habilidades para a vida — de letramento e matemática a saúde mental, finanças e esporte.",
    # Skill chip labels
    "students.chip.literacy": "Leitura e Escrita", "students.chip.math": "Matemática",
    "students.chip.science": "Ciências", "students.chip.history": "História",
    "students.chip.coding": "Programação", "students.chip.ai": "Letramento Digital",
    "students.chip.critical": "Pensamento Crítico", "students.chip.mental": "Saúde Mental",
    "students.chip.finance": "Finanças", "students.chip.life": "Habilidades de Vida",
    "students.chip.values": "Valores", "students.chip.creativity": "Criatividade",
    "students.chip.learn": "Aprender a Aprender", "students.chip.sport": "Esporte e Saúde",
    # Section labels (orange badges)
    "students.sec.literacy.label": "Ler, Escrever, Falar",
    "students.sec.math.label": "Números e Lógica",
    "students.sec.science.label": "Curiosidade e Investigação",
    "students.sec.history.label": "Passado e Lugares",
    "students.sec.coding.label": "Construir e Criar",
    "students.sec.ai.label": "Entender a Web e a Máquina",
    "students.sec.critical.label": "Pensar Melhor",
    "students.sec.mental.label": "Sentir-se Bem, Aprender Bem",
    "students.sec.finance.label": "Dinheiro, Bancos, Seguros",
    "students.sec.life.label": "Cozinhar, Mover-se, Viver Bem",
    "students.sec.values.label": "Caráter e Comunidade",
    "students.sec.creativity.label": "Fazer e Imaginar",
    "students.sec.learn.label": "Estudar Melhor",
    "students.sec.sport.label": "Mover-se e Florescer",
    # Section headings
    "students.sec.literacy.title": "Leitura, Escrita e Comunicação",
    "students.sec.math.title": "Matemática",
    "students.sec.science.title": "Ciências",
    "students.sec.history.title": "História e Geografia",
    "students.sec.coding.title": "Programação e Pensamento Computacional",
    "students.sec.ai.title": "IA e Letramento Digital",
    "students.sec.critical.title": "Pensamento Crítico e Resolução de Problemas",
    "students.sec.mental.title": "Saúde Mental e Mindfulness",
    "students.sec.finance.title": "Educação Financeira",
    "students.sec.life.title": "Habilidades de Vida e Saúde",
    "students.sec.values.title": "Valores, Ética e Cidadania",
    "students.sec.creativity.title": "Criatividade, Arte e Fazer",
    "students.sec.learn.title": "Aprender a Aprender",
    "students.sec.sport.title": "Esporte e Saúde Física",
    # Section descriptions
    "students.sec.literacy.desc": "Da fonética à redação de ensaios: prática de leitura, gramática, vocabulário e linguagem expressiva para todas as idades.",
    "students.sec.math.desc": "De contar a cálculo: prática interativa, ferramentas visuais e explicações de especialistas para todas as idades.",
    "students.sec.science.desc": "Simulações, experimentos e explicações visuais em física, química, biologia, ciências da terra e espaço.",
    "students.sec.history.desc": "Explore continentes, culturas e séculos — mapas interativos, fontes primárias e narrativa rica.",
    "students.sec.coding.desc": "De blocos de arrastar e soltar à programação real — lógica, algoritmos e criar com código.",
    "students.sec.ai.desc": "Use a IA com sabedoria, identifique desinformação online e domine as habilidades digitais que cada futuro adulto precisa.",
    "students.sec.critical.desc": "Raciocine com clareza, debata bem e separe fatos do ruído — a habilidade #1 em todo relatório Future of Jobs.",
    "students.sec.mental.desc": "Mente calma, regulação emocional e aprendizagem socioemocional — a base para tudo o mais.",
    "students.sec.finance.desc": "Orçamento, poupança, investimento, bancos e seguros — as habilidades práticas com dinheiro que as escolas raramente ensinam.",
    "students.sec.life.desc": "Cozinhar, nutrição, fitness, primeiros socorros, sono e habilidades cotidianas — o que a vida adulta realmente exige.",
    "students.sec.values.desc": "Empatia, integridade, consciência global e cidadania ativa — as habilidades de caráter que sustentam tudo o mais.",
    "students.sec.creativity.desc": "Música, arte, design, 3D, cinema e invenção — ferramentas gratuitas para que as crianças criem coisas reais.",
    "students.sec.learn.desc": "Técnicas de memória, ferramentas de foco, anotações e ciência da aprendizagem — as meta-habilidades que tornam tudo o mais mais fácil.",
    "students.sec.sport.desc": "Rotinas de movimento, treinamento esportivo, yoga e ciência do fitness — recursos gratuitos para construir hábitos saudáveis e ativos em qualquer idade.",
    # Teachers subpage
    "sub.teachers.back": "Voltar aos Recursos",
    "sub.teachers.badge": "Ferramentas Gratuitas para Professores e Educadores",
    "sub.teachers.title": "Recursos para Professores",
    "sub.teachers.desc": "344 ferramentas gratuitas curadas e organizadas conforme o fluxo de trabalho docente. Escolha uma fase e depois um tópico para encontrar a ferramenta certa.",
    "teachers.stat.tools": "Ferramentas Gratuitas", "teachers.stat.topics": "Tópicos",
    "teachers.stat.phases": "Fases do Fluxo de Trabalho", "teachers.stat.free": "Grátis",
    "teachers.grade.prek": "Pré-escola", "teachers.grade.primary": "Fundamental I",
    "teachers.grade.secondary": "Fundamental II/Médio", "teachers.grade.higher": "Ensino Superior",
    "teachers.grade.sen": "Educação Especial", "teachers.grade.all": "Todas as Etapas",
    "teachers.picker.label": "Explorar por Fase",
    "teachers.picker.heading": "Escolha uma <em>fase do fluxo de trabalho docente</em> e depois um tópico",
    "teachers.filter.label": "Filtrar por etapa:", "teachers.filter.all": "Todas as Etapas",
    # Teachers phases
    "teachers.phase.fundamentals.name": "Fundamentos do Professor", "teachers.phase.fundamentals.tag": "Didática e Pedagogia",
    "teachers.phase.before.name": "Antes da Aula", "teachers.phase.before.tag": "Design e Preparação",
    "teachers.phase.during.name": "Durante a Aula", "teachers.phase.during.tag": "Ensino e Aprendizagem",
    "teachers.phase.after.name": "Depois da Aula", "teachers.phase.after.tag": "Avaliação e Acompanhamento",
    "teachers.phase.supp.name": "Apoio", "teachers.phase.supp.tag": "Em todas as fases",
    "teachers.phase.furtherdev.name": "Desenvolvimento Profissional", "teachers.phase.furtherdev.tag": "Cresça como Professor",
    # Teachers chips & sections (28 sub-clusters)
    "teachers.chip.didactics": "Didática",
    "teachers.sec.didactics.label": "Como Ensinar", "teachers.sec.didactics.h2": "Didática — Como Você Ensina",
    "teachers.sec.didactics.desc": "Domine o ofício de ensinar: modelos instrucionais, estrutura da aula, transmissão de conteúdo e técnicas baseadas em evidências para que cada aula funcione.",
    "teachers.chip.pedagogy": "Pedagogia",
    "teachers.sec.pedagogy.label": "Por que Você Ensina como Ensina", "teachers.sec.pedagogy.h2": "Pedagogia — Por que Você Ensina como Ensina",
    "teachers.sec.pedagogy.desc": "Explore a teoria e filosofia por trás do grande ensino: psicologia da aprendizagem, motivação, construtivismo e a experiência do aluno.",
    "teachers.chip.together": "Ambas Juntas",
    "teachers.sec.together.label": "Teoria Encontra a Prática", "teachers.sec.together.h2": "Ambas Juntas — Teoria Encontra a Prática",
    "teachers.sec.together.desc": "Recursos que conectam pesquisa e realidade da sala de aula — frameworks, vídeos de ensino real e kits que funcionam porque se baseiam em ambos.",
    "teachers.chip.fund_start": "Por Onde Começar",
    "teachers.sec.fund_start.label": "Seu Ponto de Partida", "teachers.sec.fund_start.h2": "Por Onde Começar",
    "teachers.sec.fund_start.desc": "Novo em explorar sua prática? Comece aqui — um caminho curado pelos recursos gratuitos mais importantes para professores em desenvolvimento.",
    "teachers.chip.planning": "Planejamento de Aulas e Currículo",
    "teachers.sec.planning.label": "Currículo e Design de Aulas", "teachers.sec.planning.h2": "Planejamento de Aulas e Currículo",
    "teachers.sec.planning.desc": "Construa unidades alinhadas a padrões, planos semanais e aulas prontas para ensinar em minutos — modelos gratuitos e currículos abertos completos.",
    "teachers.chip.materials": "Criar Materiais",
    "teachers.sec.materials.label": "Folhas, Slides, Vídeo e Visuais", "teachers.sec.materials.h2": "Criar Materiais — Slides, Folhas, Vídeo e Visuais",
    "teachers.sec.materials.desc": "Crie folhas de exercícios, slides, infográficos e vídeos polidos em minutos — sem habilidades de design, tudo gratuito para professores.",
    "teachers.chip.adapting": "Selecionar e Adaptar",
    "teachers.sec.adapting.label": "Nivelamento, Acessibilidade e Necessidades Especiais", "teachers.sec.adapting.h2": "Selecionar e Adaptar Recursos",
    "teachers.sec.adapting.desc": "Selecione recursos existentes e adapte-os para cada aluno — niveladores de texto, bibliotecas niveladas, leitores acessíveis e ferramentas amigáveis a dislexia.",
    "teachers.chip.objectives": "Objetivos e Alinhamento de Padrões",
    "teachers.sec.objectives.label": "Padrões, Frameworks e Estrutura de Aula", "teachers.sec.objectives.h2": "Definir Objetivos e Alinhar Padrões",
    "teachers.sec.objectives.desc": "Ancore cada aula em padrões e objetivos claros — frameworks oficiais, taxonomias e bibliotecas OER alinhadas a padrões.",
    "teachers.chip.explaining": "Explicar Conteúdo",
    "teachers.sec.explaining.label": "Slides, Vídeo e Screencast", "teachers.sec.explaining.h2": "Explicar Conteúdo — Slides, Vídeo e Screencast",
    "teachers.sec.explaining.desc": "Entregue aulas que ficam — slides interativos, perguntas embutidas em vídeo, screencasts e mini-aulas curadas.",
    "teachers.chip.interactive": "Atividades Interativas",
    "teachers.sec.interactive.label": "Laboratórios STEM, Estúdios de Arte e Música", "teachers.sec.interactive.h2": "Atividades Interativas — Laboratórios STEM, Arte e Música",
    "teachers.sec.interactive.desc": "Simulações práticas, laboratórios virtuais e estúdios criativos — deixe os alunos FAZEREM física, biologia, música e arte na sua aula.",
    "teachers.chip.collab": "Colaboração",
    "teachers.sec.collab.label": "Quadros, Mapas Mentais e Brainstorming", "teachers.sec.collab.h2": "Colaboração — Pensamento Visual e Brainstorming",
    "teachers.sec.collab.desc": "Torne o pensamento dos alunos visível — quadros colaborativos, mapas mentais, quadros de notas adesivas e ferramentas de mapeamento conceitual.",
    "teachers.chip.instruction": "Aula ao Vivo",
    "teachers.sec.instruction.label": "Enquetes, Quizzes e Sistemas de Resposta", "teachers.sec.instruction.h2": "Aula em Sala — Resposta ao Vivo e Enquetes",
    "teachers.sec.instruction.desc": "Realize atividades ao vivo envolventes — quizzes estilo show, enquetes, exit tickets e sistemas de resposta que mantêm cada aluno ativo.",
    "teachers.chip.grading": "Avaliação",
    "teachers.sec.grading.label": "LMS, Cadernetas e Correção Automática", "teachers.sec.grading.h2": "Avaliação — LMS, Cadernetas e Correção Automática",
    "teachers.sec.grading.desc": "Reduza o tempo de avaliação pela metade — cadernetas LMS gratuitas, quizzes corrigidos automaticamente, ferramentas de rubrica e relatórios baseados em padrões.",
    "teachers.chip.feedback": "Feedback",
    "teachers.sec.feedback.label": "Escrita, Gramática e Notas de Voz", "teachers.sec.feedback.h2": "Feedback — Ajuda na Escrita, Gramática e Comentários",
    "teachers.sec.feedback.desc": "Dê feedback significativo e rápido sobre a escrita dos alunos — corretores gramaticais, notas de voz, ferramentas de rubrica e plataformas de ajuda à escrita.",
    "teachers.chip.reflection": "Reflexão",
    "teachers.sec.reflection.label": "Exit Tickets, Diários e Portfólios", "teachers.sec.reflection.h2": "Reflexão — Exit Tickets, Diários e Portfólios",
    "teachers.sec.reflection.desc": "Ajude os alunos a refletirem sobre seu aprendizado — reflexões em vídeo, diários, exit tickets, e-books e portfólios.",
    "teachers.chip.tracking": "Acompanhar Progresso",
    "teachers.sec.tracking.label": "Tarefas, Prática e Aprendizagem em Família", "teachers.sec.tracking.h2": "Acompanhar Progresso — Tarefas e Aprendizagem em Família",
    "teachers.sec.tracking.desc": "Recomende recursos seguros e eficazes para as famílias — apoio às tarefas, ferramentas de revisão e aprendizagem em casa para os pais.",
    "teachers.chip.mgmt": "Gestão de Sala de Aula",
    "teachers.sec.mgmt.label": "Comportamento, Rotinas e Engajamento", "teachers.sec.mgmt.h2": "Gestão de Sala e Engajamento",
    "teachers.sec.mgmt.desc": "Construa rotinas positivas, reconheça bom comportamento e gerencie sistemas diários fluidos — ferramentas gratuitas que respeitam os alunos.",
    "teachers.chip.comms": "Comunicação",
    "teachers.sec.comms.label": "Pais, Alunos e Newsletters", "teachers.sec.comms.h2": "Comunicação — Pais, Alunos e Tradução",
    "teachers.sec.comms.desc": "Alcance cada família no idioma e nos termos delas — mensagens seguras, newsletters e ferramentas de tradução.",
    "teachers.chip.admin": "Administração e Arquivos",
    "teachers.sec.admin.label": "Armazenamento em Nuvem, Tarefas e Calendários", "teachers.sec.admin.h2": "Administração e Armazenamento de Arquivos",
    "teachers.sec.admin.desc": "Reduza a papelada — armazenamento em nuvem gratuito, quadros kanban, ferramentas de agendamento e espaços de trabalho em equipe.",
    "teachers.chip.wellbeing": "Gestão de Estresse e Bem-estar",
    "teachers.sec.wellbeing.label": "Saúde Mental, Mindfulness e Prevenção de Burnout", "teachers.sec.wellbeing.h2": "Gestão de Estresse e Bem-estar",
    "teachers.sec.wellbeing.desc": "Cuide-se primeiro — recursos gratuitos de saúde mental, mindfulness e prevenção de burnout especialmente para professores.",
    "teachers.chip.ai": "Copilotos de IA",
    "teachers.sec.ai.label": "Assistentes de IA para Professores", "teachers.sec.ai.h2": "Copilotos de IA — Ajudantes em Todas as Fases",
    "teachers.sec.ai.desc": "Gere planos de aula, rubricas, folhas diferenciadas e feedback em segundos — ferramentas gratuitas de IA para todo o fluxo docente.",
    "teachers.chip.fd_start": "Por Onde Começar",
    "teachers.sec.fd_start.label": "Novo em formação continuada? Comece aqui", "teachers.sec.fd_start.h2": "Por Onde Começar com o Desenvolvimento Profissional",
    "teachers.sec.fd_start.desc": "Sem saber por onde começar seu desenvolvimento profissional? Estes pontos de partida confiáveis ajudam você a planejar um caminho que se adapte a você.",
    "teachers.chip.fd_courses": "Cursos e Certificações Grátis",
    "teachers.sec.fd_courses.label": "MOOCs, Badges e Certificados", "teachers.sec.fd_courses.h2": "Cursos e Certificações Gratuitos",
    "teachers.sec.fd_courses.desc": "Obtenha certificados e badges reconhecidos gratuitamente — da Coursera, edX, Google, Microsoft, Apple e Open University.",
    "teachers.chip.fd_methods": "Métodos de Ensino",
    "teachers.sec.fd_methods.label": "PBL, Flipped, Investigação e Mais", "teachers.sec.fd_methods.h2": "Métodos de Ensino — Como Ensinar Melhor",
    "teachers.sec.fd_methods.desc": "Explore abordagens instrucionais comprovadas, do aprendizado baseado em projetos ao flipped — guias, cursos e recursos prontos para a sala de aula.",
    "teachers.chip.fd_subject": "Sua Disciplina",
    "teachers.sec.fd_subject.label": "Aprofundar sua Matéria", "teachers.sec.fd_subject.h2": "Sua Disciplina — Aprofunde seu Conhecimento",
    "teachers.sec.fd_subject.desc": "Aprofunde-se em sua área — recursos gratuitos, ferramentas de enriquecimento e orientação específica para matemática, língua, ciências, humanidades e mais.",
    "teachers.chip.fd_lead": "Liderar e Mentorar",
    "teachers.sec.fd_lead.label": "Coaching Instrucional e Liderança Docente", "teachers.sec.fd_lead.h2": "Liderar e Mentorar — Torne-se Professor Líder",
    "teachers.sec.fd_lead.desc": "Avance para liderança, coaching e mentoria — recursos gratuitos para professores que querem apoiar colegas e desenvolver a prática da escola.",
    "teachers.chip.fd_evidence": "Evidência e Insights",
    "teachers.sec.fd_evidence.label": "Pesquisa Útil para Professores", "teachers.sec.fd_evidence.h2": "Evidência e Insights — O que a Pesquisa Mostra",
    "teachers.sec.fd_evidence.desc": "Acesse a melhor pesquisa educacional em linguagem clara — estratégias avaliadas por evidências, principais descobertas e comunidades de pesquisa para professores ocupados.",
    "teachers.chip.fd_community": "Comunidades Docentes",
    "teachers.sec.fd_community.label": "Fóruns, Grupos e Redes Profissionais", "teachers.sec.fd_community.h2": "Comunidades Docentes — Encontre seu Pessoal",
    "teachers.sec.fd_community.desc": "Conecte-se com professores ao redor do mundo — fóruns gratuitos, comunidades sociais, redes por disciplina e eventos ao vivo onde grandes ideias docentes se espalham.",
    # Sport (12 cards)
    "cd_s01": "Vídeos de movimento e mindfulness preferidos da sala de aula que tiram as crianças das cadeiras — danças, yoga e pausas para o cérebro em clipes de 3–5 min.",
    "cd_s02": "Aventuras de yoga narradas para crianças pequenas — posturas integradas em histórias imaginativas sobre dragões, super-heróis e mundos mágicos.",
    "cd_s03": "Centenas de tutoriais de jogos de Educação Física e ideias de atividade física para a escola — fáceis de fazer sem equipamento e adaptáveis a qualquer grupo.",
    "cd_s04": "Imensa biblioteca de planos de aula de EF, aquecimentos e atividades de fitness organizados por idade, habilidade e equipamento — clássico para professores de EF.",
    "cd_s05": "Artigos amigáveis para crianças sobre ciência do exercício, nutrição, sono e segurança no esporte — escritos por médicos para construir hábitos saudáveis ao longo da vida.",
    "cd_s06": "Rotinas de treino em vídeo construídas especificamente para crianças — circuitos de força, flexibilidade e cardio que se adaptam ao tempo e espaço disponíveis.",
    "cd_s07": "Kits, fichas de atividades e guias de programa para incorporar movimento diário na vida escolar — 60 minutos de atividade por dia, na prática.",
    "cd_s08": "Mais de 600 vídeos completos e gratuitos de treino em cardio, força, HIIT e alongamento — filtráveis por duração, dificuldade e equipamento necessário.",
    "cd_s09": "O plano de corrida para iniciantes mais popular do mundo — 9 semanas para correr 5 km sem parar, com app gratuito e guias de áudio de treinadores famosos.",
    "cd_s10": "Artigos de treinamento por esporte escritos com treinadores profissionais — velocidade, agilidade, força e ciência da recuperação para jovens atletas sérios.",
    "cd_s11": "Biblioteca completa de treinos guiados por treinadores — sessões de peso corporal, força e yoga de 15 a 60 minutos, todas grátis depois que a Nike removeu o paywall.",
    "cd_s12": "Cursos universitários gratuitos sobre a ciência do esporte, atividade física e desempenho humano — ideais para alunos interessados em carreiras esportivas.",
    # GDPR
    "gdpr.title": "Aviso de Cookies e Armazenamento",
    "gdpr.text": "Usamos o armazenamento local do navegador exclusivamente para guardar sua preferência de idioma. Nenhum cookie de rastreamento ou dado pessoal é coletado ou compartilhado.",
    "gdpr.accept": "Aceitar", "gdpr.decline": "Recusar",
}

# Uni cards (144) — translated below
PT_UNI = {
    "cd_uni_000": "O assistente principal da Anthropic — uma camada gratuita generosa cobre escrita, código e pesquisa com forte raciocínio.",
    "cd_uni_001": "ChatGPT da OpenAI — a camada gratuita inclui GPT-4o mini, modo de voz, compreensão de imagens e análise básica de dados.",
    "cd_uni_002": "Assistente multimodal do Google com integração profunda no Docs, Drive e Gmail — boa camada gratuita com suporte a imagens e código.",
    "cd_uni_003": "Copilot gratuito com raciocínio nível GPT-4, geração de imagens e integração com Microsoft 365 — incluído grátis em qualquer conta Microsoft.",
    "cd_uni_004": "Mecanismo de busca com IA que cita cada afirmação — perfeito quando você precisa de fontes verificáveis em vez de respostas alucinadas.",
    "cd_uni_005": "Faça upload de seus apontamentos e PDFs — a IA do Google responde estritamente a partir das suas fontes, com citações e resumos em áudio.",
    "cd_uni_006": "Execute milhares de modelos de IA de código aberto no seu navegador — texto, visão, voz, agentes — e hospede seus próprios Spaces grátis.",
    "cd_uni_007": "Cursos gratuitos de 1 hora de Andrew Ng sobre prompts, RAG, agentes e fine-tuning — ministrados com os principais laboratórios de IA.",
    "cd_uni_008": "Curso gratuito de código aberto que ensina as quatro competências centrais para trabalhar com IA — delegação, descrição, discernimento e diligência.",
    "cd_uni_009": "MOOC gratuito da Universidade de Helsinki — 30 horas sobre fundamentos, ética e limites da IA, já feito por 1 milhão de pessoas.",
    "cd_uni_010": "Currículo gratuito do Google sobre noções básicas de IA generativa, design de prompts e uso responsável — sem experiência prévia exigida.",
    "cd_uni_011": "Guia comunitário de código aberto sobre prompts — técnicas, exemplos e artigos científicos, tudo grátis e atualizado com frequência.",
    "cd_uni_012": "A lendária introdução à computação de Harvard — vídeos, exercícios e certificado gratuito via edX. Continua sendo o melhor primeiro curso de CS online.",
    "cd_uni_013": "Milhares de horas de programação prática e certificações gratuitas — desenvolvimento web, análise de dados e machine learning.",
    "cd_uni_014": "Currículo gratuito e completo de desenvolvimento web full-stack usado por autodidatas que conseguem empregos reais — orientado pela comunidade e testado.",
    "cd_uni_015": "Aulas interativas de programação no navegador — Python, JS, SQL, HTML/CSS — com camada gratuita sólida que cobre os fundamentos.",
    "cd_uni_016": "Microcursos curtos e práticos de ciência de dados e ML — mais milhares de datasets reais e competições para praticar.",
    "cd_uni_017": "Notebooks Jupyter gratuitos no navegador com GPU grátis — perfeito para ML, ciência de dados e prototipagem de pesquisa sem instalação.",
    "cd_uni_018": "Practical Deep Learning for Coders — curso gratuito top-down que transforma programadores em praticantes de deep learning em sete semanas.",
    "cd_uni_019": "Primeiros capítulos grátis de cada curso — boa introdução a Python, R, SQL e visualização de dados com exercícios no navegador.",
    "cd_uni_020": "O tutorial gratuito de SQL mais claro online — focado em analytics, com datasets reais e editor integrado no navegador.",
    "cd_uni_021": "Programe em mais de 50 linguagens diretamente no seu navegador — sem configuração, hospedagem grátis, colaboração instantânea e programação assistida por IA.",
    "cd_uni_022": "Exercícios práticos gratuitos em mais de 70 linguagens com feedback de mentores — afie sintaxe e idiomas além do que tutoriais cobrem.",
    "cd_uni_023": "Introdução do MIT à computação usando Python — aulas, exercícios e provas gratuitos do curso presencial do campus.",
    "cd_uni_024": "Gerenciador de senhas de código aberto com camada gratuita generosa — dispositivos e senhas ilimitados com criptografia de ponta a ponta.",
    "cd_uni_025": "Verifique grátis se seu email ou senha foram expostos em um vazamento — pelo pesquisador de segurança Troy Hunt.",
    "cd_uni_026": "Mensageiro gratuito com criptografia de ponta a ponta — padrão-ouro para chats, voz e vídeo privados. Usado por jornalistas no mundo todo.",
    "cd_uni_027": "App gratuito de código aberto para autenticação de dois fatores — muito mais seguro que códigos por SMS e protege suas contas mesmo se senhas vazarem.",
    "cd_uni_028": "Navegador gratuito de anonimato que roteia tráfego por relés voluntários — essencial para jornalistas, ativistas e usuários de alto risco.",
    "cd_uni_029": "Guia de compras gratuito da Mozilla classificando a privacidade da tecnologia de consumo — celulares, alto-falantes inteligentes, apps de saúde mental. Fácil de revisar antes de comprar.",
    "cd_uni_030": "Guia gratuito de segurança digital da Electronic Frontier Foundation — manuais práticos para alunos, ativistas e usuários do dia a dia.",
    "cd_uni_031": "Treinamento gamificado de cibersegurança — salas gratuitas cobrem redes, Linux e segurança web; a plataforma de hacking mais amigável para iniciantes.",
    "cd_uni_032": "Cursos introdutórios gratuitos sobre fundamentos de cibersegurança, hacking ético e preparação para o exame CompTIA Security+.",
    "cd_uni_033": "Orientação gratuita de cibersegurança da US Cybersecurity & Infrastructure Security Agency — prática para indivíduos e pequenas organizações.",
    "cd_uni_034": "Open Worldwide Application Security Project — listas top-10 gratuitas, fichas e frameworks que todo desenvolvedor web deve conhecer.",
    "cd_uni_035": "Curso de Segurança de Computadores e Redes de Stanford — slides, notas e listas de leitura gratuitos de um programa de referência.",
    "cd_uni_036": "Curso gratuito da University of Washington para detectar besteiras em números, gráficos e histórias — todo vídeo e leitura abertamente online.",
    "cd_uni_037": "Introdução gratuita e completa à estatística e probabilidade — o letramento que você precisa para questionar qualquer gráfico que vê nas notícias.",
    "cd_uni_038": "Mostra manchetes de notícias da esquerda, centro e direita lado a lado — calibre sua dieta midiática e identifique vieses diariamente.",
    "cd_uni_039": "Compara como a mesma história é coberta no espectro político — a camada gratuita destaca pontos cegos e vieses.",
    "cd_uni_040": "O site original de fact-checking — vereditos gratuitos e transparentes sobre afirmações virais, lendas urbanas e rumores políticos.",
    "cd_uni_041": "Podcast e artigos gratuitos da BBC com Tim Harford desvendando os números por trás das manchetes — o treinamento mais legível em pensamento estatístico.",
    "cd_uni_042": "Auditoria gratuita de Richard Nisbett, Nobel laureate, sobre os conceitos mais úteis em psicologia e estatística para o raciocínio cotidiano.",
    "cd_uni_043": "Introdução gratuita em formato de livro à racionalidade — vieses cognitivos, pensamento probabilístico, raciocínio científico e tomada de decisão.",
    "cd_uni_044": "Guia interativo gratuito sobre 24 falácias lógicas comuns — favorito para identificar argumentos ruins online e offline.",
    "cd_uni_045": "Enciclopédia gratuita de vieses cognitivos e ciência comportamental — explicações claras e bem ilustradas de como pensamos errado.",
    "cd_uni_046": "Cursos gratuitos de letramento midiático para adolescentes e adultos do Poynter Institute — fact-checking prático com exemplos reais.",
    "cd_uni_047": "Artigos gratuitos de Ben Goldacre desmontando estatísticas ruins em medicina e jornalismo — o antídoto canônico contra manchetes duvidosas.",
    "cd_uni_048": "Mais de 2.500 cursos do MIT grátis — apostilas, exercícios, provas e frequentemente vídeos completos da melhor escola de engenharia do mundo.",
    "cd_uni_049": "Audite a maioria dos cursos de Stanford, Yale, Michigan e mais grátis — vídeos e leituras incluídos na trilha sem custo.",
    "cd_uni_050": "Cursos de Harvard, MIT, Berkeley — grátis para auditar, com certificados pagos opcionais e programas MicroMasters para crédito.",
    "cd_uni_051": "Cursos gratuitos curados de professores de Stanford — IA, engenharia, medicina, educação e empreendedorismo.",
    "cd_uni_052": "Aulas completas de graduação de Yale — filosofia, economia, astronomia, literatura — vídeos e listas de leitura completos.",
    "cd_uni_053": "Cursos gratuitos da Open University — mais de 1.000 tópicos com declarações de participação disponíveis sem custo.",
    "cd_uni_054": "Cursos universitários autodidatas com certificados gratuitos — alguns elegíveis a crédito via parcerias ACE, sem taxa de matrícula.",
    "cd_uni_055": "Cursos adaptativos baseados em pesquisa da Carnegie Mellon — estatística, psicologia, biologia e lógica.",
    "cd_uni_056": "Cursos fundamentais com rastreamento de domínio — cálculo, álgebra linear, física, economia e preparação para provas, totalmente grátis.",
    "cd_uni_057": "Cursos curtos gratuitos de universidades europeias e da Commonwealth — aprendizagem baseada em discussão com pares no mundo todo.",
    "cd_uni_058": "Buscador gratuito de mais de 200.000 MOOCs — a forma mais fácil de encontrar a melhor versão gratuita de qualquer curso na web.",
    "cd_uni_059": "O MOOC mais popular da história — curso auditável grátis sobre meta-aprendizagem, prática focada e vencer a procrastinação.",
    "cd_uni_060": "O maior buscador acadêmico gratuito — artigos, citações e frequentemente links diretos para PDFs gratuitos em todas as disciplinas.",
    "cd_uni_061": "Gerenciador de referências gratuito e de código aberto — capture qualquer fonte com um clique e formate bibliografias automaticamente em qualquer estilo.",
    "cd_uni_062": "Buscador acadêmico com IA do Allen Institute — destaca citações influentes e trabalhos relacionados para qualquer artigo.",
    "cd_uni_063": "Grafo visual de artigos relacionados a qualquer artigo-chave — uma virada de jogo para revisões de literatura e trabalhos de tese.",
    "cd_uni_064": "Maior agregador mundial de pesquisa de acesso aberto — 300 milhões de artigos em 11.000 repositórios, totalmente pesquisáveis.",
    "cd_uni_065": "Banco de dados gratuito do NIH com mais de 35M de citações biomédicas — essencial para ciências da vida, medicina e psicologia.",
    "cd_uni_066": "Directory of Open Access Journals — mais de 20.000 periódicos peer-reviewed com texto completo grátis, sem paywalls.",
    "cd_uni_067": "Livros didáticos peer-reviewed gratuitos da Rice University — biologia, física, economia, sociologia e cálculo, totalmente baixáveis.",
    "cd_uni_068": "A maior biblioteca de livros didáticos abertos — química, engenharia, humanidades e medicina, livremente remixáveis para educadores.",
    "cd_uni_069": "Servidor gratuito de preprints de física, matemática, CS e biologia quantitativa — veja novas pesquisas meses antes da publicação formal.",
    "cd_uni_070": "Mais de 75.000 livros clássicos em domínio público — ideal para cursos de literatura, história e filosofia.",
    "cd_uni_071": "Milhões de livros, artigos acadêmicos e documentos históricos gratuitos — incluindo o serviço de empréstimo Open Library.",
    "cd_uni_072": "Verificações em tempo real de gramática, ortografia e clareza no seu navegador ou Word — a camada gratuita cobre o essencial diário.",
    "cd_uni_073": "Destaca frases complicadas, voz passiva e advérbios — torna a escrita acadêmica e profissional drasticamente mais clara.",
    "cd_uni_074": "Corretor gramatical de código aberto com suporte a 30+ idiomas — camada gratuita sólida, ideal para ensaios em alemão, francês e espanhol.",
    "cd_uni_075": "Editor LaTeX online — escrita colaborativa de teses e artigos com pré-visualização ao vivo e modelos de periódicos; camada gratuita atende a maioria.",
    "cd_uni_076": "Alternativa moderna e de código aberto ao LaTeX — compilação mais rápida, sintaxe mais limpa, ainda produz PDFs lindos para trabalho acadêmico.",
    "cd_uni_077": "A referência de escrita gratuita mais usada da web — guias de estilo APA/MLA/Chicago, dicas de gramática e manuais de escrita acadêmica.",
    "cd_uni_078": "Aulas gratuitas do TED-Ed sobre oratória, narrativa e apresentação — ministradas por pessoas que realmente fazem talks no TED.",
    "cd_uni_079": "Maior comunidade de oratória do mundo — muitos clubes locais permitem visitar grátis, com trilhas estruturadas para crescimento.",
    "cd_uni_080": "Especialização auditável grátis de Patrick Barry sobre escrita e edição persuasivas — prática para ensaios, candidaturas e pitches.",
    "cd_uni_081": "Treinador de oratória com IA gratuito — pratique apresentações em vídeo e receba feedback sobre muletas, ritmo, clareza e confiança.",
    "cd_uni_082": "Processador de texto colaborativo gratuito com edição em tempo real, comentários, histórico de versões e digitação por voz — universal para trabalho estudantil.",
    "cd_uni_083": "Assistente de escrita com IA gratuito da DeepL — reescreve em função do tom e da clareza em inglês, alemão e outros idiomas principais.",
    "cd_uni_084": "Plano Plus grátis para alunos com email .edu — notas, bancos de dados, listas de tarefas e wikis em um único espaço de trabalho.",
    "cd_uni_085": "Anotações em markdown locais com backlinks — a melhor ferramenta gratuita para construir um grafo de conhecimento acadêmico pessoal.",
    "cd_uni_086": "Flashcards de repetição espaçada gratuitos e de código aberto — usados por estudantes de medicina e idiomas no mundo todo; a ferramenta de memória comprovada.",
    "cd_uni_087": "Gerenciador de tarefas limpo que lida com tarefas recorrentes e prazos em todos os seus dispositivos — a camada gratuita atende a maioria dos fluxos.",
    "cd_uni_088": "Timer de foco gamificado — plante uma árvore virtual que morre se você sair do app. A versão web gratuita bloqueia distrações de forma confiável.",
    "cd_uni_089": "Timer Pomodoro gratuito e simples — inicie sessões de 25 minutos focadas no seu navegador sem cadastro ou configuração.",
    "cd_uni_090": "Bloqueador de sites e apps gratuito que é realmente difícil de driblar — agende blocos de trabalho profundo que nem você pode anular.",
    "cd_uni_091": "Ensaios, podcasts e guias gratuitos do autor de Deep Work — manuais práticos para foco sustentado e sem distrações.",
    "cd_uni_092": "Grafo de conhecimento local-first e de código aberto — notas diárias, esquemas e backlinks; alternativa gratuita ao Roam que respeita a privacidade.",
    "cd_uni_093": "Quadros Kanban gratuitos para projetos — gestão visual de tarefas para projetos em grupo, teses e projetos paralelos.",
    "cd_uni_094": "Calendário gratuito com time-blocking, eventos compartilhados e entrada em linguagem natural — a base de qualquer prática de trabalho profundo.",
    "cd_uni_095": "App gratuito de monitoramento de tempo com timers de um clique — veja para onde realmente vão suas horas de estudo e projete melhores rotinas.",
    "cd_uni_096": "O curso mais popular da história de Yale — auditável grátis, ministrado por Laurie Santos, sobre a psicologia da felicidade com práticas diárias.",
    "cd_uni_097": "Headspace Plus gratuito para alunos em mais de 1.000 universidades — meditações guiadas, histórias para dormir e cursos sobre estresse.",
    "cd_uni_098": "Meditações guiadas, exercícios de respiração e histórias para dormir gratuitos — os fundamentos do mindfulness sem paywall.",
    "cd_uni_099": "Programa gratuito baseado em TCC da Australian National University — comprovado para reduzir sintomas de depressão e ansiedade.",
    "cd_uni_100": "Apoio gratuito à saúde mental baseado em chatbot — usa técnicas de TCC para ajudar com humor, ansiedade e pensamentos estressantes.",
    "cd_uni_101": "Hub gratuito de saúde mental do NHS britânico — conselhos práticos para ansiedade, sono, baixo astral e estresse.",
    "cd_uni_102": "Meditações e exercícios gratuitos de Kristin Neff — práticas de autocompaixão baseadas em pesquisa que comprovadamente fortalecem a resiliência.",
    "cd_uni_103": "O maior app de meditação grátis — mais de 200.000 meditações guiadas, palestras e músicas de professores no mundo todo.",
    "cd_uni_104": "Apoio emocional gratuito de ouvintes treinados — chats anônimos 24/7, mais terapia online de baixo custo se precisar de mais.",
    "cd_uni_105": "Apoio gratuito 24/7 em crise por mensagem — conselheiros confidenciais e treinados nos EUA, Reino Unido, Irlanda e Canadá.",
    "cd_uni_106": "Recurso educativo gratuito da Harvard Medical School sobre biologia, higiene e distúrbios do sono — claro, baseado em evidência e acessível.",
    "cd_uni_107": "Calendários mensais gratuitos de ações diárias baseadas em evidência — pequenos hábitos sustentáveis comprovados que melhoram humor e resiliência.",
    "cd_uni_108": "Curso completo e gratuito de finanças pessoais — impostos, crédito, investimento, aposentadoria e imóveis, ensinado com clareza de ensino médio.",
    "cd_uni_109": "Enciclopédia gratuita de finanças e investimentos — mais de 30.000 artigos e um simulador grátis para fazer paper-trading sem risco.",
    "cd_uni_110": "Guias gratuitos comparando cartões de crédito, empréstimos estudantis, contas de poupança e plataformas de investimento — orientação independente.",
    "cd_uni_111": "Wiki comunitária gratuita sobre investimentos indexados de baixo custo — baseada nos princípios de John Bogle, padrão-ouro para investidores passivos.",
    "cd_uni_112": "Ferramentas e guias gratuitos do US Consumer Financial Protection Bureau — empréstimos estudantis, crédito, golpes e noções básicas de dinheiro.",
    "cd_uni_113": "Hub gratuito de finanças do governo australiano — calculadoras, guias e ferramentas de orçamento utilizáveis internacionalmente.",
    "cd_uni_114": "Curso gratuito do Nobel Robert Shiller — auditável no Coursera, cobre risco, finanças comportamentais e mercados modernos.",
    "cd_uni_115": "Introdução à teoria financeira do MIT Sloan — aulas e exercícios gratuitos sobre valoração, portfólios e mercados de capitais.",
    "cd_uni_116": "Vídeos práticos e gratuitos sobre dinheiro para jovens adultos — orçamento, investimento, negociação salarial e inflação do estilo de vida, sem jargão.",
    "cd_uni_117": "Mais de 15 anos gratuitos de escrita acessível sobre finanças pessoais por JD Roth — quitação de dívidas, poupança, investimento e consumo consciente.",
    "cd_uni_118": "Ensaios gratuitos sobre independência financeira e frugalidade — texto fundador do movimento FIRE, opinativo mas prático.",
    "cd_uni_119": "Assinatura gratuita de 12 meses do YNAB para alunos universitários — método de orçamento mais querido, com aulas incluídas.",
    "cd_uni_120": "Curso gratuito de 10 semanas da melhor aceleradora do mundo — mais de 1M de fundadores treinados, com biblioteca de ensaios e palestras da YC.",
    "cd_uni_121": "Muitas bibliotecas públicas dão acesso gratuito ao LinkedIn Learning — milhares de cursos sobre carreiras, ferramentas e habilidades comportamentais.",
    "cd_uni_122": "Feedback gratuito com IA sobre currículo e perfil do LinkedIn — criado por ex-recrutadores, pontua seu CV contra rubricas reais de contratação.",
    "cd_uni_123": "Modelos baixáveis de currículo e guias de redação gratuitos — práticos para primeiros empregos, estágios e mudanças de carreira.",
    "cd_uni_124": "Arquivo gratuito de artigos sobre carreira — preparação para entrevistas, negociação salarial, política do trabalho e mudança de carreira.",
    "cd_uni_125": "Dados salariais gratuitos com crowdsourcing de ofertas reais — veja quanto cargos em tech, finanças e consultoria realmente pagam antes de negociar.",
    "cd_uni_126": "Avaliações, faixas salariais e perguntas de entrevista gratuitos sobre milhares de empresas — leitura padrão antes de qualquer entrevista.",
    "cd_uni_127": "Conselhos de carreira gratuitos focados em fazer o maior bem com seu trabalho — guias baseados em pesquisa sobre carreiras de alto impacto.",
    "cd_uni_128": "Stanford CS183B gratuito ministrado por Sam Altman e sócios da Y Combinator — 20 aulas grátis sobre construir uma startup do zero.",
    "cd_uni_129": "Comunidade gratuita de fundadores bootstrapped — entrevistas, podcasts e fóruns sobre construir negócios paralelos lucrativos.",
    "cd_uni_130": "Certificações gratuitas em marketing, vendas, conteúdo e SEO — reconhecidas por empregadores, completáveis online em poucas horas cada.",
    "cd_uni_131": "Certificados Google auditáveis grátis em suporte de TI, análise de dados, UX e gestão de projetos — reconhecidos por mais de 150 empregadores.",
    "cd_uni_132": "Visualizações de dados gratuitas e de licença aberta sobre os maiores problemas do mundo — clima, pobreza e saúde — feitas por pesquisadores de Oxford.",
    "cd_uni_133": "Explicações gratuitas curadas pelo MIT sobre mudanças climáticas — a ciência, as soluções, a política — acessíveis e rigorosamente referenciadas.",
    "cd_uni_134": "Lista gratuita e ranqueada das soluções climáticas mais eficazes — banco de dados pesquisável com análises técnicas profundas para cada uma.",
    "cd_uni_135": "Jornalismo climático diário e gratuito de Yale — reportagens precisas e acessíveis sobre ciência, impactos e soluções do clima.",
    "cd_uni_136": "Introdução gratuita e completa à educação cívica dos EUA — Constituição, poderes, eleições — útil mesmo para alunos não americanos aprendendo os fundamentos democráticos.",
    "cd_uni_137": "Jogos e aulas gratuitos sobre participação democrática — criados pela Juíza O'Connor, usados em mais de 50.000 salas de aula.",
    "cd_uni_138": "Hub gratuito de recursos sobre ética da Santa Clara University — frameworks para pensar tecnologia, negócios, IA e bioética.",
    "cd_uni_139": "Relatórios, primers e policy briefs gratuitos do Stanford Human-Centered AI Institute — fonte líder sobre o impacto social da IA.",
    "cd_uni_140": "Manual gratuito de investigação de fontes abertas — verifique vídeos, geolocalize fotos e cheque afirmações virais como os profissionais.",
    "cd_uni_141": "Arquivo gratuito de jornalismo baseado em evidência sobre o que está funcionando — antídoto contra o doomscrolling, focado em respostas a problemas sociais.",
    "cd_uni_142": "Guias gratuitos da Electronic Frontier Foundation sobre liberdade de expressão, vigilância e direitos digitais — principal organização de liberdades civis digitais.",
    "cd_uni_143": "Cursos gratuitos sobre os Objetivos de Desenvolvimento Sustentável da ONU — clima, igualdade, pobreza e governança, ministrados por agências da ONU e parceiros.",
}

# Merge all
ALL = {**PT, **PT_UNI}

src_path = Path(r"C:\Users\larsg\OneDrive\Claude Code\01_website ctwp\assets\js\i18n.js")
src = src_path.read_text(encoding="utf-8")

# Find translations object end: "  }\n};" — but we need to find the LAST "  }\n};" before the next const declaration
# Actually we want to insert a new "  pt: {...}" block before the closing "};"
# Pattern: the ES block ends, then "}\n};\n\nconst SUPPORTED_LANGS"
# We insert ",\n  pt: {...}" between the ES block close and "};"

# More robust: find the closing "};" that ends the translations const
# It's the one followed by blank line and "const SUPPORTED_LANGS"
end_pat = "\n};\n\nconst SUPPORTED_LANGS"
if end_pat not in src:
    raise SystemExit("Translations end-marker not found")

# Build PT block lines
lines = ["  pt: {"]
lines.append('    /* ─────────────── Brazilian Portuguese (pt-BR) ─────────────── */')
for k, v in ALL.items():
    v_esc = v.replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'    "{k}": "{v_esc}",')
lines.append("  }")
pt_block = "\n".join(lines)

# Insert: ",\n<pt_block>" before the closing "};"
# The current src has:
#     ...es block... "  }" (end of es)
#   };          <-- end of translations const
#
# We want:
#     ...es block... "  }" (end of es), <comma>
#   pt: { ... }
# };
# So replace "\n};" with ",\n<pt_block>\n};" only where end_pat applies

new_src = src.replace("\n};\n\nconst SUPPORTED_LANGS", ",\n" + pt_block + "\n};\n\nconst SUPPORTED_LANGS", 1)

if new_src == src:
    raise SystemExit("Replacement made no change")

src_path.write_text(new_src, encoding="utf-8")
print(f"Inserted {len(ALL)} pt-BR keys (structural + sport + uni)")
